app-template:
    ingress:
        maintainerr:
            enabled: ENC[AES256_GCM,data:XIrqkA==,iv:aArW1NMXoRzFAMNfV9YoNKHjN6bj4pageUFWWxnMRuw=,tag:2HxD3nMufrlEatv/YTRCvw==,type:bool]
            annotations:
                cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:5+YvR68nPAxEO6OmHqtnRQ==,iv:luNnY/AnyZIi4Qme++HGVLzwYbFvhhLsOJBCl0dB+co=,tag:lFDxzN92Qp7mXLpI8EVTgg==,type:str]
                gethomepage.dev/enabled: ENC[AES256_GCM,data:rAaKnw==,iv:44UTbMea33IEc9mQDsSRJKdZ7gL0ZgeAdab6VV31hxk=,tag:deHUgXdSEkGah//XkctABA==,type:str]
                gethomepage.dev/name: ENC[AES256_GCM,data:NflQoQwnVmQCnO8=,iv:m91jCGs9Lqx7JmYeEYokKQDsPjnhwNUhckrinxDdlSQ=,tag:saBpgKX9glBCWQlD6kYbEg==,type:str]
                gethomepage.dev/description: ENC[AES256_GCM,data:eBC3MtgA/w2OEGsVPiP/z8m53I+Kb/USKi32pw==,iv:5zxLhZBDimbV9C8c2tYhIYiKCR7VITHYA5BtcykiSxY=,tag:xtR5gNQtQ72xgEfgli2kBQ==,type:str]
                gethomepage.dev/group: ENC[AES256_GCM,data:y/as+gmTH9lqSJA=,iv:WGeahtGnapeOSsqJxLkYquIwjCIMZ60oCGzyxl2Mync=,tag:Eztjb9CcgguaFo3y/Jegvg==,type:str]
                gethomepage.dev/icon: ENC[AES256_GCM,data:/J9P6b8PNyKRKrOwI/SzLHQ+,iv:tO2EUFH4xCMy6BUAbQPTmD81OZ2pAzX/dLF+oDWxf3o=,tag:sn6hg5IWhkfAo3BOjyNUZw==,type:str]
            hosts:
                - host: ENC[AES256_GCM,data:uHM4AMRK2bAI1W4RzbjFzAIjJDfAxww=,iv:C1dE8C8idXQA1BxkkSDENiKBeojZGR2elpyyOm4PV2A=,tag:5jAzpwOm5eVzOtnScc6GYw==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:xw==,iv:gALl2MqEwB3c+B3cYZdsGDgijx1Sj4xLXiawWtzAPaQ=,tag:SxudvaptfdL/0Oz3pBNUrA==,type:str]
                      pathType: ENC[AES256_GCM,data:HK1rQ1At,iv:o79julsgLMwlfTNHMvEVU33PzfzoDM31ZpHK8LDc0Dw=,tag:vgca1zIX1ZJpXtYEb2SXYg==,type:str]
                      service:
                        identifier: ENC[AES256_GCM,data:kev92rgUIVcwyyk=,iv:OVkJewozyXl2UxHooHpUlDTSIqXYcxn8FuLd8+G3txE=,tag:zkTkWkkLV4qNOEBpsE3xoQ==,type:str]
                        port: ENC[AES256_GCM,data:AI3GYA==,iv:L0Zja/f8pJ76SAAeeIjFJAiVPTijYM368gHsdl9vR6U=,tag:QdfAN9jZMVMuzLPIzjeX5Q==,type:str]
            tls:
                - secretName: ENC[AES256_GCM,data:EJO0tIu58vChV5JC0OE1a4AxHtM=,iv:H2AsxB2IxCgeI7W5mE8Z8FatTfis5zJfg8nzqp6t+3o=,tag:myUQqnReeON+8STgIUX2ig==,type:str]
                  hosts:
                    - ENC[AES256_GCM,data:lBQQAjy70GYyebwm+tsGLztBhT7YBrg=,iv:zBg+A/9UYFM9iF/a+B4e6NvYsVnuhoHQ/wrJ/eetCdk=,tag:RQZ5ZWEORvFHhONYR7dn+g==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ZFByVmpzUVdZa0xhTk5x
            K1lvNHlTVXpUZm5HTTRNenBmU0MwRUNvZkRnCmp1aUpLeHBSajdiek4vT1Q3SEEx
            TW5WZzh6Y29QS2xqT0RYTG5UcnNNN0EKLS0tIHdLTUpyUkJnUXhGaXhrTXBjZTdW
            SHJaOWVKWWFUREx1MjhvMEJ4ZUJyUkUKEP4bvVlLJ/LOclrU5IYHqB3XQQp7Akq/
            drXef556fhMHQQFej5lr1A+RuBLc3jdpLdmZ+z3h03cDAJrXvrdv9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-19T15:04:09Z"
    mac: ENC[AES256_GCM,data:TPEwYq1xZrJrs7b4+YngaerJcq07Dfp7CWndn9A0SYTme/PVGYcE+5b8d+T4LfAPtBUFkjNcfF/d49zmKN/MX62Bz0sqYfinKGv5kmDTwxA11EKP4C21gwCDZh2BeKvyFI1tK7Urapyru6sK5Uou2OX3hy+5irRByjRW+zku9lo=,iv:fZKRMr55PiAIHulg1XT4Sqtq83TS53I2eQwnqdM1dNU=,tag:6s0IsigFrhyNzbsLh1rIVQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
