app-template:
    ingress:
        maintainerr:
            enabled: ENC[AES256_GCM,data:dAF5+w==,iv:3t9SddoAuajsc0GJuMXViNw4joGU2T6Ur3QJONENjnI=,tag:TJdyd04L+BDZGPYMynje7g==,type:bool]
            annotations:
                cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:PWsyyrpdKLYWptn8LNFZdg==,iv:JaVH5tDSstgqPfPKCIRsiN2BPfQO6BgMQo3vBX69hJY=,tag:/Y5PqNibhRq0L6dSTV4LtQ==,type:str]
                gethomepage.dev/enabled: ENC[AES256_GCM,data:4Mfr/g==,iv:CE0wzXp6qpf5VFy++rvcqUQrqrsOoxsl5MiuO+i4aFI=,tag:PAg/gdCsibqlyoHdiRaxKQ==,type:str]
                gethomepage.dev/name: ENC[AES256_GCM,data:vp5RUKL2XMATZ40=,iv:MbkHDio6dOFdm8y1Ic6XUJFxnAKc60021lSseGPWscM=,tag:56lnRzUYPAMSGwftkTx/Lg==,type:str]
                gethomepage.dev/description: ENC[AES256_GCM,data:O6VNyEoyaRQyGmVmfKqZhQurnIbW3+9a3vuceA==,iv:8I4EVGqKNRNSXnQFXvX9a10bNR0aAJ/1ylHofOUp45w=,tag:9n6SAbFMH3dr/eA9LkStDQ==,type:str]
                gethomepage.dev/group: ENC[AES256_GCM,data:+qgU0BcSE423wV3qEW8=,iv:A1CFvXQIRfRzVSr8lw+xGi+Gw0mErBVOnFFf6CTtb2I=,tag:WH0gjdft7a8lf62UN5BVrA==,type:str]
                gethomepage.dev/icon: ENC[AES256_GCM,data:RREdrbzKyY9OV2bMmwa18MSe,iv:9fKbOYDFZ0omBhhc94RZAUoCUls5mM4e31raAFhUeoc=,tag:zoj26T7+OIze4wLEzM8+uQ==,type:str]
            hosts:
                - host: ENC[AES256_GCM,data:0DglZq5isaYZLPFqel4Fau9OTQYOTuo=,iv:I+RjdUtwduTukbTd4X2lQkNMcOg03JzLZoWgiCYVkB0=,tag:5n+aIAipFaeZ3kHQPs2CYw==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:1Q==,iv:nB7+kVyjrScccpgqfdd455C5ar8uGEttwMFLwTvLpPU=,tag:JUhwLp1cEb25oQ/dUyC+TQ==,type:str]
                      pathType: ENC[AES256_GCM,data:wCwhvgjl,iv:/gIFpD+Oclt0e8K5A+dBsgYnDJCDCkPxYJz8om6GCCE=,tag:szikWszsvJnZ9RHZTM/zAw==,type:str]
                      service:
                        identifier: ENC[AES256_GCM,data:IeGPYFtqQSFPVsw=,iv:wBmXxBFYfzerAspL4UOl3mbAAnjviPgYvEnqEZPyMI8=,tag:aTUqJnEEMSSqCHFxXqWCSQ==,type:str]
                        port: ENC[AES256_GCM,data:uajsIg==,iv:zr6LWPD0SO9OCsAAXim3ATux5zcVt6zTtAqg7dhthHg=,tag:HegPb/K1+QYu2gvDrVqK8Q==,type:str]
            tls:
                - secretName: ENC[AES256_GCM,data:32E6ILXG73nLw7o60BVX37y9TVI=,iv:L+McckzM6+oLuEOeDjR3xyT2BhaXTYKHGwQsbjEsPiM=,tag:ifOnHkxI3BDmL7smtelbgw==,type:str]
                  hosts:
                    - ENC[AES256_GCM,data:bnB92D9QSk52I68MPVVvaPPJisRZHdc=,iv:JueqGHhiItZXxZMJuQWV2iIjC9oBCCgPoRO76DFIACA=,tag:gXV6Nl4OV2dmZ6GPc/nSkg==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTKzRSVXhNc29XMk5lVFQ5
            OFg3dEY1ZkZSbFZIemtwV3VnVm41R2dpb3pJCktjU3ZrbXZzMGJZd2pSbEJLTElS
            SGtNTG92V3pXRnplL0FSNVNrVTRZN1EKLS0tIEFSRDQ5T1hjenQ0RWFoWkorQy9R
            MHVWaU5nWWw4RjNraDNRNTRjcE9zUkEKZJ2lGomLjbSA/6V6rDDcmI04ab3EIUR4
            028wtRpOXJmCyLA8dVH9s6Oaf0u+6kFAbT9PwuiVqFSk7JmFK+bW1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-19T14:58:20Z"
    mac: ENC[AES256_GCM,data:Q4b+l8UQTW7Z3Q1NycvDj2rNxca7sWpsr+p4dMNxlYxoEbyaHoniIRKHSghVolgjUwzOEgxbbZMLTMIjnML3EBMrfSKYLXusLksZFukUEaKKMitarVw4cs2a/384oURt4qdkgnVbQZSNVwlkZ9k1V30BnjUVhFB1onOBLyttIZw=,iv:0GJyMKTirntbXapE03tY9kU5KqeBVlJ4BP+g8UyTtZs=,tag:5I7F2EC5Fqrt/ZV3TII2yA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
