---
app-template:
  defaultPodOptions:
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000

  controllers:
    maintainerr:
      strategy: Recreate
      containers:
        maintainerr:
          image:
            repository: ghcr.io/maintainerr/maintainerr
            tag: 3.15.1
          env:
            TZ: America/Los_Angeles

  service:
    maintainerr:
      controller: maintainerr
      ports:
        http:
          port: 6246

  persistence:
    data:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      globalMounts:
        - path: /opt/data
