app-template:
    controllers:
        tinyauth:
            containers:
                tinyauth:
                    env:
                        TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTID: ENC[AES256_GCM,data:yjj0SkhNO4tGCn/8FqwZfR2E/KUhfQvSlV+u2ivVuIMXeHXQ,iv:CINgfVfMmDST734zNWOHPWw6UUSIc1GQNrtHzF26taU=,tag:cjUk5z3fsez4Xh7TjMtVCA==,type:str]
                        TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTSECRET: ENC[AES256_GCM,data:TKdCWA60whoP+5ubiVMOSuYI7MFSET5ePklZjuu//VA=,iv:AiRAF0MTr88WSUoHJvAqJmKVY+kT1FKQVCcw/0itF18=,tag:NzA3k2ClmwB19RuuSmAQmQ==,type:str]
                        TINYAUTH_OAUTH_PROVIDERS_POCKETID_AUTHURL: ENC[AES256_GCM,data:EALIJ1s1D5pZ8egddhhCq9YCdRDyPKryBhikh7Vf7a3r1bSI,iv:IbSMScaAtAPRZ0tr6qb86mZhUhgMoJK0o09Vu1v6F5s=,tag:lV6/a0twYCJDdQoBbeXu0w==,type:str]
                        TINYAUTH_OAUTH_PROVIDERS_POCKETID_TOKENURL: ENC[AES256_GCM,data:T5Vx+KapFuNw0KWc2KBXhSk5RviIdBrzqTpGvVozqhUQq5zuxkEDN08=,iv:R3Em4R4k+6HGbHW7JVbZdDOIJPbuJCGYq0an9C4bBY8=,tag:7PEqp2RR2FpkZZPHDqdmow==,type:str]
                        TINYAUTH_OAUTH_PROVIDERS_POCKETID_USERINFOURL: ENC[AES256_GCM,data:O4j74XDFONBpadsimY4DrjoWFKPJOEVNRtFOQDDLuMpTDs+2nXCPtY63iVM=,iv:iSsGbl7Y38lvBBodo8QaVDoHHlYdqQTR3kETLiepMJ8=,tag:Ht8QrQelZ6mhHIQB304Nsg==,type:str]
                        TINYAUTH_OAUTH_PROVIDERS_POCKETID_REDIRECTURL: ENC[AES256_GCM,data:419soFAkj2pv/M0JVV5dXmYVmhuLDgvR17+T1Q+IkvZF+vH2q7qHY/MTVPaK23wt+pVEQ7ZVtow=,iv:BJPDBIE7/d7Y+4FR/ruDUEnJDZrlejfrlHY3pVfPM1k=,tag:ZP0Q/59aHiIR9yAsXA1ueQ==,type:str]
                        TINYAUTH_OAUTH_PROVIDERS_POCKETID_SCOPES: ENC[AES256_GCM,data:K5RQ00cKGTp8Uq1b2Y4UnB205DLUbXgHycqK,iv:1C2Nz4hoeuIzU9xm6+E9FuB5IS0nRMtPT5oFwdt/pyg=,tag:1nppxlQ4ZFBl2kN6BO+Gxg==,type:str]
                        TINYAUTH_OAUTH_PROVIDERS_POCKETID_NAME: ENC[AES256_GCM,data:yZaLyhozz3MF,iv:drsQE6XoyQz2oIvyrPbrWJAcjvqiBlz/Gy+mW1bbnTQ=,tag:UyvQjXx9y9Fm2fw5g7yoig==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUHpXdkRzbHFlL2lzVUhM
            VVg3UkM5cXNsaHM1THRLaFdpb01hVHpkeDJzCnJZYXZKT1lXU1puZ1J4Q0FhdXNq
            ZWxrZkpnODRtbVdEMUpxM1NlQ052UDgKLS0tIEtTbkVhWWZuRi9aQ0dzWWROR1lv
            NHN1WVBmSkN3WmpHVk4wRjRwVnptRTQKBd9Fuk6n/fYNmFNtgGfCcWgSfHy4hEoy
            MndRwU87+AgiLLHCxAJDlIqePo9xs6dJumv9/n1ihbou7JsvJgoUtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T00:59:54Z"
    mac: ENC[AES256_GCM,data:V3KA6klGh9VnsekCQgr4umiyEniVAQSgX+t4hje/a8khaKd86IL39D2DCeEoyOI1ZTCK6Lv+HNJDt5+ZKgbBClthLYY66GuWTc2o8PkXVb5LE91eDkc4z4HCpqXr2uQVKoSnISNvLZT8B/bBOBjLI+h0hN6yr1pOivE+mgyo+bs=,iv:N0rZu2njYMemr1IKRi6Wr/1ZrTXP3XeEtum8trBgruw=,tag:Viz1I5lp1DgTXCive3wwIg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
