app-template:
    controllers:
        tinyauth:
            containers:
                tinyauth:
                    env:
                        TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTID: ENC[AES256_GCM,data:ZP5UBnee2EtcGV0MARicHV+S4EvdkK9IWn1P,iv:yssVDsiIyclE2Qd9Hq+Iic3fIh/Pncuk/qXoAXa9qKM=,tag:WLI53AEIhtKITuCIFQ/9sQ==,type:str]
                        TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTSECRET: ENC[AES256_GCM,data:oWKftWHzx48bh2Jw7bVyh5GzoQeApSeg6s7G7ndu+w==,iv:9yFryPhSfvFJj2TNQSK8zDOVnpTb/gQrCtTF4gdMRdc=,tag:gq5QU33phgj5FpKMLsNSSw==,type:str]
                        TINYAUTH_OAUTH_PROVIDERS_POCKETID_AUTHURL: ENC[AES256_GCM,data:sOfnNC0lo5XCcGeX/7NuLG1mg8BWLmj+xq9deE7KwwQz+duM,iv:I8VDggBStKUs7W7AYvJ5xm3zKeoqtsUUieheH08rmH0=,tag:eJsfOd83jwhY58XaiiGdKQ==,type:str]
                        TINYAUTH_OAUTH_PROVIDERS_POCKETID_TOKENURL: ENC[AES256_GCM,data:pah7SRSHOU5jTOEjPnSvHWP9DWNNVa3fRJOKw0O9N2sDv/ApfH6q/sE=,iv:tU/hYjkCvDsud+OVn7Y8FHHq4lJd78ESULgduBO7HfE=,tag:UtlwULj5Mv8qRigdYnJWNA==,type:str]
                        TINYAUTH_OAUTH_PROVIDERS_POCKETID_USERINFOURL: ENC[AES256_GCM,data:Ey2wRXksaDk35NcAkzszgqWUWOAaawprf6+W0wazYyZtaPSYkb+LO1sq3wA=,iv:7884uE21jCZ0G5MC31TdAwXKxu51LT6SHUi2qzjeuo0=,tag:EtIG9UKWC9M8CD5QzdhsNg==,type:str]
                        TINYAUTH_OAUTH_PROVIDERS_POCKETID_REDIRECTURL: ENC[AES256_GCM,data:1v/9vo3y3XmQzF+uN6vrKda7TOv6BhCjYC//XQabLXNTqFetTCnIktpyphZ684+dFh9rjwp8a9g=,iv:MDRt6nmtz4ot7ZhJMN6HP++jts7MsMPnTJjiVxPRW+Y=,tag:EyjAWLnshUz5Bqp/a+ffHQ==,type:str]
                        TINYAUTH_OAUTH_PROVIDERS_POCKETID_SCOPES: ENC[AES256_GCM,data:j4sj0QlDLlec8hSzmxxJsdRK+KH0wMXOckAd,iv:GBpn9ZrhYYcxyuDj0nHdjRcRzAdGlJKFdE7qsZkk2MU=,tag:bX/WRS8lJAxUZ/7V15lA7g==,type:str]
                        TINYAUTH_OAUTH_PROVIDERS_POCKETID_NAME: ENC[AES256_GCM,data:8eH3h/mjlh8x,iv:w6s4rTnHfS/hjAMHF1gRUX+T8y5Ygb855FrlnZfGi2Y=,tag:t/8Qm/qBZ8Dh8wmsbDpn9Q==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIUENLKzE3b1FuVFRPSHJa
            UzNYcTlLeFlVb09mOFFkR3JBdFZESHBRNGdVCktjZWZvdlpVYkNUaittb0VZSFp6
            VEVaVnY0bWJFcWpBNkloZXJLcXpJWTAKLS0tIHJCNkVRUXJSU05ocXdVVVFuSHl5
            eTFvK3JJMlJBYlBsRWFkYzBRaUhlODAKiqTesKKAw8dJcUlnNBOdzKsLcINnBYVD
            LXq6TuCV0ZAr/dkC117sOtzgg48MsEbi+GuLSgs4wSF0STmlPmS9IA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T00:36:05Z"
    mac: ENC[AES256_GCM,data:zPFYXhEQVq81NM9A5UogO3lMdBUKRtHccF1lfexNDgFasKFILrc33901f4OpPpPijZ4GqY12NRrAVpf4W9L8HRI8i2xWKbM3sAc7rVloo0csB1nhgd9PyfGE35Zc/CPV7y6DibOUNPPyi8lg3X7Wg/7MJCQ7kRd/c9NbrfWzMqg=,iv:RAPNd/5Rh0d2L4j7tb4dyTSoDkGhCH4u1xferDRbEY4=,tag:jj9jeE2oobPyYKHhQ784IQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
