---
app-template:
  controllers:
    tinyauth:
      replicas: 1
      strategy: RollingUpdate
      containers:
        tinyauth:
          image:
            repository: ghcr.io/steveiliop56/tinyauth
            tag: v5.0.4
          env:
            TINYAUTH_APPURL: "https://tinyauth.mdeleon.dev"
            TINYAUTH_OAUTH_AUTOREDIRECT: pocketid
          # OAUTH secrets are explicitly stored in secrets.dec.yaml
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              memory: 128Mi

  service:
    tinyauth:
      controller: tinyauth
      ports:
        http:
          port: 3000

  ingress:
    tinyauth:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "TinyAuth"
        gethomepage.dev/description: "Forward Authentication Proxy"
        gethomepage.dev/group: "System"
        gethomepage.dev/icon: "sh-tinyauth.png"
        gethomepage.dev/pod-selector: "app.kubernetes.io/name=tinyauth"
      hosts:
        - host: &host tinyauth.mdeleon.dev
          paths:
            - path: /
              service:
                identifier: tinyauth
                port: http
      tls:
        - secretName: tinyauth-tls-cert
          hosts:
            - *host

