kured:
    configuration:
        timeZone: ENC[AES256_GCM,data:EGCZYqxAfo8kRo3l5dpyZR5rBA==,iv:Py+t123hy3mrX5+gk28m6cCytrZVKUo1UG+BipZDzg4=,tag:r5JgBoOdq+YUK4KNKZkxFw==,type:str]
        startTime: ENC[AES256_GCM,data:vBgVnUI=,iv:OcA+F3OCUrXIdnzBzDrHzjxIuyd696BA09OMvXusi6w=,tag:nhT9V59Do74F5jGYl67jsQ==,type:str]
        endTime: ENC[AES256_GCM,data:pG19VpY=,iv:ARZeMQDc7ToZyzJxFLI14nTWbiiUTa7haub9ZlJAdhg=,tag:qPqVwg+mdqipPmoXQERvJw==,type:str]
        concurrency: ENC[AES256_GCM,data:Wg==,iv:FUwYfhwsNQQMdhicWTRSG46gQ+N7wNZa830bmLEm1I4=,tag:/EDHCsPX//7fHgC5FPvdkg==,type:int]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3V2JPdkFmRi9OVDE1dktn
            SkN2RzMxS0dZRDRCMWtqVmpkUWxDRUlXcjA4CmRJbnJqSnNWMWV2ME5hUHJ6RTB6
            TlVHbEF0RGpoUm95N05hcStPTWYwdjAKLS0tIEFMK0dPVXR5MXZnbTlYeGhKRzFK
            YVdZY3FKT1N6bEFYWjZIRGw2c2xPaEEKSmQk3+VuAwexG4Sdo2oJdO14LFCrd4RO
            OgDu+RkID9vO4s9pI2uReQhlmkzBRSqmVjQ/qonn6I+WmyZbHDnA1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-07T18:06:53Z"
    mac: ENC[AES256_GCM,data:r027/nm3m2iWCSNh8FMNwtuW96olXZNFwFVhzFHgbntUDbbJt95fvpv0C48dODxhS2g+Qh0Hi1eK3uC5czNLKidSWIsuAfA6slQ+pdbWMzm+tzgut49Vs+0NxtwfuW0UOux5qjZH5OZO14Wy1QDcTJfFDnq1zayfgaA869EzsF0=,iv:u6csw4aWALQuzRYVB6HwMC0kpAWhR+ZGHJCx63cMtz8=,tag:M9/x3tBryumqEQD/eOpkRg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
