kured:
    configuration:
        timeZone: ENC[AES256_GCM,data:OHGiNICloH0/m3J8XWOzilwElg==,iv:gcRNxkBC8WuD/CJqMKoEIUIYjJgqhhDwb6Qq2Yin2+g=,tag:fSIJmUEcQfdd8WdZQOQtjA==,type:str]
        startTime: ENC[AES256_GCM,data:ytHntKk=,iv:b1+elwsdhlDCLhhh+X9/gBT+F2fZayW05ThmQ/VDsf0=,tag:WId1HBZ3KlSzrBjPIH6XpQ==,type:str]
        endTime: ENC[AES256_GCM,data:3ZFWE1k=,iv:XJWuYQOH371/8JZG58Cl/QFevxa+itTIjFCdEkaaRf0=,tag:R+uyRrvdshE633EGWITEJQ==,type:str]
        concurrency: ENC[AES256_GCM,data:Jg==,iv:+kjHcclvCXWy/XEDATB3G3hjOojzRMkikYf4yjAmdr4=,tag:KTXd6MM6HzRnFe4fOlHatw==,type:int]
        #ENC[AES256_GCM,data:1ir+AjJyGoDMZhCCV4HpD8DtEpIeONmDxxTfHuw8fw==,iv:+Ty/WnSYIZ3GPfv8czf09AV0Np7GATSu6M6bWjapUZs=,tag:1DkxlFxS6LW74NPU+BOirQ==,type:comment]
        drainTimeout: ENC[AES256_GCM,data:Vnuy,iv:8otIDzuWtrLAe+cPIJE4ySL0XHUQZsZS5C2wWvC/lfA=,tag:EYa9cI7RYUF0cNMcMRr7QQ==,type:str]
        #ENC[AES256_GCM,data:qHXidsWqIXuX/uTqyw==,iv:KNn61hWvoJy5exqsSvZh8ttZ/HEStk4epeGHpt8z/3U=,tag:Y+yIgmz0AuJACvSTAX9ccQ==,type:comment]
    tolerations:
        - key: ENC[AES256_GCM,data:8/+LJtVm4+eJD+EV03z9kW8yo1geyCX4YASVSVaT,iv:x6+057zRX2mC+0gDM9rX2sM3ggr7q5POLnWZn0w2tuM=,tag:GYrG3sAtbaBJbqCPZoAqdQ==,type:str]
          operator: ENC[AES256_GCM,data:YN1hk0xe,iv:hkVqn41883Wa5RgDNxqavg/PkIzsCo8VWyVoGWlXXb8=,tag:C+dWhg+MS9SObI5SBlFpWw==,type:str]
          effect: ENC[AES256_GCM,data:XGXTykPuYDArhA==,iv:UEN0quDTYOdw0Sj2xPVMZAfhqsrUXKS6Mce8n2/1PAc=,tag:2FddEcg8tjV5LN75gP5qhg==,type:str]
        - key: ENC[AES256_GCM,data:tRcPx9GEbSk/Xm6EegSNm1PQi1wuNQ1e4MM78M39MkDj6FlkIg==,iv:yhQLj1Fm1c+xtnj8CgFvvs3ZdaWE8RlvVc8xLVZmCK4=,tag:mPDQCTqtToTZ+5XWLuuCRQ==,type:str]
          operator: ENC[AES256_GCM,data:Nplpl0RL,iv:OeR7pDmLSPJYBgeaxMzSUauG9a5FW2fFOtn+th3Oxk0=,tag:OZr5zxIwuyfqYv3WnmhLmA==,type:str]
          effect: ENC[AES256_GCM,data:s1kmFDbTLV9/0A==,iv:JHD74mbFq1zBMh1Ce3qlnnCqXCP1bXcbDH6mcF3CO3k=,tag:U1hY4ePww0oyqj6rDOPatA==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUOGwwSndORU5hT1N2MWVO
            SmlNdGhoZmlvdlE3eG05bXo4Y1ZwaHNtK25BCnFMaGFlcWc3VDhBNUorc1RXTnF3
            bjcwYmJmZGlaTnBlQ201ZDczNk82VVkKLS0tIDJZRUI5MW5hVk5vRkNPbm1Tb0ZB
            c1lBcTdOK0NDK3FpNjZKaThnN2dWUTAKA/FnMqTIZW4RniSYBu7pD96i3yZopGA/
            pSP+WcdU7ERB5nu/F3fiQZ9Ry8Z11tef4focsyBx3/k9jSJMEXFb1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-07T18:15:53Z"
    mac: ENC[AES256_GCM,data:9JxyMeUJ1AIWmdRsVOLJs2nUx6vduXiopfmaMj0/otMXy95tRFkvkeoBM39BaJbHMXxM9wffGimRESNXLnAXfQRs80SNKbLnfFT984TX6Q0hH3Oli9+l1CNTtuhx3bTt2gBV2MdbXWsbQnEJ+s7vTqXYtGmY/FV3pS0I3f4MIoA=,iv:z+cP6g36LdlrE03aguqY3JraKHvaAI+efL4K1YQiPSM=,tag:nJAzUAJjAfvRs8khUlcRAQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
