kured:
    configuration:
        timeZone: ENC[AES256_GCM,data:vAuclrZEBkAj/ogrr7vmDZBYMw==,iv:8ThYXXOO2R/v81FIj7VjLpnFrPrwxXm1ntP1Wvh9IwU=,tag:s8eReOBReq5N8IAJsFH43Q==,type:str]
        startTime: ENC[AES256_GCM,data:DFph6ig=,iv:DJKbPlbJU3cbeHnH9B6Bj8Pk/z7CfBJq66CYoGaVRuA=,tag:jhMgoySvg6mYXcCMdg4CVQ==,type:str]
        endTime: ENC[AES256_GCM,data:9sS9UvI=,iv:qIbSGBffY2t66uzz6xHOC42fc2sFpOigXfnuk7EL94s=,tag:/VmBztUCodmz/RwTeRHDhA==,type:str]
        concurrency: ENC[AES256_GCM,data:TA==,iv:fT0BnPyGEAJzOcoFWLMoo2fuuwObLF5mWbl32HIHK04=,tag:u4d7KlryjqFB0I8b/1oOWA==,type:int]
        #ENC[AES256_GCM,data:onmgTpXrGGzORqLXCk+NZI5Zm4bj1TC1V3kaVXQN8Q==,iv:wxzzFokEVZJ4CINGmo7TpmAGMo+MJFijMyn5t+OpIZo=,tag:H0mB4smrUxkosDPRTQ0pjw==,type:comment]
        drainTimeout: ENC[AES256_GCM,data:Ej4x,iv:YOOM/rKPEab+JjAjTPK1LbeYdnEfaV40MhWmEmNXIdc=,tag:PGqIazdDLYXcxAv7wQqX8A==,type:str]
        #ENC[AES256_GCM,data:3WaX9wspo5ne52+Z4w4=,iv:7Ecz+uf6+cgri7bvdjxNTKeTa3DShc7COm+V6E2mlpg=,tag:tWylUgkKuRMAunuGHSL3OQ==,type:comment]
    tolerations:
        - key: ENC[AES256_GCM,data:b0rthUmOAYF2x7TAr6NmgqD+MLXv4ZafzFqE8dXk,iv:Gomz066GwZZ3UgUlzlWDe9gZUkrmZDroCYMhMr6YOvc=,tag:iUGLiLyP6yMc8zVZoY2eZg==,type:str]
          operator: ENC[AES256_GCM,data:RsvQe4qI,iv:1yoAA69dO/Sxs9lR0YFAqA2xv14ZOeaMfFHmuIrSQxo=,tag:t/PktklK4pRLIfNI3hWY0w==,type:str]
          effect: ENC[AES256_GCM,data:6maLSAS/MxYEEA==,iv:cIWWjx6KctmDEgH5WvPqbBpXgmY5QP3bHKHScbwnVQ0=,tag:smsZQ6Xvs+ufUtCnuOOrBQ==,type:str]
        - key: ENC[AES256_GCM,data:9tkU8GFhtsNxS/eg3U2Ynupc2dLNOSznJeHG+hFtMC74BgtLGQ==,iv:Lg/ORsV98qfcvk9RFda4H1QSS4707vJ4hSdpKzSYfJY=,tag:gmGmWmkddwZOkHfyFjHugQ==,type:str]
          operator: ENC[AES256_GCM,data:IeZBn+Vn,iv:LNTDdC7MXIFebk4gfyCtBkbsrQUCoQXxSgcMfs/Dy3M=,tag:6XsQWKEYZc6b4yk2VctnWA==,type:str]
          effect: ENC[AES256_GCM,data:Oq6BELKmD3Q5tg==,iv:IkM8gzMgW++Mhaylbax80hB/QVIsVur8xRwP+EKb4YY=,tag:MNzoIvl1UsPhBKTj6ajxkw==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuL2NlZWpMRHJlMlhLNit6
            YlNtcXMrYXcrUjFtdWtYam1ZbkhPWGJmWkZnCjJ1RFZML3dsN2pLVUh2OXNmL05q
            S3ovNGxORkdaTFNZdzFqY201ZGNxVVUKLS0tIE8vWkowcUVOOG1RNU1sTmxTWkNW
            Q2ozL25MNHJJRXhNc2hPN1pxeGR2cVUKnpwZS1gO9VgF+J3fm8Vd+Prpvvu4Vryo
            Kl8+prIMiw9u7lJ1y7cYhTGBfK2ODzi2kZIxRdEdCAc66If2Y8nYjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-07T18:46:31Z"
    mac: ENC[AES256_GCM,data:rRnIaaiAsBJ/PyWVQPK41O5/R5fvpXAgyRkgILO5w3VumeSgaaQwfK70zWEqxm5UkaEvBOScpsJoKsPD/snHysHSboGuJgHokkM+LzqLsldQPM1GakOYoCq6YVbZ+nS/1A443r3w8CjsDW+ZDHNidVDUB+axlcxg3MtvWGvGACM=,iv:HNT4Q77oWTwOrZNiKe6UCkFae0vnJAdRBkI5WnF+4vE=,tag:kVUne60KkaiyLG5zPDQieQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
