apiVersion: ENC[AES256_GCM,data:nus=,iv:yZ8lqizLv7i90OPIpHQSQzXH9uihUNCLbkTVLtvBMUw=,tag:qW0sfARQWtwt/r04Tzw8yw==,type:str]
kind: ENC[AES256_GCM,data:N1fE4vlP,iv:h9gsKyvwI/QZcfcdvsWJipGSW+SoLvYl0PwBkybKbx8=,tag:iuCcagOYxqGKuGRZMyiaGw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:jbdFurQOgPsxo8vEWA==,iv:V243KEHAQDzODF84fNMBe3wELDSjk0ELc/CXTWAhDqY=,tag:VxBRlKN6KQ7RuUJdRVSeew==,type:str]
type: ENC[AES256_GCM,data:mvxb37SM,iv:EaWmbIzLM5SSaACUxOvuLAUoXhxa/n1Y9BXOiSHT76M=,tag:z48jTY7KWmsTg+tE6VBW9w==,type:str]
stringData:
    CLICKHOUSE_URL: ENC[AES256_GCM,data:HZoc/nqvqXmm1HBJD3OydRM/E/Hb70z4k/Va04xUx7YwZCklOKPHT1Klok09+arleMb8JEponnNDP3W1Lt6d3ghoAQhsz/MUCpDwg2KFIyvIICHPLWVzahOvB7hNrqz0+LorBLjRpyKq5QOWXnE=,iv:M0KGvQk8XWmEQ4DGiRXgg6x4XO3Vf5j/HIFmuttum9w=,tag:UN9OZOTkmu9uJDt3PrZuvQ==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMVcxa3J1OTdTazAvNkRp
            bldheXVOQnpITEJxSEY2aW5KOFNsa1piMHdJCjRhRE5aeDlqK1pROXVnbmRrUStW
            Z0JnWHEzSGJUdzJjQ29ldTlEWTBWUzQKLS0tIGxLaFJNMXpOcU1JWEl3eWovc3k5
            ZmU3UlZXOUg4MVZSbGdZOHVPZjVKbFUK9D88NPK3vPnxFzpiMD81w2IgJr97V/8B
            JB62zLiKf6hL43E1aeNBggLPKbcq/0j+nQmYeidOG0//s6LLTBvMSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T23:27:50Z"
    mac: ENC[AES256_GCM,data:bPKUpcjXMs7qvxa+2ccJ9VWZDCMBNaTjHrF/zH79fX27eaJRqjXY6RTgO5pLLmfkFr+cSWFACtWrNNP6lNxxKzbBuPkdE9xbXgdtocRm0muJoZU1FEZuyrIA5VWEaDTa3QL7bdInRe0Ayv9y/bGB5PPiqpxlIzc5UEMIS7o9Tjw=,iv:eidnH3XA0N492eYmwtDx2Z0zHturYVLhVIZ4VpZM5Do=,tag:btIWLgbBAIM/YpLkOtw0ZQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
