app-template:
    controllers:
        ch-ui:
            containers:
                app:
                    env:
                        APP_SECRET_KEY: ENC[AES256_GCM,data:IDjkn8pN7v50ddVJvYQWp0ChW6Jb6KQjPS46eSb5Twn1PlG0qyn3BMZeYXY=,iv:FF0lofgdSglOQBCrWB/GUU2yy8BHn2gMmh1C+ClJNRI=,tag:C+pgbvrOUvQQIW7GAjrvEw==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1eWFvOWFNRnRKZ0FUUmNr
            Q003WUlXNnZqZFRHZmw5cWtRVEVSeGl0ZUZZCnJqbklSRjZ5ZFlNUUNkS0F4bkFZ
            SjMrbkgxUldJNXJiUnRaUlMyZzg0U2sKLS0tIDJ5T0Mwc2F2MWN4cnNqTjduMUFS
            ZStrUlFRdUlHYzJqMHNpdy8xWWlpNjAKBA++POGfw0HVarictOoCY17R3HV0WwuU
            PW0tDaLo6DN3S1eBGd0oshYnSQD7v6HXILj4LQmGlYTiMRFs8VKRsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T23:56:14Z"
    mac: ENC[AES256_GCM,data:SZCkEomiid186xx6UavYG7D0BhBbv6psxuMPyTPkRTT9Ub7lrXAAk9uE60QxVsDdBROZAJp//o2XIjdt5/ooizVpI9fwFOQkTmcU0BxwaOWtafkkD996k/D2oOEG72dznW1anyNOg2yBppuAMO3MiTwnON0QGitrsxD/JvR/EHE=,iv:Eg9Tq1Wmnoq7xaJmJR20EJjedq14I21JCJ1X3JpJJp0=,tag:d/QE7PzP1MK0smQG61mcMw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
