victoria-metrics-k8s-stack: null
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkMzJjTVBDalJiR3M1SU1E
            UlJ3ZEdDOWNxenhhb2JhMXdhK0kvN01aNFNRCmpHNlNxVklYVFlkQS84Tm51alhI
            Wlh2L0x1TVBodlI4b09hbklKcXQ2cnMKLS0tIFZhYVU3WDVTTWs5K011TllSclRi
            Z1FLcnBFSUhqaDlSTEhTYSs0RHAwYkUK4KCTV2zzrB9aPnn771BLPCDI5ZY5snlH
            V32zaKBsQ62kxx3aP1WNaxr7hcaSRmN23uQW3trfNYDKbj/d4lf9ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-15T20:16:38Z"
    mac: ENC[AES256_GCM,data:T2Ief6FRbZ4ndkgA57nb1Q8CjzhZQ5+RnvXrel1OG8faxxTFm7Z1MlzlyeD5Tj7PpIz4HBgmnk9mSgWA2Yp87Y8zz7aD9NZpi2BW2HA5OYLPkQpd1mphS09HJQCE8tHtHtHcoyc5h9Yf2sNEgr+zwkznPZ5AoUI6KRnpIDrY6R8=,iv:WXKlf2vuiM2ySRUsvO7t+lo4GU/oAEjAPC7HsLCzUvM=,tag:ZgxL5LucukeMHsEEStYRaQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
