---
apiVersion: v2
name: karma
version: 0.0.1
annotations:
  homelab/description: "Alertmanager dashboard"
  homelab/url: "https://github.com/prymitive/karma"
dependencies:
  - name: app-template
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 5.0.1
