seerr-chart:
    ingress:
        annotations:
            gethomepage.dev/widget.type: ENC[AES256_GCM,data:k6h0w2w=,iv:YW5Q4iCRlcvr62HcJ28ZIahETKfbxn3dBL/ykf1soyo=,tag:ca3+pe5D+4KnCwy2LeE55A==,type:str]
            gethomepage.dev/widget.url: ENC[AES256_GCM,data:UzZcsuW/Yg15xa/bQ6Dk9MrY77ItqL3aa6E1PGDP7bdh1ua49QEl,iv:/dyzWdAkKRdaSTLdT7DltOT+w3qiz+8ZHhZC6YlftME=,tag:OcY8QRWEDUY8dUV39L76LA==,type:str]
            gethomepage.dev/widget.key: ENC[AES256_GCM,data:3ns67GY0g8Ca32sZFW0ABQudLrkCnFQ3/w+/DDYG84Od5+J0bKRoAt1IfSr0uxDy/dxNrGT2oZxG4Dr6gbhsWJFWjKw=,iv:l43inbPfqiciORU1kPHeAlU/fID14TzdgkhEcS0fQEM=,tag:M/ZZM2V8FsN+NHbFInK3OA==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtcVd2MloySHlxYklJNzVS
            aVBxNStmSUdLSUEyY3lUbzg5R1NxRnFKTldvCjRIZHl6Z3lUOER5eUMvMHNWTEtU
            bVJpaGMxMjFicHFvNEJ3Vkt4VmZhbDQKLS0tIDNCTjdSbTdiVk1WNDc5NUVyZlJ1
            SGEvRk8wS2lsNjl6M0RZc1N5ZFRoamMKEqp0NtL378fC+rQ3NHYECEi/ym52DgCn
            7xa1eoh1XZk+7r3KZK/3ii3MhRAvZzANQOiUvjdMr+XXXjGTfEP9qg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T00:58:45Z"
    mac: ENC[AES256_GCM,data:vxEuv8DwsJso6sNnvnW3RagLKeSSLl9ON1ldh7C2Ly8R+GFRSNHPgjsmt9+V4YkBbSDsXC4uv4TaeSPg98fmcTtghb2uehRQ7dFx5dsESkA0qse2bqcW3CPtlUCiby3/v81jm3/Au/fVKCeHgwhreKZYBuJDKPbbANONaJgGy6Q=,iv:47Bz7n0xVywRIQnY/Yk/nEypprbz43keXSZxqIwHVdI=,tag:TdgaEpqFNnuR+rGN1gwIUQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
