app-template:
    controllers:
        actual:
            containers:
                actual:
                    env:
                        TZ: ENC[AES256_GCM,data:YAVUdA2DM+Gu+RsccC2dc1Vj/Q==,iv:lIZPwXEH1jlJ/a1CvpaykO/Hsn2178XkPFIBjqPvUN0=,tag:wxNlxwbMiWe/S/moZPF7KQ==,type:str]
                        PUID: ENC[AES256_GCM,data:wRB1Cg==,iv:aJYX4b4ehgUZ4qNLTmr98EsIlopeoeG64EoYTLn2B8I=,tag:+r+J0IfTIY2yV7NPYHD1OQ==,type:str]
                        PGID: ENC[AES256_GCM,data:vRRfzA==,iv:Tg38iGumQ0U7g2EOCVRxeb59okYaHsY2h4DfppN29ug=,tag:z99ygfgnWChRFsALgRgLHQ==,type:str]
                        ACTUAL_OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:0mMnCLuEDu1rhlyhT7q5Z1EwLGpQLqFalEY0i3Ukfrc=,iv:ZJ6Z96Kz7FHcq+txHZAYNu42cEmiIZne5UZ01SixySQ=,tag:ebM2IfrOaXCPGT9e5RsCGQ==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtcHloQ1NkUHJSY3hnaU1a
            UlFBRmxONDF0Y0JTVTRoa3FSMndDemNoNUVRCnZXMDF6c2VDYnNiN0Y5VW9DWGxO
            YndzNjNOTmFlSTFTZlJra3ZQK0RSZWcKLS0tIDZ4d0RGOExZckwxYjRDeDFValZL
            K1ZNMnZtZ2NudmVlMXVKMlVZL0w0ZVEKqspsGyFRiKXh0y+xMkrd0j4TYbuwghu7
            eVzxWv+RE0ORHf81Vy/oZeM01MYRSX8ZqzsIZJF7FZHzOPWou951pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T01:22:47Z"
    mac: ENC[AES256_GCM,data:Skf+vQqe2aeQSIWxRdEUyqwkty8lEOtKQP3v+Xjif9wthhzpVfO8qyHiMKgN2ZchjcxublJEIX0odLVtGComF8XAV9aHoQANQWejMO4LGM4igo5aakJcYfhk92QygThZ8KQO1GT/KWEjLAzie0V1RY6n1l5KlP6ze6togSPlWtw=,iv:HO3+HClvGujz07WC+WdYzuympj6tOwkjuebwmoiiZIg=,tag:lYCugfM6S0EViE3a6Vwf1Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
