app-template:
    controllers:
        actual:
            containers:
                actual:
                    env:
                        TZ: ENC[AES256_GCM,data:TFESIjAb+7YdyeABHH+OkzI+zw==,iv:vkic1SPRTdheZkYu/CdAed9pDOJgCL44k3De1CCUkTs=,tag:h//8YomGIl2LWG+Y3TDQvw==,type:str]
                        PUID: ENC[AES256_GCM,data:6gBbeA==,iv:XGSv9pARA9iF7Rj6yEWMEiO+u8EKanErXjGvGpnI3tw=,tag:APY+8b6mwXwPa2qR0AILdQ==,type:str]
                        PGID: ENC[AES256_GCM,data:bPdwCg==,iv:TZmQaW1V4V/JTcjWqwHY1z1r8AnP552AVn4z+o/y4F4=,tag:dwOJzEbGzG4vV+55qCew4g==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZVVScWNtbktDVFNIdnQx
            aDVLampJbWFvaThyZzVLSkRhZ1ZMK2NpdWtFCmcwMkVDU21QNWVWVGU2TGhOd0M3
            Yisya084aWh5dFlUMmEyd1Vsbng0b3MKLS0tIHVTaUkyRzVKeU9uNGNTc2xVeUJp
            aEI5bHgwWnRMclY5SlhadXhmSE5vakkKImStG5WbYqvrlwKEluXqaIJ/nxtrm6/a
            J48wCptTvry3mLXDFguYNO+zvLia2vbchE8a8VzVW/WIhn/uMs6wLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T23:44:53Z"
    mac: ENC[AES256_GCM,data:P9mZYjTlIfFF+mnzWhFmPz3mLY0I9WoCNkb6u+GU6T507+i5ExuuMZdozAL04uzrFKA1zwT6m6DAF+ijAup6HP0OFKkcpH1UaAmbnXyB+Ap0x7sUZh5sSKarZFmkHyscmDB55cJjZX/z5LVWcCDY4kTMCXha7b/dmCzN6jLCGKo=,iv:bnQXPbPTOHn8OzKUBndEX9B5MD6keZ0q1f3N7AZH0FQ=,tag:VCNGIxozsFQUpYb5aAnqaw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
