app-template:
    controllers:
        actual:
            containers:
                actual:
                    env: {}
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlMFRqbW9SMjJMYjl6b0Fk
            SVlRVjFuOGtGN1NaL3RYbXdBSDlLNm41d3prCkdYWWRsSGNFek0vWU5xeGdtaXFl
            VDZ6K0Zub2lEcCtLYTd4dms4WmtMY1kKLS0tIEN5ME9xR09lQ2dQeENLRTJmcEdt
            ZWMxU1NzTWJHWHVaMFpaemZkWVFCNUEKEySGm8D7Y6Aw7mrezPmfK9U7VmfQXaT+
            U+aCLzF0CxGEqWom0jwbDW3lR1knrVXO/7yG1Q/NCoRRTog/iPj6hQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T23:28:55Z"
    mac: ENC[AES256_GCM,data:y6Nu+QhguELfuCWiOtIjFuzSZXOt5D4KeP3ycBeAZIGp0URAHXz0JxAWkNRDsjQGJVYN9QIwvfD/2NBxcUvzK/TMipFIGqadlW9UATZhJreCOg+FzEq945M/nrykmbQSJ6HPa3t/hwfkBPnF9IXFY72AlDZZBigMMnnmrrftwBw=,iv:cNklRu6Du1wAFQIQ2WoFupvj06vh2izj8+dU7kxbc4o=,tag:BMHmKbRf83VrLuezvbghnQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
