app-template:
    controllers:
        snapotter:
            containers:
                app:
                    env:
                        AUTH_ENABLED: ENC[AES256_GCM,data:wxhDc/8=,iv:0xYu95Cs23wdrANkrUbz7u379zah+8fGczEGYnImKAc=,tag:zqt3PfohCCl9yuV6B/sirQ==,type:str]
                        DEFAULT_USERNAME: ENC[AES256_GCM,data:0p00hfc=,iv:inWGyze+vT/ZTEZ9pb5OdliMR1BSQ+g4+jaJRnVkVYc=,tag:dAId6Zncec88TKvlo/5G1w==,type:str]
                        DEFAULT_PASSWORD: ENC[AES256_GCM,data:wB8fkx31/N0mctOYCKuLbYe9dPLV1vMEIor6VNyr4Eg/dM0QlNv7YjuQ8Og=,iv:b9medtliXyyEirrPuMpdAgRuDasB6emkcPrvQEbyCX0=,tag:2Av3M6X8kMQY/CTqBotjSA==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSkg2M2ZQZjB3VDFRSDNq
            VThVUFFFbTZqcHdSTlZNelRRV3JWM3ExTFVvCnNZV3VtZFVPSDZjMXY4NVlPOW9U
            aWQ5SnhjSjY0VXEvOXR0UEJIZ3BjYlkKLS0tIHBWaVdQamltRHNvTXIwYXB2Mmxw
            NVhlYzNRUDhCNjJBbWdxR0ZDZlptTkUKEKPWsxHcb0JyczUwUViBiUIyR0FTwmg0
            wKwlbCOqBPfDGQe5tjBnEYpNmfhuvygViwqUkNYXa1r6mC8amKvtMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T20:26:38Z"
    mac: ENC[AES256_GCM,data:UKeoejsx8oJgKfgB3O6qtTxDMskQrG3Nd9tmctEUOhdXgjY6RvBV3bsKXr412uZqp2zsuHTCMOdx9TqrCk3odsqCcejsgcEPIrrYdLsf1ltoN/7qns56ncFTwFTJMaKDjjzCLJoE+2d4PsUfVYD6mAQWoKNLVRGBqDV8YHMZZC0=,iv:5MqtfTl+TzhsRh3V5g6CdUnasbOqhwX2mcV4R/AxmMQ=,tag:KtUGbaHr4iitNy9S8RgooA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
