---
app-template:
  controllers:
    snapotter:
      strategy: Recreate
      containers:
        app:
          image:
            repository: snapotter/snapotter
            tag: 1.16.0
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              memory: 1024Mi

  service:
    app:
      controller: snapotter
      ports:
        http:
          port: 1349

  ingress:
    app:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: SnapOtter
        gethomepage.dev/description: Image Editor
        gethomepage.dev/group: Documents
        gethomepage.dev/icon: "https://snapotter.com/logo.png"
        traefik.ingress.kubernetes.io/router.middlewares: tinyauth-tinyauth-forwardauth@kubernetescrd
      hosts:
        - host: &host snapotter.mdeleon.dev
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: app
                port: http
      tls:
        - secretName: snapotter-tls-cert
          hosts:
            - *host

  persistence:
    data:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 2Gi
      globalMounts:
        - path: /data
