open-webui:
    ollamaUrls:
        - ENC[AES256_GCM,data:L2MBBoKCVEgNcdhWvoW7JbGWOwEOZBrX4/g=,iv:0KRbDys8ewBbKvE8ZsdKIVcnCZeHatZwu6ElhxGA244=,tag:6pr5/9X2aL+ZXtBqgTvuhw==,type:str]
    ingress:
        enabled: ENC[AES256_GCM,data:0VBrkg==,iv:b4aDFg2sISxEHBoj7Nci6TiT8CR22SkM7WAkFgdQJTI=,tag:dp4ZbFvvF7qbRWd7wstYXw==,type:bool]
        annotations:
            cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:1ukL2pSPcFJ9dSIWtZyenQ==,iv:suZUu+F3eDgoYf4pKrJe9yU639ODzSxVErV6fxVfmOI=,tag:Zb2LpW0caf59NzVWuM861w==,type:str]
            gethomepage.dev/name: ENC[AES256_GCM,data:CKWmooyBajqfNg==,iv:ig4JMyFzG3ojjGN5aysgFj3CThzLEGhfPtvjEdsXqpg=,tag:Oquelu4infVx68pzMiCTAQ==,type:str]
            gethomepage.dev/description: ENC[AES256_GCM,data:6MjO7HXhqE/urww=,iv:QUZ+DYYBS0mxCEX9RQp+ECxy6n8TU1s0R22cc2JP2Wk=,tag:6HdmI19d5RljqeEtqZh+Mg==,type:str]
            gethomepage.dev/enabled: ENC[AES256_GCM,data:+cPunA==,iv:B9VDX74T0pJGki8pbzGZBpyoByn2XD2AnxwL3Z4zp7A=,tag:0VAlL6HE4xPRfWjCWzUBbg==,type:str]
            gethomepage.dev/group: ENC[AES256_GCM,data:Nvo=,iv:lZX/gvzuqHfoycwjc4FmqYYd/GcEJSMKwK5mQaZ5aL4=,tag:yC+blQcEtooRt0n2b2FuYw==,type:str]
            gethomepage.dev/icon: ENC[AES256_GCM,data:YslXakLfYOeokZS83GnyQwk=,iv:5H83n90vFk/oVPf7dAfvg6aol/F39BKyqjpBlw0TZzM=,tag:psWiDKMQ9jvl0JDFWXl31w==,type:str]
        host: ENC[AES256_GCM,data:BZFc+oYZAGKor8iB4gbxt9CtlweGvw==,iv:j//k/cD/aeB8/Z/ZdyyItguiAJgMyhlTgMlf8tWD3z0=,tag:VIONpmISje+QO/p6QUux8g==,type:str]
        tls: ENC[AES256_GCM,data:BzG6DA==,iv:sFwplAZMwBVRqZZxBNMOMT3ULnnt32nStTOWFs29/Mc=,tag:KnExzgtzaywVt0s2VwfZnw==,type:bool]
    enableOpenaiApi: ENC[AES256_GCM,data:MHajoQ==,iv:vBVCnKCNq+JF8/jxvc4zG3NiGXgBkTD6lS+Rf7hbLxw=,tag:HqfrZORF2jzy+i+70RioVg==,type:bool]
    sso:
        enabled: ENC[AES256_GCM,data:2u+ayA==,iv:CiaOby5K+7jxpRXDODbfYuxs+4tQ3+RSKjTMgl99jM8=,tag:o9vexnRTqTPBPSNOR+X6Dg==,type:bool]
        enableSignup: ENC[AES256_GCM,data:c7v6ig==,iv:xgsxZE0igQkfSD7frr3+HEoBusAzrGofB5IWnQA43pQ=,tag:bh/DaDte9g92dS5A973ypA==,type:bool]
        mergeAccountsByEmail: ENC[AES256_GCM,data:ktUSww==,iv:MFDcFzR9U367IObhj9xwEHZRYVCvOaQjXeUjW5BhdWo=,tag:rkgNFE/BD+dOwXkVtUnAgw==,type:bool]
        oidc:
            enabled: ENC[AES256_GCM,data:YpISVA==,iv:zmhsEfv1OhuVWrRq/D99IwThA1WgKcBNERMCXF25oQk=,tag:LbXLTB1pUpX/TOmcWbyHXw==,type:bool]
            clientId: ENC[AES256_GCM,data:vZl6A2iqI736B+uY6ctb+iLCTRIXvJJ+ldYlqArw9CxCcvTY,iv:Xfv+PDbsyMmA8UUn2YeM+hMlI07/cmqSFBiXVYm4WGg=,tag:EL9isOfpYmoNFRLj+E/1ow==,type:str]
            clientSecret: ENC[AES256_GCM,data:RMUF+h6L6gMRUPFWlE8q1sVQcBNLxV11p+HsdXfJ5Tc=,iv:iCbA1x/tw3qLLZ9tqlOofyMAuVkOa90liJIa4EFIgv8=,tag:VOW+wXle+rOX3I8VXIOWcA==,type:str]
            providerUrl: ENC[AES256_GCM,data:cfH8sA/ibi238svIeB73PGEb8VaX+7liABjD6I0odBM0PJS4BigrP/M+Ap9v6VZXAvCoqrT7pBcTzew=,iv:cas1n9e0IDjGCY8sBnJCdFuZMCsRGwBxoEPlLcKJGFM=,tag:Mg5F2ls6WSLxwrHB9zDZrQ==,type:str]
            providerName: ENC[AES256_GCM,data:z8nVxgFM+fiZ,iv:M6CF4yE/lu81MFZy/x3k0+/plhB0crZJEXnUiM/PV7o=,tag:GyXjpSNMv2URNGqVPfvQ5g==,type:str]
            scopes: ENC[AES256_GCM,data:P2qjd1cbM3B18R/QCctqNKDdF7k=,iv:85TF02yOychqoL6Mq0WweZJE9wRhZ1RNkvy95CgGDsM=,tag:q8yxcF8b1pPZRPFlzhscGw==,type:str]
    extraEnvVars:
        - name: ENC[AES256_GCM,data:bkv4IQFwzgIQ,iv:4H/EqVYQK7aMkOJfXVC6tTTIN8FjzjvHKhCt1ScZ6Bw=,tag:JA6sNf9+bXxZhW1TH5BMuw==,type:str]
          value: ENC[AES256_GCM,data:Pc3O7aL7jEwHjI7XWupMb4jiBKtCq8ZD+0itQb3u,iv:n7ANZ4T6MXx1+X29OCXbCFpG1kyzslAv657D9E1UyBA=,tag:V1WSVo6H6dusdJ2LP40mrA==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1YnVtVU5JRVR6a1g3MzNH
            Lzlhd0RHT1U4dlNmV3liWmRNVTRuUTZ6dFhZClRUcG80SzJVTGNQN1FBV0pnbVJY
            dFdTT3NBQWw5NEx4cjBaOUxwcmJyVkkKLS0tIGtoZEJFNnhtZXJya2FWa0dCUXg3
            WW9QWEhJQno2RkRoeXE4RU84bkVyWFUKh2NM/1YZWzVUqVcI8p3xKUPPx/sE1YDx
            UanpK6WYSzmLV2RPRr3CW7gedS4yuTcNaavV+/B9HqfvfjirRZoe4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-19T05:18:29Z"
    mac: ENC[AES256_GCM,data:3YP9NYOYKTwbk/IG46pO027Tzg1mgP9VA4JgSJy2keUMkZrggAar1h9GaztS6EhScjNCnTVZTskRRtTTbhjjtVK1i+K4mn4emiaCWNGpeVX40mnA6ZhpJ5WNh5C9jVY5mzSo2Vqw95fjkpAm+bHfvZyuqU6L3TB7wFUIpd/5U/M=,iv:9DF5pkZ0O9ZhFmji0xjKHpvkBvevAdbYVI/mGzIGy9s=,tag:nVWnY6dMmJAwagxEDcekOQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
