---
apiVersion: v2
name: metallb
version: 1.0.0
annotations:
  homelab/description: "metallb service"
  homelab/url: ""
dependencies:
  - name: metallb
    version: 0.16.1
    repository: https://metallb.github.io/metallb
