app-template:
    controllers:
        jobops:
            containers:
                jobops:
                    env: {}
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNby9UNEx3eUNpQytEUFNQ
            SXRqOWIyVzBUblRIdUI4NWpZd1N0WkMzOVJnCjZ4b2tpTk5abDdyN0tPdXhkUWdm
            SVhub1hJRDdqdk5nYi8wV3JVUisraWcKLS0tIEM0T3YwaW0yRDN0cVhOcUpJdGM4
            bjZLemIrSWRNbmsvQXNnTVJCZWZaZTAKDMS9LUxG/8QwqyPVt9BLIRuV3YX+Z5sK
            UePD+Q5EAvXHaq0yqkIDYQSGbADMV/OZqML6pPpIgZcClEm+74Nd2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T05:33:12Z"
    mac: ENC[AES256_GCM,data:yxnnQRNaLhNOVZpnwgusmqYQXHEYvNzygVMSeN7+P/VSQrjomoZLkwrjRPeiU7Bc9J0yLwCbfqfYkbG9GeweBi6y33bph6hbKd1m+cXqBX5CzIQvZ5+Ps0pFeTUGBiuocCLsaqJlnFM3Sh18Kh4LIpNm7KDhQunZ+RpP/claS7g=,iv:VUus5oCDEGeDdQKL1OLKaIELApOQRdvkK0H/rQO5bKM=,tag:IgvqrkcvMvQ7y6z3mEJ+0A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
