sparkyfitness:
    ingress:
        enabled: ENC[AES256_GCM,data:1W4Ofg==,iv:psz3mLRZ+bHkMLw0COqSzrnAEidQvu1k9RrSZ/3mgXo=,tag:9/XVJHVjvC7fFsSesVqc3A==,type:bool]
        className: ENC[AES256_GCM,data:9JUWh7yNgQ==,iv:s90ovXwxG1oZtIzZYRxoFJrqfS8EsNW/QxNv+l8k2xc=,tag:NB8JsN2tMrD41KaMOLpqhA==,type:str]
        annotations:
            cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:7bQMj3fTUNAwh/TYvRbVyA==,iv:vTo/jpMiJv9bp2C0H3ZyYBOrh34ReEidSJ4SlO3uQsk=,tag:G9B5+VmO1Eketj9/5ev3aA==,type:str]
            gethomepage.dev/name: ENC[AES256_GCM,data:9ja/W6X7bHNx3L/v1kg=,iv:dWlGJ82yjpbfiuO1higr6/WWrvKJl7fbaLPVQqvqExo=,tag:LJFefgBhMH6njaopCot4Kw==,type:str]
            gethomepage.dev/description: ENC[AES256_GCM,data:q8BTn3OdeVNsKew=,iv:IJO6ubvWME1MOhjIuBo7XcDUs4IqBP7+tf+nmjwSgyk=,tag:foul8Zv6c80e/ZOkgGyeMw==,type:str]
            gethomepage.dev/enabled: ENC[AES256_GCM,data:Mx/XOg==,iv:IjQ+by4iNnm7uJMG/LkDJX4XnYVPRUwkqUOjvoKriA8=,tag:Ixa2dkWgfK6U8HpnF8wwZw==,type:str]
            gethomepage.dev/group: ENC[AES256_GCM,data:VJoCEmZ8hA==,iv:wP2xbf0Bbs+8AesZ8DmhLiLF37qdAvx2rMdWYL8iVtE=,tag:5nieLT799JHKRbRkiEV8+w==,type:str]
            gethomepage.dev/icon: ENC[AES256_GCM,data:HRkpKXiHOEJztSivqfJoXxcNd7w=,iv:7Dad6rGVyWzsAf3O3CABM8i0z6grGUSH+YmlWG4l2zU=,tag:RyEMFjDWJYn5J+5DpHHmRA==,type:str]
            gethomepage.dev/pod-selector: ""
        hosts:
            - host: ENC[AES256_GCM,data:NSvHIeZw390oaekhydPm5MUAag==,iv:3gDXnSHCRHVNKtK2UyLpYUIlU9pFhPEBiBKU805INmw=,tag:a3Cm+2qP1KDQWGZhDpLxuA==,type:str]
              paths:
                - path: ENC[AES256_GCM,data:BQ==,iv:bVi7jiNEADG3e/kb8oRdooQMmDL8FouSRjb/MYIA4nk=,tag:HDfqDIJXdEalZ3Jx8RfPdg==,type:str]
                  pathType: ENC[AES256_GCM,data:Bt6+h+5o,iv:1iOEmWIXs9WildRgsXs8jsbchKplNQsRIHjDWohK4gM=,tag:Fyk9tL0Eoa/3ncxgXavO0g==,type:str]
        tls:
            - secretName: ENC[AES256_GCM,data:uDQoFT+3JyvCThQAgOXrTR5XpKxnIyQ=,iv:SwOwwYYexvLvQPgkBbxbVVx4Es6d8RVLEk7MjnAyKBc=,tag:ZlYg220+dRrJQo4AW2Hf2w==,type:str]
              hosts:
                - ENC[AES256_GCM,data:VWaqkoDmEaAZ6utRfuBk19albA==,iv:djf9lxw0pqNuw0Pfsi63UPBz839RWodiMchhTeKokXM=,tag:nznDG/EHJTDR3zht6M1EXQ==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArcFNCUUFUN3BiWUJZclVK
            QkNPQ1ZaSjdjQ25xMXpvd2dRR1kvWjF2VGtjCmI4Y3FvK1lIUUczcGlWNExVRVBK
            OHY4U2d4QXhjMml0WWpSL0FROGRRM0EKLS0tIE1rZjFRem0vQ3FyaVhkMXdXZ29t
            ZHN0aXhEemVvT0QyRmdLRlFBaHA4b2MKqeccHKA+awHpE22OFsF2sxUUi7YXkFdl
            mZc9N3/ojXMyxW5MLwd36gbRCtK9gZqq34s80iJeBDn/bBirMQKT7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-23T18:45:10Z"
    mac: ENC[AES256_GCM,data:rEKXFIsniGeY/H92C3p5v0366bjC1rzoiXPhppr67+Uv7MAvjOuJiHq7fgkHauTj8llEA/6NhLu+ePbbnYRNVvsMB8i9q0gM7Jde4/gpfu2BX668DWiW63v9m1b/y/N+koEaEEB1J7tHNgXUmY/6diBBxlb522htVD7n+h76Gf4=,iv:iXBhjkku1eRW8xSC1cWmfSyaZNuUUZ8VOUYby0KJdak=,tag:pw5OyErKdMaOULSbgRUMfQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
