sparkyfitness:
    ingress:
        enabled: ENC[AES256_GCM,data:JTlKhA==,iv:6w3iI+vXQyR1isIPRru5ASl/ETSC52CMFAIUaeeewfE=,tag:XYqSqUZg2boO4saMADESdw==,type:bool]
        className: ENC[AES256_GCM,data:gnB9ozFQlA==,iv:QBfxMd5JOAl4eyCB0RuBzIQgHkNFRf7QPkF0x9ory3s=,tag:rQ/AEx8p70NSON1QlI+wWw==,type:str]
        annotations:
            cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:jlyWORJywiiu2ignCoPydg==,iv:LKnYTk1wUYGFjyLBxaf+0Td/J6jO/UVpFzFY960e/6c=,tag:22kpA+WzscO/hSqvjQrRTA==,type:str]
            gethomepage.dev/name: ENC[AES256_GCM,data:rvEc7CWUOKU16CXZdMg=,iv:6zq5f2sjZ+hswnmki2B9fvCfDmkG4+TupJ35Bq/SVjA=,tag:dbECwfKy/2C8rT+rayNNJg==,type:str]
            gethomepage.dev/description: ENC[AES256_GCM,data:C5a8wf5zZpgkrok=,iv:7PJ9GcoGs+WjewLmwqCZBVgbVKeC8QhrwhXrv1S9VLc=,tag:8Dq7B60h271j9pYuwR1Bjg==,type:str]
            gethomepage.dev/enabled: ENC[AES256_GCM,data:qP3Zrg==,iv:YPdWt55wBnoZnnXpV4KeZ1FgdWX1tE4S4P88eiFa+v0=,tag:2FON7QV+vIoqhieaF3RQXQ==,type:str]
            gethomepage.dev/group: ENC[AES256_GCM,data:gQvsOP17RA==,iv:/d6shQ54j/huJ1HLSDl2wILHmbpaqiqqlbdeUW1hoUg=,tag:HjKhF9I1Fze80dvjOA72Gg==,type:str]
            gethomepage.dev/icon: ENC[AES256_GCM,data:Bx/dke4lZEYs+2Buf64z9YOo7pA=,iv:EWkAPQ7BPxcycjvMC6/h6vhWTeHDcpQ4rw9JDUYnr3M=,tag:35rs8e5/vA3f6FgbidNDug==,type:str]
            gethomepage.dev/pod-selector: ""
        hosts:
            - host: ENC[AES256_GCM,data:T8XGkEquibNQjL76MPEe2j872Q==,iv:oQAULJ41M6QMq0HEJ4J2Ub9Jr7SdpU57hrguLqSrH50=,tag:hfMFqkDVPKjdxZzZKafJvg==,type:str]
              paths:
                - path: ENC[AES256_GCM,data:aw==,iv:W8SWV7ZCT3EvsyGLZfFzdqXVDZtEzMeQJXTYYJl7X/I=,tag:Bm4jQ1ULiauWiqKrv2acEg==,type:str]
                  pathType: ENC[AES256_GCM,data:EqbkJHFL,iv:Z3s62ftiK5zqKT+ReKM6ebukz8fqvQQ2qKRF8fbosRE=,tag:CN/3YAkty3pN8xnLX9bSsw==,type:str]
        tls:
            - secretName: ENC[AES256_GCM,data:gB2mfrJzXN8LeW81C1GUUTNmGd1Pt2M=,iv:Y7ejKupJMKr4obk5JA1Z25PKTlYAUcL4LRACqweyT58=,tag:VGmBCV2wTpNViZSbEsvyqw==,type:str]
              hosts:
                - ENC[AES256_GCM,data:IxPvIo7Zn7jnQfyf2SdgmaNHFQ==,iv:5/9LMvKBzM6fcvhR+34tAvKGVkPBmc9Nx9M/wT/tQko=,tag:xkEDQuxuelb5Ye+J4ZsOnw==,type:str]
    config:
        timezone: ENC[AES256_GCM,data:QBOI26KZJk4ubAegVPKILvNt6w==,iv:dxWVttJLUJhWdf5RWSfQuQoc09kWmgBNIge3RciJWzE=,tag:8IntADImqiqxdVZIZCz1YA==,type:str]
        frontendUrl: ENC[AES256_GCM,data:2k/mB7B05Ppy/OimTMOJ/FlkTmPvPFnk0BYO,iv:bri+poPMSdjEaPQ4g8RW5VnPYffV2+mLTAuN6tXJsgg=,tag:kV6J93oY0mIrStBTpCt9Gw==,type:str]
        disableSignup: ENC[AES256_GCM,data:IKQqHxM=,iv:xX1XjaclQgQNPgPu58SOUpf2jpMks8WV4PPPsPKGUco=,tag:YA7F7RaWiP4vjYW362k/bA==,type:bool]
        #ENC[AES256_GCM,data:wmpKrc+lgwX+XRfhWCxtLa/+SkdYHDYsuDkPMI9ZT8MlNZj+TS29//L48tEbGYxtyHmUuhs4CKSk+KIhkzhquVzfGaav16IYYam8mQM=,iv:MMoFtTvD4OSlml0KimUy3Eh7Ydcp0TWu4dMMbv3ZPdY=,tag:YYI+hF3cfpzzQIU0dwaU6A==,type:comment]
        forceEmailLogin: ENC[AES256_GCM,data:MP90jQ==,iv:Gxi4b88z+7ifc8hu6CYc/ulh7uDiya/jwxdNdjeKrj4=,tag:SwVVvMZg7HqeqleKiMd3ng==,type:bool]
        #ENC[AES256_GCM,data:3BBZZmYNO8deo4RjI1GZzH7xf2rAYN+OoV5XU9iXpTp2w3uQZMSdokC/3YHCC+CpUuSE8kTV2o9UjzkcJSyvKRJdRJyq9bjsyIvT,iv:nV1893vmIOD2N01zUOd3HQ9+kMJzJ0hSjVAz0hr7Yy8=,tag:gJ2+BZaeGVW19beETuEJfA==,type:comment]
        disableEmailLogin: ENC[AES256_GCM,data:GDXOXmY=,iv:euF7VqVnUe/D1V3Ceewq3gUVqJqNM9chJMu3c0IzR2c=,tag:RNNE9XB5il2TAbSkXTU/DQ==,type:bool]
        oidc:
            enabled: ENC[AES256_GCM,data:/gEHhQ==,iv:No4aXdbL9qbJyYoOFebG13Yg57g16Yy8ajHIouVsS3Q=,tag:3rMjdom2aYRNjtsBrPHPPg==,type:bool]
            providerName: ENC[AES256_GCM,data:SAKa08B2bPqy,iv:kWef/7bIadUEnsEzPwF+IFTFDrHM2ZRDOI5poFcx0C0=,tag:fOQrcCi/3z90fe/p8jrKpg==,type:str]
            providerSlug: ENC[AES256_GCM,data:ZqO/aiEguk9m,iv:/v8Hk0hvnm1MZHAFt/Gj+cOD463RZJgfZmdgV1w1j6A=,tag:ePVi+qxEI4VPE3DLCdAa6Q==,type:str]
            issuerUrl: ENC[AES256_GCM,data:ldNrM1+Vw+Yu1eox9AVaMj6jm8VkDRI0kDk=,iv:cP8xwo6XTfnw8XLbKRNA1iQXWRk1harN1hnbezUaTPQ=,tag:+t+5/5L8PpIpHRA+XsXHCQ==,type:str]
            scope: ENC[AES256_GCM,data:RI3WbuxKVKY9EsogbIvZMH6mcb0=,iv:q+Z9bNyKVpEWaYJAMth36eHyfey4xoA4gsmkTbNnKAo=,tag:Dz8b5pGysfTrLE8jLbDSjQ==,type:str]
            domain: ENC[AES256_GCM,data:BEK0uRo6kUhYtFo=,iv:Gx7WxOjCoBQ81YuJHN1EEI6oRgtqLAneD+ECoGHO91I=,tag:+doIY+s2reMLRiXoYO+j6Q==,type:str]
            autoRegister: ENC[AES256_GCM,data:wAC6BQ==,iv:w8ZMueA8DC6RU7d/GpWV+s7+6bRu2FfMGrl3Ak+HTfk=,tag:T80nDMdXX5H9SEfxQ/qlAw==,type:bool]
            autoRedirect: ENC[AES256_GCM,data:gh7k8A==,iv:AsxJTbac1todsrBdM0kIKEAl4a3JThN75X73M0iwBdI=,tag:RvIius6Ko0ntIsw1MmKNGQ==,type:bool]
            logoUrl: ENC[AES256_GCM,data:b51/c1V0Tp5MM5NWcOzq3qyWMqx/M2pu+/cDs0Vtu5GT3Smo2qB6ot378H+GvGEL05BeqWEwEr+MFuWpRJ47uw==,iv:mhxYRs4MunR6ka+wKpHtUg4V8xLn0aFKihAbUm3EFro=,tag:PVAHvELnOT+x4O7EUYUSLA==,type:str]
            secrets:
                clientId: ENC[AES256_GCM,data:iUH1G6aibjbt96pHwADidfXIsJzvXwDqZguUF626dab1u7/S,iv:7pAAZvORTt0myFDdGgiSipZrbw4zphZkl35GNAxKaxA=,tag:5zI9jPLhdzvUu0qGnFEEAw==,type:str]
                clientSecret: ENC[AES256_GCM,data:j8zic7D4oEVuAghOdeHY/0y8xSkCc8TbFrgtwtq38hM=,iv:buSJg92Eqhv0D/sdg3/T4pZIfQidhEkfofF9zD1l7hg=,tag:3wPtR5n2KUirFI5pKp9vSw==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESFlBT0Q3amtNOEJleEpU
            MGFrckVUSVlndWVadWg3emI1Y3RwajJodnhnCmRPR2hTUTNlRjIrc2x3eWVQYXBU
            STdKNUlOMmNIc3NSU1BWTWFoejk5cFkKLS0tIGI0WVdPYVNUZ1NuVGlmNkVJZ2Y0
            SzRxNTBnOXdrdXZITVd2ajBJZmNzZG8KP4aVT0R4C16NTC6VtexbPnDfhfESss7e
            JjU8myfwKlh84/Byo2j72oVvtPRMdka7wuDqhUfCKRD0NQv2e1HJ+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-23T18:52:26Z"
    mac: ENC[AES256_GCM,data:qX0oQAgjRv1IRx1A467Iwtn9QroGlNopxvOdn97945dRHd/ILNlGgeda7JLVdUnyp97yXBBYQWxtT8nhJu9Ngtn/TffKJoU95ALDY5y7kSUQji+7MexKpPmqWTse4iL0Vq6LFkHNhPT2KX/MjXDuWbzoZMq6fpFXWiI2NzgCTlA=,iv:OR8kPejmWTIPrBhy+RZ63oY3JgrpHjQ8DFCRuNAGfck=,tag:l7wmhfWIQeClYZYyT56d1g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
