app-template:
    ingress:
        romm:
            enabled: ENC[AES256_GCM,data:5IpWgA==,iv:AB6IJVW/38wDYtbwqUkha+KpSRV/SC8vv2CnEvctTVE=,tag:vwPXI4vm5aYEGW+hXtAXzg==,type:bool]
            annotations:
                cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:vgZR5ok73VFg9qzw86noqg==,iv:KbAbl4hVAxUiFQ4IQbcqvrhCV81S5hJkWmCmu6Sv5AA=,tag:setDwww3nZDjbGpmhu9eYA==,type:str]
                gethomepage.dev/name: ENC[AES256_GCM,data:YSykxA==,iv:wkUBVUnvicZSPzoJj8ClhrS6wq+Oxla9eRCOZseYJNM=,tag:GaEHE8EgvZUUjaMwy5EMWA==,type:str]
                gethomepage.dev/enabled: ENC[AES256_GCM,data:kisHbw==,iv:II4k/uafuWF8kUI14+8fP9klH98Dlo8b2uOGamQf7fs=,tag:1LCmVIitNJqpGYcy0JUddQ==,type:str]
                gethomepage.dev/description: ENC[AES256_GCM,data:+QgOC/wqQqKza+8=,iv:pUF7T8CWiOc2bxeQsG0LML3q4EvS4IruCUamMCHLXno=,tag:KKiW3sJJCBDj4Pb6q+3g1g==,type:str]
                gethomepage.dev/group: ENC[AES256_GCM,data:B1/OxU8=,iv:xfhsXyV9EFc1mQkbnSux4Wl4bSpODHs8ZNIS0ASkTzA=,tag:fsk1uiF3NdbYK7jyh0Tqnw==,type:str]
                gethomepage.dev/icon: ENC[AES256_GCM,data:MZRTz0sSHuFNlUY=,iv:umoLHeDgrgub8oYADkY7GD0SudPhq73UcNWTTnekpvY=,tag:k6wgbk5dCrecOnfzYADd1Q==,type:str]
                gethomepage.dev/pod-selector: ""
                traefik.ingress.kubernetes.io/router.middlewares: ENC[AES256_GCM,data:Fd/Eb9HDDQ9grxV+Qgimcz6Foi0VaEUNcwI64sQ=,iv:/pjo8a5WlDRPzcT9Gi+OgHtTlG8ASYLgNUufIK38zYY=,tag:u/iISqCDNG5i7o9sQlWCtA==,type:str]
            hosts:
                - host: ENC[AES256_GCM,data:3DWDie304XAgyFyRaaRHkg==,iv:ZP+Rs1sgraeGjn1gMxI8klL3irPwbjLvV30CJzkpdnI=,tag:0o/j5Xg1QU6Y0Wzslcer7Q==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:eA==,iv:Uo1zijh1Z/6XXmHEkv9Zu6dEQSzDMawN1uPGJB8HIFs=,tag:ABCcPfnpWbSjl5T8Onhnwg==,type:str]
                      pathType: ENC[AES256_GCM,data:l/mYMS5I,iv:8irtyOKy9xkm14X8yimJ3KaDfguOa4n6zWZKg1dB4ro=,tag:yCbqduFKRSZgEit7l6a8mw==,type:str]
                      service:
                        identifier: ENC[AES256_GCM,data:J8n9OQ==,iv:cM/rsCs5UsNG1FDuME32Afl3D6sgVoyKJ1yYqatHmc8=,tag:SD6xOcVWfXfU6Z8oCR0h5A==,type:str]
                        port: ENC[AES256_GCM,data:D54SWw==,iv:9LSsiC2b0XF2xRh5LUC1BOimKU6ZDO8AR65Ju7/NtsU=,tag:P7rctWFLZOw4hi18J5d1qw==,type:str]
            tls:
                - secretName: ENC[AES256_GCM,data:VOSuVMfTt8fM92EwEw==,iv:pHt8g4mF4tFQx1qRfe9uvXoOV9NCjfCBksfecHJixNk=,tag:Wn8QZ64zqJTTUmJCRsPYzw==,type:str]
                  hosts:
                    - ENC[AES256_GCM,data:LmVcoOC4ZAlXFInc7Cd53w==,iv:KtHZcaSteTUIlKPBnteIHkUwD29oNwKe76UBhJBitng=,tag:9efrOPqEdy7oKskByiXRsA==,type:str]
    controllers:
        mariadb:
            containers:
                mariadb:
                    env:
                        MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:6DvIVO3cilS2t7nKxUzv+tkZSE8Pn35GI79RacrQhrA=,iv:p9dJBbG4dchMI3XAU6iHA58/3lQ4xmp8Ao6F3W2gzAY=,tag:sJTQ41gmGnnADybNXDLymA==,type:str]
                        MARIADB_DATABASE: ENC[AES256_GCM,data:r65eUA==,iv:RIzle5w7FEksbtxG6xxST/gxzcozZQL5T7r2oHQCWGQ=,tag:O4Xar+8y7cCXxaAMPNUfZw==,type:str]
                        MARIADB_USER: ENC[AES256_GCM,data:rlT+z6kv52za,iv:0KJLxpTeXoT9uNw7zmJzZ2SHcuFQWtbn8/2oBwQ0OJQ=,tag:bf3CFi11BvrNQTQqq5zu+Q==,type:str]
                        MARIADB_PASSWORD: ENC[AES256_GCM,data:v40+9q4yAGVJ3oBe3+XdfdxV5YjU+5Ka0Ce76kc+Cfg=,iv:89o+6MqJ+ESX4Dc7N0JDSNSRBl7njoAvUI5c3NBuSfw=,tag:WnLEaFLsw3y+oMZrXoq9UQ==,type:str]
        romm:
            containers:
                romm:
                    env:
                        DB_HOST: ENC[AES256_GCM,data:sAZ8Cc/iiVd3qF/K,iv:GncEcFGEfaiub4/3zuqACNaM9v0peiLsPdiVAdV/q90=,tag:8s2t2nf1QcCF17TLIjc75A==,type:str]
                        DB_NAME: ENC[AES256_GCM,data:QgpioQ==,iv:AkUE4ZOzbou5omScYJxGAWyWVny9nwZeWJvi5ikiDRU=,tag:Pb0sk2KwYfPFsjFUFqV5RA==,type:str]
                        DB_USER: ENC[AES256_GCM,data:krmYTwsy9Pal,iv:l6E5y2xdxCp9dCi4jQLRAYLHwEx1y12aWDa5B261EK0=,tag:8N+vCD7G8iRyNtjWucUgIQ==,type:str]
                        DB_PASSWD: ENC[AES256_GCM,data:nbyCkIsCn2hZDx29c4vquejbtbH5jUZMPq5DYXT5ITE=,iv:ciIhJi9o742mGNHWckQ2r5zOV115mtv+iegsXL0Bdw8=,tag:s67094gaxbVoWt47GrCOTw==,type:str]
                        ROMM_AUTH_SECRET_KEY: ENC[AES256_GCM,data:a5Ar33wRz8NPP+8D8hCT6jjeLT4tLMMMor92ZcOINCfFUuvAhjbaQCh/K+qCIN15+GJ0Gt9IXjzrO6xbPg2rSQ==,iv:ZDMHXG9glghHe1ICvlB4j4Bwi7fbiaTmmHCr8a9PCZc=,tag:MkF087Eoq8HY9ALPwXralw==,type:str]
                        #ENC[AES256_GCM,data:0EesiqPCnN6eIbIslrVSbz7RgAXr9PL7IEpGstrs,iv:9VRDP0+RxrL1nsN3/JXfXeOG5bkrxoLpmwI2kiIF1nk=,tag:oqTuRFLNfTN3Qyb5Ttifbg==,type:comment]
                        IGDB_CLIENT_ID: ENC[AES256_GCM,data:3Z2+nmn8QonlsPNbcWgJhqQlYglwxYwh3CsBJCHD,iv:Jp23gfdlnaZ1HL4lDlrHEeX3ncFkAzcPMpfDdL6i37A=,tag:5jntrTjhf+kwhVpvpRN33g==,type:str]
                        IGDB_CLIENT_SECRET: ENC[AES256_GCM,data:5pL5hW16BB9HeTffGICVjVA7nz2i+/7szS7XQjhk,iv:c/tO9S1Mi9RjLiDAzzPFF8xjDOvY6M8b/eBHbKQKkSM=,tag:1sM2JMWo83905W52d2I8/w==,type:str]
                        STEAMGRIDDB_API_KEY: ENC[AES256_GCM,data:ya9M4Iqqg/Unq2FrKM6rECwpx+q7hvzjhnP1aRRiwdU=,iv:9d4Ko6sMj1MoSr8S9JM122WNQ8LNYDFHwd62c4EIyZE=,tag:EaBeCTdIcGn2qeT52iCPJw==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMMlRBcEJUY2FVTm05bzc1
            RFo2aFRvQjY1ZVBBdStTWlNSOUVKVDA4QW5vClFPdnl3WmR0UDJaTUl3VlBDbVE3
            bnhiZGJsZkZzZEY4eFBQNDdPUGpUOWsKLS0tIGZSbU8xeGFhbVJVYkY0MUc1K1JQ
            WTIvVlAyMjRKTlJPcWFqcVpZTzk3VHcKZgzwsYwQ3xGxuDS5eyEYQdLrodre8mTd
            Q+1+TIE7Qig926/WHDqn1LwmHzjr4AHm/sblJreQo6OeYwRjUgKFMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T23:05:09Z"
    mac: ENC[AES256_GCM,data:0c6xsaCddvTX3worYVBHtZfXdywG7sp8MI6YjZFg7ULWJHX4Nt9rwXcdvbUxGwxBIJC+jrckYCwkhi2NpgaPb7xXNx2VaQlr2737/6kvtq0/OgWFsbKx1xMEWTH8cMUjD57DU8LQvX4+sNSebMLUd2qQrsjVg/zn7hpKqwzneYI=,iv:0cjOaxI1e6wxGZpBlw+BCMp00GykuYEZjCL9BLn3VJ0=,tag:9A8dLyoGIocGTb7Cf9Hfjg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
