app-template:
    ingress:
        romm:
            enabled: ENC[AES256_GCM,data:NN33qg==,iv:mLhDB27JFVqirt1RH29Mjd90xBM99ztx+GKE3vwFpq0=,tag:4kZy3D5yg6a7Mk1mq373tA==,type:bool]
            annotations:
                cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:afTXiBpNWGx5aXHpuKQcdg==,iv:NFvnaXOY3+4DaxW02iUk7Px1CeuajA/gg9HZ7qtgWRE=,tag:ujzjF+A6ceipV+HYJ9YKSw==,type:str]
                gethomepage.dev/name: ENC[AES256_GCM,data:epCDHw==,iv:80ph6Bf2agRDNT45McrzPRm/McvuxLbAHwV1/MWz+gM=,tag:XPoCF9WG3ShIC/rUGSpkOg==,type:str]
                gethomepage.dev/enabled: ENC[AES256_GCM,data:mBgAcw==,iv:wjIlTO7ROQe4db8LELYV/GyQRf/TmdirO2Mg/P1+Qlo=,tag:PpbPfjLzvGm7DRBcpl6HIw==,type:str]
                gethomepage.dev/description: ENC[AES256_GCM,data:VzgsKD9mhAWcykI=,iv:JfaRqeGxa46b0B0g5AbxJYaAZeocqDGSdx9EQmFvUqI=,tag:sw4XHIYIXqICNSxo9wSHWQ==,type:str]
                gethomepage.dev/group: ENC[AES256_GCM,data:kHOQLk4=,iv:R/f+7lfa3lbsujCQns2w1o3mgL7xi+FtBQ7GNKpVlfI=,tag:PO+vEhqy8HVScj24yqUSTA==,type:str]
                gethomepage.dev/icon: ENC[AES256_GCM,data:aONhHId8WTC26mg=,iv:SKKGJ3qgCxP0ImceoOnRQPJBOh+SNwv5ewLrhIjpKjw=,tag:tuTnqgFfHjcB7LxHvNc0/Q==,type:str]
                gethomepage.dev/pod-selector: ""
            hosts:
                - host: ENC[AES256_GCM,data:m6NswPH+Henibi3FwhWVAg==,iv:sO0lxmYAAMKUwPiWfs4HQpQEfeM/2iTC1A/NNvrPTYA=,tag:rrfH495DVx/IEVf6lwk9xg==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:ng==,iv:fwYKsGbT/AWHaOOfVbD9/Lgf+TPB4iI6CBKe3Pgqork=,tag:kpFIbiQ5E8tA2T62Fe9drw==,type:str]
                      pathType: ENC[AES256_GCM,data:rbzN5Wus,iv:k2mvc1TXJgB0zI5LQKaD/Ul7b7N1tPvTMoliMDdOoTc=,tag:JkeBr2aKHNc/UpUNS5XP1A==,type:str]
                      service:
                        identifier: ENC[AES256_GCM,data:IFFO6Q==,iv:aw3BvR80hUfat5/SNOVmzLhACzQdOLqQaWWcjOjhoiQ=,tag:HYKVrhe0LPMA1YWdRyW74A==,type:str]
                        port: ENC[AES256_GCM,data:qBFbhQ==,iv:uB96498JFN2Hfg4Fi71DQCn8LxOzKtK3q3T4h+GspGY=,tag:DG2evjkQimDtSsgvVRcB3g==,type:str]
            tls:
                - secretName: ENC[AES256_GCM,data:zuBg2Xh8/AbeME/IPQ==,iv:G0WgVy5DAjIUl2o7DhYE7oBwGZQ7Chh8iIogW6dEr+0=,tag:2AJIdcM2Omf+7qDTi+2uzg==,type:str]
                  hosts:
                    - ENC[AES256_GCM,data:+9/SX5gcOwmgqBLaZEsJVQ==,iv:yKIfffKRDx8RUSAiHfY34Rnaj8dx8aRlyAz3UMiFuxY=,tag:cUS5suDhA7+RWrKuSbVXaw==,type:str]
    controllers:
        mariadb:
            containers:
                mariadb:
                    env:
                        MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:40sX38WKmR+GzRUf82IP++9NC49PHbIB9PnFw2JN7YI=,iv:/7E3eDjinP5HZSxWCAEJ87wr4B5RRczilsJftAUhh6c=,tag:yY9/dDIlYO8Ym6HSCN2E8g==,type:str]
                        MARIADB_DATABASE: ENC[AES256_GCM,data:uK3E+w==,iv:pRuecBD8vMX/iHseILW+OPV1e3JfOETgxfGgdKL9Zs4=,tag:Xm8IrNfPw0NwxhQLIpoEMg==,type:str]
                        MARIADB_USER: ENC[AES256_GCM,data:3QnnEnflQ86f,iv:6Ey8E3GlbomjVGfdlFk2VFFHp5MQj0tSToVnGwuPt0s=,tag:jROS5KY1gErl5Q9TfhuAnQ==,type:str]
                        MARIADB_PASSWORD: ENC[AES256_GCM,data:veuxBZES4dJ97Ei5D1hOBkmJb6tMGXXwqHOuODjDnyo=,iv:LnZm6WsbXWIRrQPVVo2dsYgBfddZkkzEyqliVAcfn2k=,tag:h9FU0IqtuHsbqTlIM7ku2g==,type:str]
        romm:
            containers:
                romm:
                    env:
                        DB_HOST: ENC[AES256_GCM,data:NQCOlinTGscaXv5x,iv:v2IFwcxCQYb8Erpx4M9ww2DXIkjZ85GUPv5ucZmu9Oo=,tag:YLj+VxhfsDex9SBbpjmTGQ==,type:str]
                        DB_NAME: ENC[AES256_GCM,data:KauH+Q==,iv:x94s8rolDh/k1yZwMYAP+NtkZU2L31hx0jVvRVU3Tvo=,tag:MH3G8pcZJlND3le8H90vzQ==,type:str]
                        DB_USER: ENC[AES256_GCM,data:Dfk5VPkW62yO,iv:v7mYO4YLspApWwtqkz2qtXzCPEEZ6m4sIZPCw9i95+I=,tag:23n/G18kcYV2MpRiJJxZxA==,type:str]
                        DB_PASSWD: ENC[AES256_GCM,data:4M3/xCc5kBhYd3DL2bed75U4CisqWtK9cOLXXi1odjQ=,iv:kBRASyZalu0S9JxSyE/zneBSoqUcWBHCZyTVQblL4Ko=,tag:Qy5BB5TB3Kvyyh8n21TFuQ==,type:str]
                        ROMM_AUTH_SECRET_KEY: ENC[AES256_GCM,data:fem1By25irkrqmlUaCuks42Wa9MKYooXoKlPFglKPdBTZuSCBjo7+Oe6Q4G6PpD4EDapmOsme4tHtsQPm7/5tw==,iv:NH3qfY7XYtDqIHoe3EjfCFlGG8z4DID0ff/kf0c1hQY=,tag:rhLN1nhFbiaa6etRYVK/GA==,type:str]
                        #ENC[AES256_GCM,data:jGPA8qhZINYAGYOSN3hbAbS1B36cqHF4ILbycIRN,iv:SfpU/AmGYt2evs0Cmais+hz536I5xTVHPEunNN4ETJY=,tag:rJI7zoT/fGR8bC+Km5OLtg==,type:comment]
                        IGDB_CLIENT_ID: ENC[AES256_GCM,data:czDDpFzh8FGLgkUMg4xKBHAL3mK+q7LRkBQUMZoH,iv:bY4RImWc8uRs801wyWDTfHzVhquUx9G/tgqFvpJUxDc=,tag:BJmLdI2sJpKdww/A3+e1pw==,type:str]
                        IGDB_CLIENT_SECRET: ENC[AES256_GCM,data:jrgUqkt4CDkwxGx7+bW7L8qLNfA+7Sl/daUmlnhM,iv:7QwbJIzx8NyAc05TSeJOdZnTpt46LT1OMywvCApLbSo=,tag:gftZJWI8iA4aUqbobClpmw==,type:str]
                        STEAMGRIDDB_API_KEY: ENC[AES256_GCM,data:KEeX11U//Ovsup1UHzA4nS7ebQEVqzfGXtdZ9PylkKc=,iv:/3fiRIA/3C9heZcsd2IY4N/XTJCwilcQP6NxGjLQVHY=,tag:FckHWJivQALu85HlAFX8Fw==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMXpGRnVrWjB1eXJkQ1ho
            Z0d1N296SEUwYW81UWVnTktSWFAwODhMQ0VvCjI1RnhPaW1RN2RtdGxjK2FoV1lD
            akF0TjRNeWFXNU5TSmFQV1ZYKzZzWFUKLS0tIFlFeHk2eUc4NkZxZm0wdnh5dUZD
            SUlLVGxHcFBMWmMxOFU1ZVN0cjR3U2sKUZnvdAtjfV8darygT+l2vtMps8noThKl
            AfEbYPnUdD0LxM3SW9x8V2UQcwhUr0V1Y2mbDMPLkwNp3OgRKNHEgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T23:09:27Z"
    mac: ENC[AES256_GCM,data:cv829K/aeF0fY3SsUPnrBa2gE2o33eVIOrJUA/W4rwWDS4zTezaG8gxXUCUxmO/TRvQabJfHLxZS1FfndagUFZEEV1Pji6LvSeNuVcv8A/7uTqZNgGF3m+tQefK4tIlbmdndcDrAecYfz2XNPd5Naqq56qezITomiFRelwQ20BA=,iv:lBfxMFVf2hDgplhCuBuCJ8vjQfXqkJ75PDXo111vVPM=,tag:zeNrBISk9lt7CEsTlWd85w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
