app-template:
    ingress:
        upsnap:
            enabled: ENC[AES256_GCM,data:tDGSIw==,iv:MX8JNKh1c/OS93KPjJUmIkvENcGxjY69JHUOSSwnFcY=,tag:nVS1wNmjSffnzhj1rfqIdw==,type:bool]
            annotations:
                cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:DOQmQWztFwyq9DOh/PV1fQ==,iv:50UNzpSkHkAKfedxk8+HHyk0V8vCrKFFy2IwGddKXKs=,tag:hSjw82qZZ+4JdlQ7LH+7Tw==,type:str]
                gethomepage.dev/name: ENC[AES256_GCM,data:A1mEGe0b,iv:Y7FvrS8LovgII6i8dUTQCulqWmI9LKSLod1HOhTfQ58=,tag:0g+pkz1q5o47rJxqU2qIuQ==,type:str]
                gethomepage.dev/description: ENC[AES256_GCM,data:MlsJJmHgMC2FUxM=,iv:ObO+kl09pEvcZi0XPc9FkZpN7AkPapgCMrRVx5Baihs=,tag:LW5aUpSlDmN4/VmpLo8F4Q==,type:str]
                gethomepage.dev/enabled: ENC[AES256_GCM,data:CF9y9w==,iv:gLcEwHOYP6BxsH1jnqpSaq7ZtoCV4+7Frch2dckQtIs=,tag:WDe91EKWlXolAqlYhfi3/Q==,type:str]
                gethomepage.dev/group: ENC[AES256_GCM,data:IYoh6cnOW2Z/I4vcYA==,iv:c0l7mk3KJUY0gWJpN2wxELeDK/59B7ToYrm/LbTPfjc=,tag:2sqmXHoPlqwzDm6lwNXDtA==,type:str]
                gethomepage.dev/icon: ENC[AES256_GCM,data:IH9EFgCiMUWpfx59sA==,iv:W2ztcZ2zuCv5SCIel+0fX8T7Vse+FdrfSA6e+bfRxE8=,tag:8GoJhk8StOqMxLX+JQ8qrQ==,type:str]
                gethomepage.dev/weight: ENC[AES256_GCM,data:VA4=,iv:UzNw6xyObYlydENE8OnXcZ2XSAzwzYKLr8mb+7T0Y30=,tag:JIoM6QbcaKHE4zZ1NkVauA==,type:str]
            hosts:
                - host: ENC[AES256_GCM,data:y7um/QeXFhSX4tT+KY0+SDx2,iv:PyLzrs71A6OUWqZpzphHNv1V9EbgYSydyrPw4ADGFBs=,tag:HDtB1PsJRIWFJhI6xum2iA==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:MQ==,iv:BqE/S3oZx/dHBNIbn2Na/1Q++kw7Tqv0b6fo5vliL+I=,tag:fU+2q+/nLB6pLBhKQOSJsA==,type:str]
                      pathType: ENC[AES256_GCM,data:NzhhBbej,iv:Q8FaE1HCJ1IN+okmJ1G+MOZeLM6gyvBRd85f4TXc1hk=,tag:wSzOMCjC3cl3kTi+RGTZyw==,type:str]
                      service:
                        identifier: ENC[AES256_GCM,data:ryF0237v,iv:/KXbqt1RrEs+abY+s/g6XVOuMR+t19O79688gqpeAgU=,tag:XtrQkN/9Fcr0CpLNJTN11A==,type:str]
                        port: ENC[AES256_GCM,data:LVWF6w==,iv:g0A81OAAVgyiPpLTE3GjmK2wY7ZkFCuo4nDi2Rg/iPY=,tag:2SIqIqaSetejmHn2G7Uq+w==,type:str]
            tls:
                - secretName: ENC[AES256_GCM,data:vigl15a1kHwYq83Ua6NI,iv:zvPmgnxPoDR86C6P1tS149XbtOdj8g2ilWvaVdWfyYI=,tag:RatLa7F2cg0CZ0/GUJU8tA==,type:str]
                  hosts:
                    - ENC[AES256_GCM,data:chY3BL8Swj90pQly616S105u,iv:e9sE+oKiD9Ped0NEpEpfSHMvrKxDgQDvXVIQlkLoFHw=,tag:TAsWChgu5ocXYB19RHuZeA==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLY3JIZTZVYjByVmNybkJ5
            ZDEyeCtqb1QwRnVqcDk1NWVrUTVHRHQwZmk4Cm00UUJKeCtScHlaNm9BRkh5RXhn
            NG1kVEFNNXFZWHpKVFNBbW93SFdKbzAKLS0tIFdYR1YrMWFSUDgxNmtOYlBJTkE4
            RU9vQUEwUVM1NGI4MkRmTTU4dGN6WVEKlBy4l76Ft2cbN6OXGTUXHbRfgGqMqr55
            6PT6nrIFIVMPRaP6QudH28muILh5McHhiD7baVRPbxoevmi6rEwzuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T23:09:27Z"
    mac: ENC[AES256_GCM,data:WskSeAiCCwZWPw/8jF3QUZpq+f4IjjEVAnDKOW4PagFA1jpYtbdLLccq2rQAdaqLrUgwKqZX7mhppgD30S0zvI6EqxSlR/dn+hL0Yx4sLUr15jQ7EFW1N1/D3hvMlTh02PaLWtMVpQb427uw4wlqxvzC07tH9rU5EUg/pvgk0Jw=,iv:Yt/nBfL3DojUOlKxyfvDiZiJgZ4METTUgStrqpCvz34=,tag:F3q31TQuUSjnZPMX1F1GtQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
