---
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
spec:
  replicas: 1
  configOverrides:
    server:
      - "default.replication.factor=1"
      - "offsets.topic.replication.factor=1"
      - "transaction.state.log.replication.factor=1"
      - "transaction.state.log.min.isr=1"
      - "min.insync.replicas=1"
  image:
    application: confluentinc/cp-kafka:7.5.0
    init: confluentinc/confluent-init-container:2.7.0
  dataVolumeCapacity: 10Gi
  dependencies:
    zookeeper:
      endpoint: zookeeper.confluent.svc.cluster.local:2181
