---
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-kafka:7.5.0
    init: confluentinc/confluent-init-container:2.7.0
  dataVolumeCapacity: 10Gi
  configOverrides:
    server:
      - log.retention.hours=48
      - offsets.retention.minutes=2880
    jvm:
      - "-Xms512M"
      - "-Xmx512M"
  podTemplate:
    resources:
      requests:
        cpu: 50m
        memory: 512Mi
      limits:
        memory: 1024Mi
  dependencies:
    zookeeper:
      endpoint: zookeeper.confluent.svc.cluster.local:2181
