victoria-metrics-k8s-stack:
    grafana:
        env:
            POCKET_SECRET: ENC[AES256_GCM,data:s/S06pEc59G8YBTiK5ovuFMXXGwewr/c1mcXqIKh20E=,iv:UFCDDY7JZbyC2vFA282I1XlUFevGoAwXmIkavHNuv9U=,tag:+JvXBQEV+XJY9TDRitZZdQ==,type:str]
        grafana.ini:
            security:
                #ENC[AES256_GCM,data:iTOX1nMtgqzEAah3uCoO9gO31AA=,iv:FePbM0nIOG9fZKwUW0U8ktySBi60rcd7Aze2isepWO8=,tag:2SXsS5wZAWKZuUE/QrmAtw==,type:comment]
                disable_initial_admin_creation: ENC[AES256_GCM,data:QJnk5Q==,iv:nVdbyuNZt5mKten7DpLAUVq2Uqf1VQmfUeIBEnVGdh8=,tag:pBdgs9BEAN5B1lS8ZIL6ag==,type:bool]
            server:
                root_url: ENC[AES256_GCM,data:AztYEPUHHbyzbsCmKpjz3DISC8nLgk6Wi6Pw,iv:79cKFU468IwJTQ3UvmusLck53mV7UvYl4EVxeZlPPoE=,tag:G0A13yn77BlAY8YpWbqaLw==,type:str]
            auth:
                disable_login_form: ENC[AES256_GCM,data:t4FXiQ==,iv:Gm0bHDiKi4ZWXrRQjPj8nhFbMY/lGELnIlIPdDdl4yw=,tag:ypLE0QEhgBe91cA3XYOzkQ==,type:bool]
            users:
                auto_assign_org_role: ENC[AES256_GCM,data:lwd+sCIj,iv:gTzVsw8NYeAM1HA2m40BxrFLyd2P+jcxQpSaF9tShvg=,tag:KmSl502E8gtYkExIfjNRUw==,type:str]
                default_theme: ENC[AES256_GCM,data:8YGo6zKV,iv:XnyWv86bTVtO0ajQhS4G1Kn+xkTiptfiASC4PVxfTzU=,tag:kjlFkIW18GtGQrADlKSxEw==,type:str]
            auth.generic_oauth:
                enabled: ENC[AES256_GCM,data:ASTW0A==,iv:ndLxwddSmEoGbT+PbtyfIo6yomje1d5VOOtZmQ55k/8=,tag:vguqlh8remv1c2P+P8YDvg==,type:bool]
                allow_sign_up: ENC[AES256_GCM,data:qYQ44Q==,iv:xM1Xnknp5Z1nYVZ4b0dN9WGx2xlFsYP8T9+xCrGevLs=,tag:KBgkGbhVbQx76EVbODRlSA==,type:bool]
                auto_login: ENC[AES256_GCM,data:/A/ozBE=,iv:xWJ9HWRMmdEsVTMsnP3kUpxlGHyZmxfL9+yVJSBAu1M=,tag:c6H0BuLnFv7Coc+scz4sYw==,type:bool]
                name: ENC[AES256_GCM,data:jbeDtEUaTJgT,iv:h3i+ECJuDHp6IRvi1nBLEdsDhLJqWol1j+NBFlWsXLo=,tag:KGcSQEqobDxs6t79jZ6EeQ==,type:str]
                client_id: ENC[AES256_GCM,data:NJk0WXe+qRkQgyVr04EhLweRTNrgg3ImjbzA2BL5UynOYl2k,iv:V15tDPF4AlmHPQ6+ug7qJ0QKNJP9fTJJ+4h7CMtjZ7s=,tag:l+ujS1Azx7VIp7z3qNrEgg==,type:str]
                client_secret: ENC[AES256_GCM,data:HjKLM2EUkb/6LnfdiFtVYA==,iv:ICuUWBA5Do5JkOQVa7e3L2kdwLfY77bsqFWjZGAFFOI=,tag:FvrBmebGpyZAxwmLVopxcA==,type:str]
                scopes: ENC[AES256_GCM,data:OxI0qAM/sxz9xsBig3j8yxKUgu4+qamXHV8akvm/5XXbXe4=,iv:ytNubMaA9BG2bhhiMD/0c2xoZSKlKcmNl2YM1YELGZk=,tag:D+sIghDn7ou5e5sczSMLpQ==,type:str]
                auth_url: ENC[AES256_GCM,data:9Ct3ZFZQTbvXI816ZqmEf68WRl1zf/ioTda92hEhkXLVO2Ql,iv:y/AnELQzn6aL3/tdo2HfffNa8GWWAIlAQfo0dgoRjUk=,tag:xj97OMz9KboRIs1DaZzQ8g==,type:str]
                token_url: ENC[AES256_GCM,data:t2uKQjkmESIh8+B0XFYB5r/9qCzZLKDvrzT6altDVdJo/szp/Gd4BNM=,iv:JLbanUa01YMIDONN5VGQQeI5wqbRaTjcQOOEKO6tWDA=,tag:iBMEEHaMqSJtFY+Qh6G8rg==,type:str]
                api_url: ENC[AES256_GCM,data:bPZq8RPjv79rZ4NUAhDnsZLhK142sYBZNIP7OqfAtkXPyrW7W9sgM57nL6E=,iv:fad8hBsoho2A6JwNx48CI4pPb7Df1lfvGUp/NY68MCs=,tag:Kdv/KsV9uA9a85SZRsyBTg==,type:str]
                use_pkce: ENC[AES256_GCM,data:zgfDbQ==,iv:GCEol9x7LnN3jTs6QNHLPRTUw0zRjbnDisIpaJxJpIg=,tag:ObGNwTbjL2g94XZ3AL/uyQ==,type:bool]
                use_refresh_token: ENC[AES256_GCM,data:pJHNQg==,iv:PYHAosfk9H9nw9ebgQ43Oz/+qnu3D5MCdx6t5sdP+H0=,tag:xt4ivn0UhMRzQjygxPPU0Q==,type:bool]
                email_attribute_name: ENC[AES256_GCM,data:ZEFuquE=,iv:x9m1k7OIQkON0zAq9/3e42jXWOurabIo4Bwfjwv1uug=,tag:dP5qyW/ndIAkSsuLbjq5yw==,type:str]
                signout_redirect_url: ENC[AES256_GCM,data:funo71pbePT8MZsl5xhR/Nrv/J2ArCnDN83uy/YiSCWsPEtCwqRAwWHZGWhqH1c=,iv:lFIQel81UNespjBB53v+fjyz+oNuljYDwOaInOOp5qg=,tag:IVrZNCD39CiixlJfvMjnSg==,type:str]
                role_attribute_path: ENC[AES256_GCM,data:WxklLEKU9hfogpye/h6Tsm4xrriOqV/I5D9w9PNNe+rRbkZzX5qPdCTVgBlOe9UyBSTiBGmxAgv7W95C12g+RJ4yZ/ITNsCbXy5U,iv:i9r4OD2WtaKP6ChE05Zrr9IyQoCwPuyxLd9RPmB6oPU=,tag:a+2Sq6AaXROD2CwDcCG1jA==,type:str]
                allow_assign_grafana_admin: ENC[AES256_GCM,data:rLq/eA==,iv:JlemxQ4s9hjJW0wXit3IZaHd6y3O2zAqi5gti9j3FH0=,tag:ilJDGqX2IsIiiyGQy7tGVw==,type:bool]
prometheus-snmp-exporter:
    serviceMonitor:
        enabled: ENC[AES256_GCM,data:6d8FMg==,iv:RG83jHMJkQnF1wGdYG3akeMKI1mj2OZcdI/0orliQfQ=,tag:iBOARi0oz4cXoybCAJU1aQ==,type:bool]
        relabelings:
            - sourceLabels:
                - ENC[AES256_GCM,data:bhZCWR7cLPU8aX+57s4=,iv:PkvCWqcsfEED/RCA0ODkhUg9PXETGCb/XFhEokr7uy8=,tag:n0kH5zxasrw8JKelAn9Y+w==,type:str]
              targetLabel: ENC[AES256_GCM,data:GO7i9mEGZOk=,iv:kaBBuLWhPGebbsGYryU5s5jNOXIdy/9gxZAjmO5yKOs=,tag:XMnJB8ejaRlWZyuFdYizyg==,type:str]
        params:
            - module:
                - ENC[AES256_GCM,data:fEbBZ5Ez,iv:nvQePOPD9WFQckum6S4XIL9MayfWXm34B4El1sQ38Ic=,tag:vXi9wlG852ZuPfgBPCjDNA==,type:str]
              auth:
                - ENC[AES256_GCM,data:i/i1vGfvo4ymfxg8kA==,iv:NIiQbUgGcbuEkt7QD8DXD3UdfnaDjJn6YzuXcVUYZgE=,tag:7JYYmod6U/TRngRmKgvwTQ==,type:str]
              name: ENC[AES256_GCM,data:ADQUVdQiapc=,iv:NCYqJ/07Izxj8ZjeS5VBbZlo3HQe9KCHCB5/sLVFSgw=,tag:riJNkxEKY5em6w2XZs3YBA==,type:str]
              target: ENC[AES256_GCM,data:K5pNZDDzVtLXNSImlQ==,iv:SGQetSjSlrGItYcsaeKxgH7QDBISB97TbXe+Zvsn1qc=,tag:I4jjqwAM5yXBawOtoFD2cw==,type:str]
    config: ENC[AES256_GCM,data:FrO1lU0et0aI16XILBgPSiTtGLs/YsC1Edv0wyC8jxxFV90I95QWIoE9diiU9KyjMJimYReB+wfNfvCVMedTogmTQeUApXIqmSLG+ffnTDDSghxL1uwqj7IqB1T3tfCUUbYMsHF8yh4SHe55th3ffIgeCAYntYFDDZJYl7Wog1rWxJoJR7/UJJE/0rJCOU3mLbSOjjvd8A0aOtUim0IYJhLAdiuK2jYSLME7PYJmYvtCeauNO1SHPJX8sIR18VkPTzUS4CoQWn4HtQLL9HNcxoha9eYghWqla1/I6eEObCQ2KXUlO56rYm20tGMah3asqlrD3akCSKjKmMMAA4PYv44JwAlCi74tYwIiqKe0rEB8zG3PNeNKkPwuk5yVU2nOWPQ24aXX7+EUx4wou0ayEspnmTj8Koso2goNXbNjKyDhUAud7qU=,iv:Z5xazfTPaixpBn8MF98fhsggpCyEh82Au1498ZFE43U=,tag:dlXQ/SnNmfegXOi8WXOesQ==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0QjlRcG0xTStVT1J2eEJh
            cHhnVmw3cjVHYXVQY3FnVUtXcWg4WlpCSzFJCk1tM2EzSjY0cG56Ylcwd2lJMzhn
            dzFXa2pZOU5wWVBXai8wQk43V3RGNncKLS0tIEdzK2prTnlCNS80QkhWYm9KeTRU
            SUxCbkM5aGl1dXd0ZmRFZ1BVcktFT28KeytGXt6o7nFBvr/QmJunyYwvHTk3jcLT
            GBpY/QUqMK3AqoAIoDrTq5EpVu75/9koqimFeoVUPFlbxQCxfDpRRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-15T20:24:04Z"
    mac: ENC[AES256_GCM,data:gYXqaLJBzDOsJ/7BjWP2jG3D0ZNBe9hBQQI16++fe4/WEVlZ4ls2O6RTWrorKHhVd0tSvCf4vk7aeGoHDtIIZhYLMzq1R8eZ49aWOH3/i7kw1u418SCv17IoxxQt4cRAfYTPVnDPaa6vBhaY6TZeQ/K2M+mKbTF4K2v5yigdEH0=,iv:7rG2kDs7P712YEzpONXaPV55pQy4atx5BAqlXPci7c0=,tag:W3n9ijLF9TOCocnDHBiHfw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
