app-template:
    controllers:
        n8n:
            containers:
                n8n:
                    env:
                        DB_TYPE: ENC[AES256_GCM,data:6I2ZhA4rvhx6lg==,iv:kgdIXlFTACdON12FMPhx7WWszqN8YckjyZcTJTl7/8A=,tag:UgRM1HWyVfZHPiXmmtGFYw==,type:str]
                        DB_POSTGRESDB_DATABASE: ENC[AES256_GCM,data:G+15,iv:PLtKLZIHxliIhcyYgjo8i2PzsQ2oU/7MKGoo+BcrTs0=,tag:FREYOvoI9gLvrxwkJZSAdA==,type:str]
                        DB_POSTGRESDB_HOST: ENC[AES256_GCM,data:CKK/Ic/VSQbzJjQf,iv:XfkkosfGwfprAgvCxgnpDWM9ZzujJuI5LyPmqadXxqI=,tag:yYDYUj5S7L7qSM/DIGbTZQ==,type:str]
                        DB_POSTGRESDB_PORT: ENC[AES256_GCM,data:cAn+Nw==,iv:kj+lcz1ObOwppkEK38+1fo+q3KNKo5k4mHQdeD/PIKw=,tag:5skb4RY3854Tp5gOrRmqew==,type:str]
                        DB_POSTGRESDB_USER: ENC[AES256_GCM,data:N7pb,iv:vp3JTZGh0nY4aDeqxRHJWUX87Rty800v5kXWrlCecY0=,tag:QUfx+9BSQvYCr5a/LCn+Mw==,type:str]
                        DB_POSTGRESDB_SCHEMA: ENC[AES256_GCM,data:t/KTc6AZ,iv:sitycUHR2yZA4gjQ1HSAImHG3a+Stq8BaykfpOTs6p8=,tag:Gn4ncpvWrSJdnjSkuBnFWQ==,type:str]
                        DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:Q3BDx40D0rQq21gAfOGsq4h33qk=,iv:89o1tbE9OZGSYgk8SBct61vzjBGbTnDjX2Wc798yiv8=,tag:v4GrL/a6RPNJdl82B/K33w==,type:str]
        postgres:
            containers:
                postgres:
                    env:
                        POSTGRES_USER: ENC[AES256_GCM,data:Hsaw,iv:XMnNQ6dhWjwjTAi+ey0xxvJLEyt003XOlVQX6g5tvaQ=,tag:I9HlS41h2mMQ8TfHQ0vx+Q==,type:str]
                        POSTGRES_PASSWORD: ENC[AES256_GCM,data:i6mim6s4q+uWBAX4RDsdkyCGZVY=,iv:vCfDl/lmYW3bdUP0QtK4m+VnXIOIJWXm5vxBnCSHTOg=,tag:QuNAh46WofuZb8KYf9z1Cg==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZXRKZ1BjeWFTRmp6QWo5
            YndTTmhXYXc1NHZEVGdpWHh4RHoxRE50b0dJCjd6K1ZKVnVLVndLeGZ4dXEwdElo
            TDA3Y1JpU0x1d0xWc0lLVVhxaGkvV0kKLS0tIFFZKzJwbGlENE81UTNaVUZVeTE5
            WWJMRzVwU2wxcFIzUzF2ejdOWkZId00K143c5vZaBwMVKJUiQo/9oX3XkqdFkQjZ
            mqd9zlOp/EoAqPQek7ElJvy0Da5XUrTDXr0CHpnWv1WGsEhf7/t+rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T06:02:27Z"
    mac: ENC[AES256_GCM,data:t6qbftN03qvKdpe0vYf6oOPpv74tLrrVHergnROTIh/BHuPwuElpYbphsm9mWYepW8TLRHJrlFEPyU4nYH03sC5bH9GPUCEAJPKceHKaYHKbFZzHAMkY6UndnhLvFGWFzj+HBNbg+AHkaafEn4ht7iMkydHT8YGuVBbXuTLbQ/M=,iv:g4gKahYX0bpwCusEXmdQweg0pTCNt5og7mEqCH2nCF4=,tag:OfNVBl7LXFL4WjYDer3hLw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
