app-template:
    controllers:
        n8n:
            containers:
                n8n:
                    env:
                        DB_TYPE: ENC[AES256_GCM,data:WVw1WK6vJ0gyrw==,iv:hHEkVX4aE87iVxdDmMYuh7tAaLfjKlg+6nq8BCQmhks=,tag:UOi5w0qVU20ZqZRZ6gcVyg==,type:str]
                        DB_POSTGRESDB_DATABASE: ENC[AES256_GCM,data:tOY5,iv:919cf+IJL60GMniC0buNiAkKA9wz+urIHins6y8/5wQ=,tag:UBlWdcYbflzakCPTHXvzqA==,type:str]
                        DB_POSTGRESDB_HOST: ENC[AES256_GCM,data:ycG6PYSE5HL/434u,iv:zhYOdqN2W8FpWdtV5TQfbRRZ4C0I7frCiiMB7djVYJY=,tag:hT2+jDLKLQo+/4MV91v2Nw==,type:str]
                        DB_POSTGRESDB_PORT: ENC[AES256_GCM,data:Ioa6rg==,iv:VRtgUks1KWw65upwBYeYq3fiJy+M7GYMtRyoasGsPI8=,tag:PYl7AS16epMRu5NINatQDg==,type:str]
                        DB_POSTGRESDB_USER: ENC[AES256_GCM,data:bsjM,iv:vp9hPEbkjtNeFix5qivpS3MKOv/2c08OpF77IVkObfo=,tag:G6zAPX9HlNLJ/Uu8Qv2Ojg==,type:str]
                        DB_POSTGRESDB_SCHEMA: ENC[AES256_GCM,data:mYFJsxgr,iv:QxkyJiTbuqSaMFGCRT20OXy78vDpa5Fpzn4HXXNMyvs=,tag:75frIg3/P878i5EHZLf0JA==,type:str]
                        DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:veCxUXnZDLfLZq3B7USeK8qVuwU=,iv:BHGn8hPX2kkoOYubLSx2QDUGEJUAX56KNn6/vhd+r/A=,tag:z1c9glBMBs4t4VYcTd6kvw==,type:str]
                        N8N_HOST: ENC[AES256_GCM,data:0Zf26xYn9CoaF/7arBeZ,iv:OHSjNcZpOfPTKWX25immUDBgYCM4dlKg+PNL0cl06qQ=,tag:uYXS6GaEG212LMP8cVSpMQ==,type:str]
                        WEBHOOK_URL: ENC[AES256_GCM,data:6xAYkBK5k6FpETkJ7iEFmD6ifWazwEsm,iv:BjcVzxls7q6M8iSez17vthDJa6PyFjBAJU4zkpFrr+E=,tag:+a+eQzHtyG5E2hk1u9lGEw==,type:str]
        postgres:
            containers:
                postgres:
                    env:
                        POSTGRES_USER: ENC[AES256_GCM,data:Rs/j,iv:dPcJdAC6oH3+cdMvrjS7GKHQiZ1RYX+wnDVejOPLKZM=,tag:uOJVlXxvowJ+pMUKPTqTag==,type:str]
                        POSTGRES_PASSWORD: ENC[AES256_GCM,data:JiLG144GAxlRmJe+buD/fcgIe5E=,iv:y61xAvGGacRCbtjGtll1TmVcXBeN0KZFYZ3Abr3rGjs=,tag:1cNaloQzggfBBuYi23t7wA==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIYzNCNXV1VVBRNTZUbDB1
            U2NTSWxjR2dLZWRqdTk5QmJ0anJoMUwxaFZnCkZJMDgra3hJVUx3QTV1UmZ3WnEr
            bm5HZXVMNnh0RWVZVkUyM1JoaGJMdk0KLS0tIG0yakJuLzBJeXhKZ3pXWlFFWCtY
            UzBKUGpCOHNPSHRLb2FFMGsyU0hoMlkKlmi6sFE7oLeMrEA/UZKSiSV9wR1sKf6h
            csHD73QFVCT/clNgZbMlgKpwYwa9lJRTeGDgcvm3EXJvJlKEea6gCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T00:49:00Z"
    mac: ENC[AES256_GCM,data:EFAhlT+R/mp+WUUNqegu6E5sk/lQfsaJRn9KG8gSLLUDvgUZ0JJHI+3sxu5Kz+HyQhpuOmIpUhbwOaaytMeZm1jU4d77d6HpavX9ojhsDzOKT7RiRsJcWXmekvCjt9f1zV36TJfXnzYoWhe4moQ+s8m43oO+Dlp3dmD6N7ORL48=,iv:9/iUBb01EfuEH6v2Em0tC+ipFsFguQFTQO5H7m+l+PU=,tag:hBgjs3SMjAezkj76UNPhJQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
