litellm-helm:
    proxy_config:
        model_list:
            - model_name: ENC[AES256_GCM,data:NMbE1rPIpe73gw==,iv:YEbhVWqcm4OcjZaWSAWm6s/gVizd7loPTD8Np5M2G9Y=,tag:FjQDqTdr0Og9WOs7fgIBLg==,type:str]
              litellm_params:
                model: ENC[AES256_GCM,data:1MMfDAdLOVa7ytyW9zz7XPw=,iv:VEU43rcdBNuaxULWi89/pkZIo/+Wa26o9OzmWexCILA=,tag:W8/VdbaYznvj+Ati8sO+8A==,type:str]
                litellm_credential_name: ENC[AES256_GCM,data:iV35LKm4lFYo+4s5,iv:XL8dFMwl+T8du7p6nvnPsOWbPyXzaGg8skJkLQdGH6k=,tag:VAOe0I+rwvnYwq92BjaV4g==,type:str]
        credential_list:
            - credential_name: ENC[AES256_GCM,data:iolsCkG7W2wpeyJx,iv:rT3NGPP0vDAgrkbpPZVOX6zFtoiKWxOtjg9npDacShU=,tag:8+CmOhJN9uM7HaaUt0g6rw==,type:str]
              credential_values:
                api_base: ENC[AES256_GCM,data:hkY7wzT46cyQ4LDZDwl+EhtqEEURE/21B6E=,iv:zGL7jDh/6gstB3hHq3QjbNYkJ0py3D5CKS5cfGcZUPk=,tag:Xa9QKJM1ZH1t81FAPqrlug==,type:str]
              credential_info:
                description: ENC[AES256_GCM,data:OIA1XWzOEMPNSuCJkqDYJiXF,iv:eOFPK0Z8zZCkyPZC2SziKOxAq/eGDFikKoFSx/Girco=,tag:s+S9B4H1fsME+sPW4g9wtA==,type:str]
                custom_llm_provider: ENC[AES256_GCM,data:OykuEJ7S,iv:hFbQbgBoo2U5ESbmA4s4oA0eSfmU2fh1KLD8kQFmGvI=,tag:D0trkGymxOg+tzkuVZcvng==,type:str]
    masterkeySecretName: ENC[AES256_GCM,data:xiM/64gxwOl/Y7WFtbCJO40=,iv:AVKBAf/BzbQ5XvsyJILqq785RE7StfEYiAy3D/Uu0S4=,tag:dsK6WPlVI85wv5QpQdWKlw==,type:str]
    masterkeySecretKey: ENC[AES256_GCM,data:qL0KjBAvLd4e,iv:590NlIXKKogDLvnJ58TlWI8alVV38gy9WA7h5CP/Gjs=,tag:zHoHakhOiaCzozsSKt6LVQ==,type:str]
    db:
        useExisting: ENC[AES256_GCM,data:TwSKAg==,iv:xpBqAnCz8Xi1l44Qih8touJvSS2sklTcBqEBikMRdwk=,tag:U93DAhFaUOeOEuBvlid62A==,type:bool]
        deployStandalone: ENC[AES256_GCM,data:a9L8nhM=,iv:MI7cPQxlXWF9qvEz8fCd/zT/ktLJqSQpIbbK8UNsU4c=,tag:ebs4XPfUDuPG2RsLSGGm9Q==,type:bool]
        database: ENC[AES256_GCM,data:9xRpQEFb+w==,iv:48afb23eAtPwHT8Fd3KZiL6oOU4kHGR2BSqk0NYkzOY=,tag:PQC1KaJ93jGTCJdauM4hUQ==,type:str]
        url: ENC[AES256_GCM,data:ZyUEJ3CUzGJIrqlTP76u0IMsm0FioGLQpm6evgYwCKAzsMXLNbI0eN89w+JMQrM2Wg9H8Ql+5qNDDzdxmWrmHw5XEoukAfYWNilCYK4F8m2DjXIqQbTegQ==,iv:JEwJNEQ/mWzx2kpegalwOYWcA0+YELDdfV1xWlfWkTE=,tag:P6VFKA6FX3/BHdbWBgtftQ==,type:str]
        secret:
            name: ENC[AES256_GCM,data:OIJ/ZA9sp9fTYrZAyYdDaQOEDCA=,iv:2XEgAt6gOiP/aHy8MlJzwpfN7Bq2U2fj13ZXyW/I+oI=,tag:2kwSkW4Dk/mUxYFshxBKlA==,type:str]
            usernameKey: ENC[AES256_GCM,data:4nxiTWVWTe4=,iv:fB5Kmug9jSlpubEOpDGbbxEEaFoVcSb53Z5swdMMpKg=,tag:e3F88wFlgD0/WgNnvDfeKw==,type:str]
            passwordKey: ENC[AES256_GCM,data:NF9tPDLREUM=,iv:8ozhKM0ppdfdbVoP87vUr7F4WafqSbYTPB5GoKPLzdo=,tag:Hzq27OhzdIaPE/lihGJq9Q==,type:str]
            #ENC[AES256_GCM,data:xcByRtXxd4f1PUq0+lUzNsLs2V9g7zBQ2VvFK0gWIMPWNHSxIUJcp+cxWACWSy7jGnzIvNxRmEQPjsU8/pflXIcW+MXTFCuA+rI=,iv:NPkLT/PcUfazu5nDWpkkpCXO57KsUxCyNeSjiulAe+Y=,tag:iil0xzc8NUhrl+LZFSv62w==,type:comment]
            endpointKey: ENC[AES256_GCM,data:tQBUKw==,iv:LPZRdhTw0RkAsJBg5pX3SXm87QdtN0TesoGZrORK3u0=,tag:WkDEsdjDyx0hqW8EQFOo/A==,type:str]
    ingress:
        enabled: ENC[AES256_GCM,data:7gbMMA==,iv:PLXxdv0DigPvyXVLI/RKC2oH3c78MmvRcARWh+SQMQ8=,tag:74OqBfvNDg/SW7AfCtFPlQ==,type:bool]
        className: ENC[AES256_GCM,data:Aj3vKqGanQ==,iv:mDg0iMBtKyctjBrq0CYXvdLufToWIeFYBKv1XX9EEg0=,tag:oXq2pnGnDRxofynpDcRj7w==,type:str]
        annotations:
            cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:z6hC0ozQazZnM+npiUr1pw==,iv:X+KbgjRM7bi5nGdYE21smPzlj01cWLjHn3Q9RjWfvM4=,tag:6JNZED5o+vgyFjcIt8lklw==,type:str]
            gethomepage.dev/name: ENC[AES256_GCM,data:KUC0KsuCyw==,iv:W0/ZQPd6kOwMdQWwINQsfvCVoKH0nXlFcuOiyFqdd/o=,tag:5PqH84G1CEabxdUHu56ZxQ==,type:str]
            gethomepage.dev/description: ENC[AES256_GCM,data:0puD+d67Ag==,iv:nGW/VyACsxOElw4QfGGpmeTi93QAN1sdrRl1b7YjOMw=,tag:qbUy+jpp2w/sXY6EtVhK5w==,type:str]
            gethomepage.dev/enabled: ENC[AES256_GCM,data:QNZ3aw==,iv:cMbf3ubd6kzJMS5ygJWExbVNga1hwzWk79rzOR2B1i0=,tag:23Zmjb5RER6fRbY2IL8dSQ==,type:str]
            gethomepage.dev/group: ENC[AES256_GCM,data:Fwc=,iv:a9EujlVqb2WmuvOm5/ynbmwQwjCEsGsJyjoCf8e5D38=,tag:8QuRrvi42rz3fXbgOiePVg==,type:str]
            gethomepage.dev/icon: ENC[AES256_GCM,data:Sxu5g2mnra7BvNX+bSM=,iv:kpdzU0zReCuvEnXM0VdonXzKnaICoU+akZHsauUm6g8=,tag:2j8NV5jkYKmmfjO00AwfCA==,type:str]
            gethomepage.dev/href: ENC[AES256_GCM,data:gALTIN5RfdexnlbldzzVsORfIi/XmsAyGoMZ9oH2hA==,iv:ei2pOqBe3IFwdpGX2bEzFpUNJPaVNkE+lBTwR6QNA7Y=,tag:OeGynwCLR9w2ZPyGMKb0gA==,type:str]
        hosts:
            - host: ENC[AES256_GCM,data:4MLeL2Q4uaTF4sINCLD4PBJSgQ==,iv:7V1cL3j0HVAGiZJ8osf4/QLMYRo7SP+ARYsZnyp0UWY=,tag:DcxE7qSiTGRu8g4KLS048A==,type:str]
              paths:
                - path: ENC[AES256_GCM,data:/w==,iv:3SotLk4Xj23Q/5h5AEKYC/+d3yRAEL8CEBBiFeZSVuQ=,tag:SdMNFMath4JFp1mpR8GspA==,type:str]
                  pathType: ENC[AES256_GCM,data:ill4xzX7S8W+yiy3zCN/eHHtJrHSPA==,iv:eG6JwraeU67cm0G8ZwcjZQYVYorGiNMrYgs5VLnExlw=,tag:Cow4NCUfEtoUGKElC9mt9A==,type:str]
        tls:
            - secretName: ENC[AES256_GCM,data:IWxKCcOgTDmdqZznPWWxgw==,iv:M0Q2zI732AaCrIfpHOTm5Asw9jbleiUm39XjwMOPi2E=,tag:1Hd1Yy5r00AeibWNqsFOlQ==,type:str]
              hosts:
                - ENC[AES256_GCM,data:WzWCFabOtxQA+/B4D1C2obOh/Q==,iv:kiUJITAqPKPIEkKJM3EMg0pTZ0bNxhlQvyUDHNjFTMM=,tag:C8K7PQ8ndgQkC5f59aN6/g==,type:str]
    migrationJob:
        enabled: ENC[AES256_GCM,data:f/dCNw==,iv:J8otzU0Z0FwhS36pfVlEfkOWH/NJiZB08O6/1Y6hcHE=,tag:hahZXKjah39ZFdiu7J7FnA==,type:bool]
        hooks:
            argocd:
                #ENC[AES256_GCM,data:HU5QM4LonPmOdN4LcaKuzkqpFBI5YZuNHbp9jhJIwQ==,iv:TZxw6RlpU1jFY2C7AUyrmj2jink5zUmZwJurbeUdw5k=,tag:u1Twg+kdZTkU0+bY/x+dqw==,type:comment]
                enabled: ENC[AES256_GCM,data:lxmr72o=,iv:jbnGPbHPqd1Nq8JnC+p8r9Unb9OGflYF6nn189yd3PU=,tag:7jjiK6zFdo5I4NIinQdlPQ==,type:bool]
    environmentSecrets:
        - ENC[AES256_GCM,data:mgPBiIhkGz1I9+M=,iv:ofhvQLuyxW0dpxVRGVGytgSicxnHRena8/ESUivnP5k=,tag:PRRgUKBjHba5iy2MAT3ugg==,type:str]
    extraResources:
        - apiVersion: ENC[AES256_GCM,data:6R0=,iv:UD4935PBG0a3nHIbugBIr1BoUL6736wpv6X6oz+EJOQ=,tag:XbQWWlmU2hJ6DC2p95iCjw==,type:str]
          kind: ENC[AES256_GCM,data:rpdCjugQ,iv:ZxJ9Ee6CSvMSSwiviaFiz2B+XXLve5Yz4rFCUmaoqk4=,tag:DlV+EaNwYQYyYzELeQPGLw==,type:str]
          metadata:
            name: ENC[AES256_GCM,data:dtO/ueR0JQc0sp3tpHG2P54=,iv:/k7knW6DZ4v1/bgfgv+GcWqrq2spDX7KeCsVsEVqJDA=,tag:vKk0YY5Ft+8wyFfMBWJxKg==,type:str]
          type: ENC[AES256_GCM,data:GmUxcUHc,iv:bqjvfU9SxFenCHkOKh8iQv7PbbpA/mixrNcJG0PRlmQ=,tag:GNrFJBTQnNFYsrT9f35nxQ==,type:str]
          stringData:
            masterkey: ENC[AES256_GCM,data:NFo8Chnp1MYk+Z4hqzhFGjUdn0lxCY9+igkDoeP1XZRHE9nZxyx5aRumjUJOWDzbjJb0,iv:t/JdftU2mxocV+W7e/wfbIqYosQhds61548rQ8RosLk=,tag:UWRvyCwDBMuFKOtPhayjtQ==,type:str]
        - apiVersion: ENC[AES256_GCM,data:dck=,iv:NGwaU3ajIb4HQKYL0QrcJtgG3fIV5orJwCEqUdqxgLk=,tag:wZqVLD1kmW/zdl5shwoepA==,type:str]
          kind: ENC[AES256_GCM,data:mYB+kOHc,iv:I/qunf7JKBeBINKZDsAqbEQ6sHt2QE8ukyzv5MC1MVQ=,tag:gDlPKTsGUHlp2n5xgBH4Dg==,type:str]
          metadata:
            name: ENC[AES256_GCM,data:K8/dkUx+NLblM3g=,iv:SRC8B7EUQpwFVE/V0CQmUrQBK2y3fazGiyZ+upSyd1k=,tag:Xqzg0w9Gl3iLpxbiZLATlA==,type:str]
          type: ENC[AES256_GCM,data:iWPd+kdt,iv:CJWCxTD+HgBMca9mmoZpJGGQ+Tx1EOzwy2kHNz3i1C4=,tag:1V9bf+L7bqkRBxWjWxhrTQ==,type:str]
          stringData:
            PROXY_BASE_URL: ENC[AES256_GCM,data:91SW65zbmsVLMAFE0e0IzstQVE/NcfG7Ktg2,iv:VIZVh01pF9iR/1b24qPKVydLl0y7hcQbGTiRv4EXwn4=,tag:AYu6+qX80Ksl1Qoi83TQtw==,type:str]
            PROXY_LOGOUT_URL: ENC[AES256_GCM,data:QaS6E9/BIVjrjg6D/BuNZhbZ91Bol5W/2fKN,iv:l0NNP1AV/xU4CwsqmWjk8oLFJMw/YLDemRm9HEOFiNI=,tag:7G/N/UIs63HS2BvmfN/2ow==,type:str]
            LITELLM_SALT_KEY: ENC[AES256_GCM,data:HdfwFG3XL3+VbaJeZBN8fZRWBFYzEzKHD+X98UbipUpFcpXUT44lYWAMcufO+vUax0RD,iv:1JKIaER+6uRz5zXv787hbu528uLJghW33JAuKRnCnbM=,tag:DKHawOZ7vBdwhshPtZuyYA==,type:str]
            STORE_MODEL_IN_DB: ENC[AES256_GCM,data:y3R7Rg==,iv:j9Di2/cG6wakhGgpqQc8x+uM5MH5DOJtZZmuT0xnWJQ=,tag:HbVngy6UhTdx40rAFivqCg==,type:str]
            GENERIC_CLIENT_ID: ENC[AES256_GCM,data:mEWQ0QCcADWw+oLY94TqkaNqxDmUnMCAsNf0+8o4ahMSAz3c,iv:hC8ABv1a4PoeWSbSGSt3w08sc01C8qrgX2TDnzlUMYU=,tag:Ra78h/hNmsV99pqkaNH5KA==,type:str]
            GENERIC_CLIENT_SECRET: ENC[AES256_GCM,data:nN//vRxSMyPtGtK4Rr+nSyP0Iu7oIgpUPl8MB8klp9Y=,iv:F4ivgplxuAm8lvCbfhuk+774O8DZMRmGS1SqD9sFPX0=,tag:xBKsDKwjf6NIfYP98DWTBQ==,type:str]
            GENERIC_AUTHORIZATION_ENDPOINT: ENC[AES256_GCM,data:3/hYHSkKredthgNElawLW7mUX0I3lL9Nw135fHFleWWHOHHM,iv:NEeSy4Z2QpurAGCWWpVqC1KYeA1+2CKeevi/06smZyQ=,tag:eN7q0pPjbZmuQOSj9gmbYw==,type:str]
            GENERIC_TOKEN_ENDPOINT: ENC[AES256_GCM,data:kYvzelT480/XmAPi8ZAfqxREyAlNkbdUyjJPT/YGHSVYpKAU1hbSX6Q=,iv:11gp8wtmhXREoW+VSV7Ke0IH3XlUWIR7U3fRpFdDCnc=,tag:WxYjoCDW3XVH8FpQF/2zLA==,type:str]
            GENERIC_USERINFO_ENDPOINT: ENC[AES256_GCM,data:dUvCsXKP0bPWSe2+rUQNHCfgvq/Ry59UnZqwNj+ph5T/UDnds088sluIzxw=,iv:XI577YJYNwdX31gPz9tuovJ2F0TdABppY+YqnLfAEGk=,tag:dY7bebESQm7JRYpsZYejVQ==,type:str]
            GENERIC_USER_FIRST_NAME_ATTRIBUTE: ENC[AES256_GCM,data:P7EldOS2zgxCNw==,iv:rD1kgtr0VQ4FIEauFuUWQ2WUXdGcAboza2dck6Yl0Xg=,tag:LeyD78dyzx1arq5AwgUEBA==,type:str]
            GENERIC_USER_LAST_NAME_ATTRIBUTE: ENC[AES256_GCM,data:hvn1bfuHEd8kZ5I=,iv:Qo4tKevlOgs33O/hguo9LtNya11f66sCne/8oWVbvX8=,tag:cjVNDr5AMKUtHFgVQodRvA==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTenZQNldDdlFaUEFJa3Uz
            ZERLdiszNnVZcFJUZlJrMmJ3MFQ2dU5HQkVVClhwaGtUeUVxeGdNM1hZS21kenZI
            Zzk4NVJPU0pkWW8vUCtFNFZEVXhkamMKLS0tIFFNVWE4dmJTNXdqMjFZOEZsTEY4
            K1IyS3JHQ3BzaDNpUWlwUDJHczh0N3MK//kMlNy4JttGv8vXnB6fiWi2k1p8AgOs
            EKDXNVk1wNxd5Ag+cmnvTibcUQ5nMInny+igngovMXa/ESZ4XqLr8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-15T22:47:30Z"
    mac: ENC[AES256_GCM,data:sXYf7chhHfRa4gj3pD4H60FtGYIcneX74lmQP7HJ7oKFaGIZ2F7bGSuvUa/+miUbHVVlFwPQcslsUW11/PH5b9rIwNG4XBRDNFAwo0DNsuHt9GlXOODqFj4pHYjD8ZWBcetCzB+3zR0rmYu1/mUrlIG1naLDzDbYhJKfYYnX5Tg=,iv:uNHI30c+hAzE6zXouW8G5o6cSJKu9B8m/v664IsayOc=,tag:AVh9IdSZMiY1h9OuDU3RcQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
