litellm-helm:
    masterkeySecretKey: ENC[AES256_GCM,data:n/uOZOyFXueACl6pAXUY29Q6fetXNVqRNbe8/cKRwa7o8U5WZ8KhVHbL0fSZFJ1FAg1A,iv:Zj0AaLSedCZQ+NZsGuuoslh2azOm+Lm2tIXn17XqRQY=,tag:6bJ6cWEDitSjQvyew7n88A==,type:str]
    db:
        useExisting: ENC[AES256_GCM,data:OT/mug==,iv:Wl3xM9kwtr+ubf4DUVWWFk7H8BAOma9bJBGJo4znCCY=,tag:P+6U+7n9lIBnXG2inPNgqg==,type:bool]
        deployStandalone: ENC[AES256_GCM,data:ATqPMsc=,iv:bkgJVmfbmZs1KbsehDwlJQix5CsxQRb6URkXlpS8zgg=,tag:JqBe6SZ+Qp1g9UMFowQ8XQ==,type:bool]
        database: ENC[AES256_GCM,data:Xe2uh/9ONw==,iv:T75GKQ7/2/zgEJnFMl9xStFHSaHMwRfMCrgHacJUD0I=,tag:tQK4VodLHxtAx6c0gCljVw==,type:str]
        url: ENC[AES256_GCM,data:w5WOJ/C10tDFs2kTZ03W+gibuUGzRRnF1j8S5iV6SRAkgyz8V7xv6y1X3QJY7UcURjV2meb/J75dcDDFOnByliJC5Av8TXPucVANaafbgLGegLIKUWcfuw==,iv:BEU+2Y+Amn99TGQv7In1UfJuFQWEb8atWrU94Qta4QM=,tag:7+xjsVuFmg49UeKCkdVPiw==,type:str]
        secret:
            name: ENC[AES256_GCM,data:VwYWUfDvOK5JUEsGQ2JK/Llhrag=,iv:oekEv4OJMfAgJJjNrByzEqjDKZ8etWYGPln+/M3xUJ0=,tag:YLYwAnedjwYf4DnZtFxRBQ==,type:str]
            usernameKey: ENC[AES256_GCM,data:uBcm3vWo13g=,iv:jUQS0oqmJtN5Y9QtUmp4yy98LVAIyxHfvNRtRCptHoE=,tag:3HNf75xexhgQ+cen/f829w==,type:str]
            passwordKey: ENC[AES256_GCM,data:rSfwHmY7Sjs=,iv:mU1buObg9nehTaAZGVXwC8FZk/nGhCuw9P86ZMz8tAY=,tag:oijMQ07c0kkqCea39ts0Mw==,type:str]
            #ENC[AES256_GCM,data:QbPGKpehtS+qba8OzoBcQDrMV+mpVsUa6vCxwm+EL7c4rspDkKxkVTujlNtYD2dgPfd/N88DQBuL0LPx4rmc6AbxpyPA5kCahcQ=,iv:JJdCmPvL/s9HfFKrI5j4LUV5JPD+wOn0N8UjYFlbqiM=,tag:+m3pFfQxioXRpfJdpXLAUg==,type:comment]
            endpointKey: ENC[AES256_GCM,data:mU3LwQ==,iv:fWa1E70r9K6thmRSyQp1lFJH9am5Q8kPPyZ21FC0+hI=,tag:7JSMu969pfLkN0IbFtlcFQ==,type:str]
    envVars:
        LITELLM_SALT_KEY: ENC[AES256_GCM,data:l4XbzzkI/jxU8t1AXz0x9jet13hob87hEWozsGIG1oDJiELK8hjHsl/h+2jSbGqZxU1p,iv:tpWruJDtV4mvGdZMAKQUAkzX17snbW6V5n+PTmBs7QM=,tag:8cLMXQqDWpAJET28xvFyMg==,type:str]
        STORE_MODEL_IN_DB: ENC[AES256_GCM,data:+oYUow==,iv:kJ+JIJvefnUArZp6v3NeIMRE8WIMTYZDbdbfTugHcWE=,tag:FeL1nhO9JgZapHpkw9lY6Q==,type:str]
    ingress:
        enabled: ENC[AES256_GCM,data:J53dUg==,iv:gcWcM8ZmoBtp0mm3Rs6YalDBkPmxio1aDy38pg1Fzoo=,tag:duQyOGmmMiqbxVdLegItFQ==,type:bool]
        className: ENC[AES256_GCM,data:gTo1XckGiA==,iv:vVkWwkhAhN4GEFyX8qudZJluoCcdYX0enqWNob5FDds=,tag:Z1zKwx5qoWdoNahELk7Slg==,type:str]
        annotations:
            cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:JIJSsfnZxfVQeDqVSvNqQw==,iv:jws3LS6iENX3tHTgBwjll25szzxLJcjjBVWC1DGMNL0=,tag:0rcP3VQDIgBgON+cjK8BGQ==,type:str]
            gethomepage.dev/name: ENC[AES256_GCM,data:Fdd8aQ/GXg==,iv:jl/d+3brvyTXk1yQ5UD7xjsYEobU3eC7io2Xoft9HNE=,tag:myujad83TrZ3BR5XAO7rZw==,type:str]
            gethomepage.dev/description: ENC[AES256_GCM,data:1zKIukZ7DQ==,iv:E6y9ij5x8JSzn785Mgb6fVlQCwijTpMkNVMjGAwcLTc=,tag:jRYKdwpwArg3rnSnQZ+Usw==,type:str]
            gethomepage.dev/enabled: ENC[AES256_GCM,data:dhESsA==,iv:54OYOM9H9r2egnONWHlAlxyDHJ3cBchCAUMhvda4C6U=,tag:qMoAvAe06FDMFNPd7I6bIw==,type:str]
            gethomepage.dev/group: ENC[AES256_GCM,data:SKg=,iv:5sBI+2LqIhBETyHTjEyZpZaTewjz0IrGF5pGKlNJu54=,tag:fnDPKb6FqARbPkgznBg7hw==,type:str]
            gethomepage.dev/icon: ENC[AES256_GCM,data:rahbehCv160PGL7l4o8=,iv:cPfpf6YBQfi05gu4Xs2TS9g0dAXm2zYsW+os/0odqyc=,tag:J4qKHb4a7oYdjhn4JB8QqA==,type:str]
        hosts:
            - host: ENC[AES256_GCM,data:TFZyBf5b3UxEABEfI6a9yY6c+Q==,iv:az4n26GuE6WTGZSpGRK8z3dQTg2XJIefTbPzhH4C3U8=,tag:MmE9mm/xrP7t7JFSwgMvuQ==,type:str]
              paths:
                - path: ENC[AES256_GCM,data:44Rw,iv:yZ7gxEQBkFfLXlv/BOwm3/lnEPDlJNBP3Ga5B/1y5pQ=,tag:Ks2Ce+TwDzbh0Vb5suANSQ==,type:str]
                  pathType: ENC[AES256_GCM,data:8JSY6GQgdHfWZTg+M2IIrpIN1JJKBw==,iv:diFreEldjTb1Jtf6axG6lLcNaM8OjKWm7zrT42VGWaE=,tag:vwkQ/fQ4m4/oqHxbjtTqwg==,type:str]
        tls:
            - secretName: ENC[AES256_GCM,data:zeby7NAvBiGYEXmC8NaAzQ==,iv:K9T/sWZ5w0ugiPxkt0+Mh/xK+bZ2cPnWW9KLbh1ACFU=,tag:UhERHROV6/oQXzWHiBK5WQ==,type:str]
              hosts:
                - ENC[AES256_GCM,data:vGaNiz4VG/45TCRJzWXVF4sgvg==,iv:NLclN1Ay5XPw22aD70V1Ixzo0QIpyJPpHA5rxE5Jpv4=,tag:v+8Ec7NKW2j3gyF4JKnzsg==,type:str]
    migrationJob:
        enabled: ENC[AES256_GCM,data:TEu0Vw==,iv:v52o+jyowruMYntHIS6vg7mrg8muI/8X10E/vbv36hU=,tag:gAhAkfYJAzEkaoNOLWjH6A==,type:bool]
        hooks:
            argocd:
                #ENC[AES256_GCM,data:azM8obxthRMsGc2zs3qxywQ1TMO5NrxInoAaQFtXDQ==,iv:GvOoo3xKYLFUz+mYI7hWXwZ8R5YI09J7XdQsc7sHqjs=,tag:Bv1WXQ8Pae/4HD//lsm2dA==,type:comment]
                enabled: ENC[AES256_GCM,data:L8DGYio=,iv:g95Pnt5wI/he01+rXGW+9p/1qvdIkgXCUtLumYqoJSY=,tag:yz43UvWS+Mxu7c4Q+lc0Zw==,type:bool]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxNUh6WVVFQWZ3WG53akZ2
            MG1OVTZsWCtMRmtZazVOSjN3YXphdHZENkZzClcvVkthbkJ4SXFUdzVNLzM5VXVE
            UWZuZGhMcXFJSHB4VG1DVExoZ2xnY3cKLS0tIDBnaE9ZdktPZkdCUnlMY0N4K3FB
            c3NEVkdleU5jNmpOSEI4SGNNSHJVTHMK7/7toh4PFh5zKVedRD9aJ93iut7FUN7+
            Afq8+p6oi4TAlin6jZ1J6eUL/izdJWXXIzUD1zB5uXf60amG0vG2rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-14T02:27:20Z"
    mac: ENC[AES256_GCM,data:hLZkAKfh+rtPDFvi1n0bziKzvh9VIRvVpuAcs+x0GVGt1rd1is/0UjD5OvwxXZ8Qd/aR0n2F2fzYWZV+B/Mp7PZPXMyGIMxBfXxU1CIqd6kOS9GaxInzeONvLkQfkExTsISD3ju4WEpVRzNkwXamZUIV0NlQl6ikdGZij7AEKVE=,iv:9wGaaZG/bjqvNRwwRf7TTU5N/ynLmuIuhZCFVolknCA=,tag:MLKeUKDWsv2540VgASjzGg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
