litellm-helm:
    masterkeySecretName: ENC[AES256_GCM,data:aobOD27ryyTmtwboSwLpq/o=,iv:NBnuGaL5Q0H0R0Du17+DLuPf2Z8rRP/gJxBRoVNvvNM=,tag:r3Nws9wnIutZo3Bv79xPaw==,type:str]
    masterkeySecretKey: ENC[AES256_GCM,data:7rwmG6Wdbr6j,iv:l/IinFlhu56UprZXle/0JZ+3FsYooNeKqQajhZAf7wE=,tag:bJGJLAZo3HQ3Ro2R08JeuA==,type:str]
    db:
        useExisting: ENC[AES256_GCM,data:b2I/ow==,iv:DaIprgvCgEUomTamGNMiruOXzWRObrsOUBX3RAwgtVE=,tag:VM+iS3ba3u+mhSThZ/gjwA==,type:bool]
        deployStandalone: ENC[AES256_GCM,data:PZVN34A=,iv:3254pgXIPvR7ORFSOUJtj51aQ3KoNy8Hga/GaH0Dulc=,tag:LGho8B69SJTGng/9y90pbw==,type:bool]
        database: ENC[AES256_GCM,data:PNZCDHfJUg==,iv:5q8uCKZRcKCGHuv3n65ujN7tcZhRK3+bAVKricSYF0g=,tag:1YQm7gRuIkVnckZw6niIDA==,type:str]
        url: ENC[AES256_GCM,data:QJWv5aFsxeOOMJFCw6MmUbUK3NtPE7a60/l9w88m1rmowLtCWi735XMUnXwSWZc/SzsUTkoEg2TQA22eXUS2gIDyyYL7DnkhidLtu75GYC2w+gfc3oI4aw==,iv:eVAZVlhPjDSYBtRse4pIEWFqvcJBXLxCY7W05WBzovs=,tag:AuALLL8YVRZvgBEaKay0Iw==,type:str]
        secret:
            name: ENC[AES256_GCM,data:JfLLhtgtDZjWokwrMWlM52KJkno=,iv:44vrf9f7AHASC8lviRGHINzML5UAEwZ1Pz6dJfwH+QI=,tag:YPF//qwAoLIeChydmLPgSQ==,type:str]
            usernameKey: ENC[AES256_GCM,data:gegCWaxikik=,iv:jWTIZjHGMfQm+9boLJDeTK5aB2Hq6k2Pc/nzPgQECJU=,tag:Mq3Fm1ye7eHR6WI4L+KNVg==,type:str]
            passwordKey: ENC[AES256_GCM,data:l+CEy3A2P6I=,iv:WYbIQLFQGNbDSxHBBJF845FRuN0a9VFlFrwDVjzgN6A=,tag:N/FFMwDRaAsEPRbxuvAsEQ==,type:str]
            #ENC[AES256_GCM,data:APUlxg+GNbS6HcrSymdNLMid7yw89w8PYRCfQbNFwx9hwLlosS+ZvdcX5rOEHaUd3VC2Wpx1r/83LwcBL8uVbxwyF466Y6aXY2k=,iv:8+ww7AqlCLx+1p9yHZlqpLbVBNje650cQWXWcp4xonM=,tag:bxr1odXcGNWOp2FRTTIyVg==,type:comment]
            endpointKey: ENC[AES256_GCM,data:OZKr2w==,iv:al/LVxlAWhE7A4v9S9wZfuP9RDGo9y17HXpu6i91D6Q=,tag:r+HlIdLXJk5zXNlKwqwp5Q==,type:str]
    envVars:
        STORE_MODEL_IN_DB: ENC[AES256_GCM,data:f8kRUg==,iv:/oRhs0kZKBHYwgTXAfTIRDbB0H9aLa2Ey8R6T7NFBcU=,tag:HxgGPcMr3SiAmp4Qj7Cy6g==,type:str]
    ingress:
        enabled: ENC[AES256_GCM,data:U0UuAg==,iv:rcq0842hE2tAZQOvlpu/lHKiJsPZvvKK3kcksnWfpR0=,tag:iTe3BU6i68KOWlvspZwYRw==,type:bool]
        className: ENC[AES256_GCM,data:AmRyMU+q1w==,iv:M7woIaKCWVcMVmsjV01K53TbKVlpIdotEz8f8Q5ezzM=,tag:xZPwgJFJwaksns5kLFiAgg==,type:str]
        annotations:
            cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:iBaB7R/tOm19xX3HwUwhHg==,iv:DXP25YMJVoB7ebJnl4FQotMyQd5ZCEy0xb/lYU0YEMA=,tag:cqOA10MLQUu3lbcr60+bDg==,type:str]
            gethomepage.dev/name: ENC[AES256_GCM,data:/gW/mj2inA==,iv:UEkn5Az55rTi6i/ZrlhZG8Imqea9At0ZTw4D+pzxOZk=,tag:8y15CC5xzAdfnhThL5Isag==,type:str]
            gethomepage.dev/description: ENC[AES256_GCM,data:GUmBKVnmRw==,iv:5GU1byQW5MWuEqnxxdqx0zuqU13JJYUx6b4T7Kjwcrg=,tag:WKfwyQgvAfE4DRwQByjJTQ==,type:str]
            gethomepage.dev/enabled: ENC[AES256_GCM,data:MbW/1Q==,iv:2oxMYFY8mrGstoqAF/8G9uGvoJEPnkSdi4RX0FhDDbI=,tag:Bsf/caIcpsTgSV0ep3fWBQ==,type:str]
            gethomepage.dev/group: ENC[AES256_GCM,data:p9Q=,iv:g/ezYmDVFSh3a7FCTcd+yrIEc1EaC/tJwvZmQLmZklQ=,tag:Q4nquZj23B1WIfMpT2ZmjA==,type:str]
            gethomepage.dev/icon: ENC[AES256_GCM,data:/k/HL9dsKvKTghGHUC8=,iv:YfOvoknCjMbRWKOEGmYFFwbaCXKrZB78uagxZL4/lv8=,tag:hKiNVX9EKa4m229lYrk/5w==,type:str]
            gethomepage.dev/href: ENC[AES256_GCM,data:D4JQcBm4bRCEbIEO2erQHAiszr3VjbOAofSRrX/atA==,iv:giYBbA7prR+72W9juJNEKTz9AMYsphbsOqIKBU4Lqxw=,tag:9Y9OfVTi1b43VS0erW4QTQ==,type:str]
        hosts:
            - host: ENC[AES256_GCM,data:NfQ3zT0aOHvWolT0awKVQkrnIA==,iv:UOxdJauwNiWgueUpVQ4VsDPUuME48sKgE0mzcptY5YA=,tag:Lr6UWutarTfbUietrynBjg==,type:str]
              paths:
                - path: ENC[AES256_GCM,data:mQ==,iv:1O+w0cVJF/WjTYu7n//pm5zVLD6HAwDtPxl8scua0HI=,tag:n3bh669zAoUNYEtrDafTSQ==,type:str]
                  pathType: ENC[AES256_GCM,data:/dVO9WTqwQga9zIek8Ffgzz2/4MLgA==,iv:v9E12LURNEECi2PprdYnHs3zdcWalWtlxFWPiNeJ4Lg=,tag:6uU/2FKrAElxOeoCNqOIYQ==,type:str]
        tls:
            - secretName: ENC[AES256_GCM,data:yIEimvwbwzOeBzMOFu2jog==,iv:k18DyLE89KMtOCg4M8Yhvqps+xpX2Tl+w11rxTc0RN8=,tag:ugGhV7+cEpmjfUCn/xJNGQ==,type:str]
              hosts:
                - ENC[AES256_GCM,data:C1sclZcqHNMIgwrubjK94je9TQ==,iv:NugI7uT9+aeosPs62qPvRWC5w8Sj7YTodiV4towKynw=,tag:x5Erkz+7HCUn7uNgw0YxaA==,type:str]
    migrationJob:
        enabled: ENC[AES256_GCM,data:hfNzjQ==,iv:FB7UnXBMQjtqPPOOI5Y25ury/CeiYKS2iAlFxUG2Atw=,tag:lOllsxGh/iDHKFdUq7NggQ==,type:bool]
        hooks:
            argocd:
                #ENC[AES256_GCM,data:ziy4RG2Myfr+y7lxTI/iqZ/L37rNG0xudX7psPQ2cQ==,iv:65AdwaBf07fycGhqsTsCCS/eM18obI6ajn+OjkmnPhw=,tag:RWPPB4Dfk+5vggH4fEdVZA==,type:comment]
                enabled: ENC[AES256_GCM,data:TW4GWCk=,iv:VBSMiYS8gD/pwyW8Exkb3Uv14Lgwnvgd4AdVwr0hM1k=,tag:M2qrUcItNEAeD472gLg1og==,type:bool]
    environmentSecrets:
        - ENC[AES256_GCM,data:dyu6f120YoG2024=,iv:sPxYZRtSWoo4fj0E3Rjjsgax5VL8uZZ7aKToP0f1xIE=,tag:XVbKTUEES2DCEmNGJwYJaQ==,type:str]
    extraResources:
        - apiVersion: ENC[AES256_GCM,data:jO8=,iv:UnGyaqzYpltEmNs/cUQTxKvUULlkOUyLmOr1GjHncpw=,tag:k+mS2feJOL2yV7OlmI3jRg==,type:str]
          kind: ENC[AES256_GCM,data:AmftYOhM,iv:LF9S1kJQlL0YUUDwN/0DxJiLtcviTJScFQ1yLLfSHX0=,tag:d0sL5Qvr+HdyzB4aMDcIaw==,type:str]
          metadata:
            name: ENC[AES256_GCM,data:qkWlQopjh08yu71uju2lD4A=,iv:5fvqyOHjiWLQ6HJ5c36AcOZIhBH9tbY9Bj8zXYjNcy4=,tag:aKOfpFXiYvCiMoUWhZPxBQ==,type:str]
          type: ENC[AES256_GCM,data:4KzpqHiy,iv:SWfmYN/sTlSwDR6aFcbc/JzIn2hzA4aiGzX+vHwtz0w=,tag:DVd8GC2AVuGkuXOzsEPk6A==,type:str]
          stringData:
            masterkey: ENC[AES256_GCM,data:yPUnPOwaLVRv7q3wqlfA31BGK6jG3vSOJnYDpqQBgXJMyHGnYZJNoQ/uu4c/9Xd07TBn,iv:j+Ijfy7nbiQINKVex1EuBxXcj8pfhrRZSszm5OA06X0=,tag:Imga4YH8zKiPedAzfXU/ig==,type:str]
        - apiVersion: ENC[AES256_GCM,data:i3A=,iv:sxO19gcf3GSEfrasXVTuOTwx+puZFy13GIXsSuFyRA4=,tag:WmffTb0MXxr0rA3ki6qQOQ==,type:str]
          kind: ENC[AES256_GCM,data:/9NnbipD,iv:ixhryJ2ZnNZT2cdM8FqAEB05nMVElSONyF+9o5c8FAE=,tag:TrGQmHlfDPt+sVOA9ZrbeA==,type:str]
          metadata:
            name: ENC[AES256_GCM,data:1r7Iurd4gPUVkTY=,iv:MNrazfR2uQ0/qXdyr95y3s9ne5k+T+o5iAnbLXJ3Ys4=,tag:YyobzGQCdMpevIOEe9uD6g==,type:str]
          type: ENC[AES256_GCM,data:4mV6QXC9,iv:dwjz06bpp9c4acn67ERCSk+seCsDsfbWzKOUxChHtGo=,tag:YP9fSGpCECbpwM5QFL/Trw==,type:str]
          stringData:
            LITELLM_SALT_KEY: ENC[AES256_GCM,data:bHexRp6IqjzgEUwtM+8sVY0vgHpK1E9TiwKYD5gaMZeBobZ768BHr9Cu/8PrMgQwUFBi,iv:62KuWTU6R6pL5q3gsQ4vAnp9e0MUM+DbKDgkCjpIMUY=,tag:EQ+yr10q16hQtIzO5PIGwQ==,type:str]
            GENERIC_CLIENT_ID: ENC[AES256_GCM,data:Txee2ab56pPjeikBFW4x3rwm24fBIh0lp1WEUqriIE0Es8++,iv:c7qZZmxSjJOjRTTk+hdpl3IbY0vrTQQkdn/tJBHHHsk=,tag:wUOYK8WsdbvTmUD4643FbA==,type:str]
            GENERIC_CLIENT_SECRET: ENC[AES256_GCM,data:LWAeaXAagXKkkxMhgAc2zXBwIEnosN5Garm+R7/ZyY8=,iv:jUVEB5VZQ/9Fwfj4sutVxT+ij3nplKUe/E6dFXPuXdw=,tag:Z6qPuY80N99WhgIjnXQp7Q==,type:str]
            GENERIC_AUTHORIZATION_ENDPOINT: ENC[AES256_GCM,data:IStZJ767bcv+YrykroWvutT6JC5UT8n19PJtAK7QMtDyfu3U,iv:PQHnogeQHREsrtYBapDnqDtqyuZVUg902zEZDHHns8I=,tag:hOsWpS9P6EIUW/Ducj80pg==,type:str]
            GENERIC_TOKEN_ENDPOINT: ENC[AES256_GCM,data:1ssHxuJy8X5oihStJ4igBhRmxuOKjdmQ9i4dkmx2wW8xedZopFKxgLk=,iv:pi/7vaXroeLK+YW8zEI/zeNND5doipSBVy113e6+PaY=,tag:xKIZuY2rbUeU041zZAEhPg==,type:str]
            GENERIC_USERINFO_ENDPOINT: ENC[AES256_GCM,data:memNa43MQivx/ZMs+GtXKXeRgA3wwcT65jrAG+/SfTmcAXk9BqS5v4CQ7tY=,iv:+4IdfpidgPX8+M9FsCl6+JsJQP2qwX45spd9mZ8zy3A=,tag:cqt7lL7D41qviXtrA4lVrg==,type:str]
            GENERIC_USER_FIRST_NAME_ATTRIBUTE: ENC[AES256_GCM,data:pA0oA/CQIeaQfw==,iv:40OOV7Pev3j2XKeF2fT/NOHOU66Er5FtuPcjvOU/yKI=,tag:xLplVN9ZXpO9hU9UqwTxvA==,type:str]
            GENERIC_USER_LAST_NAME_ATTRIBUTE: ENC[AES256_GCM,data:ENB8OyeGoh0ollw=,iv:jcs6WDrUJM9YuUqQpIxjvcwtRCbg25PHgF4MXVfjmqU=,tag:GPy45fPTEe4QE0k2A4QtPQ==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaSnZ2QW81MmppZlpGMCth
            RTg4N0Jqdmc1UE53Mk1kREk3WWkrWnYrSzAwCjNuNjFYdmc5RThOdm85Vkc4YWM4
            aTBZdHA5ZnhMK1VheGFMaWY5YnRJSDgKLS0tIFp0b1J1dDFVdFE3YWlhN1dvNyt1
            bmszeXFTYTlTUFU2MHVVdnZJTU5abUkKFqSFoefyrmDH0PEb/XUu01x5l1nkVCIx
            LO3vQaTFb1CodDh4PEM5sieVccKsbD/utG3S9z2uSvrMARpahSlvIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-14T19:42:43Z"
    mac: ENC[AES256_GCM,data:Z+9Z1aRpwZ1uq2M6Tqvvaao6tqgMokQiHkFkvIRsb13J44jLpvIo7XOvL7g8bzAz+a4VV71CdlMMIYdyM8be3d0wOdmYQwI2ey+nWkgZssWFIf2IH/i3ewUXeMygOKb76LLqNTInNEHbJPW2xPr8d/fya4RnwltcN1JJmrfDAV0=,iv:OTIl2qDzb76BwbasY2CCOaJdNt+s/lfnM/cGOLegUGw=,tag:gu564sDlP6T7V9rEGHBLbA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
