---
apiVersion: clickhouse.com/v1alpha1
kind: ClickHouseCluster
metadata:
  name: clickhouse
spec:
  replicas: 1
  containerTemplate:
    image:
      repository: clickhouse/clickhouse-server
      tag: "26.3"
  dataVolumeClaimSpec:
    resources:
      requests:
        storage: 20Gi
  keeperClusterRef:
    name: keeper
  settings:
    extraUsersConfig:
      admin/password_sha256_hex: {{ .Values.clickhouse.admin.password }}
      admin/profile: "default"
      admin/networks/ip: "::/0"
      admin/access_management: 1
      default/remove: 1
    # extraConfig:
    #   metric_log:
    #     database: system
    #     table: metric_log
    #     flush_interval_milliseconds: 7500
    #     collect_interval_milliseconds: 1000
    #   asynchronous_metric_log:
    #     database: system
    #     table: asynchronous_metric_log
    #     flush_interval_milliseconds: 7000
