---
apiVersion: clickhouse.com/v1alpha1
kind: KeeperCluster
metadata:
  name: keeper
spec:
  replicas: 1
  podTemplate:
    nodeSelector:
      kubernetes.io/hostname: monarch
  dataVolumeClaimSpec:
    resources:
      requests:
        storage: 1Gi
