---
apiVersion: v2
name: paperless-ngx
version: 0.0.1
annotations:
  homelab/description: "Document management system"
  homelab/url: "https://docs.paperless-ngx.com/"
dependencies:
  - name: app-template
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 5.0.1
