---
app-template:
  defaultPodOptions:
    enableServiceLinks: true

  controllers:
    paperless:
      containers:
        paperless:
          nameOverride: paperless-ngx
          image:
            repository: ghcr.io/paperless-ngx/paperless-ngx
            tag: 3.0.2
    redis:
      containers:
        redis:
          nameOverride: redis
          image:
            repository: redis
            tag: 7.4.9
    postgres:
      containers:
        postgres:
          nameOverride: postgres
          image:
            repository: postgres
            tag: "16.14"
    tika:
      containers:
        tika:
          nameOverride: tika
          image:
            repository: docker.io/apache/tika
            tag: 3.3.1.0
    gotenberg:
      containers:
        gotenberg:
          nameOverride: gotenberg
          image:
            repository: docker.io/gotenberg/gotenberg
            tag: 8.34.0
          args:
            - "gotenberg"
            - "--chromium-disable-javascript=true"
            # - "--chromium-allow-list=file:///tmp/.*"

  service:
    paperless:
      controller: paperless
      ports:
        http:
          port: 8000
    redis:
      controller: redis
      ports:
        http:
          port: 6379
    postgres:
      controller: postgres
      ports:
        http:
          port: 5432
    tika:
      controller: tika
      ports:
        http:
          port: 9998
    gotenberg:
      controller: gotenberg
      ports:
        http:
          port: 3000

  persistence:
    pg-data:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 4Gi
      advancedMounts:
        postgres:
          postgres:
            - path: /var/lib/postgresql/data
    media:
      enabled: true
      type: nfs
      server: 192.168.1.200
      path: /volume1/paperless/
      advancedMounts:
        paperless:
          paperless:
            - path: /usr/src/paperless/media
            - path: /usr/src/paperless/data
    consume:
      enabled: true
      type: nfs
      server: 192.168.1.200
      path: /volume1/scanned/
      advancedMounts:
        paperless:
          paperless:
            - path: /usr/src/paperless/consume
    export:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 4Gi
      advancedMounts:
        paperless:
          paperless:
            - path: /usr/src/paperless/export

    scripts:
      enabled: true
      type: configMap
      name: paperless-ngx
      defaultMode: 0555
      advancedMounts:
        paperless:
          paperless:
            - path: /scripts/pre-consume.sh
              subPath: pre-consume.sh
              readOnly: false
    txts:
      enabled: true
      type: configMap
      name: paperless-ngx
      advancedMounts:
        paperless:
          paperless:
            - path: /scripts/pwds.txt
              subPath: pwds.txt
              readOnly: true
