app-template:
    controllers:
        main:
            containers:
                main:
                    env:
                        DB_URL: ENC[AES256_GCM,data:8BmEK2z1JZ4LcsqlQU4Vv3YaAqvWFNknk1ZNzrz4TuGPplk9hFlnmScDhnmGchgOnC9p5XxDbSPZb6belYW42k4rNBI9YAengfTlzOrb2VY=,iv:vLnIuFkuJDwVZgoaBHofby5MACocX+bcPRjFdxdzooI=,tag:MlSjUFLxoM5sCbwq0lEu/w==,type:str]
                        INSTALL_BASE_URL: ENC[AES256_GCM,data:mQHuNflIje4Lm0L2dcXWE/aUCOXDSilwBo8=,iv:QCsLBlIfm9zzm8u9IVdP00UaX2biqH48q+uzL7fJ9bs=,tag:R/2zji4dZ8ZzQYIiHrcRaw==,type:str]
                        NODE_ENV: ENC[AES256_GCM,data:cjvwVQ+/aD/t2g==,iv:hO/Bi8Wyq9wPvcl+3Ps5EQDv+HDaCG/HEFbQPhVpoJA=,tag:v7W4sq+LrVch81NDcL2zFw==,type:str]
                        JWT_SECRET: ENC[AES256_GCM,data:zw9nUj+1TA92nZXnPDhGfOP8UEkdvV3H1cNJ8LjHUXGySBlsMMywso6s6bKVg0ZAQRD7nukq4HF4a+5nJdSe9w==,iv:rIcDyGu/4PZbB8wMFMq+Q6LHVF5JYt3q3xMjx+LM+IU=,tag:swFXzcN2mdAGnQmYISTFtg==,type:str]
                        ADMIN_PASSWORD: ENC[AES256_GCM,data:620obX4/thp05x82FnismQ==,iv:ak8FQOERyCxRUL8m0k+cKBRuGTaYGHVBo4C5xIAEph4=,tag:YA0z4GOtRiM0Mrrarf/t3g==,type:str]
                        BETTER_AUTH_ENABLED: ENC[AES256_GCM,data:5akBCg==,iv:VMumPCFQoqT+Oyx7jeIjGGMA4nqsxa0fRBtQBdmgKjI=,tag:TMvfjuXuJSWeMusRWKHsOw==,type:bool]
                        BETTER_AUTH_SECRET: ENC[AES256_GCM,data:bEOexc+EiXLW7BMGn67pPV4TgOEUC93DCz7FBwe38N1/JBzo2TU2cDHuMPM=,iv:BfKUFIWniFhO9QPexqnah/0ytTb8v+AROp4P+7VSYgI=,tag:upwGLg3MT7KA3w1eQe7PkA==,type:str]
                        BETTER_AUTH_URL: ENC[AES256_GCM,data:shSEaLfert1+gAJO3nqswfXaZ6Syvp6CFnE=,iv:hRnoOnaWKS8hlPIGKWadqyp36ZHT1Qv9aXru29Ohjuk=,tag:lfsI9uoHfcMt5zzXhjJ5YA==,type:str]
                        #ENC[AES256_GCM,data:mg2ak+NZLewdBaRpd6NH6EGOk2dSDO5n527NNa+8EstaOehKHvqvD6Iia4fsBPp2BQiM7w==,iv:UWhnujHCT0jeT4ByG+WVyOoXOtDdkrM6C61TspkFJDk=,tag:WcfsSLKmhbkdOhhEWGv+wQ==,type:comment]
                        BETTER_AUTH_OIDC_ENABLED: ENC[AES256_GCM,data:H5QJbQ==,iv:S0c6tA6be1bbxdTOHBonGS98FffE0z/vc6OVL7HKq9s=,tag:4Ide00i3kIbcZX7+oraaaw==,type:bool]
                        BETTER_AUTH_OIDC_PROVIDER_ID: ENC[AES256_GCM,data:+JqrP1CUtnw=,iv:cBEC4tYasYO4zVJovcTNQOZIqDO186sqSMatcRat2oI=,tag:lldzi/PQTnOO7GDTQHzZRw==,type:str]
                        BETTER_AUTH_OIDC_DISCOVERY_URL: ENC[AES256_GCM,data:WeSXiYsFFMt1Rp4NqNNAWZ1XeTWxfLq94LYlc3SompjpUJm5QrejX02qP6pvgjI7JpdW2hnt2F1ccNw=,iv:qosFFLjFjQo2w3oSC8BcqRm+nGviJPDVkyhjzrKUtgg=,tag:jLOvT3EuPOXeJnyFoLjLqQ==,type:str]
                        OIDC_CLIENT_ID: ENC[AES256_GCM,data:QUKoyn1wrcgC0masNpH7J6RPH9jM3SoruC3o0Rqd9ExG6+ND,iv:Gudn9Mfe6qmntIc/n8pwqKcsTeUIhzEs74CCxH0hlZk=,tag:1gbCJH/y0Z2xefUCcZUZ/g==,type:str]
                        OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:6+ylqOtRBmPzVTvbVGv7+9//hVBNShqtlqeIprsAJMs=,iv:bWgB38lb4DGAzq/Zs20K+fEmF0s0ek7Sj20Q8lQn/xs=,tag:hbsZbeWPr8v3pjM+UZVzeg==,type:str]
                        BETTER_AUTH_GOOGLE_ENABLED: ENC[AES256_GCM,data:5nD5HEk=,iv:1/IG1HnbW6/zc8rT8nbhLEeQOx9kxkPEiZW1xKaMj0w=,tag:0tC5iRvPp2S4+YObHuvbig==,type:bool]
                        BETTER_AUTH_GITHUB_ENABLED: ENC[AES256_GCM,data:3iGPoxU=,iv:vgCjZv9HVNas1kn/H4YGdD4HBL9l5PkuNrolcj6uKAo=,tag:UuK0jpA6Ga1rAiML0wLlNg==,type:bool]
        postgres:
            containers:
                postgres:
                    env:
                        POSTGRES_PASSWORD: ENC[AES256_GCM,data:RmXDcPu7sb7F55wVkvdOiTv1fcL6Jy1KiExhlvnSq54=,iv:vouBPGlweT32pdHq9wVdxzeXm5afK3o6a6oAbA4y5zs=,tag:RRTctzz8GrphrVKlLC4PEw==,type:str]
                        POSTGRES_USER: ENC[AES256_GCM,data:frmw+1yl,iv:H/OC6J0rnKD3jpHQT0Vh0c8qdK7aWWmbxaSznD/6rEE=,tag:X9xlPez8rByKudydsITPgQ==,type:str]
                        PGDATA: ENC[AES256_GCM,data:VpdyqSPxjIzWNua4FxRv3kpPAyngcdt4k4c1MepsseM=,iv:WSft/QBuQYuCTiS4TXP54XfYaI2hhdDFvPIweBpJlss=,tag:mNZ9NZCEjMvYcivVxn7okg==,type:str]
                        POSTGRES_DB: ENC[AES256_GCM,data:QOvMt3CI,iv:TWDNStKFnCE5j1buHxJbl2XZrTyhCgtw3ZKonQbsGwI=,tag:pcvWcXl5WHzJonVOyDeqsA==,type:str]
    ingress:
        mcphub:
            enabled: ENC[AES256_GCM,data:9ZOK9A==,iv:Tk6ZL63SamF5RYW7nDogYTJGEz7Y+rQWqSbsNKO7jOg=,tag:e2Usou6s1B8rUfQT7g3Pyw==,type:bool]
            annotations:
                cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:+OhZjP9S9Z6nTMNr3UdZwg==,iv:GU3TBHO27BQA3MCG2gKE1wYBuPlQoXei+sprAsbZN8U=,tag:PFUIWqegE8fI18X453Q98g==,type:str]
                gethomepage.dev/name: ENC[AES256_GCM,data:nMXBfE0LRQ==,iv:uNvITt+4FeFeX8rOYnFGFccuvzjwDd3WKsyreQDHaIM=,tag:Uv7/VxSxpz7J85CXc08nEQ==,type:str]
                gethomepage.dev/description: ENC[AES256_GCM,data:x5ShBVOcX5FVmxY=,iv:i3pcMceubG/TkNODlw2TecVIWGYN/8mGOf64yus4/O8=,tag:OOp21cVal4UMqcUNB2gtTg==,type:str]
                gethomepage.dev/enabled: ENC[AES256_GCM,data:k9VpTA==,iv:FSrno3hZg8EgntRDhbLxrWQNvGQ5WcNz7HX1Rnp81X4=,tag:0+AYoZhnVSwNKbSq6D0mhw==,type:str]
                gethomepage.dev/group: ENC[AES256_GCM,data:UgM=,iv:KwayAI5J/W24AKdC8UDtTj+25dwH6cuCUqOiUhjcEW0=,tag:e5PlhcxaBU6SgzUjwHKeWg==,type:str]
                gethomepage.dev/icon: ENC[AES256_GCM,data:gJzWdVXSjaSaBFxm7A==,iv:XEuhDHCxxW9cfUVRSir7/llDCbQVCPsovP2gRdj8UUU=,tag:PXRP5WTVQNBI66wdBu3Opw==,type:str]
                gethomepage.dev/pod-selector: ""
            hosts:
                - host: ENC[AES256_GCM,data:Zi6kV1INYZAcJBfxC9mPNjDR,iv:pPY5+iQnfn6sNR64lWG8KUaftTdcHqNdd8cbEBJKpH4=,tag:vERV4mRG2Z8s5hCNLksRPA==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:nA==,iv:MO109cV9LyjP8D6PEzvTCcRSvZhgIpRTKDnQoSn1P70=,tag:k1kJ4Ck8w7iMwPUXrUzlTw==,type:str]
                      pathType: ENC[AES256_GCM,data:/c8xdXK8,iv:dz+qSxZE8XPjxl+4qpOv1veBIA3w1jGeKyy7RLgfh/0=,tag:Kbt3QEa+NUwyEBMrW6Cfqw==,type:str]
                      service:
                        identifier: ENC[AES256_GCM,data:MI5usA==,iv:USpYPWWMV8HjioHPNMnZ6VEaAhGEjTqamO3J3MMHxBM=,tag:ZbY9i+VopXx21XRBU/fvOw==,type:str]
                        port: ENC[AES256_GCM,data:Rk4WUQ==,iv:dNhHN5C3SdFfeEvL4ztwqaZd3tDFxOjJlg5NqYBcuwI=,tag:oTMoxzK7ReIte1uam2PNbw==,type:str]
            tls:
                - secretName: ENC[AES256_GCM,data:q1EaWXNtg6K9CarXpPAN,iv:ejB2ieLQVr9Kr4ion531HKV/0LgK5T8sFNVMN3Ulwu8=,tag:5jQAdb9sVoMcX+n+sCb2/Q==,type:str]
                  hosts:
                    - ENC[AES256_GCM,data:Eey9zp7+05kAAFPX8GVlP2Gd,iv:fzpZM0+3htPpUqrEkIAEg/gIGpRwC37E77jhTd1rK0Y=,tag:QBV4Aelwmv9FqdDeB8sIHg==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1N1hweWxNSUtNdFRUbW5Z
            ZDU3R1pWWHhwQTBsTTVXZWFWNFJQSWN2dkc0CjlvVW4xdUNlc1p4UEZNaWN5QjNj
            WjBqMm8zb00xS2htdFdBWXd2TWpUYlUKLS0tIFZEcEduRTVQUlNtUEhyQnJWbVl6
            SHlqTUQwM21xcTY0VkRvWEQwa3I5OVUKoqCYbBnCKtw4i9MJAOvG/fR9Q0b7zm+M
            DQrlOZ37hsqXJM577WA/iI6K6eA9zdQKIFbWIMidg4wVe3C7DIRh2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-30T21:38:23Z"
    mac: ENC[AES256_GCM,data:SCZuuTJ6dv7VvVGJDXvF12bnhNMFEpCIgGtQdNKmyBSX1F2nvGkb9JJqv57e9IeBGDEsB0YQcRtvmkzK+WTxppEJ/MKC/quzKAbSouXnMLE9lCbtcsHIzyo/wI1GQdJcfN/FkOowdQFEoQq0RsAxQpZVxm8ZjqvlVh+axiuP6NM=,iv:5flUgfHQ089UvtJjDVTCepOiHgZ8wkoehzVtNuysISU=,tag:df4v76kcLU/GLpZQODJaFQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
