app-template:
    controllers:
        main:
            containers:
                main:
                    env:
                        USE_DB: ENC[AES256_GCM,data:XKvAqQ==,iv:QliQBC+ziSpCud6J+dJ10vX7LKQ0HbA/QpjHX3ZMNIs=,tag:aluv/b348GmbET072ldBDQ==,type:str]
                        DB_URL: ENC[AES256_GCM,data:lLIdFMARr6hdhkZPCrznis9K5XY0hY7jAzDc8moOVPUqKWMtYeZ9bEpem0BrFK/m1/MjDwUMUgrhx9DZXv+fr/l4e7gu1zBHzSKiafd0ie0=,iv:47Lg8uEtSGJS6yuFEe+PPEg1VozvQNruQqK7PjNRztg=,tag:/qIR46nPgdzbwF5BehhvHA==,type:str]
                        INSTALL_BASE_URL: ENC[AES256_GCM,data:VTkvzqLMmxIUQDR159ia08Svu2CR2nPQqBg=,iv:lylPY/f224WhkoCOgRb6l5RupvcbHyfI+RbZ+Ys1MNY=,tag:KbLJoJQNLK3JpLJ4PbiZNA==,type:str]
                        NODE_ENV: ENC[AES256_GCM,data:C9qKqnUyz2wLUQ==,iv:yfWxAqyjt0j2MkvHz9vwSY2/5FJN8yK0MQWKAo4+d2w=,tag:z9hEc+zLZqJM8fRw/83lrQ==,type:str]
                        JWT_SECRET: ENC[AES256_GCM,data:ZVaU0K9rfnV6HNJFzuz6DItTUyOitUt5L++bdx3su2j3nLZQJtpQ5890jDGyJ+Gh7wj9KrvB/AN9kBBdwXFgyg==,iv:f2tr+MtlMYCXoFneYBcfU81X6rph33PP8QAAmT/3gBk=,tag:B8IDGtZz3NhC6zVpLZ/QgA==,type:str]
                        BETTER_AUTH_ENABLED: ENC[AES256_GCM,data:UgM74w==,iv:kF1s9AOPvaj/LL4fJRxZPITT/3IhuoNU07PYAiSQvMA=,tag:Bl1n1qLUuKYqYW6kPeL2Zw==,type:str]
                        BETTER_AUTH_URL: ENC[AES256_GCM,data:qyoiSKmgSPgJF15skGx8H2J3TZ74K2Aya48=,iv:9YUqgRqGdW+xJeRKJrtdzUwbMQBv1XQLft+rTMEtAt0=,tag:RXLo0Ci7zK0HG3JHY3jKxQ==,type:str]
                        BETTER_AUTH_OIDC_ENABLED: ENC[AES256_GCM,data:zqO0Hw==,iv:n0TDtoZl2lwEO0hN3b5pzbgwCxoRzSI4y/lDL7hWCJo=,tag:ZV2S82Lc/1pjUWwJcuEWbA==,type:str]
                        BETTER_AUTH_OIDC_PROVIDER_ID: ENC[AES256_GCM,data:ydQmLtldxdM=,iv:pYgC4o4hFV6qMmojymLsj7XuNkkaHPOHGhKHsZOd9Uw=,tag:mpXZQHNkF9aKtjtRs6WHUg==,type:str]
                        BETTER_AUTH_OIDC_DISCOVERY_URL: ENC[AES256_GCM,data:nx7HhvSEcUo5lizgmsGtkURtZlYlmAsVtNM4pQNcl7psn9J9mh3iCXKQ+A/jw0iSQ+uQ1kO4pYsMdWM=,iv:bIOTrGkN6kP6R4V5gU4EddDgZ66GIFXK8Nh4C4PV0hE=,tag:6dwaWkGgpKrPdKlkxgAG4A==,type:str]
                        OIDC_CLIENT_ID: ENC[AES256_GCM,data:MAm2zORgSuhEOQ6xEv29ZZVAfme3ArSxQOjpzCp/rjn8bEjW,iv:LJVx1fpkHT49qimaaOs8PCVCAWmgD5PevZTVGKouUuY=,tag:lgvn0OwoETa/Djd80MAiFA==,type:str]
                        OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:RCJ61Oa/O/XyiKZnu16o/WpqVHfQlM5Hz9FFxaHKmoM=,iv:T8a7zNxriERhYTrss9GtK1DZ5IM+hPDnae31OmWS4GA=,tag:ZkhM9CWFo+voPR+2soL1AQ==,type:str]
        postgres:
            containers:
                postgres:
                    env:
                        POSTGRES_PASSWORD: ENC[AES256_GCM,data:hUKmY44qib887ZplWE2vikXbZvACy2b15Mls/9HJSMk=,iv:1l3NVYu4FcWgac2nUIKPC0gSITcfYSoArJPxT0KrLZw=,tag:QAKoKfdDY5tk4w+zVBCjkA==,type:str]
                        POSTGRES_USER: ENC[AES256_GCM,data:Qy4Ur1Pa,iv:a4xYRB1bOITzufklb6p9DCB6uSZF+rGQmtxONXpAJAU=,tag:SEgWApZ6vjGiQA5t4sR+hg==,type:str]
                        PGDATA: ENC[AES256_GCM,data:9TFXT51rB3P30e0Bq93g6tk3L/PEEYrlK47OWyI1NrU=,iv:pO7dF6vdJyjPu8LIV2fdWjHqA9Ekmh47ogB3qY1w0xQ=,tag:rDtLk0MnngvbjqhZZqmP3g==,type:str]
                        POSTGRES_DB: ENC[AES256_GCM,data:NF7zEFrS,iv:IYvIvUY880/E7ouGZwxzSMYlum2+fyiX+rD6AZ3o4Xs=,tag:fNBMax4c24MxFaePb4xLNg==,type:str]
    ingress:
        mcphub:
            enabled: ENC[AES256_GCM,data:Pgbi+Q==,iv:9M9Gh5M47XagXv1wZ8hPafSGuQZnUsvqyjqEe884Ze0=,tag:ygpexIAIuCKMYMW8LBA67Q==,type:bool]
            annotations:
                cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:WujT3yCw9y6Sp8x+fIGJvA==,iv:NCMrtedt4GNU2XCLOSWFYxhUQKP6+AA8cKA+GzesV90=,tag:t6OTEOmSuxtHpV9ja7yC2A==,type:str]
                gethomepage.dev/name: ENC[AES256_GCM,data:Igg5UA160A==,iv:z5/7uILPUB9UtTO5EwU/FgdlYiUi8PnURtNjChs4YG0=,tag:BIjG9CNpoEiUCmup3m0Dpg==,type:str]
                gethomepage.dev/description: ENC[AES256_GCM,data:h8QhtqYNw84XzmU=,iv:bv2zEOEbqLrkRnHnDAD6gXi9mLrCDFn1w0muE+CE05U=,tag:jaSGWs9ueU7jqVYaOfSTQg==,type:str]
                gethomepage.dev/enabled: ENC[AES256_GCM,data:o7DCBg==,iv:OZZajyJmIcqNkvLRsWJ8NCp3Cp5Hq1wi/YvHjC3IXas=,tag:i1GBNAZNCWKZrJ6SKg3oqA==,type:str]
                gethomepage.dev/group: ENC[AES256_GCM,data:ccA=,iv:s6Vt9l8zXMWdX57T8tixAGn8B2gjvK9zRp40+Doe4k8=,tag:2EoEmsqjBmXgoPEbZHETHg==,type:str]
                gethomepage.dev/icon: ENC[AES256_GCM,data:7FdeNNVd0Ffd/Rld6w==,iv:GMMcbvQMrqgEbsHK4lP9MSeEpIbD9r97ocyDpiAmJfw=,tag:WKHxdtFQ9mb3oRCfNEhaOg==,type:str]
                gethomepage.dev/pod-selector: ""
            hosts:
                - host: ENC[AES256_GCM,data:f9O6g1tJuXTyrsVdwiZlIPdE,iv:0B0T4B1lNgDfYYuaJPnZaS1Yb/j6sf6bfaycV3BANHY=,tag:gokZoj8PY9glraHcXg4+qg==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:oA==,iv:wkZTG0g3dfGRqTY7SreYQUN0YhkfhZiXOBNZe5xZrgs=,tag:huUaUcGWtse8DzIIer3Rig==,type:str]
                      pathType: ENC[AES256_GCM,data:MgtLk2lF,iv:Ewp7zA8QNyRmOpOtvPCrGBA718vVrHp++y0MihpEOZI=,tag:FIFilwFDqsQbzRxA347zKQ==,type:str]
                      service:
                        identifier: ENC[AES256_GCM,data:rmIQ8Q==,iv:HLZntVoS7PXuRpJc1QcR7VHemriJ79S/5quLGIittrM=,tag:M+QAfyeQKpfTkq/x5+RmyQ==,type:str]
                        port: ENC[AES256_GCM,data:+7jiDw==,iv:Z29BLnhwQ18N7rZL6/IqCoXYifqUP5+sm8QYp+Q7Z8M=,tag:2q1/ujUxHWSMRlDh/5n/dg==,type:str]
            tls:
                - secretName: ENC[AES256_GCM,data:D5+77RARrttHae3L6PeZ,iv:/ZA+CEh+IUelx4khYnA/fslG/afLKckqk4pFAqunHEo=,tag:3GqrDyuxrBUzTcemfVWXoA==,type:str]
                  hosts:
                    - ENC[AES256_GCM,data:BivxMtyTNMXgZVArHQ8I2E/6,iv:l3q8cys3xKSTQydo5bUJtTbGDMMkhptSCWrZh4wEvqw=,tag:0d1Mzms4gzrsH+l21XBNEg==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVE1UM0hJVHZlaHJJbjZX
            czNvQWl1SWpmRy9Ub3N4YTR0SUxrS051TlJJCmtPc2JLdlprSHVXcmo3ck41Qi95
            OHYzWUhjRHZySUdqQmlMbXBCU3JGUlkKLS0tIEdyeUg3QmQ4SjUyUUVPLzFrWTAx
            SWdrOEkrOVdLTFFLTTUwWU9mb29OTmsKqNlSxw2Q7yGXVajjcbJQcRsRRZ/geZmj
            qNiMf0Wu3yh6+BkUjpoUl+2I7CyM6kN1ZCH9xwjjzrzsXnpncZSdxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-30T21:13:48Z"
    mac: ENC[AES256_GCM,data:h9P6mA1vq1juY9Fu3TatOg3iCFtgucgquK8rpVRz8wgMmi93UEEMgAjI3O6nmlgIG6ScM5cbR0fMm3gCDD8T5h4ou0zWGGIupH9qnqC8WCfiI/3GBr/EFRN0EFci2c9i6PmUrGdEBynC8qrJPxDHAaA2UcWGYkJ9Dvxt+cC5RZU=,iv:1rFj47cul9BTx0xZ51rLB+gPPaQbrMpLtmQQvZIuYV0=,tag:N8rgHUDJR4mA56T/3vtKPw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
