app-template:
    controllers:
        main:
            containers:
                main:
                    env:
                        USE_DB: ENC[AES256_GCM,data:sjQwfA==,iv:hNyOgVqJIBUswlzdDUwKOYurRCfQmvWeyPBm5BCKRJA=,tag:b7ouhIm9tuVtjiaWh3nO8A==,type:str]
                        DB_URL: ENC[AES256_GCM,data:bS/iklc71PgW926mTklzvt7M985WdqsTBt045U0pwzahw5rUm7Unsd8XlUnISefpEKMSkvVr28BGLOYf2K4x6mPfeJSU9l+dGtmNmqs/ycQ=,iv:LZ0UF8rc9NG/AfcDmAR8D25u2bq5a8Skm9dl7muLcaQ=,tag:/UP/WsMpgmoj9wXpC3riLg==,type:str]
                        INSTALL_BASE_URL: ENC[AES256_GCM,data:F8+guZ8y7C3NST1rkbFniwKstsVsn9Z6L8k=,iv:8mwVEAgNiqMEl/YIyEEbpTa50yThWEx+zqPgNB7vQQI=,tag:CPUm2teJMDfp4PfvLlrucw==,type:str]
                        NODE_ENV: ENC[AES256_GCM,data:K1Gevl5DzFNm2A==,iv:QC20xJ1xUWJQXAZl/HM+uWnmG4VaiOa7LORY/+GHWj8=,tag:0Nwri37jnwnYUZ1Crp5caA==,type:str]
                        JWT_SECRET: ENC[AES256_GCM,data:X3xjaZFxRlqEXj/lddQpD6bHzF1b4DKMiVvy0rdW7orAnLIMQURiFgU4xaZAAfheo2Rdjh7tHlLdUwtigpW3vA==,iv:960fp+j54Cr9ShOvgcbmNuVf+5ATy8cAewIufC9P4/Q=,tag:mI3SgEiezMshMZ3KBz+J7w==,type:str]
                        BETTER_AUTH_ENABLED: ENC[AES256_GCM,data:ID/HHQ==,iv:BF37dmBSN76KsE/vsn/9KcpKVT3FSKODgGlmJCEcPqA=,tag:hbEAZldWmhqkiWKhkCjVwg==,type:str]
                        BETTER_AUTH_URL: ENC[AES256_GCM,data:W+IpbPrZFrIilgkk0fAjtlid/Y9vowGjFl8=,iv:XAeIjz5COUtiZyV2bnwvMWePv/5WyvtgSjFFGv2Omjw=,tag:gWOAvy42lK8kLcHKEdBPdg==,type:str]
                        BETTER_AUTH_BASE_PATH: ENC[AES256_GCM,data:oA7ucUKFFDqqYwdvFrFYfQY+/DFMYw8sUqI=,iv:azleYrFnB/lOwbaxuHAw9uDGldtQfd7u1wcfCZ0/RMQ=,tag:BRTW5SaN4YBYlSlD0Z7MCw==,type:str]
                        BETTER_AUTH_OIDC_ENABLED: ENC[AES256_GCM,data:74pNSA==,iv:hGVyoaPNl/ow8BzejW7mRiAWh9AhHV3W6b0nYSc8BXU=,tag:wc1+bl4SVDZBXoETysZclQ==,type:str]
                        BETTER_AUTH_OIDC_PROVIDER_ID: ENC[AES256_GCM,data:TT0PJsx1+fA=,iv:7Hbqfh7lWmEGblbxbne0jfhDd9wpCHzRpfG9UDhPFvY=,tag:yjYxI+ta9zSIpaFksI/VeQ==,type:str]
                        BETTER_AUTH_OIDC_DISCOVERY_URL: ENC[AES256_GCM,data:gbc0V6YRl8TmUP78sGi+ntrTTaQbXFvdRPmkcAJ4+7jAsBQzJy9bvjLjmqUsx/UJaK7EG6mEzIO6F4A=,iv:VS6M6uHoJAKcY0AiuOfObTm0S4fFQRsDYyo7/huJ9SY=,tag:Ua3N1DgRk6h5qALoKePqVQ==,type:str]
                        OIDC_CLIENT_ID: ENC[AES256_GCM,data:kaEAFmCvfAWqE9FrcLZeox0xce9JfT7NHecXqO/XgIvAvXjj,iv:iNBzR2auBcAimz3u11sqQpSe4JcjJUh6ywCHONUH3GY=,tag:OTw0Pz/yMRdturf96oWpxA==,type:str]
                        OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:mczqlzPYfkixcBQvsUckhX4/rx9/Nvz1KvSaHScPGQE=,iv:R9hnK2LoL4/uBO5PkdSbpDzVnnrbI8fJBI628jfx9sQ=,tag:WaQEIHmh/l1UNo9twabK6A==,type:str]
                        BETTER_AUTH_GOOGLE_ENABLED: ENC[AES256_GCM,data:3sfdVXc=,iv:IG3z7X8gcLtSoW76679Kgh2KMGVJiVVUClX29OcK18A=,tag:YkgOakktZeLKF8UJ50ytbw==,type:str]
                        BETTER_AUTH_GITHUB_ENABLED: ENC[AES256_GCM,data:QURZaUw=,iv:vqYEO2C6x7K7Nw91UiBU6qWA1+g7SMAfrEYhFKw4u4U=,tag:0AHnpH/8wt2BjadEMeVugQ==,type:str]
        postgres:
            containers:
                postgres:
                    env:
                        POSTGRES_PASSWORD: ENC[AES256_GCM,data:AKRAyyELpTUZGp0zahS83Ipwbjysk+dX9z5DgHrMR+c=,iv:7pYump1qFhPYuofMZe661QL8by6DMtCywjmZzX+Tkms=,tag:aw5FU4KAduaWG7dFnQY4tQ==,type:str]
                        POSTGRES_USER: ENC[AES256_GCM,data:aGPYIuPe,iv:Yb9sICqJtP6Mz64wbynHsR+KOTTuqRVVNyB7oOgPBvg=,tag:J9hbFacK46k86xyCL2sOqA==,type:str]
                        PGDATA: ENC[AES256_GCM,data:stUtlv375Elttk9Ciua66R8eCytuTExkXUoaedPlhBU=,iv:8HK7Xv4ZTUHvfMBZzRKMdOGQ8m/WfAutyumxC4Gkezc=,tag:qNhYN1JrOwPRA4R2dASAHA==,type:str]
                        POSTGRES_DB: ENC[AES256_GCM,data:9+KbAvMx,iv:3Zatol0XYLSPj2jzfE5D4cMFqQmVnUMcTmjMIlYTMio=,tag:xP/Ab9OHDX/TcJO8TnN83g==,type:str]
    ingress:
        mcphub:
            enabled: ENC[AES256_GCM,data:h0NBZw==,iv:wEY8k1EeyWu33I2im44R0CSAxPzIIoL8eCbQRcYY1QE=,tag:dMdbrV++7rFxAUk2t3FP/w==,type:bool]
            annotations:
                cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:uZKmPxDvWXXzZAH1oRIbTA==,iv:rzMyNrqMuTxkitHx6KgH3wDdjVQCCoGspa6a8PIBxLg=,tag:3VxLqUUrfb7kF2plCitWdA==,type:str]
                gethomepage.dev/name: ENC[AES256_GCM,data:vX0p8wFAIw==,iv:gPiIV6nj/VAwTPG3qZX5B/VmVgHH0wt0sC/xXJPfzaU=,tag:gAOda/ad0HhHpiIxiLnF3w==,type:str]
                gethomepage.dev/description: ENC[AES256_GCM,data:TdMV/phC44QlEqA=,iv:IiVFyRz4esObnI2fIl2M+dJj8J1+Vujnj2BN7st3lRQ=,tag:KnaCqvLgLVfIgZGhts+Leg==,type:str]
                gethomepage.dev/enabled: ENC[AES256_GCM,data:m4kHLQ==,iv:U+7SOmR0JT+SSL3hEbN7qlHKFjcmMJBNLnAhy4nPPro=,tag:8aEETvTO+T2jzRwiJDEQJw==,type:str]
                gethomepage.dev/group: ENC[AES256_GCM,data:IzA=,iv:PnrHrvSGAKtNACO+WF7v17cawynN4HueT68+UfcS18U=,tag:mqf0JP5isBdHga0sAkax7A==,type:str]
                gethomepage.dev/icon: ENC[AES256_GCM,data:PQWZYxmMt96uX5m62g==,iv:8Jq8+4saMKhVL0Vv1/X4C6RO/4Q86X7zX43sqt21LO0=,tag:U+QPVQK+PICfWyQqEIQ6ng==,type:str]
                gethomepage.dev/pod-selector: ""
            hosts:
                - host: ENC[AES256_GCM,data:Z/HBE60u/+eoyPdTrohKveM6,iv:wMUdlnX/tF7Flu45DhwLqriiDv13J/4GnEsfeN0k3TE=,tag:Tn5yBekf4O/6H9i8YwtolA==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:Zw==,iv:i8Mz9OcjIiqfGgyhBFNoz+7ifbeQdyxQskUht8y4vWw=,tag:NVLDJfqmna3zbIaSSuQD5A==,type:str]
                      pathType: ENC[AES256_GCM,data:r4wVcTfs,iv:00T3DVe0TtfC/5JjSekKRis8dBrLtAP3OzswcWzwj5I=,tag:KMKRMl9X889pC46orCz6fA==,type:str]
                      service:
                        identifier: ENC[AES256_GCM,data:nR46CA==,iv:b65b3gjm3XcNQGkMovl+zgkf3QB+rFJ9qvfqxrG5Uy4=,tag:n1O5nMKkCBWop7h7ucuZ4g==,type:str]
                        port: ENC[AES256_GCM,data:4HTKxw==,iv:E9aCnTndJxr3OZeiym/IOoaVOoi3A7AWtCwuxMdNBGw=,tag:oZs8hq80/J6wrbf8ZYjjHw==,type:str]
            tls:
                - secretName: ENC[AES256_GCM,data:Ef+KzwhhJG1OSVm/iP+Z,iv:dc809uYMC2KGMsdgNHOmA20ANmKm/fA3lWpycY3JB1s=,tag:R1U2sjCOHkNfKxb6OlDWKA==,type:str]
                  hosts:
                    - ENC[AES256_GCM,data:IRFz/Fs3xDut0L+V9A9REc5v,iv:2Foq7gjNuWYinAw43CluN3KIFx/dl1qKTVwl2ovUQYM=,tag:VXPUoprMyFgdErELsjhHNQ==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsaFhOZEtyZ0hSVGt3d2V1
            YmxYNUFTQW9wNGpRQXhHVEdyeWtjTGtTV253ClZpbmNORVhReWZ6YVE0SlRzSUxS
            Mys5NE9EOG5pTXB2N0N2NkxCMklFWTgKLS0tIHVXL2FxcFovbGlISHpDV0J0OC9t
            SlAwaERvOU9wWlR6Um53K0dndXl5WHcK0R31TOXAQdlNLeds7T3PQwDO1rde4BdP
            SKjmL+GRUeQHVTKO2ZV+aqE++5Yih/02/Qk+URaj40GYcuVYPh7ZVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-30T21:29:00Z"
    mac: ENC[AES256_GCM,data:6RC/6WvNnWnMzbrJLp7oqcjJ/TogmoUR9NcIHcJH2vLMGvq/IW+rZycE/ftRgyJGRx9K4II6348+L2Fy3iLkExQYrKlFYCHRGeZonYYD5xvMawIQ/sGPcqP6ppdkGa6Q8qC22381SJEv6khrpiIa7LiM9THAroGx6fU59NVo/Lg=,iv:TvP2dVlEMOHmBj7Q+3C7uUfS89Q2WLD5AzkcOaSw0zI=,tag:tlqosIM3lV8F/OXNlGLRRQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
