---
apiVersion: v2
name: pocket-id
version: 1.0.0
annotations:
  homelab/description: "OIDC Identity Provider"
  homelab/url: "https://github.com/pocket-id/pocket-id"
dependencies:
  - name: app-template
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 5.0.1
