app-template:
    controllers:
        pocket-id:
            containers:
                pocket-id:
                    env:
                        APP_URL: ENC[AES256_GCM,data:cRyVKv9QzzW+vJKHlHvhyjFQh4AJmgd+Leg=,iv:W0lRU7QlmWVPUSmXpuygu1aAcTSlBJwxayc5bVtdFh0=,tag:XW0l1w4CjR0qYeM7ErlTnA==,type:str]
                        TRUST_PROXY: ENC[AES256_GCM,data:kptYYQ==,iv:a3LEvMU8qywB2Lw2JrLHtIzuCZ0pca3V+aLPelUE94M=,tag:Z5H/aANKrU2sNoM+SHgLvQ==,type:str]
                        MAXMIND_LICENSE_KEY: ENC[AES256_GCM,data:+u/wfUc9DEoj4H/va4c2SX3DEXfgF9XuGQgzkfNEhp30MPLFkU1q6A==,iv:6qgis+Ik4rjX+m5PPR4i4eiH4Z/Nw+KHd1ytKOpFS60=,tag:Il/oUUVeCqieV9u3hn8MlQ==,type:str]
                        PUID: ENC[AES256_GCM,data:nd5ocg==,iv:ANVvRTIlj+Q2vlTz8cRe7HfpWVxI1uurKtmRSNCp/Mc=,tag:CYd5X9tWQ2E6kzNu918+/w==,type:str]
                        PGID: ENC[AES256_GCM,data:ILmtqA==,iv:fvj1elTctBMuttWr7Aisx7TTsD+6NcY3cc9q0VnQMBo=,tag:hmVN31mQp11QwEAdkiXP8w==,type:str]
                        DB_PROVIDER: ENC[AES256_GCM,data:x/vm1vCj20M=,iv:Od0qOYJFi7BHYf5Zc8lzpmAqtcicuJbvMDFBiFjcMVw=,tag:xUNa2tlnPTYEeOusAVujdw==,type:str]
                        DB_CONNECTION_STRING: ENC[AES256_GCM,data:8KRsCE4aaLNAtXa1FhNss9YeaSiJ68p3R7KRPzRLDW5pb6k39dhguYHXH6+56NXabvnwHCHfJUs+CFBYp1Z7JkuKNL9ZQ58sfqqHMbmqSdIHFhzX4Q==,iv:Uc8FqpTdg1gAYjaTdK6A4uTyLHbNADKpEY2heEPsJcs=,tag:LjtoIf+TeRWxSEGJXCQt7w==,type:str]
                        ENCRYPTION_KEY: ENC[AES256_GCM,data:hcy7vSEQXC9/f7nnMdByWK5P9fF2Wrqervf8j3RbwpNk9SNQ1MEoubzrQVw=,iv:TePAbAo1Zoz/cP3nxS5/M0/IKxio4mDdlitjmYHTiWU=,tag:MAXYiz1cuo+hIxI2rZ3KxA==,type:str]
                        UI_CONFIG_DISABLED: ENC[AES256_GCM,data:i2yhYg==,iv:RJ5e9/cwAl5dKyra8NLbf7CPrPb2EnYU1pMjtco61Zs=,tag:Zxy2FxyiJQYf7FUUS5iBAQ==,type:str]
                        ALLOW_USER_SIGNUPS: ENC[AES256_GCM,data:StN28q6W1oE=,iv:t+8f9lZo70OR4/3nB+Mb9TTnMP7wuJkHFuSd33CiLpk=,tag:/AF7zpySkfMhrah+aLYfRQ==,type:str]
                        SMTP_HOST: ENC[AES256_GCM,data:F8YQPGsfNj7SkLnfkRs=,iv:1rPtlO8RNEb/vZtZTmFRmcC8HDY4Uwml5MRos1l0cfI=,tag:piVN4z9ZHlcamgMr6rs7WQ==,type:str]
                        SMTP_PORT: ENC[AES256_GCM,data:CVbB,iv:nhFsVUANob1lHkuyGQrgQ7IAMAe/IVrW2RCvjAIjL3A=,tag:mRm0ZLUJ62pHzegzcdz3rA==,type:str]
                        SMTP_FROM: ENC[AES256_GCM,data:tPJIWw5eoJF9Wic5WB+tRhE=,iv:DT1nBBtSBVE4v+3R66jW950WgpXx6J6zyEuuQeLk/lk=,tag:0MtBEq0N+Fb29gcpxIwKvg==,type:str]
                        SMTP_USER: ENC[AES256_GCM,data:UWKrlLYU0yYNYUq99LCVaDcg3l5L0BRhQuM=,iv:VemSStLe6kQ+xGVsIq/gVqBp3jGr9qVyWYJAY5kHkts=,tag:OhX51wBteh5gXI0Qj8Umbg==,type:str]
                        SMTP_PASSWORD: ENC[AES256_GCM,data:QLVqSRXWADUW0W/7IE5kjw==,iv:GtAxNPMxC4LuI6/FCo93Bgu/lTRC/mL7BWCOdhQWMYk=,tag:UfXQCTm6rGCvi4HsnFbLrg==,type:str]
                        SMTP_TLS: ENC[AES256_GCM,data:eWDA+7KZo08=,iv:AHOnQ7vrnjaqyEe8Cbfe7ik7yRasiR7wWLEKaDYJHfk=,tag:FGXbT3frDOnZXxpn8dZAHg==,type:str]
                        EMAIL_ONE_TIME_ACCESS_AS_ADMIN_ENABLED: ENC[AES256_GCM,data:798kXQ==,iv:0Q4SSQL8YH/UidG2XnPiyIzy8YJxjKV2SQFLnu7wjzA=,tag:KpUmhJT/fmnbL+uphU64IA==,type:str]
        postgres:
            containers:
                postgres:
                    env:
                        POSTGRES_PASSWORD: ENC[AES256_GCM,data:uvzLv24zjLKoAXXszdHgC6GkP4jR4c7LLYDC/zlW7kc=,iv:+PWsooSlSDXzE/ST8gRQkuEjkG5WHUyBZs7TL+bKAfA=,tag:m1hJZNNsd0S3UNZ4qc8VMQ==,type:str]
                        POSTGRES_USER: ENC[AES256_GCM,data:SRcNBfKQqjc=,iv:g7a2qk57OdQNkZiJpnCYhLlwwuoMhIOntTQNKGs/B7w=,tag:E+x7uYZYjtqec9Lj8pqggQ==,type:str]
                        POSTGRES_DB: ENC[AES256_GCM,data:dMCc6b+UEOk=,iv:2Rza6gFUKUi40d1qYo6XEPsfk8NEbZtTlOg9wkUGrKY=,tag:jiznb0uLupV8PkK+ViNcBg==,type:str]
                        PGDATA: ENC[AES256_GCM,data:bD/2omEdfHXRSNi3fnm1MWHhJQEJd/BshgeyNnLzcko=,iv:thgydUaD/X77tGfmVcic7n+1nAA9ttiZamrOBPMustw=,tag:UA7cuaUTkEnINY32D5Tc6g==,type:str]
    ingress:
        pocket-id:
            enabled: ENC[AES256_GCM,data:SB46jg==,iv:huu9OTyD/BAbMg/FBJn9kKT6qIpLWj4I5TBOwhATIxM=,tag:VEempiEksxaxpgxj/WjLmg==,type:bool]
            annotations:
                cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:Ysw5I/b7xXj6i9nu9jhW/w==,iv:xO2nYDoHKOK9HF1IUW9yX03V1KIGxWK+6OrC7nSXeq4=,tag:9tlvptXgKVfb6SXW42R0NQ==,type:str]
                gethomepage.dev/enabled: ENC[AES256_GCM,data:G4dzFw==,iv:Tq2w0vwfasUc8ojpsDXNWzGjzYUMwmbzeS9hEAvTtQY=,tag:InrKDZxYaSp6osm+vDvmzw==,type:str]
                gethomepage.dev/name: ENC[AES256_GCM,data:rMwg/qbFFeET,iv:5qJpxW5VhVPmB+9F6t8izdBVPW3s981YtfHh1MRRMx4=,tag:TTIL+616n4pLih4Wwb0Pdg==,type:str]
                gethomepage.dev/description: ENC[AES256_GCM,data:vA9zfqNPtKwjVoSU2Q==,iv:PItsuQZkramr15nZEBaNSxqpoo5GeCkxHhlzEiVi9zw=,tag:OHChcLEYAAOVIleQ88fn2w==,type:str]
                gethomepage.dev/group: ENC[AES256_GCM,data:GozltsAA,iv:1spOo55Rn6iJXlvfEzQqPBLL+QH6Yv6aOcBB2/I2smY=,tag:aNojcTOeq1BnWasFC4Cz/A==,type:str]
                gethomepage.dev/icon: ENC[AES256_GCM,data:8UJA7y99zL8WDalG0WqTSQ==,iv:KBla3Z1fvmAVTdl981yiKmMXImqb0X729hLXscOBjUY=,tag:JUQ0B/SN5JgumTa9adPBmg==,type:str]
            hosts:
                - host: ENC[AES256_GCM,data:I5u7FYTJWO1gGDdVzM3cNf0d,iv:m6x/kPzIHsFPyAnA/uZ4dKGpVMSt42SaYYGnxxo82uw=,tag:F+3O4tv/hZ0/WigJsmP0ig==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:QQ==,iv:uGYhyXia9L7TYFXi20BZiaZsHenNAHjx6NBvAGgmsLQ=,tag:3RGUMWMfenv0/8NkpsOx1w==,type:str]
                      pathType: ENC[AES256_GCM,data:8F01kQ6k,iv:syxw3cIbvRhg6hajKvASUwhYvwZWhNpZLE1C5o+RaJI=,tag:5hOi1zZ6K2JZg7XbW1xZ/A==,type:str]
                      service:
                        identifier: ENC[AES256_GCM,data:sQyEqaAxiTrz,iv:hS1QMmxbhyUnluk+Rk1rOpLbNn6skc+l1oPs9vlHXZw=,tag:1jEURWKz2qFIqtFOawO21g==,type:str]
                        port: ENC[AES256_GCM,data:lJGmXw==,iv:tKKbyeGuhJCTV2+r/LfgEasz+dh8W8MLiDAzdpvyvac=,tag:LHGMCZ/wsxolFOa6mHgeLA==,type:str]
            tls:
                - secretName: ENC[AES256_GCM,data:V3t3lTcBBoo9I6VzdSNz7vTt,iv:bVNw5EpyYin6NpRyjiy7hL9O+qoYxgQfV6bvZELnqD8=,tag:TQXFUrst0eNuzrOtgGq85g==,type:str]
                  hosts:
                    - ENC[AES256_GCM,data:Y74YTz/I83qeAo6CwVPw8unp,iv:BCDz6i3t3vpg2voyuLwvK95vOu5agwdlX+Yb12QfVQ8=,tag:o/69Ad5eTKQdVvCXREMnTw==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQXhQS3ZEWitlTkZ5aDE1
            SldkT3dhUGZnOE5GY0ZxUThRUWdacUNQYUIwCkFnaW9tT1lqTlZlVXhkUVA0RTBX
            NTFEUmJyTFFvM1E2MmpNa1RRVGxLZnMKLS0tIGo3SXltMTh0N21XbzhIY3BST1RP
            aUpqMlNBVXRUV3k5NzhzNzFKSHJ0cnMK8iFGi8GtRLQN9hCEIK6CVYeiPD/zjFsd
            XgIGm3ukm/lFKik4kROVBgSIW+FXxKA28kzropeSFyPsmJyjytEeLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T23:09:27Z"
    mac: ENC[AES256_GCM,data:9u2l0jgDfAS2IkZo19iI73g4m0k45sBnMMbpuShOEQGZsStYed6vEL5d/l6r0UEP3YaAoM7FL1jV0bvCom21agXehCHzh84IpLqEcm3iIwN5mBMW86Y2n279CwT4+N8FQleJLbU/7FNomooHNEI6DIZq+4tcoco0KQEf9B74yeo=,iv:dghjNbDa79zct9WnP0SmvF16dfxLzzSZm0M7WEjrPHs=,tag:U8Zj3U0TaR1IaZ0WXQ6GDg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
