app-template:
    controllers:
        pocket-id:
            containers:
                pocket-id:
                    env:
                        APP_URL: ENC[AES256_GCM,data:KvMzo9uQI2A/abtFjqeKx1TCPAJmGGrDi0I=,iv:Y200by79Vr+BVR8BevAr9Px8C/Jft7hv4cH57j2uLig=,tag:5KyDexusCEmgUmlvlFv2GA==,type:str]
                        TRUST_PROXY: ENC[AES256_GCM,data:WUfdaw==,iv:u7MNodFe7C+Tl1Ezbaq//zKzpksrloJ396D9Cx29m5c=,tag:ldP2tmdS1yCidWo0Slmi2g==,type:str]
                        MAXMIND_LICENSE_KEY: ENC[AES256_GCM,data:Zr0d6K99O6TivpdwVQ7ytShTjlxwcA1LTSg2Rp1zZOM5DoHQad/Zuw==,iv:ljB2C7IjCzi/F5QKtRCgR506x6EDYiw31r11tJTgr4M=,tag:wjsk7r6+MrMHdkeRbgm7LQ==,type:str]
                        PUID: ENC[AES256_GCM,data:bEGaKA==,iv:vXFB1SbBVzBhCGl/CERYp1iM9DU9BDEBKeP+3Pb4pR8=,tag:v4lSJHNofrZZiMOotQTALg==,type:str]
                        PGID: ENC[AES256_GCM,data:khNN8Q==,iv:8jahy0FonWXCg6cJ14UXI2duVrpHG87qYz8OCEx/pVs=,tag:EpOXNQJtmXVooFcUaHi0WQ==,type:str]
                        DB_PROVIDER: ENC[AES256_GCM,data:53qhp/JIL20=,iv:4GZkwpnd4vZndi1YYX6qViapEQ5kCmLH4Rt0kShsOEI=,tag:26D+ZVSN0p24dKAWopwKfQ==,type:str]
                        DB_CONNECTION_STRING: ENC[AES256_GCM,data:6RFtZf/XybYeUnb7Y6yKgn/j5D8dAIT8ZGuCYXs8SVDLHDnSJB0av9MJCS4BgDPQ8CAJO3KQzXQVGioqdSNElcuM3rnmFZOGaIzYcIVn3LZDyt23Jg==,iv:queehy4lMDx2mzbHNTaHwk8/aYaKBInWxr5cLpiZEC8=,tag:Wcxy5NNI99u+efjYuN/QZQ==,type:str]
                        ENCRYPTION_KEY: ENC[AES256_GCM,data:xnP8xMKjv7P+BEjuySe1Fv9wtw4qM9miA3/3oTbQdykxFPegVPxo6ZXzCHA=,iv:2+uv+mhGOUJ+IB79WSDIOKcPgMarp57Ti/25Zd2SNvk=,tag:52NunlbulZE3pnhBwi+9ZQ==,type:str]
                        UI_CONFIG_DISABLED: ENC[AES256_GCM,data:NKFymw==,iv:alSIVAg3wVLh9Lm+M9DeinRtKKfWiVYUB1GGUotzFzg=,tag:IJ8cA/KRsj/Nfwx8kXhfdw==,type:str]
                        ALLOW_USER_SIGNUPS: ENC[AES256_GCM,data:XrsXtMG588o=,iv:27/TKqafAivccBVYOeNSAY+/cFaEgF8xaZJ/8RfHzO4=,tag:5BJTAWR9eU7XCJ8AUARzUg==,type:str]
                        SMTP_HOST: ENC[AES256_GCM,data:yakhu9ObeIoNchBRXU0=,iv:2fzORVtc5HkPyRutcoveXEBQko9LOtp7T7gwPy3EfKA=,tag:Ay6gzvmU+ojb2q06IxULXA==,type:str]
                        SMTP_PORT: ENC[AES256_GCM,data:YCEY,iv:8Ej6J8yMFV9uBzODBykwnymLGo4SCJef5mzIdwTNpFg=,tag:tmeCk+ciqER1oJSBy+9kZw==,type:str]
                        SMTP_FROM: ENC[AES256_GCM,data:2a2GCzBEthLJ5CiIkFVsTTQ=,iv:qdBr3XY9sGK89rMqNAqp55WXtavabRWmcpFDGfDHBHM=,tag:8M82xW9GT5wDw5EFDThHUw==,type:str]
                        SMTP_USER: ENC[AES256_GCM,data:2c219CBhsgDUnbbcSOvy1ItOf6Dv1//s8cg=,iv:l+ZU6UJyIY2H9bandy0nq1lStbM9FuPjjQlJl5dvm4I=,tag:QvMESlfJbWtXXyJI7eq9ng==,type:str]
                        SMTP_PASSWORD: ENC[AES256_GCM,data:ezSszcDxAjf/TVFtxkltBg==,iv:wA/6I+Y7CBWjEoN18TaL5llWC99P4K3EWw8psYW0d00=,tag:l6ADlZWGX7uasPTh6bjJog==,type:str]
                        SMTP_TLS: ENC[AES256_GCM,data:NGiIyH/hmjc=,iv:SLfI/vAU85EhnbXRiEo/IVbOCONHj5crTjIO/Xj8IQg=,tag:SdNp8xXvX/9qdZlI/s2ZKw==,type:str]
                        EMAIL_ONE_TIME_ACCESS_AS_ADMIN_ENABLED: ENC[AES256_GCM,data:3ozwoQ==,iv:JpMYYrRldXBWTqfGV7f1esvUXNHzVz8YoaDWfu8T6+M=,tag:Ek2Ch4xG2t/FVaVSExAO9A==,type:str]
        postgres:
            containers:
                postgres:
                    env:
                        POSTGRES_PASSWORD: ENC[AES256_GCM,data:2NlDC90J3akdsqI9Rj5M1D6pA+FQIC+n9S02qB/yhyw=,iv:bapv2tqyPiIovZMP20KvhiBo6gbM4i4jUKAiA3WUxD4=,tag:LS+Kz5lT0ztSBQ523PmgIQ==,type:str]
                        POSTGRES_USER: ENC[AES256_GCM,data:mmhq8sp4PRs=,iv:bZV604MVubGbx6phryD8b395Ec28Vy2SVapqgqwBGsc=,tag:6ZdxRBrXW8reJLjnuGtbOA==,type:str]
                        POSTGRES_DB: ENC[AES256_GCM,data:/bDy4wr2ihQ=,iv:PmzNEUmy0rtk5aYGrT1QGARmuRhnPeobiAzMrnFJuD0=,tag:gROMF8yzS/DbIwv5w2XVmA==,type:str]
                        PGDATA: ENC[AES256_GCM,data:qAMlhjpZc1+tFOwHcdeSmg+11VjzgbaOcUvbxm0QZo8=,iv:gM2NmaC9gKTZmz5KpKGaQs5vDljUTBjIRmH/E4TjE2o=,tag:HyVtLM8A8MiyrV/tCq3WSw==,type:str]
    ingress:
        pocket-id:
            enabled: ENC[AES256_GCM,data:689YhA==,iv:ZVZpAhcqBep7Vus1wpI0LzPeimhZpp3lNnjgI7pKqsw=,tag:ZGnTY4/eOamh4o7xJtKE5A==,type:bool]
            annotations:
                cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:5xrUPnphYeFk0zj9rAOyKg==,iv:n+9LTZZvX0QvEpe3JWUMmZ1vMe9O3ERjRdp1K4qxjBY=,tag:v4dbLZU9Uc/k7onbf20+yw==,type:str]
                gethomepage.dev/enabled: ENC[AES256_GCM,data:EUzN6A==,iv:idyDdapk+B/Jd38/hRK/6YqP3npSR7NCX/KVJeMV9P0=,tag:YUypOXGLoR0uyO13UCr4Lw==,type:str]
                gethomepage.dev/name: ENC[AES256_GCM,data:xGvYc9QOOfEs,iv:23lGfCq/NM+c1A46AtyPuYC1+ZHgM2podyIjLoFnIsQ=,tag:kTIi/zITcBLszBxQFguRgQ==,type:str]
                gethomepage.dev/description: ENC[AES256_GCM,data:tBgis2/qe3jDj446Yg==,iv:WjgU6u8lF6u86cLxsBdd7Muwmcw10S141V2M3G0Its8=,tag:IC9G5mTwnMjmraIQiA6sxQ==,type:str]
                gethomepage.dev/group: ENC[AES256_GCM,data:PT7w6OcZ,iv:vX1Gp3eR5Hf2Yi4A0rFMOZNgN45w2mcYB+76quygYq0=,tag:4zAP+Lf2Fdvihcf2KEYS4w==,type:str]
                gethomepage.dev/icon: ENC[AES256_GCM,data:c2b/UvDJJUT+r/iIHDKuCA==,iv:Y7d5o2Pmdv+dBr1IjpSMHk/4Qe9guSssmapdgOXyb98=,tag:OzxDV9xu1J0mdkN6oLaKtw==,type:str]
                traefik.ingress.kubernetes.io/router.middlewares: ENC[AES256_GCM,data:cBhbNT6KEpuLARLHEOnRwBSe3xSWZYc4hvTk7iM=,iv:PO86kqIl/oTr3BMhBTfbwta8WFrFu+Nw2rCDyfcWhns=,tag:ba8/bsBC+8oqYppJxlPBfA==,type:str]
            hosts:
                - host: ENC[AES256_GCM,data:lEJNfNs7Q7AV/Xg7Ac1FOyt6,iv:6adlTkZlBqqYRCBQqHCveuYpMr9TOC8vCkwHub4L4HE=,tag:AU1uAVc8OmXUCxeguOQnbA==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:yA==,iv:XJ+kSX0QrZj4iXlMsI7Sq4c7c1iuDC4cg6zplwOmLAM=,tag:O2XmfoEcke/599aGdw3yAg==,type:str]
                      pathType: ENC[AES256_GCM,data:YX/CyloI,iv:ELJgQD2kDF3eBWSR1iOpVn5zZ08y1slYx44w30eNWY4=,tag:MkaysJWDKuBmbPvuZmjzRw==,type:str]
                      service:
                        identifier: ENC[AES256_GCM,data:EdHIRhlucp7u,iv:/15BaJdkqq1Gqy1GuENrUk89GWyjlsrZuWwPtdt7ghg=,tag:lcP5vt9ukZ1e/s92fiW+sQ==,type:str]
                        port: ENC[AES256_GCM,data:dNUbvw==,iv:D7AJ2YWmtdcnGCJOHTHlfpLK9BDDEae9eJI5BqEBBO4=,tag:rYnuMxFFy18tqOTFHfelRg==,type:str]
            tls:
                - secretName: ENC[AES256_GCM,data:s09jMhGK4rDPwaTDm3WUNmUg,iv:haKeKTeRWz3QLxw9FndP9WIejkW72e7qEIhi7BsimWA=,tag:wnbALXGUQUcBCOSfbNkqhg==,type:str]
                  hosts:
                    - ENC[AES256_GCM,data:tPqiNZSuA4tufXc6HPOYNaQd,iv:UHEbGDzcEL50vEFy5k+iq1R9XaX86Q1s3BuN8cuuE1c=,tag:ViL+6JwL71Twaivg+RA7zA==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MTR2Q0UrNTJaa3o1dUk3
            eHJFdTFjakh4NVl6NmIvQjQ3ajlwNlUzTVVNCjdHZFArM3ZUZm1GRE92eS95cVBT
            VlREVmRScUV6VUx3MUJrcnROTHV6YmcKLS0tIHdBOW1HSElBMWRTWVRaV25HUzE4
            TlBFaVVadDVwNnVnQWlZWWF0MmFrUTAKnivw9dbbWxv+agAWhvHrw5edkPgE15DL
            0OxXVY2KXV+RYwxekuInr+5tNdBvEQNlJwHH1CzP2sFD4lm0tpInNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T23:05:09Z"
    mac: ENC[AES256_GCM,data:UVr0N0IlX1pCdPG1blvjQa0rT4e6SvVXR8aUFOUKfhSlUmW4rF9e+Fw47xAiWsrSQeorB9JALQCoJ29i0cBvK/sApwEwaebtpDWcLUcHJP8Ls7awFOc2fYBCIJuavy4toqn+GE0HxpxIOqJ/X/R1fUUfkcogyEcjx6069GUTOuA=,iv:gVpG0uW6RPu2sSigtj6/Lm07CSu95BY3fGMXNYi4xvM=,tag:ZwYqNtmxIxWNlk6M8ysOwg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
