app-template:
    controllers:
        portabase:
            containers:
                portabase:
                    env:
                        PROJECT_SECRET: ENC[AES256_GCM,data:Ghg+HwRKFYL2GhxrtSVgz8LmnO2rgmF8BZ1/bmF7MiI=,iv:4aGYKD7ViIGiorXRkY5UZCOZnsR/OjgGaSEcHOUW2ng=,tag:OIXQz5nLhkzQGRLbJZP+zg==,type:str]
                        POSTGRES_PASSWORD: ENC[AES256_GCM,data:iznoAG4JYV+g2+9y/xFwsN8=,iv:+s1VVyUMHvf1DlMl8F0743T/gFMZDOotmK9xd4B8Yqs=,tag:0DcHK2rdy9rqI8tAkfTXtg==,type:str]
                        DATABASE_URL: ENC[AES256_GCM,data:U9UpBiW3DyehSpj/SYB6jvBlMDQYah+LnhEyJQV2fmByP9DMU1ezHcW7z0VeeFEliex2q4aLKPEefDtWVWYVfKFLml5GNsob6oVh/eDOWgUgGcJhF5nKhw==,iv:stg+FUJA2cdviac1c/LQ97zg2t5KGCsJ87EgU2RdRlI=,tag:eyfpEm42565Cp6unjFjZQw==,type:str]
                        AUTH_OIDC_POCKET_SECRET: ENC[AES256_GCM,data:l1Xbmikdid/SxrOeMd/SAk3UsFrY89FIJB2KseUzsHA=,iv:A+CfRpP+e29LsolcMxOOo2ttUpqn4bguZQ6AaGMKoYs=,tag:6/Y0ge5vU+OOPxh0ZWyZyQ==,type:str]
                        AUTH_OIDC_POCKET_ID: ENC[AES256_GCM,data:t0DZbq4S,iv:WT58t4nUsxbuTc2e8N5r8HomDxTXYWgmDlgft/lxj1k=,tag:bGBgpVcvO/IDW/iuV1awHA==,type:str]
                        AUTH_OIDC_POCKET_TITLE: ENC[AES256_GCM,data:EzvZqpxvFZcD,iv:BFUGv795+vv8Gh1e0OcJQB0KtO2p93+5G3JIizpHVhk=,tag:lWjKXxAzR2APg1lVc8mdkg==,type:str]
                        AUTH_OIDC_POCKET_DESC: ""
                        AUTH_OIDC_POCKET_ICON: ENC[AES256_GCM,data:mKdvcTI8lIepjT99VaUA+5pH9XoBaIyfd5/wGhBkYrDSU3p6/e710/Tqljk9rKS+BiXjzCNxL5Y6Q74TTx5z7NPNg/IeDVsEHq+CH1eT5A==,iv:8+nDhVvMMBnadhY/dz7hOj/iZ7P8Bwax6FgBPgNNAJs=,tag:NrDNgRJoGgyBRZOZV09CNw==,type:str]
                        AUTH_OIDC_POCKET_CLIENT: ENC[AES256_GCM,data:T8FlTsFKry9mpMPukR3GyOywRUnylMuTYYAtT0lDpNG0nJ+l,iv:KsDCOaYvLGYGDDzf4DLaaaWGRXdRaPcJ+oqYaNcspAA=,tag:TrRcWeZlNMOaSr3exRW6tA==,type:str]
                        AUTH_OIDC_POCKET_ISSUER_URL: ENC[AES256_GCM,data:pPyyfNaO0W21SICs+UzyMJM/3xxHTYL9zNk=,iv:FfOmKSk+ic/WetIThWckY8SRZGU3Hl7n4hK28FvGnWo=,tag:C3/k7KSlNT02j8HwLddvQg==,type:str]
                        AUTH_OIDC_POCKET_HOST: ENC[AES256_GCM,data:eW5S0G646Csx1+FPnE0aLPvUKrrg,iv:gHKf0mYZ/S6ADF5fnnIEkJpjqe9gj2ja+L2cFD+6I1o=,tag:N0gshY7JeExLJ7B7xEhJfg==,type:str]
        postgres:
            containers:
                postgres:
                    env:
                        POSTGRES_PASSWORD: ENC[AES256_GCM,data:UtnWulph5MF1NzL9qIImrAw=,iv:LWXczK7Bq0BfgMk8cmSIkUC/ju6cNVj1ExyFAzV4Wvk=,tag:OefRJNGHPuWYqDIcs5bpzQ==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNS3FCUk1vd1dBSytQMTVy
            UGhwNENzUjlUMzNIekF3MGxTMVB1alZtYkFRClBWYm5MUlZGcXlFZVExVFNLNHF4
            YkFMbUNvVjVONW5uWFpKK2ZHWUNtS0kKLS0tIEhYQzZ3dzR0S3FlMUhMOTdUeXFM
            ZWFyLzVRL05BQVRJZjB1clQyL1NhYjgKGktvUP8a7zMRlMiyB3B4PL6E09nUw7FD
            goWrgkMsXrHGxhAcN20bagTVF+TXFq1JQlMRR+6ODXwDCu2CMCdk4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T06:37:32Z"
    mac: ENC[AES256_GCM,data:PyZ0+mMy2l2RmAehNjeETCMq4dTpkcxrfCn2hRvcpxR5XdhLqYPrKW+QmIJijDitCSApcgmYd9e2ePpVf4JzQOJjAMvtRjkuGiEfbA9woQ7G91Vv/6fq1MxNlmAHvTOTXarAnfRq6hpsTcQaS7+N2WrSqsSLI3ao6Gvnp1aoqPo=,iv:Dn24Z3rLJ5dArsN1VRHUW7B1YPVGz3Mt9OqDhnj3Po0=,tag:Ha1dx/m8MAoYbByJkpuGlg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
