app-template:
    controllers:
        portabase:
            containers:
                portabase:
                    env:
                        PROJECT_SECRET: ENC[AES256_GCM,data:4OuEcKT+EkGoKq2eYFtVl9jPYm2zagSo1gam1IfGJII=,iv:E6Wsks5n1YiD+be/nc4vLBxIsvusuApDneujZQ2wJtY=,tag:5bcoCEfxYMo0/+kX52BORw==,type:str]
                        POSTGRES_PASSWORD: ENC[AES256_GCM,data:ZB0iCnMO9pGJtWloBjdUdHEhEV0/DDsycqfY9w==,iv:DI7aU+76GTDXxoHL/Sov0UZG+NbVeSrt5LlK4vYX430=,tag:eGPwDcCah/JrGHlH3+KoAg==,type:str]
                        DATABASE_URL: ENC[AES256_GCM,data:xoHOPt2X+lukht8ikkUs9tW+VcliVrDdI3I+sbL6wLwBy3ZU+Kw4zsWgM5OCktFylV+yHQlJAThIZ3JFOlTV88fiT0Uh16jVF2SnsUCuwyXUaUmxvr6Snxw9uAkwqU3cRHl/,iv:0PjwwNCgy782F2txy3I2j0JEpbGnN6L6i3L+I9HHkP0=,tag:52/V4wLZlQ3xk/T/36bO9g==,type:str]
                        AUTH_OIDC_POCKET_SECRET: ENC[AES256_GCM,data:U70sZHgLyICgzTD1uh/3RZ9qj19wxDHUVmZIjzBI1E9S1w==,iv:aROEHIXf53NX7LO8IsoNE+0q8HXs7zNjx5oGxy4giC8=,tag:2LMudOhrLV7iB6nfl6nJUw==,type:str]
                        AUTH_OIDC_POCKET_ID: ENC[AES256_GCM,data:nH5P/SRM,iv:ek2A3UdGHeozidzGjtekfvsxCdgciC4aR+Z1d8WBoNg=,tag:lgmI4uy1mztJNVUu+bIwyQ==,type:str]
                        AUTH_OIDC_POCKET_TITLE: ENC[AES256_GCM,data:fIr+ZHBXKW8q,iv:3hazvAy9aibXlOVqwURkBGIvmgOjcV5msPjXyu10RMg=,tag:neQKdl4DLBjxxcv9DkibFQ==,type:str]
                        AUTH_OIDC_POCKET_DESC: ""
                        AUTH_OIDC_POCKET_ICON: ENC[AES256_GCM,data:i4NUBTfom4Om5fXPkEC1FRow6iLlHBudK+QZ48rWuiXmmd+PAAHbZquWhQ8CvdOnHSqtHL6XdUx52QcyKuIgc6sZ8b2JywzmxVxHs4/fKw==,iv:jo3rJUtykxTTtP0xodsrUIe907TZPsTMGYqkgUlD0hE=,tag:bqAV8DJU5QPBG7+2wLDD0g==,type:str]
                        AUTH_OIDC_POCKET_CLIENT: ENC[AES256_GCM,data:aPeFnWO2W0tZKHdvfIfOT/SbU1mMQBEHywyfo2NeoHbkhdBQ,iv:j/j47H+bZyCYlte/Bv1ueiE5FiwoxZrGrMr8WEDOv3w=,tag:IzABfo2/EPw3BV9otStWFw==,type:str]
                        AUTH_OIDC_POCKET_ISSUER_URL: ENC[AES256_GCM,data:ly7BzMD+1c+eAgqSTTof/uuIDOKllzVch6Y=,iv:uCftHQ1pjeALVIa8IWWOXmexae4SuMajYabM3q/hsK8=,tag:2Dh9M3eF0pfv5405Kz9umQ==,type:str]
                        AUTH_OIDC_POCKET_HOST: ENC[AES256_GCM,data:v12L5T6UNDVR9x6wP2ppSOw8kNBm,iv:fnP1Goyp8gkeaI+Q/eemmk34KyokQ2PBIXNCEgCB+fQ=,tag:ZeV5mNPyq/deacVkFcignQ==,type:str]
        postgres:
            containers:
                postgres:
                    env:
                        POSTGRES_PASSWORD: ENC[AES256_GCM,data:RFey3yUGkcvqVdR/Q/tgahABSGnswMY0RAdl6muEEfg=,iv:BQrD5u4pI42XmOPLyJEPbJvpfkHQgp0+Oqbp+2HbWm0=,tag:HLqP96blofddLLIk9rFzdQ==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBNWR2SXpvOENQUnhGWXBG
            UEwvVTRjeUhDejV5NEFveFJlbjdqeld3RUY0CkVwbUg4Q001TWhTZ1NUOFF3WXB3
            bU5xNmJVcm9rNHRDTDZUTWwrVGZVODgKLS0tIDZMZ2FhNHhwS3c3WGd0b0xyYmJy
            NURBcDVsUlBCYzJCais4aS8yOFN1RVEK1goRvCfIuoP4k3zd18LxI+SDtZyb/Xm9
            ngE/vMsPHBg3by3gsOlaw1auzocn1wmy6fjzIt0GyRtumD4wVMyq0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T06:31:05Z"
    mac: ENC[AES256_GCM,data:s7Fg5+epTg4UZsXLMg6P47QkrETsW78xxm3rVoDR4C6yJWZZHiANZRWFQl/r+NfxJ+ninsGe5/tBv+GTkTwTx7MlDrE3hVryPBAA69qoZqqojiBpGht8J10lC1Rs0SgQdT2/unMbcK2PGzLUnGiLErDFkhMvdGl8cEkpITKwCM8=,iv:6uqZZ1sgXFI3pQBmvJ1iQgsIRAFmiVIL0oHJ5VWVKb4=,tag:59vTO/KYaEU5+f+PC93dgQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
