app-template:
    controllers:
        portabase:
            containers:
                portabase:
                    env:
                        PROJECT_SECRET: ENC[AES256_GCM,data:VuKLEjdiVjV/67ntjwIczDi0bujs8WOYpIuqvBSJk3c=,iv:hTZD2fiXDwdIoceTUrl/tVKiwg9ZY4FrkmBsWN0bhJI=,tag:2IuBFOQu9gBhIIr5kYGfiw==,type:str]
                        POSTGRES_PASSWORD: ENC[AES256_GCM,data:Mx0q57aw5xM6l1L92vAgSkvbK0gRyJyl,iv:aJLj2AQPO49MPEF1JFxtC/vNHBQ+iPQnogajN0+FOt8=,tag:LVS06Hr5hBWhc2LcEXAq+A==,type:str]
                        DATABASE_URL: ENC[AES256_GCM,data:0Bn1xcbLY/mcCRm59L+66F3S57a7yj1tiRCYNvx+yuCyQEvErZqR6mpU5E1Bx2f/ToveX345GHFrm4j/igmnx1+7GmyVD6jvC1usPUPOhH7z72TPP4xUX+GLhVVD0pU=,iv:L54fh24b+aXpejav76pV661AB0xb1f0CfOA45zTqJv4=,tag:Wfo7NyrnIHANZdSlD294Pg==,type:str]
                        AUTH_OIDC_POCKET_SECRET: ENC[AES256_GCM,data:Ilnc6twpDSoQr0paz2t1msGQhMa1BU7nHSco0/13Fvk=,iv:tuHtA9PBqBJaDGYopiyDIKGmnzcbxlBsleP4SoE02fU=,tag:FBtsgvJsDqk3lOcgZwlAEA==,type:str]
                        AUTH_OIDC_POCKET_ID: ENC[AES256_GCM,data:7o+pT2Zh,iv:PWmSnEV8rbli+39MxqvOvEr7dB3hEzN3J8Pnp/ljyTM=,tag:WHyAzQhKtGTlV4t1II0y8w==,type:str]
                        AUTH_OIDC_POCKET_TITLE: ENC[AES256_GCM,data:9JJm0X2dIWhJ,iv:C82cIbLlfZQna8vY4ga1ti2yvJm/pE+yNZ2kh6KIao0=,tag:jvCx/O/7V7lnjQJxL2URtw==,type:str]
                        AUTH_OIDC_POCKET_DESC: ""
                        AUTH_OIDC_POCKET_ICON: ENC[AES256_GCM,data:XtSdZDBDNVZzgBdw4HrT2U/046EDurf2gd3laky7130u0U80W64RFEw8mK8BAted1wz++EM+v+36i+Ph6rzTu5eq5dlrvD+ToNyUfk/WoQ==,iv:knlVBijl6thm9mVLh/6hzZkPQRlu4GB1LxbXvOhQcL8=,tag:p7mCo0bNKSO7u06ITO1v+A==,type:str]
                        AUTH_OIDC_POCKET_CLIENT: ENC[AES256_GCM,data:SlR4Wt6QRaR8uwmDWQqz+J4g6sbbcNm/yxgrnamvakM+ulrt,iv:T97T5Tke+0gvFzuZJl0jDoMEl1xdKwMP+C/3UqEmtk0=,tag:WUe86HE6UMz0Su8/oMcc0Q==,type:str]
                        AUTH_OIDC_POCKET_ISSUER_URL: ENC[AES256_GCM,data:ThS9cR7Y8fvcT4LlKJciUjJ0Bzi2nLO+JO0=,iv:bnFR1+HS+7XWuxI3vJ8evLZfT8nm0wsgM/nUiDx5SeE=,tag:2TkcBttje/pIY2niOlScog==,type:str]
                        AUTH_OIDC_POCKET_HOST: ENC[AES256_GCM,data:aF+Fa4UHTX/pZU/MJ383Tsoz/oSw,iv:Wl1hxGysgq13/cmXqAxx8Ht25mVsEXbci5IVePw9SNc=,tag:IZ8xZgZzxLudtj/2M3vZPw==,type:str]
        postgres:
            containers:
                postgres:
                    env:
                        POSTGRES_PASSWORD: ENC[AES256_GCM,data:LMtMJdZdMetnIOPl4uyKZ8ide3ezmWtJ,iv:yPfoPxOSgwAV7aRwDay88f5csjWZOoYqTAo32bGiFzs=,tag:+KMuDQTgaaj8wUFz0wR2Dw==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3T2JuNEFUeXZCcVNRR0VE
            TmZvS3pjQ3BwaHFSeEt2RERSZTE5MXhuTTBNCkFrYkFuekJoYnUyL09TeWRHc1hV
            aUNKQkd0LzFRdVROQTNCMmdMRHRJbk0KLS0tICtvcFVXU1l4SlIwQzFLdDNJYURZ
            bWk5MUJjTWZJR1NBR2FHWlJRR1NEMjQK3Nu6FZOLzo3D5Gx1PbKAReUKJ61lHeSl
            zZDTqyM+rYJFIOpxecFq1McMKpY4xMhRPr1kl3f8h+E8CDGo6AorEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T06:15:11Z"
    mac: ENC[AES256_GCM,data:WPSyet9hJB9UKMabzhMV+94YMWYIBYAlgIDFtlCyrrglL9MgjayYJbkUeGBm1b5JGECjs+hRVyaLg41yMWiwRahNYggwOGUaiNZ0LqzpeDXS59eOHGoMCTml5rYVPPw+MQAu3uz4wBP1g6mD9WL9Fd8HEL68DsSsY94IlMkp/uQ=,iv:6BgkktdRbApPgDKymHnPTbNH40vjf7/hW1Du/oUG/2g=,tag:cOhwwvmDEy4tKjM1wRPERg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
