---
app-template:
  controllers:
    portabase:
      replicas: 1
      strategy: Recreate
      containers:
        portabase:
          image:
            repository: ghcr.io/portabase/portabase
            tag: 1.8.0
          env:
            TZ: America/Los_Angeles
            PROJECT_URL: https://portabase.mdeleon.dev
            POSTGRES_HOST: portabase-postgres
            POSTGRES_PORT: 5432
            POSTGRES_USER: portabase
            POSTGRES_DB: portabase
            AUTH_OIDC_POCKET_ID: "pocket"
            AUTH_OIDC_POCKET_TITLE: "Pocket ID"
            AUTH_OIDC_POCKET_DESC: ""
            AUTH_OIDC_POCKET_ICON: "https://github.com/user-attachments/assets/4ceb2708-9f29-4694-b797-be833efce17d"
            AUTH_OIDC_POCKET_CLIENT: "34084e8c-2a17-484d-a2c7-852f6de0db5c"
            AUTH_OIDC_POCKET_ISSUER_URL: "https://pocket-id.mdeleon.dev"
            AUTH_OIDC_POCKET_HOST: "portabase.mdeleon.dev"
          resources:
            requests:
              cpu: 10m
              memory: 256Mi
            limits:
              memory: 1Gi
    postgres:
      type: statefulset
      replicas: 1
      containers:
        postgres:
          image:
            repository: postgres
            tag: 17-alpine
          env:
            POSTGRES_USER: portabase
            POSTGRES_DB: portabase
  service:
    portabase:
      controller: portabase
      ports:
        http:
          port: 80
    postgres:
      controller: postgres
      ports:
        postgresql:
          port: 5432
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Portabase"
        gethomepage.dev/description: "Database Auto-Backup"
        gethomepage.dev/group: "Database Tools"
        gethomepage.dev/icon: "sh-portabase.png"
      hosts:
        - host: &host portabase.mdeleon.dev
          paths:
            - path: /
              service:
                identifier: portabase
                port: http
      tls:
        - secretName: portabase-tls-cert
          hosts:
            - *host
  persistence:
    data:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 5Gi
      advancedMounts:
        portabase:
          portabase:
            - path: /data
    postgres-data:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 10Gi
      advancedMounts:
        postgres:
          postgres:
            - path: /var/lib/postgresql/data
