app-template:
    controllers:
        koffan:
            containers:
                app:
                    env:
                        APP_ENV: ENC[AES256_GCM,data:LSQZWfPX53O5wg==,iv:zQuea5Bjal92BW8/SOCHI+F4QeF/XKBot17LEt/2zpA=,tag:uHByTXYZOOO0avUpEeoMSQ==,type:str]
                        DISABLE_AUTH: ENC[AES256_GCM,data:vkkA7A==,iv:IvhfCkOEO51fEUQmK/hOYV6fMy6DwPB/UUWkLYEGdz8=,tag:5xltOIQZhE/UK+rW/yivgg==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjWElEdHFXazBLUGN2QWNZ
            N28xRHIxTlNNenM5d0VnRXMrakFnQ1Zud0c4CnRCazhKWlVXdHI4SEFTWkd1Z200
            aGZwbWpVYjhJbGRwWXAwbGZoangrVDAKLS0tIEMzYnc5K3JHQ1ROcmdGMks2K2ZH
            a3d0SWxkbDJIeHJLcm1ETE5jSW0zRTgKDAAWY1Kl+NQRQm7K7rik3Hm4sKZsyj9j
            aDafHeVysm8hlkYf+uKoVdsW48CVoeLKtqZkguhghM/A1SrE6CIO6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T20:38:55Z"
    mac: ENC[AES256_GCM,data:+40/V55IR/daUo4TlZU/3NU3iir0NHwmcN0lsP8JuHp/zYhXv3yy0IdvP5+xm+iMeVHoNYMswKEdsU/ZHfl2QPuZnGFfBgosmqlmY0Z5eDKG0i0zKy/FqCp3d6aeNlk0ovr1zmAjFkolPIyhP/YpwcMLx1H5pny2KBe8Ev84Ldk=,iv:K1IdJHe5OvGLr3A1U+xlV3BetZ9QatyHR9/1rbBkAYY=,tag:J9dmL7k1AhPyz5nQnIdvhQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
