app-template:
    controllers:
        koffan:
            containers:
                app:
                    env:
                        APP_ENV: ENC[AES256_GCM,data:49UzvjnXRfRMNQ==,iv:BoynTYL9tZmnCU3ZUMLDSz7AfEsmZaj3arRpqwmf6WA=,tag:VsJLaMq08T3fZsrON6IX7w==,type:str]
                        DISABLE_AUTH: ENC[AES256_GCM,data:vNin8g==,iv:nYovXJ1gK7kryWkFO/BYu+6GEJ0AWd/vjBAmeYKCakI=,tag:I+uXrrWh+RxBE19VhNYL0A==,type:str]
    ingress:
        app:
            enabled: ENC[AES256_GCM,data:HabmEQ==,iv:6vUOAxkTd8qqy/OU1h3iUydCeqz/tJ6YNJyWlmpoWfY=,tag:32HgViws4UIeYI2Azqksqg==,type:bool]
            className: ENC[AES256_GCM,data:0y7edq4xlw==,iv:A+9EgxoiwdWk0mylAc0Wz6DybKw1DZ5rQBlkuBuThY0=,tag:RukaAHMCXngdEyP8gA1N1A==,type:str]
            annotations:
                cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:r3RBGZYgJA/q2Umq3ybqJQ==,iv:O8kZD7J+JD7JbrwRfUZhErSK351MXNiREvEc85ayLyc=,tag:qpL0B4iuQdvnB6EF+QLRhA==,type:str]
                gethomepage.dev/enabled: ENC[AES256_GCM,data:w7e91w==,iv:2EikfLhTcJIXXhxQRo/KAuxVfu5h78vSC+4xochSZWY=,tag:3kezMPma4X7u7kKEMHfDuw==,type:str]
                gethomepage.dev/name: ENC[AES256_GCM,data:VI5EPud6,iv:fNAjSo/27U4ds5tt71pba5hXiGN2Tu+1t8J2WmI5AMs=,tag:jyoy9N4qZY/Hl7ZMaLqE9w==,type:str]
                gethomepage.dev/description: ENC[AES256_GCM,data:KxpD+devmv3CVc4pv9xv,iv:wXgsDv/RXouU5turEireXwGRGrAxUahg+WURGk5FX7c=,tag:nzqtWPKmaVNK+PQDBuWotg==,type:str]
                gethomepage.dev/group: ENC[AES256_GCM,data:mj/OrXVylK6l,iv:NwMmu+ZtE0b1rO6NtTmdVJWCip02JPpxUFdfirJEQQ4=,tag:V77pBsgzKDZFDDlj8ImzIA==,type:str]
                gethomepage.dev/icon: ENC[AES256_GCM,data:USL86zFZ4BXy3BokTQ==,iv:RqKbA+8AOFHKtE0GBQf4KRHjIBwLs+KIKW0DfAiO+qM=,tag:33MVJFI9gl3LcV1L+MYM8w==,type:str]
                traefik.ingress.kubernetes.io/router.middlewares: ENC[AES256_GCM,data:m5HseXYJEr8ZI1UKLdKI0fUnHKci7L8h5NhqWmRDjRdtigNSN7m3+sUkvA==,iv:M/l3FyAjczIsPTIuJhlzrtloojLvzfcZc+vATibZbIA=,tag:Y8WnwoG1ktI4bNAk+hT0wA==,type:str]
                gethomepage.dev/weight: ENC[AES256_GCM,data:lg==,iv:AXHgaTZK5dslXgjhSny71Po5X/yr1bZmljLf9SbsdSc=,tag:gKeZvNQfg16+SFJUdh0+cw==,type:str]
            hosts:
                - host: ENC[AES256_GCM,data:11mIbqLUTwu4cfwxnClBjVUs,iv:x6Vrhgjp0Qh/95VLhzJUEKI0q6VBZk3P23tsKqIIvhU=,tag:NancvSnviaBsw8ghaRq5mw==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:4A==,iv:9VfQZMsMwadfB3ENrXDLDF3RSpO0Pam0JMjTtTQYvFI=,tag:fBMJ8K6GoIPqDXvaq0pSfw==,type:str]
                      pathType: ENC[AES256_GCM,data:68dxykyT,iv:IpexRFAtLcgOQZ5bWoBcyhy7FPlDqzTas/PDJa66XaE=,tag:63IkEEBKtRWHbuVx/yDIKQ==,type:str]
                      service:
                        identifier: ENC[AES256_GCM,data:xG4Z,iv:z1f55Py2fonoY/xAUr0/Z2lLkCVYYZsrfToeE+LUavY=,tag:NDX58nMroeN8s8rsFM3gUA==,type:str]
                        port: ENC[AES256_GCM,data:YDJrww==,iv:/xA36XBgv/hth6tbsLvQD82GF/l+/hSAKNGD0MTCVmM=,tag:XXUMYiqdiPDSssJU+yY2Lw==,type:str]
            tls:
                - secretName: ENC[AES256_GCM,data:pndxDY33owjvWdGXTUl9,iv:s16FEtH7dd50LuCEJcmOgCZ19gAN6W0W8pdACyPmP+s=,tag:OkiEgkxXP3qN/U0HuefxDw==,type:str]
                  hosts:
                    - ENC[AES256_GCM,data:+a/GkyX4ZtCsUpB90t0S5k1A,iv:t/q1xdnH2ulWD9ZbOlBYJxsMuoWhzaknPW2HlO7Vwf0=,tag:ZpN2idKaoDrRFSSGdh6Llg==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUXo4cHp6YThVYzdsckhS
            WWpvWmtITXUrOE1JejFaWldxYmxUNDM0S3lrCkdhZENCak00YmNzSjBRU2hCMUFk
            eHd0V0srUGN4ZmJ4bDBLMkJBcURtYnMKLS0tIE5xQk9oSlB4UDJvbmI0QjM2ejl0
            eU1Xb3pKN0p5OHhvcG5xdzVNMURWM2cKp07Rh7nc4ikgSmDwE0eH8e7aFq8FBMzh
            dYiYlzfiNT2rHeVew9p91E7HrRMy8B2v4/BX45I2s/LnzuuG5uUr6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T20:42:20Z"
    mac: ENC[AES256_GCM,data:JCuDEuGwERq82QuTUt2HunjhGpHKCy25p1/m5ZH3nN1B5SAaNUXAlpKPtln21Sbcm7u+h3u4/Z5EIvi/U9faX8GZGSeRwj2XXxmtkBV9TM6qkNONcFuSGCllwY5hCWuOAMBWegpkRQs0GYRG9BmRCtrB0pGC+OKGz9gST2xwWU4=,iv:Qh/eCscnP6lDr+xYKNvIuUnLI/PIw61LSOniA++GecM=,tag:csInQUFGXYYWHcaEkZtI6g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
