app-template:
    controllers:
        koffan:
            containers:
                app:
                    env:
                        APP_ENV: ENC[AES256_GCM,data:c5QlW91Qlw0s7A==,iv:jLVb4PlfoKUCYk3GWP2laePQ034ACB8oKF3wKlZDUzo=,tag:NrmbxgZbcZTNXEOpBirU4A==,type:str]
                        DISABLE_AUTH: ENC[AES256_GCM,data:C5Iw9Q==,iv:U4jUIb9jHyxVo7IP6V8W9HIfky9ADblMGxKfIE8oC/A=,tag:G81BWPdILgb8u8iDJv7PGQ==,type:str]
    ingress:
        app:
            enabled: ENC[AES256_GCM,data:CSJQ2w==,iv:zlmEXNUpgBWyzgLZXB93RtMQHjX9SWSfddhRkAeSpEM=,tag:hKjW1rn9+iP6Irk/Z1YAbQ==,type:bool]
            className: ENC[AES256_GCM,data:sYQ6R9/0IQ==,iv:BBsB2wacVHCgkEh31jGpGnIkylcb/mCtWI+IknmbITQ=,tag:O+ylTimYVnCuOO0QLeImQw==,type:str]
            annotations:
                cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:CtLGysR4uV7k2UY/7o0JjA==,iv:MJaf73D5jZ/GEqMnOOKNUse2HEpvqOcxjLu38xKCC/w=,tag:2AYGJHHWVkH+nJ9RdHQwsg==,type:str]
                gethomepage.dev/enabled: ENC[AES256_GCM,data:lImN5A==,iv:3E7b8z4H1Iy9C2TramgX+gJF/OBq26w+ED97An3/oKQ=,tag:ONbV7pU4GS76tI5srCrx8A==,type:str]
                gethomepage.dev/name: ENC[AES256_GCM,data:PIkKXPuv,iv:Lmsss9MvcP2PQ8RW8kgSa+xSOJozt25FjZPjyO4UDJ0=,tag:fYGxjQb4CgrBI2wWpsTc5g==,type:str]
                gethomepage.dev/description: ENC[AES256_GCM,data:UfHT6GIDHq/x5mgeLPeU,iv:5B7yk43xsjsV/7ltv+CzOBgczl/s1DqtfHHF2HJn+4A=,tag:OKSETIkONlJ30qohY68y7A==,type:str]
                gethomepage.dev/group: ENC[AES256_GCM,data:sgOjMpLR9QB/,iv:77sk0ETvcS5Q0GTd9YRs22RUce2qkZ3jkE9Q0yuF/HE=,tag:6WkC8g9/XOKnTRT52aRAfg==,type:str]
                gethomepage.dev/icon: ENC[AES256_GCM,data:NcxK/uLZmkEISOEXyQ==,iv:80ZYkbFNJwW1EHrXOplUvJ9JIIeyuoTTZf4MC9IzRW4=,tag:DKcP5X8RvOAiwFaMw5pOdw==,type:str]
                traefik.ingress.kubernetes.io/router.middlewares: ENC[AES256_GCM,data:amCBsYtdwRDHt6ii1jprSuJHyPjuxG01AJyvhcvdkYtyKnoJ4Pgkrz+lKp4HQZJ+rLI2hW2vbsvedzhIar/ryCLpJjfx9z77s9fYql5Uoi9HY1MCNg==,iv:HkvCOWQQn7vV5wMZbCy3+r1TvtJdhsq7/9N8f3+ILCw=,tag:kBmCm7Z5FUJDVpK4kpXOzA==,type:str]
                gethomepage.dev/weight: ENC[AES256_GCM,data:2Q==,iv:1UDhyhDVI2u4vTbCNvGL6aS1zqhiVyFj1w3mTeUAzw8=,tag:VUD4Ra3PJJVhT5PtHeekvg==,type:str]
            hosts:
                - host: ENC[AES256_GCM,data:IOVZ8ecStndvvhZJBf8L2BVh,iv:XVZEl8QNu/YTVaKnEEvZuQCw0yOwGLF+9XQPJCDbTCI=,tag:xvQeXKLwgOPkwBtvjd01CA==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:gg==,iv:FBQXcbaaqnRXwpTLrGh/qibK9SYUoi5QgI2PFRkl6EY=,tag:+CWaWeXGwC9+28yZjGZVZg==,type:str]
                      pathType: ENC[AES256_GCM,data:9uTMdzHz,iv:Fb1ysE2rzNiYaw0d0XjttE8Jx1z8sXWeqtxXUN28MYk=,tag:JAyC6JUIwdsj0MUF7xvqJQ==,type:str]
                      service:
                        identifier: ENC[AES256_GCM,data:cjWe,iv:Ra1YEjAhdqS5Nm5DTZb+e8n/SP8g68qfWygU1Ahjiz4=,tag:cL3H/6aZFjB/1LLTBf1WLw==,type:str]
                        port: ENC[AES256_GCM,data:5EgpWA==,iv:7HWif7HYyQBUzisH9TgtBK7gIgdzLuRrnmeqlwRnBHE=,tag:hJl+ENaBJuAj4JYMQREbvA==,type:str]
            tls:
                - secretName: ENC[AES256_GCM,data:d5MJUMTbhf7oYrrZlA0R,iv:8edNLvMGsb9Xpe7r9TpIr8V4UfjjdlCkWEVoSNYy2u4=,tag:rCgG3UR9nexLfMx6JwgwRA==,type:str]
                  hosts:
                    - ENC[AES256_GCM,data:Asb8mlHJbtJl1eNqXvQmNwnJ,iv:j1MpicEUaCt/YtxEk0nltH5gtwGrmjLHhh54F6u0klQ=,tag:yH5ngaIt5buQRrnVHfTnvA==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZncvYmVsRkY0RDhOYTRM
            SnhhL0p2cktZeDB0K2VHVzZtdVVKQ25nOTNRCmJ1TG5PU0xmcE1CMzZJT3hGZUxr
            cUl1UFVRTDZyRExuRWI1WnJNZ3YycU0KLS0tIE9GSDA5QzJpU3BNMllXcEh5b1pV
            eEt1aGlXd1F5OXhhdkhOdW9qUnpNWEkKv+QtagF04CUQ3mXbNxrUaRgrIGqKryPW
            jSQsWVMHvDC3WeOSw0yqzQS2AnKwyusy8NBX+fpK+jc/dmFEQQb2bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-01T13:07:57Z"
    mac: ENC[AES256_GCM,data:itexgboM1nVnRxejsgjGkvTgBRGL28s67MHPrvWRhnfS68/NRmLjqhfrJAZFeoDRnMU+vPtq3ElSlDZlfIh1qppINGPDjegc8SatIz2OPQq+FOscDsOe6s29xFhITjt0cGTuTVcaOaAMvj/octMxWW6EZgnW3WIoeS9ZBBlcpCQ=,iv:rO2u/6DCflJklXDmzdB2PRDYlRY07axa68p4nJQ6AoE=,tag:aC3uZhOe90peHoZuu7MKsQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
