---
app-template:
  controllers:
    koffan:
      strategy: Recreate
      containers:
        app:
          image:
            repository: ghcr.io/pansalut/koffan
            tag: v2.10.0

  service:
    app:
      controller: koffan
      ports:
        http:
          port: 8080

  persistence:
    data:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 2Gi
      globalMounts:
        - path: /data
