---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: litellm-database
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-1"
spec:
  instances: 1
  storage:
    size: 10Gi
  bootstrap:
    initdb:
      database: litellm
      owner: app
  imageName: ghcr.io/cloudnative-pg/postgresql:18-standard-trixie
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: litellm-database
spec:
  name: litellm
  owner: app
  cluster:
    name: litellm-database
