velero-ui:
    config:
        s3:
            accessKey: ENC[AES256_GCM,data:yVxOmtjyKVv1M0ScU/VRu6RemfZuwwfY+5k=,iv:IWCyV+RP7EFIYqYrVgY/1K86e6nVqmtW10PiZtc59VI=,tag:AZ6jEZxDAWNlqWS3y7Hf6Q==,type:str]
            secretKey: ENC[AES256_GCM,data:UfpgV/KF3nnifcDcQuEDIpE6BCJcyaZ+Ug4hPl4oU75Sy9VkvkDxv1r9FOdNcAv9tF2upPVFXhJaMpNSIJxVFA==,iv:T43HjwzQHt3uNGQuAAQEzbTfkrFEe4MQgYSOvUC9Avo=,tag:hwefa8dhHE0vdosXOxgHLA==,type:str]
    env:
        - name: ENC[AES256_GCM,data:3ZeZJopmsTe49HJyylNyAA==,iv:ia9hNlYiSMFCSslqj83fsVWNpVFYkarzPiIJIJKOdjU=,tag:/l0IZyjd0h7a9iPmuJUyaw==,type:str]
          value: ENC[AES256_GCM,data:djVPzH3w6PyRyHjbqfinAToHFw==,iv:Spn5X3CB95X4FyyGj0iqXEL5wrINKnMBA6+fVD9asCk=,tag:qqEwArf/Bll1ZQ4Hwl2XXw==,type:str]
        - name: ENC[AES256_GCM,data:rMOG16nGcx9Wu/ZsIH0wRo17Q3qgCQ==,iv:2DlqJxlA/PvJ3tT3wCmLH4U+69pAgyhR23aRfbY6s6k=,tag:aCC80EcDbLNW7cKkfHZ6zQ==,type:str]
          value: ENC[AES256_GCM,data:pRAcJfb8tSUsoMMFh9i2iiTdZYvtMNb6bCI6yevLW92gQfLwMNg1CUwT1Z0=,iv:SCnpqwbqnqRHyXxf2pzZfineQ8Gttab/C66/TAQIpks=,tag:8SnMTTLDeBmGZB1v4hP5lg==,type:str]
        - name: ENC[AES256_GCM,data:zrfmT7WaGx1XVt+X9Qp9syB+,iv:t0kp77Ar4dzpHhwm5pCmbskbxM/WU5BdWAuJJezG+Ek=,tag:r1EbG3YoHtcuSyu+HZXM7g==,type:str]
          value: ENC[AES256_GCM,data:IUP1fA==,iv:DFBC4pNUPVErjd3TUZCX60gG25XwKWhGNoIkGi/8lzE=,tag:Lav/kwL5kfemld4nLa5OgQ==,type:str]
        - name: ENC[AES256_GCM,data:9cxBlxVCVbstnA==,iv:x7fFs2gjwmo0WCVv5LyrP8P8oqANUs5raACcN7vc6TU=,tag:xUox9vdoN1YHLfONEKj56w==,type:str]
          value: ENC[AES256_GCM,data:gV3ORTQCURE=,iv:JikLlMvJ3zH6ZvP0FxrvHJmFkfJDojemPEj6Fz75Xe8=,tag:paUS2v3fNhV5+WCVrz4VXw==,type:str]
        - name: ENC[AES256_GCM,data:NxM43iCpJcylynkNeXKBkvSCpTwKUxc=,iv:dY8VdMlbGreRe38dGp1M4q0c4S3YOshMSc9vkW/SODY=,tag:f8sGWkFEou4ztFwhwdKe/Q==,type:str]
          value: ENC[AES256_GCM,data:0H2mlB4wkQh7/4WhrNqkiJeOjxjvXyMQ1mfF6KSbaswCUhKJ,iv:vTu0Wd2p9Fc4iRbu4R1aeXFCXNgVsrA3ZwbD0Pq77oU=,tag:5i2xsMpxgPzvSZoN0hoocQ==,type:str]
        - name: ENC[AES256_GCM,data:UVw1fwagcQsm5E5MXF3wLKgTiA==,iv:8LLZFLqh1SmXzz2X8XX+tJa4HlW2knRoXSpazmXcG7k=,tag:tCp2lXmDRpYGdh67A6N8Xg==,type:str]
          value: ENC[AES256_GCM,data:6fgb7mxqz2pNS4cdw1VwTbT7LFdGdWakUrOFzlFSXSfXyQHdb3gZVKCxwgk=,iv:SLqWSFXOz2uXWDStlp/XIwoBwOam86+I1ZXufO2Hh2M=,tag:04XrXVJLovzn1i/+udFLNw==,type:str]
        - name: ENC[AES256_GCM,data:k6AoZ1q9CERpyIz5VAaK,iv:jkP6llt4X2gjXUZRFrZQOFIvih0pa06nZoZxcTp0ruk=,tag:w/9A1xPQyZUbh9dNJ36Csw==,type:str]
          value: ENC[AES256_GCM,data:fui16uNFw21A8wa4KDsvcSTcJMTOCG+KVxZS7TAtpCfvFgp3Dsf9IU4=,iv:EThk5cB0Zhn5+x/wQXzMB1LjyVhorX/mkYIyTw95plU=,tag:v5gfl6yWhTPmimAYs8m1LQ==,type:str]
        - name: ENC[AES256_GCM,data:EiljDu5ymf6VgAK8peB6,iv:ZyIikBJj6u5ehGqGdnT+xLRIdjuvHv2u2kzmCJh6c7w=,tag:+9d0Yt6QPIf2Ea3xLsODRw==,type:str]
          value: ENC[AES256_GCM,data:rTeQos9Lv2MzeB5UwjoVcA2VvpbqXNqD/9Imq4gxmlYjF9IT,iv:GiDdXsdfqgTGLhH/uqLFcxO/JmN4DHZlUWz+4FdtxjI=,tag:wEfTrpB1UmeBXTpEnQXEvw==,type:str]
        - name: ENC[AES256_GCM,data:uVt+F/NMHcJdp7IP+wGHhBX0Yw==,iv:QbuOMbCdjOftPoLaqOYlu1gwcf/XXMDzA9i83Pbwnm0=,tag:3cUFMuYAthljXz3z/Ge+Ew==,type:str]
          value: ENC[AES256_GCM,data:lt8lFFe+J6PBhuO2NAOuIpNdgeL1gB70N3effLgRnyk=,iv:9q/nBqemJVKxeymxHbOIZjotosshLUqD1tuelfAYKD8=,tag:0xZ2iLZo/VSr3xaiNIfJ7A==,type:str]
        - name: ENC[AES256_GCM,data:u3JakG24F6lF5/u1zbpsUos=,iv:YUu5D7SA1QhEowbI6Y3rWMo/BkqaRC6ibNXDvX9ZYI4=,tag:zAIRprYMsMIslki6jsZ1DA==,type:str]
          value: ENC[AES256_GCM,data:vV80un+Z5ADZPCoSQ4ZoFVM46W3uVd+0Rg8t,iv:PiR89bOiZzHDe+0D4noC2INOy2xc57c3IADOgxD9YPw=,tag:wyJxhuGaWkhwXmQHFvk/sA==,type:str]
        - name: ENC[AES256_GCM,data:AnOLD1tLRiyPGVfDG7tAupz9,iv:KV3IA2YA9JDZH/6S9spVnpov5WODVJ+V/H88lK+oauQ=,tag:qppu3WXsYnv59h1Cu4NTPg==,type:str]
          value: ENC[AES256_GCM,data:PO2iMzSXQplcmP95Di1VUQhmQBihErHO/BaYTppUOYo=,iv:6/EyMSSfM99ZpK4z26fKiUj4OfcLgg0rzD9TI/4CkxM=,tag:LySYXqJXTTzlC611ck8jRA==,type:str]
        - name: ENC[AES256_GCM,data:yOFQ31fjWGcdv0JiyM59hvs=,iv:Wv9RHx8y2mJ5yea1I+Ry4ALXrbUdSRPl/wsWvP5z2Dk=,tag:GYkymhyL+iTThP/mofdrvQ==,type:str]
          value: ENC[AES256_GCM,data:y3gWf3RO,iv:qdalC+EeZ2kVrvLLnUOVNyQ8rs1ZZNsul9MGogPgoFo=,tag:tQtucuw8ux5y+QiTe9my7w==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrVG9XazBrMWgra1A3L2NU
            a0VtWmR4Y3lscTRwUG96ZzVERjRzMFVZc0ZJCnliN3I2OWtVQngweVEyZitFUmpj
            Z1REaS9KTWw4UjdMTm01MmNmUkpaVU0KLS0tIFV4Zi90V3U0Q3NCWWhzcTFZRHE5
            dWdVMWt1VFZNaS9rUVBNbEx1MVBQQ2sKuXDsB1bHQ+S/U7sUV9dJx20rv/Cbu8Fm
            MgA4OiqFJhqXu13Z7ajNjq7+4MAgn+dBkfSwRi1ffPNrMJPqfT8f6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T00:23:20Z"
    mac: ENC[AES256_GCM,data:aNePqmWGvEEB/HLQGuFGLVGRaeC9XmJ54+78ZfCUhup6koIvlGAhK2grIKrkd2VKK7qY07szRbFqWdtuI+aaEeBXcxcAHxgcggM+aFL6lcs/eKujMidgAvBacmP5IwWMuEURO+VDDtD0790bwcdyPY/eBFFhYDJSgBaEcJDghMo=,iv:zO4juu0/blbOZ94MpSD0DsOKeqMYKNL2DeQRxEIiKhE=,tag:hbmXg0z8wgSol3rKtAbZdg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
