velero-ui:
    config:
        s3:
            accessKey: ENC[AES256_GCM,data:VO8co/aCd40GCIwsVX0b+nd432sXdQAsd4A=,iv:uBvsMQBMZBQACx0/ccsQwwt+9+xATCLOJl255cGqULM=,tag:e24ZlHnoqYH66Xkyvj/Yug==,type:str]
            secretKey: ENC[AES256_GCM,data:eUw3X89aReL37qDBeqZiGT8oaWfA3d0T1D5LXf6P8VWZnVD0qJJ6wcb0Ha5b0ITKoqZ7XlMvlqNJG86wFGkMiA==,iv:axfS1LEKnb9uK2wze/iFTVz2z+VWjwYjMAGhbPw1CW0=,tag:qrd5skcWhjOb8PxECW1tAw==,type:str]
    env:
        - name: ENC[AES256_GCM,data:gaNCadny3uxnTm7nI1vaRA==,iv:iAmSXFt+5Lv2wpIfEB5ruLaCGAXhGw72C/ZTH4ZqZQg=,tag:UuCwYZH934HE7kmlZhp5jA==,type:str]
          value: ENC[AES256_GCM,data:Xer84/NGa1GEc3ASFNs7VmPCEg==,iv:LoAyJbplLWlqWlcT8Vigvc6hVksd5UnKHmFbxMaPEK0=,tag:7u0qVMjfj3Q0gyT+NeOjZw==,type:str]
        - name: ENC[AES256_GCM,data:KMUpI6OfAQ7LoeSCfxdh5UB3nUyT1Q==,iv:0nXh6xSjFIS0/nfFux53piA2yvxwhDD6iUaRj/wV42s=,tag:gU3XFF8nIN1if9V6BPDK3A==,type:str]
          value: ENC[AES256_GCM,data:XGRug404wq6xBv3zknx1jFvcwPRyrqVHA7In37sfjObJukYirxWgeowtVCI=,iv:2Mf4BXRI6z4/8D0VAiwJBJZzDn72/ZUJIOQPu7RNd9Y=,tag:/xVjTzp8jH6kjz54CewLuA==,type:str]
        - name: ENC[AES256_GCM,data:6SocWHw3bv/Y/13QVe0mTYUY,iv:cipEMul8EZXHzh10Ig3hYVUsu6xv50kbV47KX0Pajvo=,tag:jRUY0Cnhd9DfjNVIsnE7DQ==,type:str]
          value: ENC[AES256_GCM,data:FTG4OA==,iv:b7B5H/XP1p1TuzXFdct+CTsxNi/Qad/6iF5inMdt9Gc=,tag:m/2w1ShmuUheHc0OpcTxCQ==,type:str]
        - name: ENC[AES256_GCM,data:qPeQoNCMoPSfHw==,iv:ZUC2N0JBElznGigDE7bILVeugKsHEGMY8AJWNR6KZ1w=,tag:nd3dECDjjjNqT21rUyt6kw==,type:str]
          value: ENC[AES256_GCM,data:kClEk0huXiM=,iv:6Q1dTImHDe38ANcT9WCUS/pma8yq6Jd0qX0jA5k5G0E=,tag:TO4569Kkiy9zsrncqKmovA==,type:str]
        - name: ENC[AES256_GCM,data:2ZN/LUls5KAvxbX1vIKkxIp6qMbakec=,iv:tTgcPh7JWdhy+Tu9PYX8nAr1CXzNZfidAFoDDZVxTP8=,tag:0VAMtt8d8VqplgSQCYm0RQ==,type:str]
          value: ENC[AES256_GCM,data:elbBDCN0eZj3mbeOI/24jqWmAxrO0tSQYpsWrq4IyyGXxlG8,iv:hs70EaOsgZ33GORE9IjN+4uuOcBThpNDMjAaURLfAD4=,tag:RkizNHwg5DjbBaSHjq9hzQ==,type:str]
        - name: ENC[AES256_GCM,data:IR0QfhxRk+dpIiCdut1oyXm1DA==,iv:Tb/BeZ7H7jMs4ksjZ0BiC3DybhLu1HHgrIrUK47AlSk=,tag:AdEOmt5ZVAYMCdLU+b1XWA==,type:str]
          value: ENC[AES256_GCM,data:zYjMhqPU24iYJ8wjRWHdahTpH3eZxXyEZL7FWbzyQK8DBHUE3NaWvymlSbI=,iv:1DDn+ox1sbHHBMvr1Y/qE8UdnUihvZwmGMXzZ83c+NY=,tag:c/xy0UiR20Q1pQkT7JGVng==,type:str]
        - name: ENC[AES256_GCM,data:6gJdbAPyvLmgrgu6mtJ3,iv:/VQPxAsKJiBxXlapJK3p6LQ38fCpWHbEqFl9L/tg9ZE=,tag:pL0mad85lrWFJLswWbVBHA==,type:str]
          value: ENC[AES256_GCM,data:fyL92lOJ0dNfc8f41Q9K1xv3YDsztyzAeg4onZhXCt4UlpRUQqkzH74=,iv:X4/4KXgPkhw/egs/tBa7y+nC1pXPhw9OWgileLcxdTc=,tag:YwvOxsg8eLlligEdQtpyFw==,type:str]
        - name: ENC[AES256_GCM,data:0XFkTLKfypnSUqLy7TCn,iv:UpCKESx6WuBD55+jGt+Yvnb5JNmsAmvXLIscfi9H+ww=,tag:pBXlxuZNrm/mX9IqoJYTZg==,type:str]
          value: ENC[AES256_GCM,data:c9uQuUKbHEm07cMsTFXV89tzai4bLrGuO0sZVLfEmBX9zUGB,iv:1u+2yRptfMn+k398C1KqxgjozabpFP6tuMakziDl+C4=,tag:GRf8ZxZyFu1oz9/YomdnOA==,type:str]
        - name: ENC[AES256_GCM,data:/x1VGDClhDO1zqunswzB8MX6QA==,iv:LhBLkvOG8Zq2K7mSs8Ycs9rQObGappU9ej2TUb/T25o=,tag:VX9EH7aQ20n3oopD8vajSQ==,type:str]
          value: ENC[AES256_GCM,data:mHQmtP9wXF6YxUuqGUhwwjn5wrz8+/PTAxMDbkyF58E=,iv:tFzXmG8A2ANa+Uia95No29gtASgnEE8iy8a3wg0i4x8=,tag:RJmlVE4KsEnyg20xPCcqlg==,type:str]
        - name: ENC[AES256_GCM,data:i5bt0KoqEh5B00+T+oqCGgE=,iv:yc8YbUJ0Wh9KUm2oKs1eOoMGKF5vRbqeUsfRi37V15k=,tag:10f9PxTMCwaLhiGB6y5i7g==,type:str]
          value: ENC[AES256_GCM,data:xgkkJ1ovGqfr2CWk08tTv2mvWQ3dZSlirlIz,iv:AXiE1naP2UmpESXbtnDB+paWxLSf6sSqLHvPLrPTAZk=,tag:c3tQ2PwJg83qrhj0GjhPZg==,type:str]
        - name: ENC[AES256_GCM,data:bdIH7gyh4Q9O0/zUxodiJU23,iv:D7xqZBmoJ8K+kvb4p7UIuY8vTgd2w0ZQIy2YjB7HO38=,tag:05G1ED7/fBH/bdGpkSNg1Q==,type:str]
          value: ENC[AES256_GCM,data:XtrPql9zMcP/+lPTpjipfw8aEJxS3PiGg9D6v1LL2IA=,iv:t3NbiY/IcPLD710s3MJDR7x21M4GKr4uGWLiB2e6p58=,tag:xRBw3mUD39cYzs0I8GyKjw==,type:str]
        - name: ENC[AES256_GCM,data:27lo92Jx7YRFdKihBom6aus=,iv:BqlWMNxWbQbwRLMpevoxfTnyPQugHGh5Efg19YveDpQ=,tag:oXSkDTg6g9m5oDJdHP4wSA==,type:str]
          value: ENC[AES256_GCM,data:12Bon5Cl,iv:Jo6x+R232Lt1NjPF3QHmWvinsN2TJd9qxF6AkgQdZxU=,tag:XMQs4/b9JhWKW1A2MwPxRA==,type:str]
        - name: ENC[AES256_GCM,data:Skyv/wx8+8enPZE1f+Jnf+xc,iv:K4O6Rn0+K7q73zHf8iXCtj5SUBUI1u8saa9Wk/zjMso=,tag:Emo6FD9H9O0XZ5Lg5P8i8Q==,type:str]
          value: ENC[AES256_GCM,data:3irgTNY=,iv:HnCzYBXPBSM9Iiuxdx3p9kfOif73dzpyMTelNIGeumA=,tag:KlegFazF+f+7yhT3nR05eA==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpNjFEL2VhVHdHTHd6b2Zh
            TUZZYWZLb1dwQjlGcGtRNXBuT3p0d3pXMHdJCkpPL1Y4UzBuUk03WHdJWlhlU2dE
            V2wxenBpUFJyNlI4ZXEwZlYwWStpYTAKLS0tIDdoYk9Mamc3dGVsbzAzWkhlVFBk
            bWxqRVJDS3hpaU1seXdrbWtEVkRJVGcKNOuY067E7dBBBXtAPIs5nV22tfAtTfO2
            23Q6/59rvcsDYCxBy4PyCMytDJz6uRx953quslU0rT3zPlY/8zv8eg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T00:24:56Z"
    mac: ENC[AES256_GCM,data:DxzegQDO5Th9FRHKTo5J+DbHKDMjYkpRlUG6tT9pr7TkE+ni2/6iDG4WEFK6Vb7F6UpZUq0Ia64kwHHS/cJdsvkFyVUd/xMOJ9fCDERc9RKDM8JCx+8goDB/ra8kx532P4FdW7D2CQrUsZMGeO2s7hBqQ8Ycz7BwtJABHWvoGjw=,iv:4zH0wiq64yvXAliqC6Mrjoysi+PTTuM55+YNhOmKZu4=,tag:305NY/9Hozv3QERzvvKxYw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
