velero-ui:
    config:
        s3:
            accessKey: ENC[AES256_GCM,data:XOhVxnIdFdlpKaLulrevhi88MbW/gR7eVI4=,iv:p7ozgsA6flu1peeOi3PdNpSExlEB9jFwlfBlR5XjIac=,tag:PsQ4T0mOsn4vPN4IJfJDcw==,type:str]
            secretKey: ENC[AES256_GCM,data:F9FswDdoDxTbXQSq1j/f470iUwjnTpMOwKPfmCIknywkHe/OO4e4Fa/6OQeYj9IkFErLKhumyh9DnxZFmzeIuw==,iv:y4aTp0us4MNLu+wBLdqi3b6fsXXcHFi6rTFBBekbbwM=,tag:uVcEdRDf0g1DHAYDHSIydA==,type:str]
        auth:
            oidc:
                issuer: ENC[AES256_GCM,data:0rIKu7hJj1UGp1NtGLbUSBEVIQ8kFIySfXI=,iv:fjK5vO0j9gYezj7mzY7WBh4Nx03S3/Ib+CpuBLKaNu8=,tag:kSBJvYdMuaf9anE697x2hg==,type:str]
                name: ENC[AES256_GCM,data:CcjjfV1FZNU=,iv:46ERnBTmuqRJeKQz5ZsGXE7nwHjOZsIYAvrQNDcoFE8=,tag:zovGSk7jdwkZBldNikKu/g==,type:str]
                clientId: ENC[AES256_GCM,data:pXkxApqhQ4C8hurTec2uvK27q4mZ38Foxi8AZHFlwjOGBKLV,iv:6qchlJ5FwES9Xn33oxulunZbizYXcSlcBvTXEkx6RVc=,tag:He++D7Agczq/Pl0GJd7uVw==,type:str]
                clientSecret: ENC[AES256_GCM,data:frXbgxPVPDgNzxBh1HloHranZHbcN1RrU4Zx42M+wcY=,iv:DwrW1fm/rwN/0peJZ/k9USKRO6ZUqtuxPOTsWYVzlOc=,tag:6KRNNZy4SASDnyEEoyFdWw==,type:str]
                redirectUri: ENC[AES256_GCM,data:iSfdryqSnXJDuNR1GGwqkCUufEwUr/DKfnvkuA3oqptrtbIqvuu8n8PjBtO6mDlTlI6MGxU=,iv:PfovNcY1sTvk13jhM5GDjfWm7lNOn4pSqilG5vQJ+jg=,tag:6P0Hm2Eexiu/HwuAYkP3ag==,type:str]
    env:
        - name: ENC[AES256_GCM,data:9kBPBNqqAcIWuV0O/hL61A==,iv:KZiYCAr5N/WYe8yreO9gbb8Z/NLezWgd/gL4XCnpfRE=,tag:TGBYVV4dm86joQSssaqJRA==,type:str]
          value: ENC[AES256_GCM,data:6qSSj6odjs3NEMYB9+JftRIcFw==,iv:fl5WlPRiIuGb9CjAlPQBFflDBWGtJSkVugMrEttwsrc=,tag:v6wKHAX4xazwECqCMSFTzA==,type:str]
        - name: ENC[AES256_GCM,data:I8kG93bupTig96AdrUMe4hCYs2tl3w==,iv:/qX7g6RsGWm+kqeiabJ8kYRqISFYNWXkfUXYO3wiO9s=,tag:xxniTiviEZS6gpXjUYMvag==,type:str]
          value: ENC[AES256_GCM,data:ksiJClFnR5dAGQo6h90bI2LiPQXwVx9F41Sa/WpqZWIp+1JLDEWzxdAIP2A=,iv:q/1ulwJVv9zbLBtdIqxV8zHUDkVy8tApLjMe+hCE6dM=,tag:5g4l414BwWK/8Z+D2UU69A==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1K2tlYlpheHU5TjlzUEd1
            Rmh0Q3FxbmNWRkhPb1p5SjBqL0g4YWtESUdRCm1IQTJXVUFZNnRjUlczeFNyQ01j
            cXZoZVZhc2JybWxOL3hNc2Z0UmN2eUEKLS0tIDQxY3lLc25kMUdHc04xeVpHVllh
            U0s4Sno2TjVPTDRJSiswZUtJY3hmcUUKph28VHs4Vkl908LVgloa9zThEXERNh7J
            TGKqJFzhBxfqUmGHyR8G9tJ1GC30kc9MnS7ig+ZfUjjKPJeWaYozOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T00:17:04Z"
    mac: ENC[AES256_GCM,data:/7VsJdNFlR+/nqBOkKrTfw0cu4dPzLwYGjT+tDTfrv5W4IGRFOLWViK/Vd9XcMxAQAcOv0f719l3wHBXORS+fa7m3qN9OoWTJricEOYurJ+LT21O4IETAJY7DzLABRvMCtMhyNIO+w1HgDeAXLc5ZJgQJpTKYbiKuujELq+2FBg=,iv:GZ/OZqTLAdGOWobEmXn9hiQq9IYc0ez6GqHmMGlxjeM=,tag:82foIvg6/3dvQvNOZm9luA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
