---
velero-ui:
  image:
    repository: otwld/velero-ui
    tag: 0.10.1
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: "Velero"
      gethomepage.dev/description: "Backup Management Dashboard"
      gethomepage.dev/group: "System"
      gethomepage.dev/icon: "sh-velero.svg"
      gethomepage.dev/pod-selector: "app.kubernetes.io/name=velero-ui"
    hosts:
      - host: &host velero.mdeleon.dev
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: velero-ui-tls-cert
        hosts:
          - *host

  # Velero UI Specific Configuration
  config:
    velero:
      namespace: velero
      service: velero
      port: 8085
    s3:
      endpoint: http://garage.garage.svc.cluster.local:3900
      bucket: velero
      region: garage
      publicUrl: https://s3.mdeleon.dev
    general:
      grafanaUrl: "https://grafana.mdeleon.dev"
    auth:
      type: oidc
