---
apiVersion: v2
name: clickhouse
version: 1.0.0
description: A Helm chart for deploying the ClickHouse Cluster and Keeper Cluster
dependencies:
  - name: clickhouse-operator-helm
    repository: oci://ghcr.io/clickhouse
    version: 0.0.3
