clickhouse: null
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDeXJOVzZiSE9Ndjh0RTA3
            TmdnM2NtWWpMV0FiL1RhZnMvR0xYUjBIaXpzCjJXanliaysvOEJWdmNGbERjdXMr
            c0pzMlpKU2FweWtqSmVFUkpoSWd6TnMKLS0tIFNnelo0U3Q0b1dHaVM5SGs2QmVv
            WFZ5YlhNWUZlTGFtdDl3eWphbnJveEkK2ES1l+3l0fxt/MK62wOKgRSnag+aHiku
            Cc+srzNSvmkqTKaZ5Cop8apqMJLfAWWGIU+q8OoDmT4nPWnaIWq2IQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T00:02:06Z"
    mac: ENC[AES256_GCM,data:kMv7lyvYp6X1PqnYHcb6ZB8eFDA6S6FGCnr1nn9Do3utH2U9JuIYYKn42i8GmCgaprMaeP9FOIdrwr4DBHBXxVBsCy1C5PYSLlT/HqVvFEb0j7NDZIlKFFag8IgkbQZeBIE+PHKBxLMzWb4C/rxB9IyZ+9a4vspstiOjiDe+hyk=,iv:9sc6kA00duZfw1ez4ddahBDeZRMH1eM6cRt+BB+xYuo=,tag:Wia/X4ZAiaSZtXbxc6sb+A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
