clickhouse:
    admin:
        password: ENC[AES256_GCM,data:SXcUm1fNTqUOJzncN5AT6KIdj+JBChZ1B+vgotauqD9kJC3iTwTxMa4sOR4=,iv:/B8A6IYsqrQ5OrfVCUGP4sYGn+kDU3ixwRZ8WnYB3vc=,tag:TZ0JP51ScuezamckLXoNFg==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCSDRHNGNNQnRQTmJUcDA3
            WjJqQjljeUxKMitZeTNqSkNaWGtLYmU2Qm1JCnZuNXZaS2RBTk5MOEJpYzhLUHlM
            QktYaVR0S0g2UWorMFlIL3M2ai8vSHMKLS0tIEwwaVE1bzdoaDlTSSs5aWY4M1ZN
            clpGWERHRFhtMWF3MFpZaEMza2xPN0UKUKb4NoJXRBt3alpsY7oOD1qi+j00b70t
            Jhz+rJ54sKZII4vV0IlFfen3q+e2ipL+eGPcglxaqycBRpiW18kVVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T23:51:45Z"
    mac: ENC[AES256_GCM,data:2I76jZ6Mg4/xAWFyrAJHUik1yZsEyRT0/yuKmFlDJH/Bo14Q4B+nKBDHjERWDhoZLgcqazOdtrDCQ+nv8Y6426SAMaa6lbvWwqx1kznTS3uxCUcSwnZ/GZ8mqGm9Va9q4bjPsgAHd8lcRCveidgmpepeAyE16MbmE2YR5EVhHnk=,iv:WjZPIm8uNvSWdOmg8P/iJU+9OBkMFVcbljuoWVygy6I=,tag:dfQw/eACcdE5f8l2zlK1sw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
