app-template:
    controllers:
        album-creator:
            containers:
                main:
                    env:
                        API_URL: ENC[AES256_GCM,data:gC5mS2J0mXx79abBTuEPRAAqKVErBGm2LFlf5NZofMWnB71nSCdZdA==,iv:o/nXcE+Z7jXIc2oCaC2A5ujn7TSmq3P+aEy9u+6WcbM=,tag:RGET18JYqwCp5RD7LZRl+w==,type:str]
                        API_KEY: ENC[AES256_GCM,data:/Iambdyc4h7NKdl1wbhOA5uo8SwoJww6qLxEmTJ7iwUTDck0OM8C/6bp,iv:eCL8zbHRSuNlPnRVrRf01dK2XrgYtu127+uVrA9f7vA=,tag:Uowrk7ul23DrliAW1ZZxZA==,type:str]
                        ROOT_PATH: ENC[AES256_GCM,data:GP5K8ioqQgzoAUqayCDNhV4=,iv:N/bwPrD19CT64boIGzZwRenMw5Z2z4bV0XBA0Apdnxc=,tag:wN4LLrWecsaC0j60n5A0hg==,type:str]
                        CRON_EXPRESSION: ENC[AES256_GCM,data:+ophm3DAcpiB,iv:wNMRIueaagnob8a/WNyxLDRls6atw2H9Qu37MJkgqfQ=,tag:H87j67tg5MVPeGjWCcU2bQ==,type:str]
                        TZ: ENC[AES256_GCM,data:cPhtRXZdgM2tyLsGyl5FbKXG2Q==,iv:64GbKL7Lwwx+BlAzC/gUsd+/6JE4xemIh/FJFHwtD6U=,tag:Vpwgo1kjBmGuKnqMeY9OXg==,type:str]
                        ALBUM_LEVELS: ENC[AES256_GCM,data:Hw==,iv:Vm5EJM/vup+xBrx4aIh4j3WqKIp9jHUIdMBojjEnchs=,tag:fqXj1JSY+vjyCoYGwNxDHQ==,type:str]
                        RUN_IMMEDIATELY: ENC[AES256_GCM,data:Ekhk+A==,iv:mO4E+FwJ9oTBmDU+ir2pUaSsWZRekMZWppzzN/W8AdQ=,tag:CcGa3MzbqsTGMQdxQn48wQ==,type:str]
                        ALBUM_SEPARATOR: ENC[AES256_GCM,data:c48B,iv:Ggngm29naGummpMeZ7ZqxkOWTQZO0vSV382kyo+2sR4=,tag:vR9AWyJmVzOVObXJmCYsJg==,type:str]
immich:
    controllers:
        main:
            containers:
                main:
                    env:
                        TZ: ENC[AES256_GCM,data:0+gFN0fCOK8OlUs8mhs7bv1m1w==,iv:wnoDVFj+3diJ5KqeY8HIME5ft6weEkQgmCkEv1i9bdw=,tag:dnNxzB4BlajX0PHhnreTew==,type:str]
                        DB_HOSTNAME:
                            valueFrom:
                                secretKeyRef:
                                    name: ENC[AES256_GCM,data:XKAtdXdgDxvry3zp20h0folUvQ==,iv:TGVv2twt2gnPFtKWv0aQf/zbh+FuJY3Bl9I0iILenyQ=,tag:WizEh8yAIitX8pnomRrBkQ==,type:str]
                                    key: ENC[AES256_GCM,data:ykHzYg==,iv:aHRNEvHXvTV8DuMan6lUqALX6IbZY/J2I9hYBD6mVxA=,tag:LyKELRE4r0XlJuWRjJAAqw==,type:str]
                        DB_USERNAME:
                            valueFrom:
                                secretKeyRef:
                                    name: ENC[AES256_GCM,data:L5rbl5yiGTJotRYblRU51iy0Og==,iv:uf2kp0chEiCHnbvnHj6Xt/YithllBvZ8cMFJ8P9KLXA=,tag:vrSmkPBAd62Vr8QGWMI5BQ==,type:str]
                                    key: ENC[AES256_GCM,data:j82mww==,iv:a/+O5TC+0fvuUam/BxiSOBA0M7LCUt/NMY+Nqonpg8M=,tag:y5aH42o0mR4EQGfhTETsuw==,type:str]
                        DB_PASSWORD:
                            valueFrom:
                                secretKeyRef:
                                    name: ENC[AES256_GCM,data:dE+yF8+jOMhiomWvS+LtdF8KVQ==,iv:UFgg7LberjI7k1V/aXibqPHinmBNc8FA9dui5Ziqz3s=,tag:W3/duRq0WS12JRfFNrOh8A==,type:str]
                                    key: ENC[AES256_GCM,data:95CRL/pjmGw=,iv:hTjSBqut9n2pVMrhHhacSXWLafUi8WQxc9kINtQ5vR8=,tag:T/65ZSQl65UOvkDlBS5bJg==,type:str]
                        DB_DATABASE_NAME:
                            valueFrom:
                                secretKeyRef:
                                    name: ENC[AES256_GCM,data:hUQMUnTK4aQsYC+fOTkbJL7WGQ==,iv:uaBfCVTA1ko1B8ftFsfWt++p/TZAGJJoyQKodMgEC0s=,tag:d+4hAVBV4XTeqEBjOGffIA==,type:str]
                                    key: ENC[AES256_GCM,data:2/+D0S/5,iv:waokwLdOrYr6GfCDN0a73EaJWBoNgpKaikuBbwNKlcY=,tag:Fww4zCt9lEzImLcmkPETPA==,type:str]
    immich:
        configuration:
            server:
                externalDomain: ENC[AES256_GCM,data:coe3M/s4QdZUAdxotzyZk3OiEXUzYZLrVWg=,iv:XvOFBbRoHqKK65A1mh78KItWJbiHHAekYPJnI1glsOQ=,tag:+UjUhb2c//Kgcao+u5Lw2g==,type:str]
                publicUsers: ENC[AES256_GCM,data:6D2w3dg=,iv:PoRvQQCPM7v9j7pC9ONi4Mpaqb03u+9bSMWJi8c/fZ0=,tag:g6+l1xp5CopHtasUqco/Sg==,type:bool]
            passwordLogin:
                enabled: ENC[AES256_GCM,data:6Cvlzw==,iv:n88vaW4/1ZsAsOtO9f1mULcLIfcfteIvRBq5uBEX0ZE=,tag:cCLRn9+8iWEH7R4Rww4JTQ==,type:bool]
            storageTemplate:
                enabled: ENC[AES256_GCM,data:W1mXvw==,iv:iiwEhz+LF0eg80lGgDqeijYRHyXuLZG3YaACrRNY/Do=,tag:FWF/17hfxIPAhFrx6MF4ww==,type:bool]
                template: ENC[AES256_GCM,data:gBCeYeXAC1UB+CbA4xmDu2c2yFegWYrk8StpaV9KMjNwUaIxpd8=,iv:cvOvYoTCY1G8LagU32wCIHdTRffxr4d6JyFQVTFmUWo=,tag:wVMoViBuyk3iYgImlm7MVw==,type:str]
            oauth:
                enabled: ENC[AES256_GCM,data:2IDBwQ==,iv:s4tqQJc16mGkN7sOg10ZMwG3Dv5ViRQbYyGQbZDYH6A=,tag:/bISwAM2xcFXpllv3Gp61g==,type:bool]
                issuerUrl: ENC[AES256_GCM,data:VmxjfXJxEc14p48ks3c0F2QYHWgQ1jfb+0eCv7xj1UMX+a4pk2we+krs+y7yz3gUpMOVs+09yssgQC0=,iv:U0QMlxzGXrua2Gnqk8ZODgpGvlpcO08tOrMpzKXrZH0=,tag:XHZjzqeggmwSJWaGIYgzSQ==,type:str]
                autoRegister: ENC[AES256_GCM,data:bdkPZw==,iv:F7bQuiv2GdF0vZHb1/HpgBI0ej3sQZ9+jYbpaPuvz7A=,tag:w5vkwTSd8qQAxTVfAfdzPQ==,type:bool]
                clientId: ENC[AES256_GCM,data:T41dYZF81kVpDqxP+EPQHdqdjWjTfwRFG2BRldARZPylp1/5,iv:7Nv+Palo5ZO3EA+qVR702Z/ngshzhOJoakiZBNrigWI=,tag:e/EBUqWBdaUhlh5xchxqoQ==,type:str]
                clientSecret: ENC[AES256_GCM,data:x1ydrBW3kJKK2tRiTHnbh6ngaTnXkBvbx+vzp92RtZM=,iv:PF/im83vpva7D8Xks5RHClmWT5UjCkdNXfJ/ktoxHOs=,tag:1S41PbVgPgkSGfJp8SEO6g==,type:str]
                storageLabelClaim: ENC[AES256_GCM,data:UvT1DYIhHA8zpNKReTcqT1dk,iv:dN10+5EdAx42R15TyZu7103n3kZ2mEaVUvVEoD9SnBY=,tag:fFVOfIJemn3RePS9Uxh0vA==,type:str]
                buttonText: ENC[AES256_GCM,data:boAPUH5diYUCZPlILZOa84U9C60=,iv:yDpym3jOK9DRIiWAjjgEQpChI3nHlxulDctxgMEvAe8=,tag:q0yoMk0KIZ5oM4YzBMGj/A==,type:str]
            trash:
                enabled: ENC[AES256_GCM,data:GCpdTw==,iv:9CqXWQmrPAZgNc2NO6RyGSjX/dkOtcNfxKw5mGUP3oA=,tag:NwjnxZqUHnIJMGxNtoJl6A==,type:bool]
                days: ENC[AES256_GCM,data:Q4o=,iv:Bmk+zy8UQQMFIEc2C+Gs073564YbU3z/Y0KUaM37bbQ=,tag:AOlZrFlo8PVZzBEWZeQeIA==,type:int]
            machineLearning:
                clip:
                    modelName: ENC[AES256_GCM,data:lC1WcG5bKRJi0Aa78gTBhg==,iv:NVLc3hNnASJDjvkbLKV3U74WR+kAJV5TgPMAiiTHx4Q=,tag:fd5Qxcypt40Q+ZLTMe48gQ==,type:str]
        persistence:
            #ENC[AES256_GCM,data:VSTdHDoFd5ZpcxBUUK5GSrJueR4UXF1TSjUBxtatp6HBQe1UcXvfurfXQC9rqF8hd0dbG5PoIW5PoAMPBuVeGmJIORk=,iv:lbzbDQskMSYrV39V+XIFDqRTGTyg+47PXBXJ4+9TCAU=,tag:nc8qKaMRXpNDoTfbeNd4dg==,type:comment]
            library:
                #ENC[AES256_GCM,data:9bZ3BO0VQacIELcQ3dhxxccji/b3qCxuxOLcIvGdqK9ioFDvIZaNfRQJFw/+1hMRihpOqrUF3+H6hS7RQG7VprL4ZcqPUgMmpg==,iv:LnHdzyq712zjKgyunclWWA/+q+AMnlfTVQCtzVo7frQ=,tag:GSc7po/EoDD085rgeK2yjA==,type:comment]
                #ENC[AES256_GCM,data:mgb177gm3nIJb08hMNGhz/kiO/dVuU/Kpi18CP++A1aND29SZrwLE3dY3Q==,iv:gvUExlzryJP9w8nWTiqMhm6TmDMjOBVoeF+/W5KGGCw=,tag:RB6461jJuv97SfRANhv9kg==,type:comment]
                existingClaim: ENC[AES256_GCM,data:pO2Ssd/Xiw==,iv:BcPtl/VvV1EgjKkLC0UCzRSHdWnxkY5Tdq/p5WOYzZU=,tag:iBl1oM6cWiUB3QJCj2wCjA==,type:str]
    server:
        ingress:
            main:
                enabled: ENC[AES256_GCM,data:b3Pn2Q==,iv:3vRQNZ4dHRLov40uBh3VaD1s1xbTrgNoAHgrBCMzuYs=,tag:97UNHys5D0y8rlVxq4v0lQ==,type:bool]
                annotations:
                    cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:dNffA5sIkBeUhSkpyepYiw==,iv:NRcDMenbB6z/FshjIcXS1apr5QyZwkoGm7g8/YrhF5s=,tag:tmRqLHwu43DYg3SYnH9uPQ==,type:str]
                    gethomepage.dev/name: ENC[AES256_GCM,data:SbEO7PK6,iv:eV8rQy24Mz0t4aTuo1dj47B0SDsVMF9IAatEq1/vFq4=,tag:LpvVSQ5xEZGLUpUEkWRU8g==,type:str]
                    gethomepage.dev/description: ENC[AES256_GCM,data:CveXvbKhsM7ovSy9rkHhacyLJHWAnQ==,iv:6YlqtisbnegivT7HCBUCo2zjAdTUwkZy2cn6nb1w+x0=,tag:lc+Hf3CNnlcWUp8gEKC5DA==,type:str]
                    gethomepage.dev/enabled: ENC[AES256_GCM,data:TSUOgw==,iv:YeU41pn/Wzrx1w/jwr4GhyvW6mPZIDai3UISav3n6bI=,tag:jE79oa+qPl4SSATdhU6z0Q==,type:str]
                    gethomepage.dev/group: ENC[AES256_GCM,data:+K2FFknsRMMy,iv:kQefnyoA/PAJb1GDx0zxUMQ+JNJQuj/NeNWEjWfJGcs=,tag:TTq/EN1lej86efASPK4IhQ==,type:str]
                    gethomepage.dev/icon: ENC[AES256_GCM,data:c2rf6/gC/zHD1tTvuQ==,iv:pULC9YohFa5p0kTMC62DMujq+JR1nuMxjMIWzEM8hXo=,tag:WQ2smvafIpz1kZTSScMG6w==,type:str]
                    gethomepage.dev/pod-selector: ""
                    gethomepage.dev/weight: ENC[AES256_GCM,data:lQ==,iv:QevFGD4cMtju/p4MtNkz7p0MLQCCGZkjuvZmaUPtWrk=,tag:RBl7r9no4Eb982uBZDBNKA==,type:str]
                    gethomepage.dev/widget.type: ENC[AES256_GCM,data:Niudt3Q6,iv:EVB5hWJLy39/sxvZ+YJe4vs36HhNt8SAp67Se+Q449g=,tag:TUKDMAaI3sABI8Fprl8CxA==,type:str]
                    gethomepage.dev/widget.url: ENC[AES256_GCM,data:gNh244gze0zdelG+ubJxT1b0z/OHFTbjYlFpfKQ=,iv:zLDg5ZmjFotT1BZsNrVghLM/cZ79q9OAxN/jJolf0ac=,tag:p5MMsh4U30HmNovIBHaIsA==,type:str]
                    gethomepage.dev/widget.key: ENC[AES256_GCM,data:l/nRQ97rQs+GmqkLfSqfh8upASq+aGx7BHIgdHG39yrV39yx3VAb1NZm,iv:Cp9mu8LDAlQtH3sqD4Sq8Des2bKYFj3GhhLMnEUyeLs=,tag:Fo4rIRA80pUJFxsdXHv45g==,type:str]
                    gethomepage.dev/widget.version: ENC[AES256_GCM,data:Wg==,iv:6vXI/juXZxYEk0gkR3PRLcb34UK6D0SaKoaVpo6PcmE=,tag:vqFTzH91bDJ8bPIzFpvzbA==,type:str]
                hosts:
                    - host: ENC[AES256_GCM,data:bZh+iw1MHwi9JXy6SMnfPn9y,iv:NIEN0hyYirUApb+UTcgPi0yyx+hBsHHSyTypeVVYzic=,tag:iRJxA21Lrtb/SEsAAbqRBQ==,type:str]
                      paths:
                        - path: ENC[AES256_GCM,data:NQ==,iv:+Iyk2JrVNf12x9fiJxrgdQgU0kAt9ttr4EleWYh1V3c=,tag:Md8ZulYoFeB3r/ED9bt2JQ==,type:str]
                          service:
                            identifier: ENC[AES256_GCM,data:kSnnFw==,iv:4Ibo/5+fTBIbiJ/leewT3y16ddUO11QYfwEPv7lOwt0=,tag:YeA2Y7xD3pBmWmKoTdGDvA==,type:str]
                tls:
                    - secretName: ENC[AES256_GCM,data:EnHgrdIzrN6qYK+nsVC+,iv:mK1SjffNm2wmrpjQYRZ/G5SoXhYCZcseiFUXCqa06S8=,tag:1Sd/sY4n1MDhUj5YKLPOPw==,type:str]
                      hosts:
                        - ENC[AES256_GCM,data:4CLo8Lu+BzGtSmetYOUccVIR,iv:Y9C0KO2d1BTP4lQBG6CAH2re2x+6BsydqidNB7T+Jz4=,tag:48YKnpjSEuPvoKsx/jOcMw==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5akp2QzNmM3VjZXN1QnVu
            a2hLdlRuajcwMmsrWjJ5T2hZVzBFL3Iyd3c4CjgvOWswSzFjZ0lSeVdxOG1MWXFx
            dlhZcE9yR0lKV3QvYUhDYk4rdFIrZ00KLS0tIFB0NC9DRTF6YUNJVjYycXVwTTUy
            dUdWVzVGcmNiVE0vcFgxNUFwb2NHQU0KkQt+d3jIMVgj4TvA5pu1X8pDbTeih5KS
            KJ4eqTqfTMZ6VdoPGz1dWRvYojlbrGa4a6QQMSRnyWrefI5refdI4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-29T21:29:01Z"
    mac: ENC[AES256_GCM,data:ysFyEgnlxG3C24usegJze0c5M+IIJseaAls6KH1KTvDRIyStyxcb/4QG9rlcx9tPzNyh8Y68aJeo9KfzZZGmMwHjoGlGcCHYYzaTEL6nclU2TAMouQsQFUgulbeXvzFwpbmFBqH0EB+oSxpcWGJqmy+ZlVJ3Fv7c85P/5etNx8A=,iv:MFzGgJX113sdTNA/l2T+naH2OrwbE4ZwTLqZVDJ/bI8=,tag:1vflrJUPAy5ZbwabvetHAA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
