app-template:
    controllers:
        album-creator:
            containers:
                main:
                    env:
                        API_URL: ENC[AES256_GCM,data:RHS0i7CiiTHDedsNjNhBSb4y2NatOwY3sqlkYOQpM9IcMsW+s6/1Ow==,iv:MVYQpBgJ6auv8tpPNbtYNUo30rZiGMkM2g38OIgxCno=,tag:G+RyiyezARlYTgaB1nsgBw==,type:str]
                        API_KEY: ENC[AES256_GCM,data:yX1Mm049nQglbD2cVmgCGB4GQdh2CiavQthJaZLTA+M4K5JwlDkfRfbM,iv:/EPziEkUrlSATmo0XsaZnzIfR3TuheWzdibjLKzmX8k=,tag:+69HOcoqQQDFIhidAowL4Q==,type:str]
                        ROOT_PATH: ENC[AES256_GCM,data:2pk4OvfQRdT/IHnmtBHJe1c=,iv:auhKuWVer4TQazNkzx/GwiTccg6ldq5emIQ/KaYsZLA=,tag:Iii7BvUsSjHOuGR1z/83Ng==,type:str]
                        CRON_EXPRESSION: ENC[AES256_GCM,data:K6GQQ1RiXVYu,iv:zx+CEVrxaWGDVd5If4Vfm5MQVTXfYhdBg1LEilKymjE=,tag:l94PGN6L7iPU3pNe57MJCw==,type:str]
                        TZ: ENC[AES256_GCM,data:1xttNgx4aIvxa+746d430HNYeA==,iv:bQ3IzbAxuVXSPETXi7DwNu48+RiHcaDVX2dBy03f9gs=,tag:4qRvn1fSmq2KffV2blGN8g==,type:str]
                        ALBUM_LEVELS: ENC[AES256_GCM,data:gA==,iv:LXi6226nohRoOuRcRpw8V6lIRzl4n8rovLd3kM+CYDs=,tag:ensJ2iWRp+GX4ltLnyRNfw==,type:str]
                        RUN_IMMEDIATELY: ENC[AES256_GCM,data:y8bK8A==,iv:Blmxz/fWwgoBXYTUTDNdqOmOf9AYUCtsH6MLHKMc9Ek=,tag:Z3uz/8DgXXapx5PFmeg0JA==,type:str]
                        ALBUM_SEPARATOR: ENC[AES256_GCM,data:kCJ/,iv:Py4JtEYT/20gDg2AkaHLBDwNj5cJvKydpY5vfbaeWTA=,tag:Y7B+Xu/MtZB6CLVK0ZmG/w==,type:str]
immich:
    controllers:
        main:
            containers:
                main:
                    env:
                        TZ: ENC[AES256_GCM,data:URxxxZMR8vkaHlnO6FRNMfEnlw==,iv:ALUYt6zWzRAyUHCbIaZKFOq5eSMM1r2gk4yZhbgSfUY=,tag:PTdggKtjE0Jiu7/94CAAQg==,type:str]
                        DB_HOSTNAME:
                            valueFrom:
                                secretKeyRef:
                                    name: ENC[AES256_GCM,data:Vs7e13nE7sMXIqAlIZ/osF+1WA==,iv:PfjSPIQv1JPUvBhaSdmfU2xlMwhfdOXV4tlYQQ7Hfsg=,tag:8810RYQBWHaOIwZd4yex/Q==,type:str]
                                    key: ENC[AES256_GCM,data:U3bnlA==,iv:xHx4bt39flrFjh/iVbCIURwk4d+JznSVC7m66WdcVIY=,tag:BSJakNfNinHyuEyoy7pTUQ==,type:str]
                        DB_USERNAME:
                            valueFrom:
                                secretKeyRef:
                                    name: ENC[AES256_GCM,data:mA8gR288DAHxk/JgzQ4clg4R5Q==,iv:cljRlEEuygzTkixPoyUaEoMmMFmj48iXXzaxhBtI4hw=,tag:4qj6XDRii6xOgu1uo45PHw==,type:str]
                                    key: ENC[AES256_GCM,data:zui5Gw==,iv:ZCwlAe/fQM5UIt2catXtH8mMQ9ljIrqMOFiS/BYONzs=,tag:PKLlkQqv6C2NAXWzCMNzZA==,type:str]
                        DB_PASSWORD:
                            valueFrom:
                                secretKeyRef:
                                    name: ENC[AES256_GCM,data:ZoC2y+6kgBASF81UNz0KePF1dw==,iv:OKErDhLzYy6LNV5qod1OZyD3oMIT2H5U2W35N1nH6h8=,tag:ZyN459vd3/zgd9jtZsXhcg==,type:str]
                                    key: ENC[AES256_GCM,data:b8haAsDJ6W8=,iv:V/WXTCE3Ae2mXILWK+psMOV+LqbW72kZk7VaOoxA2ks=,tag:Q3NzWdNsBFntKzCUTT6VNg==,type:str]
                        DB_DATABASE_NAME:
                            valueFrom:
                                secretKeyRef:
                                    name: ENC[AES256_GCM,data:DICa0EzstCc9J0yZ9HSjw2HAyQ==,iv:6VZFX3D55M3zfiQNoTvd6UAj/5Xc/XI4XUbLwF1a6ug=,tag:osQwcpZBKnmQcpktCa5h+g==,type:str]
                                    key: ENC[AES256_GCM,data:ScLE819o,iv:Ce41wOl4KKiHoVALZ0X99qlC5bhXSNYiDF31woVP58Q=,tag:A4hQQfSk7nyl04y0Pgr/ZQ==,type:str]
    immich:
        configuration:
            server:
                externalDomain: ENC[AES256_GCM,data:nuggkRagQGjB5EI9414mUC3x9t0/PCrqfKQ=,iv:tZEaLH7gO492hA2ZivfAm+mPRRGm52BiC5snYbJupA0=,tag:rOwkE6lTcYsOq9y+TlI0uw==,type:str]
                publicUsers: ENC[AES256_GCM,data:6yEPlA==,iv:LVDR+SSYHJQDmR0skvc1fHN3p8pBpHbM/pCw5wSRXhk=,tag:ZIO4ePysNKqMW3IRs45z3g==,type:bool]
            passwordLogin:
                enabled: ENC[AES256_GCM,data:Brfa2g==,iv:LUQa185jNbgGM/gvhoVQ3t6l34cAI7bBeH5Ko03LwSE=,tag:bVabcOaV06MUTrvWbsyGPw==,type:bool]
            storageTemplate:
                enabled: ENC[AES256_GCM,data:8IzUrA==,iv:6Zwe1PKWYR45KfnoqepGS4CvmMNsSh6VlGhhqyucORo=,tag:QrsLzjb0fJv/6LWblrAgbQ==,type:bool]
                template: ENC[AES256_GCM,data:0jEt6Arv82vhDxvQW0Vj0kROUTHGxGhu9qhJoAzMAHEY,iv:rqGlXgOegz2j9jiYBMGGvDGikO5ilApsejI5mW4NnQ4=,tag:Ikewql/fKwZpMhwi+tcZrg==,type:str]
            oauth:
                enabled: ENC[AES256_GCM,data:JcDN1A==,iv:dqXaYcl+GkdNU4JMjQOGeP3JrlQY4u7XdUjbhvqYEoo=,tag:Xix77j2sSbvNTE6pZEcMtA==,type:bool]
                issuerUrl: ENC[AES256_GCM,data:Izz5bnOCbgddM5koLlGsOcsrjD8E1GEmcEK8/JCAJt7513fWIZzm+whoNEd7LhNp/K7IVBLIgo97w7Q=,iv:JUrbGqDJjYMPgZVW5lij0ozUUWv6gtHVCc8kctHrGCA=,tag:pK7+dzc5BAJMfyBbERtUlA==,type:str]
                autoRegister: ENC[AES256_GCM,data:bANx9A==,iv:a3iwrSUi3rMD+cqth2ZZfH7bg1bnfMevVK7YjsmMyXg=,tag:3ntefZdSVC9iaRuZIpr26A==,type:bool]
                clientId: ENC[AES256_GCM,data:g5T3b8mcr/yfSdjJKGX8t35R6cNhoAbFrSwtEP/3rSwo2OPo,iv:3hPIpfqzPboAcrw9J1gxYDQxhiS/Q1uiywDO0Ai80p4=,tag:z//MrSgkPJtOGhDfIuCpag==,type:str]
                clientSecret: ENC[AES256_GCM,data:pyh+RTOYqMMtuCm8N3kVMuNb38MiYxQyCDYHQNLms1A=,iv:V3+qKTtvg5/tA2vQGX30qAHoVNiAvPEu5uxAIsNfnik=,tag:Y/zAkl3RMYZVgOh1zjeoag==,type:str]
                storageLabelClaim: ENC[AES256_GCM,data:2XHTHxLc/Jk3k6A2cj5yppE+,iv:8QCwzC/WI4p5rFoHiTVUVtrtZeXXllj3tqRxrsPcrv4=,tag:uBhLSi760LNVXD401eCorw==,type:str]
                buttonText: ENC[AES256_GCM,data:aUU1Z9PqKRDnj0sdS3YA6Aj4srg=,iv:xvXTqjVrntAMrIFhOJu9xEpvZTnpbSi+AmHBxhQGU9E=,tag:4bB+OCsluyoTfEisbMCsKQ==,type:str]
            trash:
                enabled: ENC[AES256_GCM,data:mSXHnw==,iv:LzchGWQqDppZikwB8FLxKfnwKpQjwrxQW9ZunzVpMGo=,tag:qm4F75YKC3EIcWWf0cqEEg==,type:bool]
                days: ENC[AES256_GCM,data:KWQ=,iv:cVVDfdr6RtDsKZ4hL/Rq4oa/ho9q1TwNUy7FBqabdlQ=,tag:kL+jpFl7jNpFlxM0YfgVgw==,type:int]
            machineLearning:
                clip:
                    modelName: ENC[AES256_GCM,data:sDvnJ6Bpezxtknn0kizwwg==,iv:E3bQEY4sk1PMTqL4x6aaTOi8ydkxmNeaDN86irKlmNw=,tag:BHBtYdC/Rqj0LDtIzV5nkQ==,type:str]
            job:
                thumbnailGeneration:
                    concurrency: ENC[AES256_GCM,data:Cw==,iv:X+su/GccURZq2AH3j32xzBrRWZ2v1HFIRUtgiVBDXlo=,tag:f4rp4voa4mEe+SbTiZp5qg==,type:int]
                faceDetection:
                    concurrency: ENC[AES256_GCM,data:GA==,iv:FTybxh/DFcTGn8WRZXNOVZfQ37mr//XHzmbv/EAx0Ss=,tag:x5dysSgvgOt9f+oxd71t/Q==,type:int]
                ocr:
                    #ENC[AES256_GCM,data:fg==,iv:88a9Cxmn1SIetmvH/EGMtQ+c5c1klW9dmnUiC9om31M=,tag:we76iHYsq/jnr/ZEqXqyPQ==,type:comment]
                    concurrency: ENC[AES256_GCM,data:mQ==,iv:AC8mrpVLxL5yAna4v5AR+lCjYaaoVhAADc+21KfUnN4=,tag:vNKbPT6kXtpONPf53QVQIg==,type:int]
                smartSearch:
                    concurrency: ENC[AES256_GCM,data:RQ==,iv:7QnZFh7NaU/jPrMq7J9mRLTy2UExqDc7ARBeL5jGez0=,tag:GMyoaIDoF0grRM4MyFqJZw==,type:int]
        persistence:
            #ENC[AES256_GCM,data:TqlL9FdGukcpO8XwK1dJtABPNiKwSSEIXL/I/cMwlUlR7AyKoEKTbhzgp63oPXzMriThz4DjeLKlLfdrEavHebrDsZM=,iv:4l34zNyhzpdwcb+K+vsPNAvH9lJNLEpUy9N3qJHyS/k=,tag:00i+IkeA4B7aZ+Jv1zxDKg==,type:comment]
            library:
                #ENC[AES256_GCM,data:eR0fPTtNq7oJzIals0xyWHrbaJaqgnmnTP6M996hwNnaTV9VUH5lleIoQMbUtSWNW0qqBCUabzWgV6gIHSCWHBG9RIrkvkN95g==,iv:kxEUMKf02MLO6h6MRpzgjfnw0b2SXccisLf/SUVxZqU=,tag:z2fCVU49+6b8TQqrVqQJFg==,type:comment]
                #ENC[AES256_GCM,data:ygQDKsQJ+51tvTVy8gHSQUCSCbAbzl6mBEQG71Xi1RbyrXEAkPDJgCJqUA==,iv:T6+vFqi1z5lbkVc09wsF9+D+dqznIYrtklQBtNn4sFA=,tag:Ivy1z3K9++zPk0BNeMbk3A==,type:comment]
                existingClaim: ENC[AES256_GCM,data:MH1ijqmI2Q==,iv:xbamFuhsA3+2UIr68AOHwR3mdWVrAt6A9136oZjKbrw=,tag:Om23xkhgxn8J2bGejRv6lw==,type:str]
    server:
        ingress:
            main:
                enabled: ENC[AES256_GCM,data:N3LyYA==,iv:ec8xb3jGYiakzWXk/hd2UNyMdBGNsT0b0+meJAVw8+I=,tag:4u9IVz3E7wqxoyXcbQKnWg==,type:bool]
                annotations:
                    cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:PG0FpR8MVyhFBAzzT3jYcg==,iv:+IrlkHv+HfrsIDSHHZWr61EZ5HCr+HkpigRt7WGtURE=,tag:OdMJHlVlPRas2kJ5TobnAA==,type:str]
                    gethomepage.dev/name: ENC[AES256_GCM,data:3BzX4VVL,iv:AvrKTOsKAdlMCz/MXOjNZBQUbzURYkHxMdwE1pzafqw=,tag:nL1hITw2cAOFD6Ww37pE4w==,type:str]
                    gethomepage.dev/description: ENC[AES256_GCM,data:/KYW/INRTE6lBuf5Rd/8HLlkA7VBTw==,iv:wdAHEVZ1KZMKDRTtoY+O+gZtdPH+wq6R4W3DuWRKivI=,tag:Dbf7KPmG7/rfxSf+ovDjDg==,type:str]
                    gethomepage.dev/enabled: ENC[AES256_GCM,data:XaO09w==,iv:/J3WJheT1TnThjNRbGQBLgR3tJxSvQ5akkrEGLrK+aY=,tag:sWffi4dYxIoEXV1f/nvg9g==,type:str]
                    gethomepage.dev/group: ENC[AES256_GCM,data:uXtHKfmSGwDp,iv:aCP2NU6a3EZPmARGqic3AFHQpZpJQFCcBio2/mRmgTE=,tag:0U2NLjoTKHpzMEAkseypaQ==,type:str]
                    gethomepage.dev/icon: ENC[AES256_GCM,data:KmxRwe1DyAm7Ys0fNw==,iv:S9LE4zFY7orRt76sTJc061LhL/pFT47fyb+NtOlBzwA=,tag:pEYUNGl2uBIyFiBt9mR5DA==,type:str]
                    gethomepage.dev/pod-selector: ""
                    gethomepage.dev/weight: ENC[AES256_GCM,data:7w==,iv:uYMGzBfuLhXpIoaerVyupz6kOb/CusuFWHPzHbMFKM8=,tag:ZQLJetIzOQMMus1rD9JRLw==,type:str]
                    gethomepage.dev/widget.type: ENC[AES256_GCM,data:D8ncZtTo,iv:XNmXFN50SPrVatbfkNWzsavRKbIA8EEaFwDPn8ebXn4=,tag:SeAyed4mW9aXz5GuUq99Bg==,type:str]
                    gethomepage.dev/widget.url: ENC[AES256_GCM,data:AnZl9iiZRXdCr0Wm+x7KVttJWiTQymJH5macpunloyx1m24H,iv:Y2vlgJPxXB5c20O4Os6tI7drqS61Hsvx5AZxnWTvsSs=,tag:Bh3DoH70zsiwOEASb7Jt4w==,type:str]
                    gethomepage.dev/widget.key: ENC[AES256_GCM,data:SCNz3g0X+520umUbgtJfmPYfThROQ8ne0ynNErynXmZZOhMOSIItZa2N,iv:sGmEJi1gGwMB7JiANMk2szGZlanqk+jxqQdgD72sg2I=,tag:uijm/7jkevsEm39pFpl6ow==,type:str]
                    gethomepage.dev/widget.version: ENC[AES256_GCM,data:dw==,iv:6MyXP8R+ttb6M35zFNumy15xKACEgqr/uJUGFY/Bojo=,tag:9VWBETz15lmlMjup3s3p6Q==,type:str]
                    traefik.ingress.kubernetes.io/router.middlewares: ENC[AES256_GCM,data:SqYgt25ci+64Ny8okF3s5SwNmPIyymyBCLnXOUIgjfCoIaukKupdSRY=,iv:HqTexRyCjq1A4TTDwQmOzIMtZGW6cbz0pYEg9xgUkbA=,tag:CXpnEUxJcJAJhnGbMsqd+w==,type:str]
                hosts:
                    - host: ENC[AES256_GCM,data:63mP5Xs826pEXlJmXMZysAMi,iv:+cQ7Csw9w0OwJqLVnM9artMHdsAUv/huPL76pHPskRs=,tag:lbKuyleQ4PuLdiRcHSY7mQ==,type:str]
                      paths:
                        - path: ENC[AES256_GCM,data:3w==,iv:80NeLUGnKocgjTs08bZ2judcQMroZGU7E9UYuVHDmGU=,tag:U8n5YeYA52F33g2haQZaLA==,type:str]
                          service:
                            identifier: ENC[AES256_GCM,data:hpAnXQ==,iv:MioyXgagywfEiCHSzaeBQEWQjOu1RsE2G2il6AY35ZE=,tag:uwyc6TL4YuRNs0b0x/WDew==,type:str]
                tls:
                    - secretName: ENC[AES256_GCM,data:stsMRGR5P/w8w4uRCnKp,iv:9l/prH6kAOhLvBSK/Q5PMd6nLS1Cd4RZBQEam+PBNhM=,tag:DAGG5XaqBYJpvjSBg5WoMA==,type:str]
                      hosts:
                        - ENC[AES256_GCM,data:yCilBB/+Cjcjdfi912w/u7Yb,iv:nBv3P56BpoUL48WoK62LZNPgQszG6mf9UXWUPssKpIw=,tag:u1BNSTfAJDU65c86U6vCUQ==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZVNONzZadkVaS2JMSG5C
            VVoxM0J3UmNVWkFxakd3K2JlQkNVUkZjcGhBCktGL08xM0dFemJSZWk2SXRZVUdJ
            SnNvZ2g1VTNvOTNEZWozOTgxTjQzdzQKLS0tIDhUbm8xUk5rT1MvUU9iMDdvN3Fl
            RGVXd3BXbVM2Vnp6S2hUTGtnaW50ajAKJ4XwD4skRvtxGVHVYTyH1eXJ16o5ovCd
            ahYFYqSYaJhfvW7A3stl4/Zc4GgZCEnHp1kLi2/UVCgnFKKOdqSlQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-03T10:38:10Z"
    mac: ENC[AES256_GCM,data:5H2M7UUj332kKJ885aD9kG9zhy7nWoHyPlOagtG6h1AZM5twrIbFzWqi7kd1x1TBh85ONWn+8YokUucW76fu7tClJAskXM0Z8pqTz9r1/oWWdFOi+zkaVpKZyTDumu2OPNKCGJLikFauPzEMD7d4MYd9b/gHJ8cqw3mmxMu9Mhg=,iv:IuMvxhU78Dngx3XY1dj4GQChN31R3izA2L1DNVxMrE0=,tag:v94DBw8QYIUM97+gsX5Zhw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
