app-template:
    controllers:
        album-creator:
            containers:
                main:
                    env:
                        API_URL: ENC[AES256_GCM,data:4fLLVjGL0wvrdfNjR7FIcSJKvC2bRSzNio/65PH+LTAwO3gKtIJckQ==,iv:raT2yMeedIvmnZytJerHTq7L1W43YAkUUjnpUuIl57k=,tag:23NjJ+lgZnzOlgzjvaPIkQ==,type:str]
                        API_KEY: ENC[AES256_GCM,data:JfO3Ls/P/l++CdHz11zH+K3MCDOLuiI6XpODMvMTzJrdPTzvW0baaSMx,iv:38mm+A/jr/f+PZ3Y55c6GpvGSrZ3dbfguaqZ6GEF0CE=,tag:kwUK/ahoSGgidn0o0omDBA==,type:str]
                        ROOT_PATH: ENC[AES256_GCM,data:CXFaAhuYbDQV5q5XNAs+HNU=,iv:FDyT6WAR7NMVdG+IVR5D34rKn062Cnc0yJ1/KmP2e98=,tag:+SMSx23E3iK/3LLtgdW5UA==,type:str]
                        CRON_EXPRESSION: ENC[AES256_GCM,data:pEvRJE7VlToG,iv:1p7q1YIqp1rn2my/nD4e4I5w6hylQohalxkwpd4iiTY=,tag:iPzSDeV+rkqGdRczMuaMwg==,type:str]
                        TZ: ENC[AES256_GCM,data:rqSdUldfBiWf0ftyHbf/w4dy+g==,iv:Yeu9j6EQzTStbGcIaSnvWqS4VHEnexwuftbE1a3eUDk=,tag:K6Ll1+ajsM43gKrV9X8k2g==,type:str]
                        ALBUM_LEVELS: ENC[AES256_GCM,data:nQ==,iv:yLP3kCtZEHzaKlQN2w2SRKaBvESgG3yNIEuBmQKB2Sc=,tag:TKhFx1SCUO/Ma4dvvOCuRA==,type:str]
                        RUN_IMMEDIATELY: ENC[AES256_GCM,data:OJ6t5A==,iv:3y2Y2hM1b+oGSrCKE6GqQBvTpc1Ctu/ALAgYvIHz9dg=,tag:iO80IhtLIwqBAa/bnpGx7A==,type:str]
                        ALBUM_SEPARATOR: ENC[AES256_GCM,data:IafW,iv:e99fkl6VKgqK2+p11bx13+NOWGDjj6VLpb7mVWpTlPs=,tag:uE+NF8T65rtWDpyhQvSB6g==,type:str]
immich:
    controllers:
        main:
            containers:
                main:
                    env:
                        TZ: ENC[AES256_GCM,data:QLt5m87zpPUncxE7myiXclDvww==,iv:TCScvskSIanDrIkdwyAv0sIPMsYHOFg01WA/c/KXpuY=,tag:TSuB0SnrOY21fmqbd3Q1rA==,type:str]
                        DB_HOSTNAME:
                            valueFrom:
                                secretKeyRef:
                                    name: ENC[AES256_GCM,data:atmV4QWfHnxXlEHdoZWvpEAMJg==,iv:L6cjg3K9hnBLSW2A+FnCjUw721x38wgoM+clNNWm3dA=,tag:r6Lw88VpLH7KaD9aOCPADQ==,type:str]
                                    key: ENC[AES256_GCM,data:i5EXLA==,iv:COf2Q0A35Kn2suTxZihRkLWbpCAREoGtpHvp9l5kQEc=,tag:j45IdV3+4NyipT3f+uFe6A==,type:str]
                        DB_USERNAME:
                            valueFrom:
                                secretKeyRef:
                                    name: ENC[AES256_GCM,data:dOUNWRoQbsh7kmIPEbt9F69MGQ==,iv:Jud+Hi1uqEatShXOsyholsg9XiPC2zyCSW6DGlP02V8=,tag:fvi/0Tosd979MeWIRvPqBg==,type:str]
                                    key: ENC[AES256_GCM,data:BTP8HA==,iv:r7Iv8nuDoxNB9ZtrG/10iw2OJNclozLAvNgcJYuVl6g=,tag:C9PBPrAZFYjs7R/dykSttg==,type:str]
                        DB_PASSWORD:
                            valueFrom:
                                secretKeyRef:
                                    name: ENC[AES256_GCM,data:oPad2uod2U2Rvgm4IudnL0q3hQ==,iv:c7zdmO8PBuO+NE2Va4mKCDDak7d+OEnkMy3L0MpUmTI=,tag:8Ynklk5sx6oWG28g8yzO5w==,type:str]
                                    key: ENC[AES256_GCM,data:CFVH7gis/mg=,iv:f68M22T6o/G8V8iPyT3EP/ZjzUB+HIS+kX+0EgEOBzE=,tag:4K46DHPKgVDIOl9JPNf50w==,type:str]
                        DB_DATABASE_NAME:
                            valueFrom:
                                secretKeyRef:
                                    name: ENC[AES256_GCM,data:975378IZ3GBR7o65IGP78oKABg==,iv:OzowV1Db80FAu7F7Mwp5VG42SJ355oMqvDTQv8uDdsc=,tag:5KhzxlolweAl2ZsUBtkw7A==,type:str]
                                    key: ENC[AES256_GCM,data:zqkldeQB,iv:PPznl25/Vy2xvx4OflDSHiHEmgIT9jvEcIjx3OJZWtw=,tag:zadOOn6T5kI7g/dqRxuDJQ==,type:str]
    immich:
        configuration:
            server:
                externalDomain: ENC[AES256_GCM,data:4+/v8qTV7KxY2+GJ2yKdI6XheflxdylGFvE=,iv:pM2SR/mOZncbkX2+M1a+q+RyQR8pn6Ll/c1fHvX2yOY=,tag:wGpxboqJ91am1U4rE+uo3w==,type:str]
                publicUsers: ENC[AES256_GCM,data:H7otkdU=,iv:Gx4vadWju96a3YTwhakU8awiT2xK2UUrSr8wWiLKpdI=,tag:jBDuNuX8p50hcTEWBL+c2w==,type:bool]
            passwordLogin:
                enabled: ENC[AES256_GCM,data:rN9Alg==,iv:+AXwxWl8czDpPV+md9jtQvadvmpe0tOcpMX8Bh2gkJA=,tag:i0DIBKrRoRneR0u4T84uNg==,type:bool]
            storageTemplate:
                enabled: ENC[AES256_GCM,data:aIQTEg==,iv:HwDut8prlwfcfEaqtxhxJeUiRWNPpQFUgD7lJz2fQFw=,tag:L115XlYq0A3KLrWS2WO1ZA==,type:bool]
                template: ENC[AES256_GCM,data:7mvfow1b9Mc+XJ5EorgBK3vbYL2IOIcCMOcKkVzBqHo2HV6Wgw8=,iv:VzKkcOcpWCw4SibN3iDqp7Y6Ejak2cEBdxJ5xJHTBH0=,tag:hsAmiBqbu3B63XbC5MTFyw==,type:str]
            oauth:
                enabled: ENC[AES256_GCM,data:lDul0g==,iv:LFiehlfu/WtXADRufUPtgQdsHatZvN652GA9W53OiQ8=,tag:iGIMuNaQWb5G+SHMNs0Zsg==,type:bool]
                issuerUrl: ENC[AES256_GCM,data:H89JtlYVjXv9xh27ZZ4C0X5YxjVURG2Ko6dxzcpS6XvzPRpxJPfwGMzMCPWI41AezUXGv+NR7L+4UZY=,iv:MFAkDyo21u8zMPT6I0fQehDs25M1guzxA4VaCPKg7gA=,tag:wEIJW6ZDUOymRq/++e8uCg==,type:str]
                autoRegister: ENC[AES256_GCM,data:Xb/E4Q==,iv:LoAHKxo+ZlA+Cp9rP5DDnqhJd+frDPk/gHIK/unxJNE=,tag:ZIRqNAvL3Q6IQ8pFD3UUVQ==,type:bool]
                clientId: ENC[AES256_GCM,data:fVZBcWlT0zcEtv2JbMSWiLJY4GCDLDu0nrHRgSgsGyHIXh6c,iv:xg1XQAibvd34lUOfE3YLG6mLvvK4g5La/b48q86xnRQ=,tag:Tn5KYA5qR5Vkb1J4cUkzWw==,type:str]
                clientSecret: ENC[AES256_GCM,data:TiDc7uzGVlTHLXx00ZClPFQBJudHA2WASO3357mq308=,iv:SK2PbSuU8EMsDv0tvTl87QXccXajgEO2EJOyaQZkKpU=,tag:teoUeE2AVKHbTF9k2PyOwQ==,type:str]
                storageLabelClaim: ENC[AES256_GCM,data:hVtXbYCcCiZCxjImSA2f6DK0,iv:+zwbpAqtoEm3ypFudJZ+oYpaYwPIePxCuTdIjmWZLQc=,tag:28yIayHW5a1B8nGcoKHSrg==,type:str]
                buttonText: ENC[AES256_GCM,data:dVfcmfc7VgUfq1lZYNOONXv8cSo=,iv:Sq2EbERi0Q1zY6BJUGT6II4j0sGRKM/HlHs72vlGclQ=,tag:1m8j40+4OyIRqTPCfLnqBg==,type:str]
            trash:
                enabled: ENC[AES256_GCM,data:aap1mQ==,iv:3nTzBEFDC/U/KxWZndDMIAl5aCkUrAdA2AMszvxIYzE=,tag:pDkljOIHv3vkbAJLYd1sbw==,type:bool]
                days: ENC[AES256_GCM,data:Y34=,iv:cFwHsps01TKPOBIyjaSqEbh6KxOcjqyFm9MTQbA4nME=,tag:6C2eFohOdPxIUHzwc9q6Uw==,type:int]
            machineLearning:
                clip:
                    modelName: ENC[AES256_GCM,data:na3BQAhTbF17MJdPkSgGxA==,iv:I0usfkPclU3q7jl0jOtUjy+kaDAxgGNr3rJTl9EnygU=,tag:DZaFKzkbfCir49F4MsjaCw==,type:str]
        persistence:
            #ENC[AES256_GCM,data:SImfZTZ1HZ2O8Vl+hmYvY2nybuIHTS/LT12pfdOi3G52xFkuh04J9L+Dit2m/FbLeAiJEju8yyH+EW02uJUBI7sl2/s=,iv:AM5kKw9zKuclBM3m1PmPXjg6iSLZLoXE2N/ZO/E+hqg=,tag:mqeQQkESaDscc5ydsdMg1g==,type:comment]
            library:
                #ENC[AES256_GCM,data:GlOWaBv8fqEj09u7egL+nve8mxJY2tlMadxtQJVnn0z158zJUDIP6ev4y7JSazYsnNQv42r0/m2m12ebTYc/P6Aif1q4j2jiFQ==,iv:WWjkGAruF6Jm/lI0v8mQ8QPrm8jjyMs347NWNfLp0NA=,tag:fD3ULtabO2jQn1ILahlinQ==,type:comment]
                #ENC[AES256_GCM,data:6KZSFw0o0lc+KLr4DsifeDCBg2M3EgDRWYrzLOzebqYYjhb9N8xvxnDQhA==,iv:iIPx+sJ35pCFztb7orEa6rKmvQA5scVaCqu1CdhQoKI=,tag:J7UhYnURMx80UkhObKCyZw==,type:comment]
                existingClaim: ENC[AES256_GCM,data:3HDdH1MmuA==,iv:4GiP3yA+qKTLmV97xN7I3Zu4gpzWki355ZAzcbm12Cc=,tag:FdH8BBIaSeQSQU06P9D9lw==,type:str]
    server:
        ingress:
            main:
                enabled: ENC[AES256_GCM,data:NmkHWg==,iv:K44l0jz5RifG/aAJhei9KjN+kgM0VKm6wwhDqTPPFKc=,tag:Q+/eO9RZGXwB/HDk8l9QYg==,type:bool]
                annotations:
                    cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:4Kh8cklaJ5+6Nl6sFw2cbg==,iv:td0N5XJmucJXUPlq80U5IlVshxjfbebQf2UPDnwyUVM=,tag:BmvT27NZeKuFiJoP8rQT8w==,type:str]
                    gethomepage.dev/name: ENC[AES256_GCM,data:3wheXk09,iv:F0jHv63gCdwEGPxICsp173j0uJP0JvhtpsoqpnR/R1w=,tag:dwz8g4DKSxtllfGhjQ3mtA==,type:str]
                    gethomepage.dev/description: ENC[AES256_GCM,data:V/Ddhkc+TVdiRx3BpJixhx5eIqjJkw==,iv:YNyx8ZrmNa6Cuk9X2Ok9FXSuVUuv5qd7qPpNscpaiyM=,tag:8KBGWgI9USIOmxdDO2SlcA==,type:str]
                    gethomepage.dev/enabled: ENC[AES256_GCM,data:xY1jLQ==,iv:PM46DrVzazUHmQVypL1/suRGG7hUt1P0uJ+73Xw068o=,tag:Sr1IDU/O9TvgmNdzg7XJ4Q==,type:str]
                    gethomepage.dev/group: ENC[AES256_GCM,data:NE7J349gIe6r,iv:t7Qbz39dU5MNMy8K4xDul01ZoJd1VfEwcD2I59JOzjE=,tag:7iEdaW6XCNe7dN2PwaVFqg==,type:str]
                    gethomepage.dev/icon: ENC[AES256_GCM,data:Dim0iglYruadRNulBQ==,iv:J2PholpW/HVux7i5awuqU3URkOLz30TSSiZfR8R6y9E=,tag:FXwz8x8z7xHc+Dti8k00QA==,type:str]
                    gethomepage.dev/pod-selector: ""
                    gethomepage.dev/weight: ENC[AES256_GCM,data:lQ==,iv:AxWUo9BAQoCaBh4G97ntZr5XkKDwkNku4O0jCPe0rsA=,tag:EOHmcKfCkgt7AOWJVhTVVQ==,type:str]
                    gethomepage.dev/widget.type: ENC[AES256_GCM,data:Le3vWoMC,iv:u8D9y9TRj1C0RzRMUNBj/53LFowJnOd7oH1DW2nPxyc=,tag:PwMbcJJm8x93tXHaTJaQSw==,type:str]
                    gethomepage.dev/widget.url: ENC[AES256_GCM,data:ngkWXK9SGo+1rykfBzJVa2+EYEHPlS64ZA==,iv:bRD9U54JqGrmhNtdLnCzsi6j+PlXiuuofPGhTeoupEw=,tag:d7Nd2EQfSXFJ8Da3kzYhRQ==,type:str]
                    gethomepage.dev/widget.key: ENC[AES256_GCM,data:ohkL95RW/XKPKCgIZI8c5g0IOPJ70XXyAL5GUVzpDm5EHgJ4OPStuX3w,iv:Jrca5lVgZJMyznC6cl/UI96eEADzjVkQyINvci3nw24=,tag:NNiyRvOK2QWZJQCVlv1Sog==,type:str]
                    gethomepage.dev/widget.version: ENC[AES256_GCM,data:EQ==,iv:g7kt/Di3/rAU2+VauAH/U5Zxvutd5C7vlMxgZ07bbaU=,tag:QPzoew1uBDwCBqkb2ZOvoQ==,type:str]
                hosts:
                    - host: ENC[AES256_GCM,data:EM9PUlh/zez3J68m6aFQ+Fh3,iv:zdqWqLUwuWQzEqpdp3nlydZL4Y8dvliDfbrrGhr/MMw=,tag:LJJSdj4suLkDl3dwSVlliw==,type:str]
                      paths:
                        - path: ENC[AES256_GCM,data:pw==,iv:0viUzPimnfZDVn6xMCoRmkrTMONdRM3lsDrOVBwqYQ8=,tag:LjRtHNpy2weNIvs4f4c0nw==,type:str]
                          service:
                            identifier: ENC[AES256_GCM,data:RRcIPA==,iv:hECuaGKAiY1nY8wk9dowuEiaL6d92TcOfdSB8cPbWgs=,tag:B018FeqHGaJ+1DWpfh/Umw==,type:str]
                tls:
                    - secretName: ENC[AES256_GCM,data:YtUanXw1qXe5SDmzUR9C,iv:mn7uywzx6EtPvXUPS5jHr2r6DCsN+RjcelJupcCPkZw=,tag:U33Si71OVXwV2dGj9MMPuA==,type:str]
                      hosts:
                        - ENC[AES256_GCM,data:WhZxO2mFiGi0O+oN9gglngbZ,iv:0kz0wJjkN/MSZLVu8QjipjwdYR7KVd2goIEKKWQ16tE=,tag:l13oPML3+VrC2+SXylSOfg==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKMThXY0hjU2t5NFZ4ei80
            TDNiMmtIOTRsMVk3QkdleVQ3SFlyZXlTUXhJCmVpK210MDlzTDZ0MkdrR1NBM3N4
            ckN3Zkd5VlRSN3FyOTZ0VmdqVC9oVFEKLS0tIFFRVjBGZnFPclB0MW1jdy9oOFpV
            UjdTWHBXcDNVRjZLNUpMQktGRzJxc1UKDKTWzD0oPUqMI83D89ztGnT1ZF70MZcg
            V8Pu6wiH/u/6JYePOt9G/SWf+CHCbjf8bvd8HQqlDm/C+bNfa0T/ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-29T21:31:23Z"
    mac: ENC[AES256_GCM,data:PiLcSGT8vFrouNISGu0vZzWUbAfV49+Wu1IzhNkEVP37zH2KctsSLtJiwKa17biT4Ltp0XqyYXI2nSY3wqcFxgYZllZLF8Dq61Mb2/uJigTGl52V8s3in5FAoh47TIqZhGXlMpR3kg8n60ujDVy8p30k9rwTvpt4819svcUOeR8=,iv:+gAwRW4eH52oMNB7om2dCv+jg76iZwo7tjsr+zjPXPs=,tag:zWtdWE0/Y5IyP53nq+WV6Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
