---
app-template:
  controllers:
    album-creator:
      containers:
        main:
          image:
            repository: salvoxia/immich-folder-album-creator
            tag: 0.25.2
  persistence:
    external-photos:
      enabled: true
      type: nfs
      server: 192.168.1.200
      path: /volume1/media/photos/

immich:
  # defaultPodOptions:
  #   nodeSelector:
  #     plex.tv/host: "true" # For intel sync
  controllers:
    main:
      replicas: 3
      containers:
        main:
          image:
            tag: v2.7.5
  immich:
    metrics:
      enabled: true

  valkey:
    enabled: true
    persistence:
      data:
        enabled: true
        size: 1Gi
        type: persistentVolumeClaim

  machine-learning:
    enabled: true
    persistence:
      cache:
        enabled: true
        size: 10Gi
        type: persistentVolumeClaim

  persistence:
    external-photos:
      enabled: true
      type: nfs
      server: 192.168.1.200
      path: /volume1/media/photos/