---
app-template:
  controllers:
    album-creator:
      containers:
        main:
          image:
            repository: salvoxia/immich-folder-album-creator
            tag: 1.0.0
  persistence:
    external-photos:
      enabled: true
      type: nfs
      server: 192.168.1.200
      path: /volume1/media/photos/

immich:
  # defaultPodOptions:
  #   nodeSelector:
  #     plex.tv/host: "true" # For intel sync
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/immich-app/immich-server
            tag: v2.7.5
  immich:
    metrics:
      enabled: true

  server:
    controllers:
      main:
        replicas: 1

  valkey:
    enabled: true
    persistence:
      data:
        enabled: true
        size: 1Gi
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce

  machine-learning:
    enabled: true
    controllers:
      main:
        replicas: 1
    persistence:
      cache:
        enabled: true
        size: 10Gi
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce

  persistence:
    external-photos:
      enabled: true
      type: nfs
      server: 192.168.1.200
      path: /volume1/media/photos/
