homepage:
    config:
        kubernetes:
            mode: ENC[AES256_GCM,data:whjp1l504g==,iv:MZBpDG6AC265ff/poR3+KqBOltOAuSKlmv5wskW4/CQ=,tag:4utTf/390WmcQEGl0Fp+Yw==,type:str]
        settings:
            statusStyle: ENC[AES256_GCM,data:+Qzr,iv:yx/wd+wr1WRUOS4QEPENMjfNK7sRXD7smklEkZoTl3U=,tag:jVlQ5702k4LP7aXuOmTqdg==,type:str]
            quicklaunch:
                searchDescriptions: ENC[AES256_GCM,data:FRh9OA==,iv:1fI1Rr6vUzWH4vYGpvVNyi3wBt5RrnKqrlkFAsOhQEQ=,tag:4OiGA4zr2o+KMyX2E2mJcw==,type:bool]
                hideInternetSearch: ENC[AES256_GCM,data:9RRgFw==,iv:vqIwNAauDXZhJDvmwBmtSksMVT2MgcJYXSSQpmhOEvE=,tag:fNOE4x0HxLAE1j5az4a0Ew==,type:bool]
            layout:
                - Knowledge:
                    tab: ENC[AES256_GCM,data:Peo41Q==,iv:bf01/61sXM7Ot04ikMMd4IXnrgu7mTAAUyWGqK8i7mg=,tag:EtdCPXkBBVLEfR7zEhx9AA==,type:str]
                    style: ENC[AES256_GCM,data:vl1i,iv:8SGkdcoh7fBlg+a2AyZYD4wRoYIySYidOasppfZBV1Y=,tag:j24cYhmGpTym448jEF/elA==,type:str]
                    columns: ENC[AES256_GCM,data:6Q==,iv:aWkg+0a78AEkAu11IYcQHQJnfT4VM/Am6tr2xvWRquU=,tag:e/xHku7YULnx0D7YtoqiIA==,type:int]
                - Documents:
                    tab: ENC[AES256_GCM,data:xv3x/Q==,iv:8Nps+8ZxBlF9lf1nqZQeAiZop6Ayykp+Inr8HMtuEPg=,tag:PRatRdbDA4IvM+xdezipBw==,type:str]
                    style: ENC[AES256_GCM,data:z2bj,iv:Cuo0tiVAUWgLqMzAnsdlr+hM2Q8k1dWpUotZkCXxiyU=,tag:wgoTRl2X6qnha6j0d70R6w==,type:str]
                    columns: ENC[AES256_GCM,data:uA==,iv:xqMlUF/VDN7sBSYftvgqhlOW2z5b9eypz0mDJXP0hmo=,tag:nUNCiLf0H/soXL1tvThIQA==,type:int]
                - Sharing:
                    tab: ENC[AES256_GCM,data:2apYsg==,iv:7q+xq9oJrcNP4lbrrEbI2iPlKwNzsuHi4NiXlGCQ7fs=,tag:6lQ4iC25/Rc7w8T+DYypPw==,type:str]
                - Smart Home:
                    tab: ENC[AES256_GCM,data:PY7oXw==,iv:yXY/TR4IFOEmCNK2k7N8DG48kiKqIUCrK41/SOVwttY=,tag:fgKr73zSFllDB+L1KT4K6Q==,type:str]
                - Miscellaneous:
                    tab: ENC[AES256_GCM,data:pSUPWQ==,iv:ctel3KmpQ/J7oDihZ4SoL9yuKeeriHcc2bM2APqNvsY=,tag:AMra7Y8qwo8QlcVhvbeCgg==,type:str]
                - Media:
                    tab: ENC[AES256_GCM,data:u62tzyo=,iv:JDy6uwTJRHxUYKMjRphSHXF14zst6HR2aT/bmXu0AjI=,tag:RhuQyHJ2Ri+NXr6YK5Eacg==,type:str]
                    style: ENC[AES256_GCM,data:ZX12,iv:MS0kUKPyuNrs6HHtZFlavaOdctYSO6S7PpXjf6pEe9U=,tag:5gC4JrMPM/ivHp26bRQ/0g==,type:str]
                    columns: ENC[AES256_GCM,data:nw==,iv:6CPPG88MKxj/esZUI+1KYsoP0mFuu0otuVdRIkZrl3A=,tag:EnH1+vlZR0mE8QKHm2wy2Q==,type:int]
                - Servarr:
                    tab: ENC[AES256_GCM,data:FScyYnA=,iv:4apd4Mlfy2l/Xmi/lzeho7pyRoaB4Mly4ONH3GmDoW8=,tag:nzXc7MQ7F960mwXqQlJgUA==,type:str]
                    style: ENC[AES256_GCM,data:D7EN,iv:d9spY4PE0FLGPxfDzvFfX+YeSlJPRLxLrXK3DQa4PvU=,tag:vPUsmjYNHtGqcXI07md3nA==,type:str]
                    columns: ENC[AES256_GCM,data:Yw==,iv:7rWokjwLV4h0PS2P70G8oLdL4STMUt1+mODzYedBt58=,tag:dvv+I7Cgob1MsdWE8AOhvg==,type:int]
                - Games:
                    tab: ENC[AES256_GCM,data:MB0dkmU=,iv:le76jTs2zBqDX1T17irK8VDPIix/ZzoIeFbuHnNzwXE=,tag:pZoBnw8AwX3LTQmHPbLFkA==,type:str]
                - Media Tools:
                    tab: ENC[AES256_GCM,data:dxtBZ2A=,iv:nBzPAJsD9+woPUIGFEvQH/Jvvzk6qPQWvptCcXfroG0=,tag:Qvlwc/SJKxzPSUOHxuk5Kg==,type:str]
                - Unifi:
                    tab: ENC[AES256_GCM,data:bQooCoDhxQ==,iv:slihuHLSVBpfkZI5ic5p9UuV134QR5uu0pgpiVu3uak=,tag:0lYBT2iO3SSK1I5OPWeQ+A==,type:str]
                    style: ENC[AES256_GCM,data:VbV8,iv:YaBSSGHIO+5M/dnDYVDaWa4JnFdzSHQBEbJMGTHt9C0=,tag:UmwCaC+ND9wAdgSvh87fQw==,type:str]
                    columns: ENC[AES256_GCM,data:aA==,iv:rHez+cgEUFvopJsaIrzB3PfTBVwISMb2o9t9t0Wc9Tk=,tag:+2dYPlDBfzJdYLGKI6S7zw==,type:int]
                - DNS Servers:
                    tab: ENC[AES256_GCM,data:5FEGMY83JA==,iv:IdorKHjLpWnNHuiorqBUKW+VENR88luZWQhFv9y1mRg=,tag:vpQJwJEGanVVskC3SWdyug==,type:str]
                    style: ENC[AES256_GCM,data:gLvk,iv:RNy5rVbVvUUyZedYJyvAaBSOn6ogMnvfOeDGjzQpr+8=,tag:TnZaLzLk4L7WT7jW8FuOqg==,type:str]
                    columns: ENC[AES256_GCM,data:5Q==,iv:wuuJlVq/EweWDUTB4UZhnyY/zsZW+rUyb90Uw/1Nq1I=,tag:xIs1znliX+Q17RifUeOgTg==,type:int]
                - Network Tools:
                    tab: ENC[AES256_GCM,data:kiI3RU64Jg==,iv:RBhYYhi9Mz/hZa2p2W/x8ivscIFFMNWhix1FUgvne0w=,tag:fd2gM9QLHojnE0luzsKo7A==,type:str]
                - UPS:
                    tab: ENC[AES256_GCM,data:FvhfkC2HRw==,iv:nHrBV6Un/e+eAcHESSrH5xRU76ugWuiP56bOy+lZGQQ=,tag:RTUO022G4F8ZEDhhkkSmEA==,type:str]
                - System:
                    tab: ENC[AES256_GCM,data:mEVJ/a/sLA==,iv:q5jBHAnecZS3zbY3AQ+wZ7sZ0keykL31ntMs6hVaRFA=,tag:hwrNWMwrbNps6qHcFs0BJw==,type:str]
                    style: ENC[AES256_GCM,data:gaQ3,iv:jylVitHis+8pE7WUCs6Im9bkmcCaEjhOHJFdriHtZM0=,tag:2mlwwFSfrjdC/t5Tat4P/A==,type:str]
                    columns: ENC[AES256_GCM,data:bg==,iv:pz0jPgxqxb44Du89s+5ezTejeKVS0DNgV8f/zf5DVl8=,tag:xpNaOLEg6RRfJD7yRB2FTw==,type:int]
                - Observability:
                    tab: ENC[AES256_GCM,data:eLGIyjwqqg==,iv:muflCdZWuI+vGViPjsGni+FiGpVlS52KLde9boxyZA0=,tag:IkOZD9jMrkR3WKLp+xYPAw==,type:str]
                - Security:
                    tab: ENC[AES256_GCM,data:46fwIzCj5w==,iv:cIdqLSW6IREHq+Fy4QPB8vfNzLjm11w53/GHN/DRHZg=,tag:uosnJIdvNFfsjx8qd4CYsA==,type:str]
                - Storage:
                    tab: ENC[AES256_GCM,data:fEelO2U1Dw==,iv:s41qWNqYEdpQqdxIPNlDutJ1leZcnfS7aH0Ot5mFzIo=,tag:wvkEdrgwEjvXOwdGk5JBrQ==,type:str]
                - Synology:
                    tab: ENC[AES256_GCM,data:ltv7L2Nbaw==,iv:o550Z8lC6pb78jMEegr7JQJ2x1IDwNBfHuqCrIv77sY=,tag:d8yKk6etHiOa4B2Y50UHPg==,type:str]
                    style: ENC[AES256_GCM,data:SfmB,iv:joEwXMMnQtoJBl7BYfj5mSLqNBRcd8e84q0aFXgBANE=,tag:u6W+Z0eeSan/gscuSIOj/Q==,type:str]
                    columns: ENC[AES256_GCM,data:aw==,iv:7vrM+D0KWCMEjOCi2PGL+8FS6pjn8FJoP8FkTU90irw=,tag:uIEz6k7pizzlPXTmDsx93A==,type:int]
                - Automation:
                    tab: ENC[AES256_GCM,data:YSfUMw==,iv:O4XHsTAj4FXTW0LN2GrwWQQhdFeHhG7o7BJnfassz5k=,tag:A7QGsz6ZWYOt86kxEatpaA==,type:str]
                    style: ENC[AES256_GCM,data:+sNp,iv:ElGSRnkPBxFyN4qwOBnYn4q+Lyqcc+YxpviKW1/5mcI=,tag:yWF5xjjr1gfWH8dKSlMWQA==,type:str]
                    columns: ENC[AES256_GCM,data:BA==,iv:FaUg9MEXpQRPzDhNzWCaoM7Y5rqN5c+r2bYPXbrEFa0=,tag:hY33HBm+vUqMNXhyl4P6Eg==,type:int]
                - Git:
                    tab: ENC[AES256_GCM,data:uwzcGw==,iv:sZ+7pMQ22rS99x42nEbI47eJrxubmXBfIEYS0eGjrI8=,tag:tecghZOgZB15nMHLalNdlA==,type:str]
                - Artifact Registry:
                    tab: ENC[AES256_GCM,data:wK22yw==,iv:CQHJqb94cMB5ddaxAa3QpNo6bYQMIRqpgFJfkUfgDpc=,tag:jcGCop5LyL85u6bqLF16YA==,type:str]
                - Database Tools:
                    tab: ENC[AES256_GCM,data:guOXTg==,iv:JKz1wXfRcDwr4CLMaW/3GFhkizaeZJ8P+y4TLWPLUcg=,tag:DwtZUcfbgxLNF2lI6kaH9w==,type:str]
                - Messaging:
                    tab: ENC[AES256_GCM,data:LgXO9g==,iv:IJaoIO8rgw9uHnMv0YfudR6ZF5qCneUNqaTBMdWdhvM=,tag:OzTKDp7n3td1RX3XrAL2oQ==,type:str]
        bookmarks:
            - Homelab:
                - Homelab:
                    - icon: ENC[AES256_GCM,data:mjfobQuHhL9riklcLEMjUGDB8Q==,iv:MjYcVUC7BH0pjLavmW3vTeE1RycqHN9sv6HVP7EjhuU=,tag:DPML+jM99ZdxdWXRsPQm1g==,type:str]
                      href: ENC[AES256_GCM,data:cW4GBIB0ZD2Vy0gZ/3/CcJf3BclwXt0uiR45QA5JhCcNNQ==,iv:G96NNeN9T/zwyvO4RE6B88foi3PhOwIDrcuknNRdtKY=,tag:rUsAVnZvGA0bEjgYoz8Cdg==,type:str]
                - Cloudflare Zero Trust:
                    - icon: ENC[AES256_GCM,data:Rtl0HSgPhy4HVBW4/DeMCWoB0OnDVbz8hA==,iv:ZPqQ6f4cWQHG1g9K/J32415qYVmwbwMAzyy4I5XYjp4=,tag:OdFtiKtFBYQhIxEFYGSpSw==,type:str]
                      href: ENC[AES256_GCM,data:QAtHUkzAsIRD4foPd4b6bAz1BADmyLYA0qSuYuiKKIk=,iv:K7ihnxCkO5c6VdsvfY/keqDGZaNUENlwDovmN3lRG/s=,tag:vIpCpo5y9/nEGEMpKUjMjg==,type:str]
                - Cloudflare:
                    - icon: ENC[AES256_GCM,data:UDrKmM/tVyvjtS4dVA3oVB4=,iv:WVBbkzkj7TK0UkIC4cvvUOo4H3q5m7i3HsNQjbdQPsg=,tag:MYn99RRfDmHQDKyuVRzJ2g==,type:str]
                      href: ENC[AES256_GCM,data:Cr+/4+xCgoFN2IswrI0zrjsLQA1u/FbxXqEVzA==,iv:kPJqsenfbOCbzTZ/WJE7QFDn9HvJET1OYBSTwQP9UNs=,tag:NvjgWx2a25VCx8w+oy4pfg==,type:str]
                - Auth0 Dashboard:
                    - icon: ENC[AES256_GCM,data:yviXmiVgdAD1QwW3mcU+fncmBsiwZ5n9qnqfshhfDU1PO9rdasPp6ijh5yuM,iv:8ARru0UVVijrfXKPL9ZLiXJCdoL1aNwSjNViDFUDc4I=,tag:lc7tHGIAZsUaPRmuLysbig==,type:str]
                      href: ENC[AES256_GCM,data:Kb31N/L08WKR8KqSF3WG8Ru3QyirgATh6ZXdwfZgCtW0W6ButRCf7aGlAlZP0w==,iv:KcL1x5Z7DNVUe1BGpVdLSQsYY1sSunENTwKuMorNzLs=,tag:Z/X/043UGntArHgzdcUg0w==,type:str]
                - Crowdsec:
                    - icon: ENC[AES256_GCM,data:QtEUFM/SOAyFlDWbD8cj,iv:MxpmjJJcDxYmPz1NgUHQ2HWGnd4guwpXN5LCYD0ztZs=,tag:ZB9mXmlQjeyMTm0rwS8ZGw==,type:str]
                      href: ENC[AES256_GCM,data:3Ns0OlitYxWsosVXH2Hy0TOUykUG+N+t7g==,iv:ci/vGGNUWR+cWZnTEDpuJw3rIyLGIgetaik+U9acZT0=,tag:QUtMham/Y118pOWzKdZaoA==,type:str]
            - Dev Stuff:
                - Mend Renovate:
                    - icon: ENC[AES256_GCM,data:ZyVJXGlD76u5F9XVQmqv1I9CNRL/WHkYVGlpEWMBT5uMxkOx1k600UnyjxeMIQ==,iv:T1pBrILFr5j6qWQjfjdPZoJJIMJk40D8PnZwJm1RJIs=,tag:X/GrkQQoaqos0ntwkVVffg==,type:str]
                      href: ENC[AES256_GCM,data:nXZi5lugAD4/mJ5EGEkyzt/r4iGUrVGa7DOTmSrRJtdrCJOJGInQ0/T0NBtJevqG,iv:c3ohOxqR3Z3nLHTYGlkECyBtppqJDf/g6vnppaONh6M=,tag:iTjet1AYbFVi0GT5y1ifHw==,type:str]
                - OpenAI Usage:
                    - icon: ENC[AES256_GCM,data:Qby6QBgzPRQq3HJSglkt3bIGUQ==,iv:V1ShZtCQ/4chPxFF90mldVGZC1gdSCbUMsBeOjwemYk=,tag:QBDdsZevZ0iTLuGMGcVTkw==,type:str]
                      href: ENC[AES256_GCM,data:8W0DDRQn1kvU24mVn0tpdLE8VUU7bou5IU4CWlWNV8vA,iv:Ms5YyD36P+Ap6l9E3eiau4jV+uLXSkZSed2ny5XS6kU=,tag:5rAtNmjeV251PLiD8Rl9bA==,type:str]
                - Helm App Template:
                    - icon: ENC[AES256_GCM,data:xNkwphmiZ08Y/SUT1kumlxc=,iv:xvcxcm+EsIgS6FLNn5yOCUJnSof2DshaAWetHlPnvxQ=,tag:QtXke6vH88c3+8fyAx+dxQ==,type:str]
                      href: ENC[AES256_GCM,data:GLN6ZBRTyfxZJSOnC6R3fOH/W4RXYvvUbyIPyqWz8TZ/o79Waf5BIjQfzQSTfw==,iv:FJpCZslHMLu8qO1hr+v8gbQvuNjgcaDa0fPhd4uEOL4=,tag:ALErn3f9ldvH3UNjjPtbdQ==,type:str]
                - Selfh.st Icons:
                    - icon: ENC[AES256_GCM,data:q0fGE3FaoZoIz/KYrhKB,iv:Opyd6eppzxeHEubW1tFtQJtp6vZX8hejUrreDi5+II4=,tag:TaOYjU8sGBu49A4fZ7Y6jw==,type:str]
                      href: ENC[AES256_GCM,data:aKW+/eC8KUZlZtATUaIw1WkRGAfL4+o=,iv:r+DzVrmnhOA00q4u6chdvIRGzkXJFV/f85sahWm0adA=,tag:xEw3uvSEvMp3f2BOZIsj9A==,type:str]
        services:
            - Unifi:
                - Unifi Network:
                    icon: ENC[AES256_GCM,data:aIXGHDPyjIcnxW6zeqU40Mdt6os=,iv:Sf5aGVfoCbB7J6WcLw5NXRXBPDHTx3iWaXyt98x0S+E=,tag:oWPgytja9sWWFyKfVDL7TQ==,type:str]
                    href: ENC[AES256_GCM,data:plRwD/1IGaElET4jT3OEF3ZpTc7PKFGdGwik+smdDOCFjc54p6q5vOxojHI=,iv:MvuPyO3Be+rklJITzkU+6PAmEf5UzThnsejcH7wmnYk=,tag:wjK7rT4pcQJSZKU7RctrFQ==,type:str]
                    description: ENC[AES256_GCM,data:ajq8pnKfUud1Wz5Ez5EX,iv:eC0TyykFBBWBxMEFWBPwMrRZXkvSxFhtfOLQGkV35Rc=,tag:Y5lRhyc80AmG9a9yX5rlYg==,type:str]
                - Unifi Protect:
                    icon: ENC[AES256_GCM,data:ictA6sabs049VXVYGw5oAFU=,iv:JcPyB1iFVPnOmH4VfhgKXJ+2AtGJVRJxWdxC7vJNFBM=,tag:EwHikfUNrdAFVOtBouIvag==,type:str]
                    href: ENC[AES256_GCM,data:Qytr6sj2MvOU2jDJjQqzgPUI4F8=,iv:umDZRyX59nU24h5GqqBAFjqq/83zkgClUuuXVGwvLXo=,tag:ub7KoMgfZL8F5ZWPROVr3w==,type:str]
                    description: ENC[AES256_GCM,data:Wu0oJr2/ww==,iv:jqnJ/glDz75E0MYwPysS3r/K/p8TAfpHk0Bo3IABmh0=,tag:ZP23cELbG8/t2F2OERDLPQ==,type:str]
            - Synology:
                - DiskStation:
                    icon: ENC[AES256_GCM,data:0/F2tmn1VO3Xlz46OhB1Bw==,iv:T5bySqsE/NKmnO+PmSIm/IJODEA1U6lJs1Js1xUB3GM=,tag:VysYBayRdu7PRMOg3cfDXA==,type:str]
                    href: ENC[AES256_GCM,data:R1I7ds3xsXDgBaq2oIZ/yFRsaLv9CmeuMw==,iv:+FizHGSSYnhO4Z+Z32Pks3lWvP91/DFhY0t3nyewvaA=,tag:oUy6g5Sl/eillIGmezwk3g==,type:str]
                    description: ENC[AES256_GCM,data:Qwc/,iv:pzFMjOFybUkVOMXX/SSL91IFHr9ApYFDK2P3KMjRj2I=,tag:ZYe9PMUEGqbJfTaaVeotqg==,type:str]
                    siteMonitor: ENC[AES256_GCM,data:DFplUv2VXeWWJb2ZI1eeRjCXBCgzuPvUow==,iv:TiPtWcq7wNduU8LOBs+XQAli0sZOe2DcZ4aicDKypKM=,tag:gnvdJGgPOc7RblAzoSoywg==,type:str]
                - Photos:
                    icon: ENC[AES256_GCM,data:dregeWlKomMjZXp26HCZPMBkr2Akog==,iv:VeISqMWIsUYXAUmHS/9tbhpzq/GFpKvYjgtpnIwHxWE=,tag:K6NSNpXUGUjG8R7UhxaiPA==,type:str]
                    href: ENC[AES256_GCM,data:sJpZDijUKhewlLpZOCBY3lJWEZcAOVBJgl8lKcybpvQ=,iv:lv8FIjlNK4U4G/ZdvBFC/wG+Z5YzkEk2hDMEAHRYmeg=,tag:j0iCxtQ8EZT9dXe+iwu8zg==,type:str]
                    description: ENC[AES256_GCM,data:mKAd5X9jR2nC07AVxhMg,iv:P85JYV4i/lTzO9S3snDaMoHq/SsIQyaHHjySAdSA1Z4=,tag:WQn/ayfCaeI/8A5lqtQHqA==,type:str]
                    siteMonitor: ENC[AES256_GCM,data:p015YFvxgiQ4/XDZo14BF96SuIx4MXV/92RxV8n2EHc=,iv:QuYJfPzpFjj2vS/DPOFsyKDs/QpieggEy6x78C4cu0U=,tag:Inbbh1zJW9xxOxDUNe/SMA==,type:str]
                - Drive:
                    icon: ENC[AES256_GCM,data:3A0E4dLv5z6Ef5/EAfsF1OIvX8g7,iv:k0Qj1AgMIBGm2glzhXDTsQAbVDViPKE4QuxPbF4OBDo=,tag:b+eMq6v0sSGX94LYMnUdlg==,type:str]
                    href: ENC[AES256_GCM,data:3lM+xXmTIPj5LptKzNe8nvB9GdroU1KQnP9ld6vYrg==,iv:FRZ03oQSQ5ZysarA0XGm32I53eZpEmqmfwtv6LMbVso=,tag:ku4BU+0pKdXhlQ0kiFVeFQ==,type:str]
                    description: ENC[AES256_GCM,data:8OsSIFuPP1p2WA==,iv:tkHfE9FPvZ3yDNllZKIpV05jO/8mOCU27ILIrIpoccI=,tag:pqMZBaWdWjcwwqlEGRddDw==,type:str]
                    siteMonitor: ENC[AES256_GCM,data:KFDQ9/0rSu/XUY5U//0tJaPtKnkuu+PlAcinhJUvag==,iv:2jyLGnW1/Mi5uWygnVdposzzQJkqjWs0ZRxJYPFERGY=,tag:yTlp4Ep2hVupaJXEDCZs4w==,type:str]
            - UPS:
                - APC Smart-UPS 750VA:
                    icon: ENC[AES256_GCM,data:Vs+dah3dXpAl+Q==,iv:IFlJnIXWf8hsi39ofHMIRmwpNfLGjrz+pOHHrSRkYUY=,tag:+rRVi7qXUoHtgDNHTJUgMQ==,type:str]
                    href: ENC[AES256_GCM,data:o/amZ0AE8A3wBKSkKm6MoGQXuOGCFKpb3JcaZw==,iv:1JzVqpdOSD5NcLW+2YCktXB7jW3oFA6qtJMJ1u6dXmA=,tag:aHZNyUbXl63rPQ1eV4deuQ==,type:str]
                    description: ENC[AES256_GCM,data:TVoZIfKzgVzldGxlfLkDOg==,iv:NmZkbx9vOtJGqefarnvmoXNP248dPxcBHoKiSB4rSaI=,tag:iUPUataYQK/OcIRrXvbF9Q==,type:str]
            - Smart Home:
                - Home Assistant:
                    icon: ENC[AES256_GCM,data:oQMCzqJOmKTMXYH5wJZ+AElTYBTm,iv:2ibSKnDULjdnmBAPAyPqnFygbrMwSdwwLWWUyMfiiUU=,tag:0hyRVYrwwFKDhTZGLpsaZg==,type:str]
                    href: ENC[AES256_GCM,data:9qd5w7QO9GK9dvXmzc/cGTc2Sz/XkM+NdnxU65Q+hy8=,iv:hUwvwb3Q+2DKOltsrU/3i7T2h/oysAy51Bb2sXKEXyI=,tag:pTnhCgzsC/UPepHWkaoFrQ==,type:str]
                    description: ENC[AES256_GCM,data:TnF3xonGqm3IewlMieI=,iv:I4Bnuhl+MFfia4TnJbAvhA2/SgS0ptKe8/vsrou7KJM=,tag:8B4mmQqtQtqDxYjgKcI/tQ==,type:str]
                    siteMonitor: ENC[AES256_GCM,data:U7P/edaQDGorm/wQ6GO87b9Qc2k4Dn8hkiQ=,iv:0ZRlTGWHva5kQEmqiaTPQV9svyh/hlzp6tVRfQxMvMY=,tag:yJ0d3kutWIDohiTs2oZaEg==,type:str]
        widgets:
            - greeting:
                text_size: ENC[AES256_GCM,data:Qf/6,iv:9ByAjGy+cfj8L9LQqzmQa+AuMdnhMaKp8mPPrclGTGg=,tag:XQcwfgbahIlH+QyrwVNNew==,type:str]
                text: ENC[AES256_GCM,data:jeqcWezlm5o=,iv:6w5p4su0hysO5bkX1P6Q35mmNoxjRBmnEKLbnfIeDR8=,tag:IY3/20mm5J1ZLM8myrRdYQ==,type:str]
            - ENC[AES256_GCM,data:iYYHoK9WxZjTS5tbGcZlyiJj8/3rZflDCLyrHwhzPhVwd+KF9h1SIBxC/WtmK5tS5G1TPMcocKKHNWjthjH70TMLpWPkC1N8FNc=,iv:yrBijMH3JjLGIa2YGunddfvmf2Zid4ebnmCKN1xomi8=,tag:AYiUudohB4MptJn0hBfXPA==,type:comment]
            - kubernetes:
                cluster:
                    show: ENC[AES256_GCM,data:HNzu9Q==,iv:JVS0GtNesgApYav7nLfepkbaWXkLShFP42o+B6pOGjw=,tag:CBZoif8/OmVMVtnxKVY6zw==,type:bool]
                    cpu: ENC[AES256_GCM,data:/xe3Dg==,iv:H418unFOUKcoZNNdmFa2entBzgOEftO/EMVO6k2hVsQ=,tag:u8qg0PPGSDPuqq2KylZpXQ==,type:bool]
                    memory: ENC[AES256_GCM,data:wVKMCQ==,iv:B5RMeAcNzRuXzuQndJDtL/Dlc7PpNn2w+RgiuIyW5iQ=,tag:vGuDmszLS974BxKEtrsQQQ==,type:bool]
                    showLabel: ENC[AES256_GCM,data:XtFipQ==,iv:IVOIbYc6MrxJTzH91CghrspAivKqLlGhP4IAawe3psg=,tag:ZGbiBh8Sz0aqfInuHIhN9g==,type:bool]
                    label: ENC[AES256_GCM,data:zwXZo5Zvvw==,iv:LTuUBhKoT6/TdiScuxEcg9C2pCKB1cvbsrXfV94uwIA=,tag:LUG0P0z9BExTKi8W2xgWfg==,type:str]
                nodes:
                    show: ENC[AES256_GCM,data:rLgvvw==,iv:gSUvMEQ5H5FXWJelMeTkqyY6JHLGfmTg+HXYW7STxNc=,tag:49fkPOLYSXy75mFqUcHJsg==,type:bool]
                    cpu: ENC[AES256_GCM,data:+u4KlA==,iv:CcQ5IV7Fj4gvYHSaFsGbqIwXpVsaxZBBIkjhDZToZl4=,tag:U9t+L8ZCSyrICO60Sr/W3w==,type:bool]
                    memory: ENC[AES256_GCM,data:Zl9E7A==,iv:JlSiACm2OxDBoWiGf4gUFvBLdJtYTMwsUyj/Xah6TrA=,tag:lKgt2S29ai600pTijcOkDA==,type:bool]
                    showLabel: ENC[AES256_GCM,data:LdzZ0w==,iv:Y7ib/MqPIILMbyaOmiADqPXheImN20noMmr5cxXaq7c=,tag:91Py8aoyFAZs0psTrh4L2g==,type:bool]
            - datetime:
                text_size: ENC[AES256_GCM,data:lBk=,iv:Ev7ah20ZWcDMPjWirbSyGmAY9G88pSghjLcnFrMQjYE=,tag:GmvrE+1Wrv/vU8zT8WKKrA==,type:str]
                format:
                    timeStyle: ENC[AES256_GCM,data:M5h3uF4=,iv:lYJnSjitxVoQXH71xIdqTzOo/FeAwDh8/DPQdsQKYg4=,tag:raV9U+tr3bRz2SmSY9xC3g==,type:str]
                    hour12: ENC[AES256_GCM,data:r/0yiA==,iv:+d7t1oWaNRFlmFjpeVXOjK/09nyYn+wRTPh4zuiqDKQ=,tag:SWdvIgA9Ks4VTE2k08n+EQ==,type:bool]
            - openmeteo:
                label: ENC[AES256_GCM,data:gWM=,iv:dSYnTIIYifwlz6DuyEprZg5giQJfCmKtYiwuJDx4XjI=,tag:m4Qm+yl4op9m4B4Yr6GJPg==,type:str]
                units: ENC[AES256_GCM,data:o9zUKzRZ02Y=,iv:J0i3p0OwSc1eySencvjcb+VjD/VvaG/hkiVDQAYf3sc=,tag:4LTCuyXVdP7nSdZn+6tl7w==,type:str]
                cache: ENC[AES256_GCM,data:Bh8=,iv:RxRuXFChIGtYX8PdYKjoXRoG/wzaKj650howD/HUwAc=,tag:hhNCF+Q0pynAwhD5+7Eawg==,type:int]
                latitude: ENC[AES256_GCM,data:Ko4uMvHk9uvP,iv:bBK+a3oJr9J/eFMJWwZIalrwSxlyVEaCEs/v+EVrPa0=,tag:toe8FWwLp1b3AL8bZxDY4w==,type:float]
                longitude: ENC[AES256_GCM,data:JML7Nx6FL8GuQ9s=,iv:o6I/tgTvNlk/YK17uoO6O4mxFu9pEnSzKV52xA65XF0=,tag:6aMWq0xRTBJ38snZ4vfN5g==,type:float]
                timezone: ENC[AES256_GCM,data:gvg4xP3weJfr6dQhQqeuk8kbzw==,iv:W0mJ0XPaqfHDF9iQmwUcBxrt4syEPeO+Ev1Mkeeliwc=,tag:WkqVUhm+PIs3+aYIhwuxRg==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZFRxMEJVQTUveThPUTJv
            MTNkaHQzSmVHbzNzYnRVRFFkTklmOFJUTlV3CkErMlJNcXFreDZqM3E2SHo5NTdV
            ejB2cEFPZVBTbUtWaVVrQlo1NXNtazAKLS0tIDhaN3JjMTlpMC9sSFJWRGpEMFVH
            b0toMWYwOHQ1dmUxZGRkeERvMGgzMEEKVZ78gRY/jtDwjzw1BJ+tsJJj19f0D+77
            E8CtZeXUGOH0LCXyjDqMny9h5R02Sto69BMvVa607h6IVVmG5W2zVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-29T18:12:02Z"
    mac: ENC[AES256_GCM,data:RoK/io0k3N6xJXAJQq/99cBPhwxGH8AesLbosH21TQ5zxonHUW4Sd2CReVH3HEz0Qwnb0cj6eLqf1qgUY2J1AJe8nv4jqnDw/pZDdYcCNb5IjXOLBjejp8/4TBimo58IC/ag1A6mGRsFbU3Lk04GkucO4CFQ3KZhmGszJkKTqPY=,iv:XSslUVEDC8CZz+XvCzCCVkF1sd+reXoFLNbNMCpZFiA=,tag:BrI4E3oEdzu8bxHnEdFjaQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
