homepage:
    config:
        kubernetes:
            mode: ENC[AES256_GCM,data:tuPBHlRHtA==,iv:hMABM2Q3+qh/qtKPvmDS9QkfxlhPDfsVmT+/Nrw2nw0=,tag:dJ70qST0RvkM9J6DcKiSvQ==,type:str]
        settings:
            statusStyle: ENC[AES256_GCM,data:MF6n,iv:vFtbIBc8KH70ZI8VKlQT8ygldKxWco5fBZdL528+6F0=,tag:FiEJHUFj8hAMpGZ4LA4wCA==,type:str]
            quicklaunch:
                searchDescriptions: ENC[AES256_GCM,data:Gb38lA==,iv:DKQto1I4/8hunVBJLC2ucpc026Zpz7hK7xjB9Uqs6r4=,tag:maVEesdA1GUzsPB/0f2uww==,type:bool]
                hideInternetSearch: ENC[AES256_GCM,data:kXgU8w==,iv:Pqb3yK+2W2TM6NAF5RbpU1RmTih+m2UL5fB7wL3XkcA=,tag:KOluMhm171h6fz6jZ+CHIg==,type:bool]
            layout:
                - Knowledge:
                    tab: ENC[AES256_GCM,data:bjngAw==,iv:KgVV1n/7feQUQ68xY+5LyDo8K8563tSgc/A7zwpHVw8=,tag:Q4m2hC3gJhKgXmF1GrkMCQ==,type:str]
                    style: ENC[AES256_GCM,data:7sk2,iv:1eUvhkzsfJjdsrar++ePHep2cpbZRB5m78+8uWtWRLg=,tag:mNrkonB7eOBQJsehQ69mLg==,type:str]
                    columns: ENC[AES256_GCM,data:ww==,iv:tRvsSaCcMTKB6UVQxe9K0PJ/6UtJOqACHIMXRbIMTSQ=,tag:O1mtA8rDWGsfZGxm1DkPtA==,type:int]
                - Documents:
                    tab: ENC[AES256_GCM,data:8urvtw==,iv:dVXe2xQSk6Y+Si/Ad0m/EBMRgnEQmegoe1Rj5fhbEHw=,tag:jjYPKYedBe/NRCOLSPwWWQ==,type:str]
                    style: ENC[AES256_GCM,data:3Rnu,iv:bS60Z1LRp2UWVuz4b1RZLuAIHfZXSI7JUIcbGWUlHaA=,tag:UA9OWheB5wx9aKvjWKZPcQ==,type:str]
                    columns: ENC[AES256_GCM,data:5g==,iv:+TLvri55xoSprGjoTvx4ZXxo/CalraOBl9yaEeYQJAA=,tag:+Zy2MKar8P/zGLvR8XeR+Q==,type:int]
                - Sharing:
                    tab: ENC[AES256_GCM,data:D3fK9A==,iv:uImA6ohiQ102dlhjvQcQSr9wC9so+DyQsky19I2FdRE=,tag:r2fvEQ7diFE9YTWrr+NrzA==,type:str]
                - Smart Home:
                    tab: ENC[AES256_GCM,data:K/Q3OQ==,iv:I/cyTZ5+OI8pyRUGFUvkymRnOcrkcjhRHXi247zwJ64=,tag:ITInkdkYdN1XQin1OjYWhQ==,type:str]
                - Miscellaneous:
                    tab: ENC[AES256_GCM,data:6ryiFw==,iv:gRUPy4emDf58QdnuLeM3mP7Q9sRkaB7udAZnM7QmfY0=,tag:xxvJ4nB0N0PEghC9b/L1Mg==,type:str]
                - Media:
                    tab: ENC[AES256_GCM,data:Mbtqob0=,iv:In1PLSyVdHJPXdZo4RaAOcwRp0SoG0F+8/F1vJzXnaA=,tag:BfpcFgF9znJVBq2Z1npMwg==,type:str]
                    style: ENC[AES256_GCM,data:XYas,iv:sHA0/5a59SSioFs8avL9m8RKPV7EiuM13pHQ1gaGUWw=,tag:WfCySvYeyWnDstSeKXOWig==,type:str]
                    columns: ENC[AES256_GCM,data:ow==,iv:6bl7nRm5zzNojmO6vvtbSez/1XjaDctb3mmOlxSYhIk=,tag:yxJq4D2tVPZ2ecOYckCAcQ==,type:int]
                - Servarr:
                    tab: ENC[AES256_GCM,data:D68Ng4o=,iv:WGnKuUrZnKMcbg9e5HFPW0U1dvfMcRQ2R1yeHbN1/Dc=,tag:BNFDm0KsIuIOP/zFhrjY0w==,type:str]
                    style: ENC[AES256_GCM,data:MfLF,iv:LWdor9+N+U0SpXnw+d/YFv43trrzPO1IkbK51I+t418=,tag:9skBLQXtLpkhPcrRMP+y8w==,type:str]
                    columns: ENC[AES256_GCM,data:cQ==,iv:IEPet2ai/BwYCbw9k8Mha6DNFeO+5AUs/msIkz/zKbE=,tag:pUI5/VQQYKxr2p8f0FKK0g==,type:int]
                - Games:
                    tab: ENC[AES256_GCM,data:GpeHfQ8=,iv:GLFJnwWUm83m8zHlU2zrEL8LIt76qUg1hmS+ReEc7Ac=,tag:TCJdsNHL4e4MHBg7Ye38XA==,type:str]
                - Unifi:
                    tab: ENC[AES256_GCM,data:hjGp6LC4BA==,iv:ytCzf8XdgbKYa3L7FsqbiThDf19e88wSG/UPv3E5XaQ=,tag:o0IZpSZZe5QomO9eGX/plA==,type:str]
                    style: ENC[AES256_GCM,data:Zz1x,iv:7/ZPty25xlL9IgqSZCj8VjtdXMWpHj5YYs0ZkyfilSg=,tag:2HJzqqS2h4hlFSmLWj6d9g==,type:str]
                    columns: ENC[AES256_GCM,data:8g==,iv:HjWepcA+/77km1lPYObgz3Br0DqdgTwpWlGedMsipRc=,tag:/MlT4B+uuhBFbmBxrOWWCg==,type:int]
                - DNS Servers:
                    tab: ENC[AES256_GCM,data:kzSwkq4y/w==,iv:99Cb570qt4mvPc8iA1EcQ94lrDolUN+fNBL6ZGJkQcg=,tag:vZljU1ZWyPIGiHlFQdn34Q==,type:str]
                    style: ENC[AES256_GCM,data:Bjif,iv:Oc+fhkyk2uFSNeo3L/CJopWwyGHLLFwE50xiISu+Jcs=,tag:mM5hQKwzy3d2rwpO6iB6YA==,type:str]
                    columns: ENC[AES256_GCM,data:ww==,iv:f7gRW9bZ5F9wcX3UN/BexnQg1aIOJkZejqmTsTg+kS8=,tag:0+JLWKKweZvoD2hcIxHSpw==,type:int]
                - Network Tools:
                    tab: ENC[AES256_GCM,data:WuWn1GAMUw==,iv:DW548E7Xw2ml8HBzFBc4Zh9eh44QYz4JlvrxbWnMCmM=,tag:cp7+SDOYixkAjX11UCDBNw==,type:str]
                - UPS:
                    tab: ENC[AES256_GCM,data:KtiueXckbQ==,iv:h4iE7sMXT6fpDzjvVboG1voL8vKZ98RJu3qptyrdFe8=,tag:YEwDrkKUkohMxF84UfGt6g==,type:str]
                - System:
                    tab: ENC[AES256_GCM,data:V+1FvMkqyQ==,iv:ZB419b/GzLFTe+3vU/nym8U822L7wsPf8GCDEF2G24k=,tag:5qfs4PHPCKWw56JoYvwfsg==,type:str]
                    style: ENC[AES256_GCM,data:yvVo,iv:8WIS7Vj7CVcZp+pWT54SO0jKk6orp9G1Hw9Rbw3Ad6k=,tag:sAfz3iBFxgpwkevmK5+yxg==,type:str]
                    columns: ENC[AES256_GCM,data:PQ==,iv:PHbo+epnBYo3hWGwrL69N6QGH2Vq6sjS2vMw6Xqg+nI=,tag:aJnjY8fbbkSODbKrIj2znQ==,type:int]
                - Observability:
                    tab: ENC[AES256_GCM,data:nLOfhPVxrQ==,iv:3cWxT3bdIvLg9X/KDu2M/5J4gS+EtQp5YVwqh0Tpol4=,tag:2+w0+9sgtipsul/varQqJg==,type:str]
                - Security:
                    tab: ENC[AES256_GCM,data:STIJVhWMqw==,iv:LnEhhy+XIkiC8zTK2u08BG37WbsFaGD1lZupcUlTDxU=,tag:TweCdCsAxICjBIftvrhhxw==,type:str]
                - Storage:
                    tab: ENC[AES256_GCM,data:ROx1ejDlfQ==,iv:cikjTKUafh2qWdWDlXvqjDX0QT40YVOs59boHyskVNM=,tag:QOPRFuY7qdYEIr26WlLD3A==,type:str]
                - Synology:
                    tab: ENC[AES256_GCM,data:4AjhmriQmA==,iv:Weroa6H+AjQw7UW+Bwo41FeEA3WKB1x1wicaUYxA7Jc=,tag:Sia1YA7x0Psg2biv6yY6/w==,type:str]
                    style: ENC[AES256_GCM,data:kWuq,iv:0jO0xITju5VHicLq01L5A3FKp+ZHeHCMW6oTkLSuQ4c=,tag:3mb3jZbAdXZuxFNXnY4veA==,type:str]
                    columns: ENC[AES256_GCM,data:Hw==,iv:1CLZlQA5oQ3W/1zasMDhpTkhb7IllK1RSNAjIwOETDM=,tag:utUikiqcICSHF3t6WWtFpg==,type:int]
                - Automation:
                    tab: ENC[AES256_GCM,data:ux/Vjg==,iv:UcUoNvpiHTYBna8YZ5CpB4bAg7JFPY9/Z4JTuF38kr0=,tag:macDUdpFd42qkqfqI+LLsQ==,type:str]
                    style: ENC[AES256_GCM,data:CzQ4,iv:zNChR8RTP46nogmhax/xq6busHk2Kpfk3gLljIpDXuY=,tag:LCWgQb4HPQI3YizlcIzopg==,type:str]
                    columns: ENC[AES256_GCM,data:nw==,iv:/Yolhy3gRVUE5Xigitvc8LTDbMzGxCmThXSYtOpY4tw=,tag:nWXuKKgherxG/Lhvf69ERA==,type:int]
                - Git:
                    tab: ENC[AES256_GCM,data:xtZZVg==,iv:iN3rPc4/ysbNHxnLhsfN46GyPd4RqtApGHawKWCeYXE=,tag:YFs31Nq6tHfL/iIxkurzhA==,type:str]
                - Artifact Registry:
                    tab: ENC[AES256_GCM,data:acfUlw==,iv:mTHsRklF1DpyPU2hr1qrg/oN/I+LCl8/Mv9WCWWhP94=,tag:j8zPQ2WJG18yBbKpLxLYbw==,type:str]
                - Database Tools:
                    tab: ENC[AES256_GCM,data:zhxfZA==,iv:SEdFRVEm0cGfFZRg3Yd6isk8RuF255QU6ANYeQ1rhbc=,tag:ihzluHmj4/rG2zE/De3tag==,type:str]
        bookmarks:
            - Homelab:
                - Homelab:
                    - icon: ENC[AES256_GCM,data:K27tucBlH4M+ylmvVFcu1v/Xzg==,iv:0I7wFLF7wUNnahrN4zUQFNBjkk3IJzjMOFEFrZigANg=,tag:kVM+vay1gLfwmKqbiTV7ng==,type:str]
                      href: ENC[AES256_GCM,data:ARlAF6qp27j7Eql/fEFS2x5mK1yn/tYfNoJ/6dTW8cThDg==,iv:YEyRy4cY4cPCHAXJBZghdZJLiaj9eaztrEtiHCjFVLk=,tag:38ddFgxbJ+5oL38L2n6k5w==,type:str]
                - Cloudflare Zero Trust:
                    - icon: ENC[AES256_GCM,data:twJu0/Nr/+N4EpqIXOY1DXTpxvQYYNqk3A==,iv:6xorR/wSmlTUqrFuUoJwQssSnibDf20vPN3pOrwohtk=,tag:IKjRypHwQ6gORs+sWqrMcg==,type:str]
                      href: ENC[AES256_GCM,data:KnN7Av3KcKcBjhHqVENCQjrzHb3hm/yHHXgBMLXV1xY=,iv:7cXBjy9PCFEkfP7O1CwsQuOxgkjcL5xkBBzRy0Fxyp8=,tag:zx0huZns0TGFhpwS25flSQ==,type:str]
                - Cloudflare:
                    - icon: ENC[AES256_GCM,data:mvl2OUIhMP0bCc8+evaojYA=,iv:DFCT2Z/iE17sz6WUYxl7dys1Jj6UjGtQLM3QRO65JUU=,tag:nWFXZNE73doJdqR0vwhhmQ==,type:str]
                      href: ENC[AES256_GCM,data:dj2rioxbR47WZMFfK+MJ+Skp5PKY1h2J4e0KFQ==,iv:l7v5kGVi0070OxOjNgfQ7Xiikk7aShTsmguNef0lwzc=,tag:GbOLrEbwDI1UKvNN/+zEyg==,type:str]
                - Auth0 Dashboard:
                    - icon: ENC[AES256_GCM,data:oGeLyFz6zknMV6anw7zVYy6B/1p4CKdIASekTzG7ZMyiSTgQK1lS81mnI6Ll,iv:ntjvTRX1OoL9/yIzYIr3UtEZj2nSvWg0yGogJdkhuTs=,tag:Cn9FW511IZYTd/njAA93hQ==,type:str]
                      href: ENC[AES256_GCM,data:lzHa7ieyAZrtixUNvs9NYq/OUBjW0ht0IfuW/v1fYxK4TNw6uann+QB8AmSOCQ==,iv:l44KYb4ifGIKe7t0LSW9IG5b2tedekwYlWZ8S4Q5KcM=,tag:6SsVowIw2wysW+Dd33cHVQ==,type:str]
                - Crowdsec:
                    - icon: ENC[AES256_GCM,data:CyBnuYNZrYLwPparWtCs,iv:psox/9HsCtYZovq84v/7VJAGKuekXQjhLq2Ndtx4MZE=,tag:w5oJQjIQflzhvtfKpSs8AA==,type:str]
                      href: ENC[AES256_GCM,data:oYQsoM77WJ9Oz9b87XCJpr8A4xQ1zGdUEw==,iv:hrsMY02E8GRA64Y3SfG3VkQ+E/4O0q29ZXUSypkCjms=,tag:TBDS1cH4naodM9l7ZTvpJg==,type:str]
            - Dev Stuff:
                - Mend Renovate:
                    - icon: ENC[AES256_GCM,data:kXgoc0F3RyHCwDlT9wb+hUyQ9ZvCvgH64XUYEi689edJxZ1WdgnQAw3LtXdMdQ==,iv:Jfb39eThaXi7VRy/OIN3WTlGfZZNkiKQalBVz0rIn10=,tag:1MVIV9hLtn9VVLJZqrGu7A==,type:str]
                      href: ENC[AES256_GCM,data:XLUs4qXHkXKzgQ0bsIQ5UZigbK8jovJgEMJZgM3TNRfDxNYh+5oQDUu1dDkUgnZn,iv:dmHJqnTLOTJX6GVwD5aF6/D6HnVoDJ5Fl8UjY21jG1k=,tag:m9wEdP0cnHFZWDufQ4koZw==,type:str]
                - OpenAI Usage:
                    - icon: ENC[AES256_GCM,data:SWD97O1aVH7x8w4E3F82XS4WuQ==,iv:Y7IdiO5eItvfUkVz6pxAASoSUwstmW2/4O/mA5N6ieQ=,tag:x98+HqQwS6EBVtoQUtQt+g==,type:str]
                      href: ENC[AES256_GCM,data:YSQFZQQPD63qLGhh4Th/T+czqlX+3IkLhxGhFRqmV5va,iv:dZBI53i25WEaZmeRhf0pL4bj4gEkFI3gSzys+7tP9b4=,tag:xlgmTsPczK1opmh97PEdnw==,type:str]
                - Helm App Template:
                    - icon: ENC[AES256_GCM,data:kpC8LpASSM3qfCTapd09tTM=,iv:oqzv95K/phuyG1cn0E7q83kJ0umm0C3F+wcfm89wZCI=,tag:hGcXyfPaa5iMcQbG6XZmkQ==,type:str]
                      href: ENC[AES256_GCM,data:m1C/sBa+cW/qrQKwVoJdIfzQPwBEBfC0Qj7XKu4UEsKVQfNGfBN025H3hXPNsw==,iv:QP5iv4iMHKJE8IGdZ0vOdMTq40mGHH3Qegmre9obX4o=,tag:cjQmIrG9u4PsigEiaghKhg==,type:str]
                - Selfh.st Icons:
                    - icon: ENC[AES256_GCM,data:9/nRdjXUHVVOidIEjH22,iv:LWwe5K3J/OGcHUBp8Dwv71VwPxJJpa1Zup59Meh5dAA=,tag:a1hXES14Cep6X0Kd13Npag==,type:str]
                      href: ENC[AES256_GCM,data:tWdEBU1KGaT8IdFcqcxXupE0d7TJV6E=,iv:6rRcBAWcn/2DqrTOBHKtSoNz0I58VtE9QTJCEnrGSzY=,tag:TRFS50P1CbaYzgGBwJ3ttA==,type:str]
        services:
            - Unifi:
                - Unifi Network:
                    icon: ENC[AES256_GCM,data:1fvcagwPqhKM7c3G1kuw1MJ9unc=,iv:yEm8ydRThzTtthsa3WtimJZQGqsVJ0vjFAy0MmgeLFA=,tag:62+ciIL1yanp1w2QkD9oPw==,type:str]
                    href: ENC[AES256_GCM,data:S2EgtvvjaRznvRNlbDVH49Wj8ZvQyAyNYksqL9A8SAEqZesf6A7pUu7dsEk=,iv:/a8OGHDUHanjZ1G6mFMnMBtCovK6vMS6OuqwAO4K0Lg=,tag:C6Xu2agG96fmKT1lNJlIyQ==,type:str]
                    description: ENC[AES256_GCM,data:iRIx5bEH5yFVlohXZRU/,iv:aXrMzen+UN3lk0tccTVZzmHaDch4HBbKgGkpW0F0lqc=,tag:Mia5ts69tbQTz9NfURqN/Q==,type:str]
                - Unifi Protect:
                    icon: ENC[AES256_GCM,data:O8jfO4GQ1iV87xx6KcASYhE=,iv:0I/56iaCH9phM7yjAwpRiWNs+AZ/kwyjvgxCh63NahY=,tag:lGMYFLlEk5EPIxBrG7w6LQ==,type:str]
                    href: ENC[AES256_GCM,data:6+Q+gUtotzYInKBk4GaIOFHCscw=,iv:bsv4AOQ/rMWta2JeqdcEMbwQEOfazLsYvX1OhukxW7Q=,tag:21/ilmGIiZgDO4X5JGRelQ==,type:str]
                    description: ENC[AES256_GCM,data:qu9ivi8V+A==,iv:Z3g8lKAgEWFVEd2bJ67ErqIRjKyFSBGCMI+O0qeY5Ww=,tag:Vpu+UG3bp9w0V1snNHVruQ==,type:str]
            - Synology:
                - DiskStation:
                    icon: ENC[AES256_GCM,data:QGtsEUk0NwDBfYyOMjNcfg==,iv:jXq42qagbCmaEiv4LzX+3lH8v3y2o2q5OHhmElF5NVY=,tag:F4ccy8ttrTWJbx604HvT4A==,type:str]
                    href: ENC[AES256_GCM,data:kcyXGyEHFPdabv8S0cgoiqp0J2MF/LFIDg==,iv:kk2FeHbLFXBhb7zGal7QrjaZAY+lY/GYp33J/gTnEdU=,tag:/X6dAYagAZHXPT/XcTn7UQ==,type:str]
                    description: ENC[AES256_GCM,data:AYJa,iv:rGaVXpB6umUQSS3w/pexHw+hWwj1PDpleGpHreE6hhA=,tag:B+uyGI2JIXb1l1zVOour5A==,type:str]
                    siteMonitor: ENC[AES256_GCM,data:UZxO8hS58HhfWH8+Qtb9PjdK65cHi+JFDw==,iv:/DLrkk94P6QFoltYbD2UcPZZTh+HF2+9+7CTiThQyxE=,tag:2E3Ku38tDwekK0+Odxu66w==,type:str]
                - Photos:
                    icon: ENC[AES256_GCM,data:WsF2YbDUO6eildLHTVK7jJ5b/V64hw==,iv:2rEwuHDXWLMRw5EsDqNK69CguwKhNopWC7+XvH40/qo=,tag:fG1o9zwG4P2ppfgp2QEMiQ==,type:str]
                    href: ENC[AES256_GCM,data:wekuVX8jAdxMl6l1zLari7/x6k0eKgIC0a9JzhOe+H8=,iv:o1x4+isoFa6kVSn0fll704ROAlEdtb4/S8k+jeDCHTk=,tag:D0m7MTiBoEOv1TJBdZAUVA==,type:str]
                    description: ENC[AES256_GCM,data:5+deT4Gem9nT0I1gHV4j,iv:0TqVxeRE2meBn2/OSMyaSWso5EBfl+swS4kmcVWUs64=,tag:aDdGaRpy1EUa/MnRBQhJkQ==,type:str]
                    siteMonitor: ENC[AES256_GCM,data:y8ocRBhVxbBfmZ5ttPJbwzK3yjFTCrj44LuSs2biMxQ=,iv:xzLXFsehpLgNGfcBSSGtOYGTAk0lT8JZ6Ecn8foCJRE=,tag:FCpy9143vwnLYz3nvTElfg==,type:str]
                - Drive:
                    icon: ENC[AES256_GCM,data:QV6G8UZ8Si8bq9XjuOKbdYAQTUCa,iv:Gd8EQvftSshHVt2Ij8TrN8QRe1so9iNMrTK6C9zNIoE=,tag:BDWampg9tgfFu4JIp9opEg==,type:str]
                    href: ENC[AES256_GCM,data:Ilvgm0uh7c61XYuEWSRRPrSxLq7htonvXW2rM0beOA==,iv:mA8j9M+md74XltGf+E31uiEJDgDKe4Yi7m+cc5vqDjw=,tag:QmroXDkZ+DUTaWZ4BanCtw==,type:str]
                    description: ENC[AES256_GCM,data:uWcECEqadvmP1w==,iv:XjNTKUQQRt2RpYcmACN23qlVlWqdl+Tsy8TGI7cYS8E=,tag:TW2E5JtLeLP0u9ITCdiocw==,type:str]
                    siteMonitor: ENC[AES256_GCM,data:dxqSOplDKj59/eKrV0LUuIUcj9y+1YotmGvThR+Yiw==,iv:cdmYBQA7aWWdpczh17hN1DKoQe73P/9MmlTQ/tJJi84=,tag:MsnSGgyW5fs5vBeUWnt1UQ==,type:str]
            - UPS:
                - APC Smart-UPS 750VA:
                    icon: ENC[AES256_GCM,data:q4E+eRqutBOvwQ==,iv:7MCiMJXMtyd2Czg3yX0VpjwORh6zbWjyaJR2IbJ/Djo=,tag:AMLwvwg0KR/ZrP7ro2eNWg==,type:str]
                    href: ENC[AES256_GCM,data:yYdVIJXL68pk9VSdU6f8wGJjV+1AC05qwyywXw==,iv:PObnUdi9jk2ETEes2P+69aNp6c8amCe8FlJ6hr6Rm2E=,tag:OTcncSy18deSOtMFVqIwCQ==,type:str]
                    description: ENC[AES256_GCM,data:3A+vtZ1G08P6jmrTb5FleQ==,iv:tbJMN8dPPc5rJHvJxfz3TPA9rWh5nRKn24B2DpVmh/A=,tag:t4uSLCo/YEgO8nFrXp/rTQ==,type:str]
            - Smart Home:
                - Home Assistant:
                    icon: ENC[AES256_GCM,data:0jPu3/oL4AoCnL7B3HQ+jL+IXYxu,iv:F7nIjsEkE+bjoLNIsQqJGQw90dORW53dU+Qb1kBXI/8=,tag:z+1JQPTwDEqg7mPmW7sg4Q==,type:str]
                    href: ENC[AES256_GCM,data:C9eZT1xKFMwrtK15EAHWF6ito8LOzT10OZUCOEEOAFM=,iv:w88PaOPoxA6Ofu1HIl0SIaMswhAnPk29j8KJvORlGEg=,tag:RYgl+VaFB5qbqvEfe018qw==,type:str]
                    description: ENC[AES256_GCM,data:rgDD+Ink+k6bc//mqow=,iv:7PsHDybXMml8/EKZdwXXWPZD3ES62HwQjZxzA6bGWYY=,tag:Gk73nkP2le8Eyk65JH9f1w==,type:str]
                    siteMonitor: ENC[AES256_GCM,data:zLK0MBL169f6p/X4qiJwQEmZ7Ty2lZGFWv0=,iv:mzMggoBxszmHnqPnK9rfaAc64L3qo4bqLsGvFNUPjOE=,tag:k2gO4dgfDvEXOY+zcH5kjg==,type:str]
        widgets:
            - greeting:
                text_size: ENC[AES256_GCM,data:+TBP,iv:CVYos+sTr2upeoaVjEZFoGBL22ktHVvbGiNOa9Tr3+A=,tag:LtZJWL1g71IT4w28FcEsVQ==,type:str]
                text: ENC[AES256_GCM,data:yQpeJeS84Oc=,iv:T2/FOVhsTFVATjncdkI3ic5h1Q0bv2annSkcjhbovvQ=,tag:nCpqoDKbReDUs77wCLAzug==,type:str]
            - ENC[AES256_GCM,data:GEcAZBnpPpTtXONRXKShCQybKRkoNnIwcUo/LEyMgvxbgugMr5CbpYx611TgikpXZgnSP7TnnfBrz1251Luw8L/BZDU9lnbZ/mg=,iv:VuUb214q8c7yHeR/ILtCnN0gr6zYQ4aCWEFqRhxxcYQ=,tag:JXLTzjC+j7LxnXG7MbVYqQ==,type:comment]
            - kubernetes:
                cluster:
                    show: ENC[AES256_GCM,data:f9Fshw==,iv:d378F7ttg3RygzdHfNWBxyuWteXYEl74/GZwg3WG+8E=,tag:SzyBjU6HT57fwXCfyjSX6Q==,type:bool]
                    cpu: ENC[AES256_GCM,data:3mNpOg==,iv:C3db5duLar8TbKZWLFe0DIL3sxkyhgSdvrt4tvQkwQQ=,tag:XaufYmQVPPOP6/6/IDuKkw==,type:bool]
                    memory: ENC[AES256_GCM,data:qRcFkA==,iv:5xEYPtSheNvxnf4KK6fFFAMYv+Y5y0r1l8HMro3tvkk=,tag:I8Y+DVo4U03yHzn73Dm7pQ==,type:bool]
                    showLabel: ENC[AES256_GCM,data:nyHU+Q==,iv:MqlyQ0z3p38O3l4Yy/3p5HH8NdrpFfhTZcaOWdAhnC8=,tag:sCgKZCgE5+MkK2H8RbRz6w==,type:bool]
                    label: ENC[AES256_GCM,data:156DecGgsg==,iv:5ycT++dkLM1MRb+CBewIBQo2t04B6y6pJN7U+XPHT4U=,tag:6r6e9cWlHvK4AGeq74o0CQ==,type:str]
                nodes:
                    show: ENC[AES256_GCM,data:L3VEVg==,iv:fX74i3DO0wOfybIn78b1q5Yur9FwYLPNBeJZJP4XEi0=,tag:Y5ehskoeWVr2MyqNP2GCow==,type:bool]
                    cpu: ENC[AES256_GCM,data:7k1OXg==,iv:lpwaVviUFhDSrcUvhaQXuyi2FW79KC5hUrD3Yubmh2o=,tag:+zeEzjgqu0oE4p7tQMoIPg==,type:bool]
                    memory: ENC[AES256_GCM,data:x/2eIA==,iv:BScB4MfsPm+zMEALwTxotIjardfsHobB6ST1Do2j2Ao=,tag:5bR0idCgG0xlsDG7bZ2TOQ==,type:bool]
                    showLabel: ENC[AES256_GCM,data:GaNhgw==,iv:gJYLDYVdjD4NZ0DUE5Hpm8B3nVfqsDL6VP6aoBPog+o=,tag:TP87u9D8VazSj7fd8JlzHA==,type:bool]
            - datetime:
                text_size: ENC[AES256_GCM,data:1vA=,iv:Wr+IdBY+DJxYex5kx+CqCDIrOn9YzMqIMun8Q+rzzzI=,tag:F57/FPnk5C31fRq2aUFxlw==,type:str]
                format:
                    timeStyle: ENC[AES256_GCM,data:k8RfIDs=,iv:8e0oGMhB7dCNyvNbmxuXsvbkoRW98Fdqsl2F1XUJ8LQ=,tag:Lx67XfC7r+abbQG0kAGgqg==,type:str]
                    hour12: ENC[AES256_GCM,data:FsklQQ==,iv:xVYwrbyodE8B+GF1vd54/0maSzbMONufBAOCuXrlZWI=,tag:suLXewc9Y921K+kq2tnVFw==,type:bool]
            - openmeteo:
                label: ENC[AES256_GCM,data:404=,iv:UPT8yS9cHqnTUXE+rA+NyBYRzMuxZBblfedxHizfPjs=,tag:kuc4B8KN50R1Wb2QVmIIpw==,type:str]
                units: ENC[AES256_GCM,data:luWyR4gYUl4=,iv:Hk455o2jOQEq70iY8LjdYNn1JIwyPPmbztG8T77JQbI=,tag:BbQ2cbYnK5sVns+QNhxxsQ==,type:str]
                cache: ENC[AES256_GCM,data:sjA=,iv:geJgmwTO9a3u752F5Tsvy5eOB/6O6cDDduYEmvNKgwE=,tag:styF6KyVvgznOjmEiDF0Zw==,type:int]
                latitude: ENC[AES256_GCM,data:iIqUpmHRqXRb,iv:gotgB7S79HYdHh9h08VoHyF9rhYSZzwmS3i5BvtqbTU=,tag:YbSIS28TZPhmXIgfm4Belw==,type:float]
                longitude: ENC[AES256_GCM,data:19v1IX45inKm0ts=,iv:hbjhdf+AMHLRF7LkCb+6VXea2JixIpLGNCiRAA/8Kik=,tag:LpjFfsDEc4EH3buo+YK8Dg==,type:float]
                timezone: ENC[AES256_GCM,data:69EPMRyxW/ycT0mu/0Ycty28Gg==,iv:kkdnh6K5kK1V6xAcniBXJEeXlR673oByra3rRk2fJu0=,tag:KEPJ508jmvAgPuDzOt9PSw==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTVpUeWhETSsvWC9IRDZh
            anpDNnJXTVhIODVVSWo4Rm1wWWYrNm4rVlM0CkZiL0o2Z2hXME53RHAxNkZhNEZB
            aXdIVFdtY3RVd1o0MlJaRHF0VFFEdE0KLS0tIGM4Z01YQi9lUXl6L05ON1psZjN1
            ZzUxaFFta2hKWERDN1dZNXc5d2wzb3cKd1tMLjsCXuC5IoeWa4B6Qoa9l7u02iA4
            YLVWm1hk/90PYUklCg2no5NG+IA2j7z0liQR7ZLBSqzjl4/ogV3JCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T05:58:15Z"
    mac: ENC[AES256_GCM,data:ZxpUD7ax3fBumJc00fKcljTyyEljXezYxnahD7t+I0/v/aI5EEQmXvrZPGzPjI8r4n++0SYewQZNp9miY9YykIy58e7wzqQJZhIuEZInPZmDHP7ZZTiW6vsDNOfzsYx8ZQaF6goo10QdVLGlCAT2PspStskWt7whLLnG/MnnQE0=,iv:J6EtQK5WMpb0K6AKoAEiux8OKf6DNafe70ljwKHB2Ps=,tag:tzqIMtWy0HK9n42i0EEZsA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
