homepage:
    config:
        kubernetes:
            mode: ENC[AES256_GCM,data:g0/xCEUveA==,iv:6g1JUdNgbIvb6Yq4FRRU25fSX9ao/54ApRTQmEbi2Qc=,tag:pHRpD0ypfr85TqIJmSxv9Q==,type:str]
        settings:
            statusStyle: ENC[AES256_GCM,data:mQ6i,iv:xG2RbgYtSJYPCr7Rckw4x4ocnBiI3ag6S4y1Gv/v+Aw=,tag:f1HtSTJRU/GebiBjWHbZzw==,type:str]
            quicklaunch:
                searchDescriptions: ENC[AES256_GCM,data:zNaIuw==,iv:dH9UOkqiZA8xr7sMWdP9o2frjM1fzvz65Tnm+c12QtA=,tag:U+Ger467HDxCzbmLz2MDbA==,type:bool]
                hideInternetSearch: ENC[AES256_GCM,data:RDsRbA==,iv:lwA9OMSq96pmywj/jhIAJJLOPuut+4fHD7nQWAnyaKU=,tag:VYAI170Ls9Ad50Qlus2UPg==,type:bool]
            layout:
                - Knowledge:
                    tab: ENC[AES256_GCM,data:y88weA==,iv:zFh0LnBwMQeBvSCpq/mdpgio8oZWeWitKI6hTaI3ulA=,tag:DkFtAuT/n15WNz2bc4vLmA==,type:str]
                    style: ENC[AES256_GCM,data:OciH,iv:XtrBrIHv0OmrCrOglUBQenYNq95GJaXrnuMezZJKzEY=,tag:9Ta90wR1pbkI3wVl1wELIQ==,type:str]
                    columns: ENC[AES256_GCM,data:5A==,iv:UL6u/L4pMPjbUBljbyFa8lJd/p2z6ZeTY3ask1rHwZs=,tag:wAcm+l437eTysl6MOrbjnQ==,type:int]
                - Documents:
                    tab: ENC[AES256_GCM,data:8LcwFQ==,iv:yZddtMab4eDLoHkBj4JWlapMKJxltoCJX7t1CwrN8v0=,tag:k3KDTOCg8N+ScagdvvxBJA==,type:str]
                    style: ENC[AES256_GCM,data:R1R5,iv:8yBWLnIKbFmahj8azlmjpc3jP0coCwvfW6i3rt9MJT4=,tag:BBAAYkgexBAv7u0u29RdNQ==,type:str]
                    columns: ENC[AES256_GCM,data:gQ==,iv:5gf1TQlRJ0m4x8/s81GJmLH5CATEnaAhpB/s9FyiBVg=,tag:YSZdGFSg+uQMhoLXlmRjrg==,type:int]
                - Sharing:
                    tab: ENC[AES256_GCM,data:cErY4Q==,iv:hzCwoj8mIu1PxuHplHE78jNOH5CqmbaTjwlkTDUix2Q=,tag:lysjXgYuaBYxwv/gk/sVhg==,type:str]
                - Smart Home:
                    tab: ENC[AES256_GCM,data:/j5DBA==,iv:gMmGwzupBJMxaXTbzdARELQmngCvpQ0hOpcWdIVQqlc=,tag:Dbet7CwpKKUZkBcsB8oFAA==,type:str]
                - Miscellaneous:
                    tab: ENC[AES256_GCM,data:TRPhiA==,iv:LayKAqF8oTp2WbCsTzrSMlyJBtF6FxfZUf0US+xzp78=,tag:z6+bAplujpIVkACKOaQUtA==,type:str]
                - Media:
                    tab: ENC[AES256_GCM,data:AdGX7Lo=,iv:+6/j5QRj8NnMA6qDph0nIS8YEPsM28eOizuxu8HHKCE=,tag:R4dlBiru8mRMlKcdDJj7Sw==,type:str]
                    style: ENC[AES256_GCM,data:mKVe,iv:IKG2Z/uNelLFx9C2lMi5LbLbqCJzWpdZiWoZGSoKbXo=,tag:eaIzQY93HmfRPGtsi3vG1Q==,type:str]
                    columns: ENC[AES256_GCM,data:Rg==,iv:svJh3Vb19no0x12/CjkXM3RxcqBmUEt2vvUD7oz/HAg=,tag:DOlAHM2Ku6iTXSPIKaAeHA==,type:int]
                - Servarr:
                    tab: ENC[AES256_GCM,data:EX5kXsA=,iv:arqCxngbQ72CJMjAkjJbp35rXQ1FQ6Ug8GmbWpJnJ5w=,tag:kUvKuNHEtOLtPRM45MIggQ==,type:str]
                    style: ENC[AES256_GCM,data:YWli,iv:mTO70y2dXe6gdQU/LL9mEOcjqRM5jWFQuh7fFREUJBk=,tag:wRJIQCeiieBz43GaP+e1Yg==,type:str]
                    columns: ENC[AES256_GCM,data:oQ==,iv:kRAs49GuVzl+3ZdD6mWRp7c445Wj0Th4U/VnOzt6wXo=,tag:YKcRj3afEUZOsWHf7yQTWg==,type:int]
                - Games:
                    tab: ENC[AES256_GCM,data:ZcxELpU=,iv:ceR6ZCjFTvUeKEKRQ/NQxqNU06YQN+7UvZ1BrRwLapA=,tag:nXlfoHWX8pRtoXDNMYbgVA==,type:str]
                - Media Tools:
                    tab: ENC[AES256_GCM,data:sR0kAMI=,iv:JE/TBK69hIHNckKfG+w/GJNZSegNtvPphkeJFnSf/5M=,tag:DC/DXqi6P2cKkmuBNAlztA==,type:str]
                - Unifi:
                    tab: ENC[AES256_GCM,data:a7dNGASWpg==,iv:egnMkGgdpyWSAyD4XNlwcB70MXNrNXF7J8n9ZaKM+ag=,tag:WeZnqhc+6qJ5v2sXJ6MB5Q==,type:str]
                    style: ENC[AES256_GCM,data:+9ct,iv:7bX3a5lUQgpoLjHAJFdg2AHkgbV/Pju83AmBHD0UZdY=,tag:O/WQqVmBDNE5NjCFaxmXuA==,type:str]
                    columns: ENC[AES256_GCM,data:OQ==,iv:j6/Vb2eR+HVWRKzk+oRSEVzoBdwtDJUIc6upzJ9t/xU=,tag:Pv7+rgoNGdVStGWr/PW5Sw==,type:int]
                - DNS Servers:
                    tab: ENC[AES256_GCM,data:0wdM2tEVRA==,iv:/AAqL2eHzQ1/y03IaN5qx8QQomHwAJ0PzhgTbFYb3So=,tag:corPBN8B3tQD2runSmJfOQ==,type:str]
                    style: ENC[AES256_GCM,data:iJ9C,iv:9k7relu3Z6ZjFxKOoEJGs+hPqSYGgbYgDCDZ3UvcCek=,tag:Ll2tIidx4tptS1HQAO5k9A==,type:str]
                    columns: ENC[AES256_GCM,data:kA==,iv:MHcn6hxLxjRuhDUFoZgJI0zvBHq1QmTdulAbLkC6/Ec=,tag:66alUR82Xa8k/W9YCmU4Zw==,type:int]
                - Network Tools:
                    tab: ENC[AES256_GCM,data:h98s979bPg==,iv:JQjOI/P7yOTSx8Wfl0QpN1RkgqzfjKtVE3p5tGPepCo=,tag:3oup0+Y1FU+lXd/0hQJgnA==,type:str]
                - UPS:
                    tab: ENC[AES256_GCM,data:YbgAbD9Qnw==,iv:N0Qg+vSQ5IY0F/Any4L3hVwLG/kiOMkc7S71k5PAhWA=,tag:EgMczqq8cZFXtfH9BS2sZQ==,type:str]
                - System:
                    tab: ENC[AES256_GCM,data:afIEU7mqqA==,iv:BE3yL4LTW9OY4Ciyu2n+t9PTymbRIzDQwdNIn6jahtc=,tag:qE3aEoPcPQcdSKkZY9JwVg==,type:str]
                    style: ENC[AES256_GCM,data:G2PX,iv:i5zBoqkK4H4uexpo3LyeVg1Acu54d9fu7YkVrPKNYTw=,tag:d2bYeoyI6yknrBqWCYM5ew==,type:str]
                    columns: ENC[AES256_GCM,data:Sw==,iv:DMh/ZA6IfUuCN/wTFer+IXsxTUNoqRPrpqKequmDocE=,tag:bN2XnUH3PcAaEK5Ma7JT/Q==,type:int]
                - Observability:
                    tab: ENC[AES256_GCM,data:s0KbVmKr4g==,iv:3SROkmB8F5NcTrtC3WfCDkptV6BQnWMIRQW3ePszw1E=,tag:tx/tASTfGk4gAZcWMsiANQ==,type:str]
                - Security:
                    tab: ENC[AES256_GCM,data:3j36kO+guQ==,iv:k0pdgpyziHmzr4WbHvIPmDj0e+cXlXNWeRclMs4WugI=,tag:s7n1vYSGisI4HwRb0lyyIA==,type:str]
                - Storage:
                    tab: ENC[AES256_GCM,data:U7PszYcWGQ==,iv:vd2XLK0iiVN5pBkY9FZNGkQv7wUjmqpsv9ctbzL9phE=,tag:2U2RnQiEBQPlhthmdtnrXg==,type:str]
                - Synology:
                    tab: ENC[AES256_GCM,data:guhMsEQ0Ww==,iv:CHzvCTRuemY74QKT57IPTMONJpjOCVMl4V2j7NcMy4Y=,tag:GKaB+FG6XGvIsUpOFpBPNQ==,type:str]
                    style: ENC[AES256_GCM,data:7lrY,iv:3/s6OnL9cg6LRyFVkCIjtbC+OwHY0Q8J97C90NmDr4k=,tag:sl1WEzQIte8JSL9EfxTucw==,type:str]
                    columns: ENC[AES256_GCM,data:8Q==,iv:TNirkrFzMUquz826RI7NdDjaQ1fN2rJxEqzNbkRY4Go=,tag:7hAlCn48UuKtjfaQerr9ag==,type:int]
                - Automation:
                    tab: ENC[AES256_GCM,data:qT/lxg==,iv:8S9wEw4qwlOQxrJNVPw2Z+OgeK/BCkgS6i1FjVhoBbk=,tag:YKVRK50X9ar4ZQ6IgSYbzA==,type:str]
                    style: ENC[AES256_GCM,data:Dwod,iv:99Vh8trRDjTyElRR7GiRnPSQDXzGVR6tk+3wBmsQDZA=,tag:gaMWw1FBMZ00nnrQAJZf8A==,type:str]
                    columns: ENC[AES256_GCM,data:3A==,iv:NDgDXVxJRxxZedu5iS8NCqqI2/B5Nbf7SAQhVXmVtCY=,tag:74DnWLVGCCRDIyuX9ENqnA==,type:int]
                - Git:
                    tab: ENC[AES256_GCM,data:KScYhQ==,iv:4luEkflWSTXjvJLFsgjgmrUqsLJc7iWUjGylKkXQhSA=,tag:JD45JiPdtr/fPyjA9iYRmw==,type:str]
                - Artifact Registry:
                    tab: ENC[AES256_GCM,data:ffjYQA==,iv:qU8GKhzXWqNJtLPiug9PYiUiRERD4RCcpruRmF4qqFo=,tag:/w5wb3qEwTomdpXYAR31vA==,type:str]
                - Database Tools:
                    tab: ENC[AES256_GCM,data:SmMcjQ==,iv:1VH9mBBUVrDTBWBS9YGNflfNL2HDRsgnJGOujWYuykg=,tag:x53RmUqPHQ9/FVzZ25USgQ==,type:str]
                - Messaging:
                    tab: ENC[AES256_GCM,data:KxtJrg==,iv:zlRURicBjuekRAQrZOngXyw4ZMbvUSo0EMJQDfUA72w=,tag:qtfA9or/x3d9aTkOHHuugA==,type:str]
        bookmarks:
            - Homelab:
                - Homelab:
                    - icon: ENC[AES256_GCM,data:rNM1i/Wz+DelCG9bMq7f6ve46A==,iv:P0SiQ58/IVn5pUiR5CekPM0MdxzOhFzAfrFRE5EgNJg=,tag:FSxMZUwGWxwKMOT722AA9A==,type:str]
                      href: ENC[AES256_GCM,data:1trBWBYoTpDnIdkvUqPq3xDenEhb0rFn58MQAczy4KmLpA==,iv:ySf+VS8dQo6I3CLDRT+4+m0VtbxUUB7U9cTY4JUEZjw=,tag:8RQLHLM1tG7jpLylH4UImg==,type:str]
                - Cloudflare Zero Trust:
                    - icon: ENC[AES256_GCM,data:oYxRsFPCHjJ5067EY/zEUNzgLYIGLrJtsA==,iv:H1TvIJuKDMzpVYyQuQs6Q+Kp1cZ8cFMxMpC2UpLM3H4=,tag:MWZOFltwuTcaE+AGayU0TQ==,type:str]
                      href: ENC[AES256_GCM,data:nsKYH1WHWtu/zNBHBbAzT0Csxu3agtj1VntSTlUmfxc=,iv:KNYgeCOKuQrAjnC1TCLUtxndEnpmK1YHgf0M0m8IlTU=,tag:3rtz7D84cxX62Xx+unvjaQ==,type:str]
                - Cloudflare:
                    - icon: ENC[AES256_GCM,data:fAbb2NEAjrDVwDf64OxwSAc=,iv:rHzucUyIRQoHbwCRtErB4lH3sktHE4WTQc0Jp+FDULM=,tag:Y/bj3NN7JCZ81j9Z23hIEg==,type:str]
                      href: ENC[AES256_GCM,data:bRYN7aukAzxyHWMyK8Ea+a1gkIoOm7GfwK9+eA==,iv:k3f9OAX8RNGFtaYgX0FlqlebRMbv1yzKGINhRgkttyM=,tag:JX/xoh9XsN/X8S/8Xa9viQ==,type:str]
                - Auth0 Dashboard:
                    - icon: ENC[AES256_GCM,data:6xIPEtNrKmn9ShQWNv6/8UbMk/0uZ7T64UJ96ru7mHqsewlkJmz/mXsRuNqU,iv:AIulbqC/qBs1EpRxG0/2ZzsqLMZ2A8Z203Lc6SdL+eM=,tag:yMF6AfwdGXlYhW8oOdn5jQ==,type:str]
                      href: ENC[AES256_GCM,data:XvgKk6cwmGvAUbBjlp9QTPteH6kpSZ8tO1Huqy3JXN4Rub2Db9ocNbxs4mMryw==,iv:2K+2cB5yiyBPNM/xSzGVKr/mUhLuwS4v9grssc9TpQA=,tag:xHUJmTPnouwWKoSlpPd7Dw==,type:str]
                - Crowdsec:
                    - icon: ENC[AES256_GCM,data:2OXwzksobUiVUV5lFURT,iv:GYSf9VY8hw7Dji3tb0LwKJZWL3CK+oJmhvH2ACDhoQ0=,tag:VBGgVJ0Ljc2TDCgq+UbQXg==,type:str]
                      href: ENC[AES256_GCM,data:RU9Ws6FBkulrQ8UrenIQmrY21VQ0y8GN4g==,iv:sC8mQLe6rDRpPiq97gYUVs6+UHecr5CXKiIlhroJPBU=,tag:gTy2dzp5focb27X2jGSlsg==,type:str]
            - Dev Stuff:
                - Mend Renovate:
                    - icon: ENC[AES256_GCM,data:pCmfotyLYVPvZcX7gOPWa8JrSeXrWBibyV1GkZ5l7KeQOtq+4OhjLiz3lczW7g==,iv:sQECJeTnMW6MQjjeuwQ11oUMFVGGdJyqyih5CbpyMm0=,tag:TO17GGFgZi+4LsuYSlah0Q==,type:str]
                      href: ENC[AES256_GCM,data:k9uDteS/FUGF228uJ5oPvGW5LxALZilYLo5AWX1vQQkU0FJS4AYc8OOqQ/agBx8k,iv:eCukh9TopqwN8hVByM+ASMOck1jOsdzFMRH/axvPUJI=,tag:2FLUDh4gxBso73r+xQTtNA==,type:str]
                - OpenAI Usage:
                    - icon: ENC[AES256_GCM,data:N5o0g4XFQf5Z+N63B9BPoFMwag==,iv:oWh8Eo46y/mx3rRO8wwDdgcyKSXOWm7sypTZcxTM3LY=,tag:ujCWqBty07K/QQapCTjqsA==,type:str]
                      href: ENC[AES256_GCM,data:dN75+r+WIX9yyvVYXZ/8N41iJsFZIlZ7A69+REOMwZdu,iv:4e8+fypXM1c0IH8v4TnC/AC1dLMWhY+Lcp7RMRC9WME=,tag:7VHcp56ylw1631G9Jaizpg==,type:str]
                - Helm App Template:
                    - icon: ENC[AES256_GCM,data:FbS117Uko16ZV5v6jlPmw2s=,iv:5tkG3kfAPnBdhSocww0YQwlRAFKIen2HhtnVUlhHzKs=,tag:vluWfYrYgsVBMhEdej6enQ==,type:str]
                      href: ENC[AES256_GCM,data:bJ6u5kpmMwIYRzWza+0SIoD1Y7SMrKKvZlWzutwyWhNn+FQnR8p3zcarHg5dqA==,iv:WSX/oMq2VhC2NeE6LgY6ADuxkCnZ/RHQ4l25Mc/saYI=,tag:N2lx3N5Y1CR2MvCzNoTJgA==,type:str]
                - Selfh.st Icons:
                    - icon: ENC[AES256_GCM,data:P23KZT/YeaLAd+E4Z61j,iv:hF9McIs1tT82U4ilaqzoBDNx20/SmtIJdh6txe0jVy4=,tag:SXt4k/D9v1XTF0IIU9kAaA==,type:str]
                      href: ENC[AES256_GCM,data:CeFtarvxsA+IJU2FQbE6RFRhZJOj2sc=,iv:Fp0BlL/QU5Tbgl1Y6SegMioolY7iyEEtd2xv/TSYOv4=,tag:q072Rf2IcJM6kP+pPaTrcQ==,type:str]
        services:
            - Unifi:
                - Unifi Network:
                    icon: ENC[AES256_GCM,data:w+7WD/KVpvp2H/NVtpuzCxSDN+Y=,iv:3wuAuzj4EEVqw3hiKpXvljMgR9XepcPguyYmvcT6I3M=,tag:3VQwsdQkscuQpDrUcAU9Yw==,type:str]
                    href: ENC[AES256_GCM,data:NcTtGKdFz2IAIWCd6ghXlPu6qxYkdFl/RFYPdg4uEDo9lpX7RxcMjL5Kz64=,iv:+gyy/KbrU8npEtAHVSzJnUka/gX6vg/4FrxGVwaq8m0=,tag:uVDgS8Bsia7j8sXmopJQxA==,type:str]
                    description: ENC[AES256_GCM,data:CIKr5ACvzTS6uKPecxsv,iv:0CY0rsiEZBcWMOUmM+4gh5+qn8r9kKT4xcPMKtcua/k=,tag:4TXxScSTroJXBjy5xcuDXQ==,type:str]
                - Unifi Protect:
                    icon: ENC[AES256_GCM,data:kPA8CgRvETjesUlDZhuVFPY=,iv:5drO365aRl5J5esihI/iY/BpG0GzTfKzEGMwjwrTBB8=,tag:zsUCJetzCaM01DaMYIqDmw==,type:str]
                    href: ENC[AES256_GCM,data:Nhp4vsh1XFZ0e/l/Yw9KwBpSFSs=,iv:lPSEcbnZ0VF27Iym0WRCE7Ho0TokvX6LGG/C8tyZV8U=,tag:rYOHtp53WQmuqlHYFEi+qA==,type:str]
                    description: ENC[AES256_GCM,data:XJNMG5eP5Q==,iv:kUvQvwcWSFrymWW83b75NSuW8B2xYqnif7MCIkjnbLg=,tag:3p88+2wGOEKWZ8ucbasm9g==,type:str]
            - Synology:
                - DiskStation:
                    icon: ENC[AES256_GCM,data:5tKLYMeVo+/zd9UtP0yOZQ==,iv:oTVCYV5ergwNwdMkLVduCTQ8LAcLsRhfehww7jhmgoQ=,tag:AYpmLojcRHqNwGVVfvIWaQ==,type:str]
                    href: ENC[AES256_GCM,data:b6Tz5fwfnEy2TAahru053ljboK31SDWVIw==,iv:ZuIfpwZ0BarnDBaiuVyhu28m95gPYRXN6Qye2ZuzyIM=,tag:oXdS4frHkbE3nxzTNgCy9Q==,type:str]
                    description: ENC[AES256_GCM,data:t6jl,iv:n16nnH6611igmZabwqW/V9O5IO3uDT1Am9FyJlEht3s=,tag:H/4z8+uJlZHieLS/S4bYww==,type:str]
                    siteMonitor: ENC[AES256_GCM,data:R/qZZdVR7jlvCdaxOx4pSX9huJTGQxZnVA==,iv:tZ8Ls5V9xLv0dNRwuK9u2pOTn6kmbdTMHfUAFkjlmR0=,tag:FKMVLmr+nBjfDxeXo/2Etw==,type:str]
                - Photos:
                    icon: ENC[AES256_GCM,data:kUyXMt9JDQruGL90KIGtaG3LmZFD6A==,iv:RB2Zg9bUwnRufFORM2weSd3HfFyzUN23QveRh+xxR8c=,tag:z4fn86/CHDOsGCqddaAo9w==,type:str]
                    href: ENC[AES256_GCM,data:Re1lsTlAiyjPEG37BTXT7E9sfYBZBG+KiNE/YcS0VOU=,iv:lnN2t+qytxgQKeVAe6en0OMZv+ZBAVV7MJqL9c5e3x8=,tag:/EsRFLr4VDdBDYwQySpNkw==,type:str]
                    description: ENC[AES256_GCM,data:WWY4X4TjXe7NutX79IqM,iv:X4K3UscK8z9QX9CVDbrxHVZfDMBsJhQ9ZOmb2kipyOA=,tag:uno7B0xWqygaEmqLIkbmFA==,type:str]
                    siteMonitor: ENC[AES256_GCM,data:UIlrZ0kVLeUqAXe2XTbtRW28sKEZtDBlXZ+2jJgEVtY=,iv:X90rpwrCthLEVCIUFxNVhvQKzJNOiDgvqsekP0srxas=,tag:pALX0CkDKr3qsTs4rr/Xsg==,type:str]
                - Drive:
                    icon: ENC[AES256_GCM,data:cnVetJ6r+BfmVcVTsx75ZzPjYWcI,iv:3Nv500IEfLcwYbWQy8Y4S9Jif8wfTFPJrEiyuCS+fjk=,tag:ucH/xiQG4A5CAqR59BDZjQ==,type:str]
                    href: ENC[AES256_GCM,data:m/sicfbpHir3oH121iy6+h31L1a43ZSKbQgE9C3K4g==,iv:QECmRKo+m+WHyC1xhYBmSTW/Uq/U7nIE7eDfGlPWbkY=,tag:CVuOh2uxFQ9cNSBzXMY4yQ==,type:str]
                    description: ENC[AES256_GCM,data:xzQ5NJcReKutyA==,iv:YRiVH47/HkCUCQuZXWdCM/TfVIM2O9lddNRUhJpLEsU=,tag:RkugQNvQajYY1had4jkmWQ==,type:str]
                    siteMonitor: ENC[AES256_GCM,data:UGIatueAOvRTOpOxsPlawXX4mGniQeJIVJklNi08pg==,iv:B2GD95VpZkEapbXGoIJWT1oZKIFAFzlv3fQzeGfEZtg=,tag:XtgeOTk3vTKfS/2+NS33xQ==,type:str]
            - UPS:
                - APC Smart-UPS 750VA:
                    icon: ENC[AES256_GCM,data:USmyZn4TQNhGDQ==,iv:heY3JGQe4Tr1fRPh1SeJjMDikvqpTS4GW0ZDEApB404=,tag:G3BEI3uMvX2DFqRwIGoO/g==,type:str]
                    href: ENC[AES256_GCM,data:bmWnPW3jUBgJeWK/XVbTu45rRzEOza29Hkzk3Q==,iv:c6yu3x1D0GczY17Hnikfeb2DPCcwcnZSAmblXdUnnm4=,tag:yRpTmnMeeD8lYYfY5vUtEA==,type:str]
                    description: ENC[AES256_GCM,data:jyB//saevgNH4AVuH8fnxg==,iv:wxYhqgR37vG/U4t4tsFj5i+DvVJQC7JRnl4FLqprj24=,tag:edIde+0BkiOd+IDT53XbtA==,type:str]
            - Smart Home:
                - Home Assistant:
                    icon: ENC[AES256_GCM,data:4Z+kegLDGyJyWfhUuylabePrCO0e,iv:HimlUGrTTCZ2sDdvsMv6v/GzIxbnWtX8+yGowuU1cFo=,tag:wD9+tbExTytdeWRBOBdKoA==,type:str]
                    href: ENC[AES256_GCM,data:EgRIbUrh2QvDIwRseYrM7j0dVoqcBIC1swQ/KcoCw2Q=,iv:Gq9tchVk5g2lDSRJtgIbAR8vjQtt++Y1NWQzEsByGac=,tag:um45JPa2n0LIBvgOEAsM3g==,type:str]
                    description: ENC[AES256_GCM,data:u/fC02NguncH5VTEoso=,iv:oc3YaqYPTmIya6j/pVhyyqGTTCd0ijhPcRPLXb6Pm20=,tag:5Ebb8B7K4x3XPto2AJ9TwA==,type:str]
                    siteMonitor: ENC[AES256_GCM,data:zaLiPUHAyTyXhQbLwjsMWnpYIUrUCSVNb84=,iv:Vz4WOBkqN0e5yOhkd/x90/MGX9Gpzs3TPHbgginxhtM=,tag:tOVBU7yPkAcvBXIjDvSHng==,type:str]
        widgets:
            - greeting:
                text_size: ENC[AES256_GCM,data:RDFg,iv:c1F6MQyq000qBYVzIAJ9HLCF9RH+yPCOFJr5sNyuv0k=,tag:enLF0utLv+QEhxQksRmcYg==,type:str]
                text: ENC[AES256_GCM,data:XjwsejSuU6I=,iv:FrYqBu3WS65jpyYX9o3DDyT6VtHyYLIhAG64KekdKR8=,tag:PjyiaC1pjR9HwjeCLPOTUw==,type:str]
            - ENC[AES256_GCM,data:Y04JImgYRHS4bfMB93Id+xj4NO5GYHzpzZTwbN5dz8Cco/IWTOYAGyB+pG9UpYkR0pHKIU9ct0TiAWljhVnbW6U6U+DoOZj5UH8=,iv:p7k5AX9U2tal4mgIaEFP06ztIQvzln3lEoemr8MegWI=,tag:eEqmf6CoPQvZ6X/lW0161Q==,type:comment]
            - kubernetes:
                cluster:
                    show: ENC[AES256_GCM,data:hTFU1g==,iv:h2OZC0XYdodfY+UKKe0fWwQofHh2GtGHv5daQTjL5KE=,tag:XdU/PaMY8jIefn505jXGLg==,type:bool]
                    cpu: ENC[AES256_GCM,data:QmFYWg==,iv:iqXh9J4Q0X6seAK8Ga2ISoH2JnHcU5kblwIWuNIFQFw=,tag:QvKoyKrS/fmH4tBSu6OaXQ==,type:bool]
                    memory: ENC[AES256_GCM,data:eFr+fA==,iv:QF00RqtcK6DTazas0nUPSEUfrbElyIP/yHjTvn8ntHY=,tag:vWkAI0oNVzujM0Uo1Z9U5A==,type:bool]
                    showLabel: ENC[AES256_GCM,data:0Zngvg==,iv:lR0NKtDfGnHK+PG4AI/yKBCPvuQvEWK8YPdEO94btaE=,tag:SfARuX6fdEE+W71I3qm4dQ==,type:bool]
                    label: ENC[AES256_GCM,data:30EflSm1sw==,iv:tpQcm+UuwePWixc4O3dGeVsMm/zTYIRPzYzK6jZ9gsA=,tag:Qio6Hip1I16vQnI3TT6yAg==,type:str]
                nodes:
                    show: ENC[AES256_GCM,data:7feUDA==,iv:zHmfCNKthM/hISD/6hxpDGJiCcLMcBt/O1T2+sRyaSM=,tag:1ynKtrSIirHbJWO9spbrlQ==,type:bool]
                    cpu: ENC[AES256_GCM,data:M3S1SQ==,iv:bSj7QADf1zeGoGrfqSN9jQ/F/HbZJXZ/QKX2XNR5B1w=,tag:pKZxdMlJBFOrgnVuQa09fA==,type:bool]
                    memory: ENC[AES256_GCM,data:jU6RnQ==,iv:P+iNQP1HnDyF4hp/6ddpcRpynxhFzHEwO6G359PCEUQ=,tag:T8h4u3tU23Ayg8Z0ZlFPCQ==,type:bool]
                    showLabel: ENC[AES256_GCM,data:1pe0/Q==,iv:zViWuZGSZDxdCKiQ9DvYThHH+b4hoGwMoq1mXmu3rwk=,tag:ww08kOjW9dMLiYysdxI5/A==,type:bool]
            - datetime:
                text_size: ENC[AES256_GCM,data:JL0=,iv:nJmZ+oIF/OWP7gQNFEySGt+Fy3JVCKReBv6uIKxunNI=,tag:2RKn8rolZ0Arn3yS9DbGHQ==,type:str]
                format:
                    timeStyle: ENC[AES256_GCM,data:RycBMjQ=,iv:5ncaQms4r+oGNDcNkxUS98LZ2upDN77RwT4xangtaJQ=,tag:xlTw2ufSPqe3ubgGlSm8gQ==,type:str]
                    hour12: ENC[AES256_GCM,data:YQlptw==,iv:aUGDCRuZfAAN40UVNXZmeDxf3gQ8tuK3h61p0OT89Zg=,tag:O2KIf44/zra5iOmOOhh6ZQ==,type:bool]
            - openmeteo:
                label: ENC[AES256_GCM,data:AFs=,iv:NNTAzaKAyfRfXzBy/+UqNY75TtF5x6c1PTLvP/2xc3U=,tag:l85VV3s0C7PKIc7bnLxBdA==,type:str]
                units: ENC[AES256_GCM,data:u/lefsDf5oU=,iv:Ur24KxkRdMEkrOfxgtTs6ScaFs6Fhg0BQfcIjcOnCQ0=,tag:6vKU6SUKDr94hiOWQAkF5Q==,type:str]
                cache: ENC[AES256_GCM,data:9zQ=,iv:p+2def9c/Tt1lIQZcxajECZdl1iQJxlZPFTPfgBlR4w=,tag:QjCtykwRHPZSztImJ66p6A==,type:int]
                latitude: ENC[AES256_GCM,data:HNyG1mubK7eS,iv:T18ZZqdjT9itrRDe5f1ZjbcYwd8jHH3DESrP0WO11ME=,tag:XV3YgzxSZg15vhtC2UNYvw==,type:float]
                longitude: ENC[AES256_GCM,data:p9Fskf+btNEGez4=,iv:NPdcvLT2tla3xpBTWqLaE2XzYO0uj1kh8XOytSEvvos=,tag:Dg5uzQsfhoSg7SbsYaDAqg==,type:float]
                timezone: ENC[AES256_GCM,data:aVBlvg/BaNdEDeEsy7LF8yYdNA==,iv:y6MTFMh45juJqftpmL0oZ3r6DqAsyzoyjG9HLmG+joY=,tag:15d87IB2YouosoxzWuf34g==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpNExqd0NTWUJ2T1FsZkRh
            TXQ2RWRlQXpOR1NOb0VxVGRKQmFsVm9uY0NvCno0UytndGRUUUVsRmI4TlVHbW9u
            OWY5QmpYTzVISTczaHFpczgzYndOY2sKLS0tIExlbHNoYkxxYjQ2OEVMZERuWkg5
            OWtrNjhYSGVjY0ZKMDZHaHJQOTZjSmsKF/PptPqH7YtjNh28WlhPAreOQamMin4Q
            rQaWjbIPE8z52Yl+3XQsBQN/Y6ZBMr6vnL3dURn1b3e56T34Du7lUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-20T18:55:44Z"
    mac: ENC[AES256_GCM,data:hCMMj6axEHS0Sxga9SByYqhXXlWNu1QoFeXSZ00czTxK3DdfEoYcNYqiEiDEQlwJ6zOHmRMYQCOfNdfhAYg7q6BbW3Q0J6JnvfELkOPWzWn5KuThbyFFpB/Go0gdCoQb18sI8k8QTb2x83Yg4Ue9ap+4FWhydhMDCur0Ignu4tg=,iv:dL4FoPRcay3+x/PxmsSD9RFoTxVqrPeT5y/Z8v18HlA=,tag:vxKkfoQYRdUqtcymIp0PIA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
