---
apiVersion: v2
name: headlamp
version: 1.0.0
annotations:
  homelab/description: "Easy-to-use extensible Kubernetes UI"
  homelab/url: "https://headlamp.dev/"
dependencies:
  - name: headlamp
    version: 0.43.0
    repository: https://kubernetes-sigs.github.io/headlamp/
