headlamp:
    serviceAccount:
        create: ENC[AES256_GCM,data:kdp8Gw==,iv:nolWDavSrMjRM3nOYsCK8dfEpDketVRzKqhDUR3ShtE=,tag:0u0kd75xKL0Wtqt9vVqdCQ==,type:bool]
        name: ENC[AES256_GCM,data:kCod3KKPWlcN1QHfIQQ=,iv:hQ5qeYPeTpQlLzfWmj71ApwMiNx1dk9cjaa6Q2yVmvM=,tag:2dD0GGvQ+KIfeMy/15Ua+Q==,type:str]
    clusterRoleBinding:
        create: ENC[AES256_GCM,data:3Lso/w==,iv:joHkwZ8/WWaT5DHMxchkuDQ4PMmaZXg8qQzSjE7LMuo=,tag:hIHJKgkMMhgsJr7/Wco6Tg==,type:bool]
        clusterRoleName: ENC[AES256_GCM,data:lHUSoZjOjxhyCm6Icw==,iv:Dcrl8UerdD5HxM4gHeFTO/hZ0ggIrwT/2kgXdJmgUXQ=,tag:92HoK6dF6mNBihJThmTPeQ==,type:str]
    ingress:
        enabled: ENC[AES256_GCM,data:LrsCNg==,iv:XQKgrCCWVt8T3ZroFrSkWt8ObFor7o/KM8pxvXuWbTY=,tag:KEGN4LQcOXNvai4agEt6BA==,type:bool]
        annotations:
            cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:Dp5Hu3dqN/LZIvfrdzGFWQ==,iv:VV92tCIRkxHx3KPnOmqypULm40eBxY45rEFBgw5ky4s=,tag:UKPli2WkpKNFhU8VzvlSEg==,type:str]
            gethomepage.dev/name: ENC[AES256_GCM,data:Ah7ahbCJ3wk=,iv:JOePypblNUXQ1LTFdb+lNaj/gdvS1AlA9g1LIEx6eqw=,tag:rtnzBvkzj9IMq0b0W6gd+Q==,type:str]
            gethomepage.dev/enabled: ENC[AES256_GCM,data:psYHOg==,iv:CZqiIlrlO/c2FS8CMhNTjiGDF38LtE8/3FN2hsxoO7w=,tag:3M+Td025yelgrGWRj5bAIg==,type:str]
            gethomepage.dev/description: ENC[AES256_GCM,data:DbV4YlpIMP6mcQwxYaI=,iv:R8w0B1MNSxZYN+0HmgC3dlkbR+ZFZPw4FeyzAfPGysU=,tag:q8Gj5DucwL2Qj+1sTNmVVg==,type:str]
            gethomepage.dev/group: ENC[AES256_GCM,data:0VuEAbaD,iv:Z829WZLSPtKeUlW76xSU3tGLU/1kY0oek/cmExZHN9A=,tag:SxF78gYv+isMHFd1InkGdA==,type:str]
            gethomepage.dev/icon: ENC[AES256_GCM,data:pOg6xU+aETY/J1Jufx2A,iv:T5/Nw+9tEr481xRjBsOF3ogCYxQhm/WNZhQrR1UV9qY=,tag:hwN1eOR74ol1AYdb33aorw==,type:str]
            gethomepage.dev/pod-selector: ""
        hosts:
            - host: ENC[AES256_GCM,data:zbzXGVs7BdU7XMY9/96TxZW8caY=,iv:M4ZeoneONXdMrg42FjEb9uBTlwWJtyNB88+pArVESGQ=,tag:ad1rLgjKX8L6hYqAYvJDbA==,type:str]
              paths:
                - path: ENC[AES256_GCM,data:Ow==,iv:yfdjVwxlFHiFEJP+N1rd2i2P9L0bEJbkmUnIJjAp0hw=,tag:nb/f69bZq2TD3ycjdCNQCg==,type:str]
                  type: ENC[AES256_GCM,data:j/NahWX6,iv:s3tiNLzEFFiB+9fXTjb1Az8wZheSrQQKp6aHgacrmQo=,tag:+iffveBHDkAQSJvnFbaakA==,type:str]
        tls:
            - secretName: ENC[AES256_GCM,data:4ahAZr02xVQjgMJB5PfVuxc=,iv:YZjNVHW06RERcNX6Dy39JX256Uvrm6Wt/C8ZxCoWgl4=,tag:COgXfNJcxhdHbKH/W3fKzw==,type:str]
              hosts:
                - ENC[AES256_GCM,data:VSSQ+uPELXegoNyy6aoXlxhioXs=,iv:M5HAorJI7fQ/1KYBmKBcPIkwRQH4i4CWIDIB3e277iU=,tag:XMauHoprYJC3xCpwa7H1dA==,type:str]
    env:
        - name: ENC[AES256_GCM,data:6RGehBc9wnernu1oRZIkkPfa5iv3TF5WcKkfB1vI7B6ha377,iv:KW8rnakXp5nhtjEZOtFtP4+BaSA2dcOo1tOBERv400g=,tag:C55M3CM3GXQwyIsvB5xD+Q==,type:str]
          value: ENC[AES256_GCM,data:y7ZeMw==,iv:JW+v2lk7ZvtleQHUxxv5sevR6KZvYyulsB1MILJwXMs=,tag:OeTVLo7oehjJy0+RIPhv+A==,type:str]
        - name: ENC[AES256_GCM,data:hwCBX42ubpjx1P3BRYUBJvvXdCzSuvdxe7jyM4A+,iv:i8YjCFJH4nZuQU88JNtNxSOEOrJAAFtBswu7mHIUVpw=,tag:jEz5zx82gp88pzQTD3heRQ==,type:str]
          value: ENC[AES256_GCM,data:Au8Oh6PfSwjIVQhHvtcMVD+VE2X0vrsAaTY0TbwhPt6PStpU,iv:OGx99oOiuHOjgDF5Xtwj+C+/8OB44AL/sYazpeXvS60=,tag:4fG15372LxwUCTqFh5ZFfA==,type:str]
        - name: ENC[AES256_GCM,data:KVijS95BlOrq33JcMPwaEQRBL88h2v1j4GL0OPWIRta52g==,iv:jFMnRt3ookDj95Y4QHQNng9mzW+a9vN++c/jC2u78zQ=,tag:sJBpJtuTgTXkQyN/ilGoDw==,type:str]
          value: ENC[AES256_GCM,data:kDSTSYWevU8e9v0TujmZoyH3q/ZytAzF0YXcuzU4ir4=,iv:z00DFhuwB2C3tUEAp8l5oCVbGCbNTe2fRxUMY4r8T/Q=,tag:+wT08Db1uXqDfcuU/y3isA==,type:str]
        - name: ENC[AES256_GCM,data:hvnyEifANQWytMWvKvfnl6SqUKtaVSpT4D4a09HPjjiXFNA=,iv:/ImYF4nNmJ87Tp+MtrehnS0r7AyJLZV/KARKuYoWBwo=,tag:4SYZemn2zDyHrsy7Ie0gnQ==,type:str]
          value: ENC[AES256_GCM,data:/4XsNCg0iJ7DXskyo5c3Og+8PW4/O8YUdaU=,iv:XinQYrnoWro/orBBfy6LG75Y3SVQm24/QE5opezMxYY=,tag:YgV3nh96kqA6LALfdE9wBQ==,type:str]
        - ENC[AES256_GCM,data:QVwMHnX937GoqibiA9ZxeUazOyuMIJyhjmJiA5O8ZjVKCqA894/gxb2WR7t4Jw==,iv:fRjwmQ3lSohBeweabZy7jCGiiYT7n1uN2zhZ0W/ha/8=,tag:KuwUeQZ8n+LUkvr5GuJG9A==,type:comment]
        - ENC[AES256_GCM,data:j++Yxrd3ySoHTzYNxCGpRQ==,iv:Ba+gc9bO7mruV6RmSJls9vDbD2fZ+tWhFeRVZAaogPE=,tag:67KW9vkuNmfBIxRnao5YuQ==,type:comment]
        - name: ENC[AES256_GCM,data:UTC40iY1i302UJASrqt5fuNTwn6ZG3wNRMzj,iv:rWCFt2jI2a4ZexHLZeYDht3H3A+lnQXYhVEdHGeoMXA=,tag:gaMB264RWoFNS3EsK9wS8w==,type:str]
          value: ENC[AES256_GCM,data:68V/aQguu7ja/+ai6p0hHr4jGxk=,iv:V1A9gjB7Q+OL9e3TGDD6Cua7CklOm4bW4QSVjKVYfO0=,tag:PWrJXfCZWUxk3J9LDVftxg==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQ0J2V09VL2J2aklhL2Fj
            NklSUHA1ZTh2U1owdjZpdUJSWnVESVFFYTBRCmVyWS9GODIzSTlMV3JPOUwwZHVl
            cDhLQm9HOVNFRnljbFc4dVRWcVdHOVEKLS0tIFBRUGV2UE5vdkxtQnhEMzNsU2xH
            NURxWXk2NmhDRkFlM2tESldRcjVxS2MKY9/cyYRD77Ylws0zNLtcgrH8iLrNttWj
            hDhCfqGqD/zBkFRtw5icW59FThgzEBkN5g9ybnArvNLi43V/4qMkag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T23:17:13Z"
    mac: ENC[AES256_GCM,data:GWNKo5I4dZKJs+WbrlGRRlVrBUU0vzzgmpwDkImaceDkCXYyAVlg/whCX/RSIVeJz61GLWUQ+xU4M3KQC5lOfHCxhRZPCu3Qej8L9BobQhsrNLrC1lEL62Ct7vY898E4BEkx50kFxl/GbRJJ5rRA7skIDfdIgPISZicG87QCqV8=,iv:V8V342jyjXa84Sf36dI/iXh/mUH4tRhqUqQiJDNCF3c=,tag:KPBDB5ptfnUVw4lyALOgEQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
