headlamp:
    serviceAccount:
        create: ENC[AES256_GCM,data:vCG66w==,iv:LbddUSUrRJSdtx2ew1vv3aooklCg0qi+/7TxfgEjoFw=,tag:pxJp4uEKMssG3EHJNVw4Kw==,type:bool]
        name: ENC[AES256_GCM,data:5NZTG+g2UrEyRX+pZkc=,iv:OMtfDfW83LAYjhe07EKlCVhYBUb7chjlsJxAIBY5UqU=,tag:OhLbIuIbUk4zyDnmTdGvUw==,type:str]
    clusterRoleBinding:
        create: ENC[AES256_GCM,data:34FkXA==,iv:AUSEP/C2swC/gtoZt3a3HzcL8W4E0biZOifPhNfSKKk=,tag:4o2Ot3//0M9S1hiI5NiHtg==,type:bool]
        clusterRoleName: ENC[AES256_GCM,data:HxHbgwVHvXxKmjG0kw==,iv:ljOrEVbu1BKLxVpu8DuWEszYv1/Fugg1cvfZOhj4mQ0=,tag:a8IkLgsfgr/qRFDCc2GJrw==,type:str]
    ingress:
        enabled: ENC[AES256_GCM,data:3hUmNQ==,iv:50toctlv8OHRh5uIW0g8oe1YEK4EE7GjIVtjgon6ggA=,tag:SnYoC+mDwKCRID7Kp4+ZFw==,type:bool]
        annotations:
            cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:EjF6iErkEoTF32g7zwNtbg==,iv:Q7wN2xxggh+RdxGEWTd5PCoICspMYhUfwARDBeHhyp8=,tag:hvMk27x67B/oJT6wtyVjtA==,type:str]
            gethomepage.dev/name: ENC[AES256_GCM,data:iAxcLkebasg=,iv:r/vhkVUQpN7o0xMP7LiaPGgEk54prckHqP6WXTLDRSc=,tag:e/oRDPhZGqQmu4TC+oTsxA==,type:str]
            gethomepage.dev/enabled: ENC[AES256_GCM,data:KjWF2Q==,iv:S7QV+pDFavq/gDuU4J5XiLovw/K5gNG4Ved4iQgE2U8=,tag:sMIpHT/gHBP2gPtZn1PLAw==,type:str]
            gethomepage.dev/description: ENC[AES256_GCM,data:Wisc1Xm639FlzpLfpX4=,iv:u6opVu9z37KnT662KJ3IaG6UwOo9CNBpvaSC9P9XK9U=,tag:KwIpdepYbhsogjoX05NCvw==,type:str]
            gethomepage.dev/group: ENC[AES256_GCM,data:ZQ8j56ym,iv:wLf+TuEvMjKJoDpWepEeoKAlXKUOJanjIjgzFI4XHqk=,tag:Ej2BcGax25htfs7ltqw+Og==,type:str]
            gethomepage.dev/icon: ENC[AES256_GCM,data:EFXtvMSw0KwlXoY1mIAe,iv:vKyZ7Vq56ijvRgaas/RAUWg1zbE8mhOFvSKOUvDfJFs=,tag:SClJ8Ml5P2NDSCDRCNCDTQ==,type:str]
            gethomepage.dev/pod-selector: ""
        hosts:
            - host: ENC[AES256_GCM,data:9hNaM2xJijIkQP5vVDHb+5RzBf0=,iv:XSKCoGssEZMc0oWs/lyb3VZrpUUpNuDIUQ8se+utfnE=,tag:aJ3YEO/b0sG0xVh4dlBcYg==,type:str]
              paths:
                - path: ENC[AES256_GCM,data:ew==,iv:Spd83u0bxALUUOIEiFdHBMbbDQnwMtyOccln4ovU0Lg=,tag:iQx+1U3dyt9u1OpEAoHdGQ==,type:str]
                  type: ENC[AES256_GCM,data:FNjXfNLf,iv:hz37IEIu3QZujPtLSdFHu+7Ibolx3tJTGqKJGYYboaU=,tag:A04hVcqqx1eUlvAdQ5hnCg==,type:str]
        tls:
            - secretName: ENC[AES256_GCM,data:N58VE8ERPooaHP1SRgbwkPw=,iv:nHiDS5ro+ZWWKAZ5/fVHAgKTFyzK+yKolUrL8+bv3ac=,tag:ZWyXwcvaUpQ2bHKt+cVd/g==,type:str]
              hosts:
                - ENC[AES256_GCM,data:CqMde+Fmma8zDm15L1Xg+cWCC2o=,iv:qRRtuuIjstZUF2OZbnNgrp49rfzBHZi2MBJD6+jiO2A=,tag:5F5/nO1ShKKO8/wftHvEFw==,type:str]
    env:
        - name: ENC[AES256_GCM,data:4z135g1TCbef6lmzSiSU2xXZj2sgzt3UD/rEvmaGYl7X05oe,iv:IpnKETDPDvDE+r9FPaIM/iWKp8L1ewMFbYkVBH2QITY=,tag:mgy1AxJcuwFTwXbMOWFdkA==,type:str]
          value: ENC[AES256_GCM,data:iU73bQ==,iv:IB+pDRTXoUGG4qTJ2Fu875We96EAjFVMManKTk6O9Pc=,tag:acETe7Ia2Jjhc3Hm9px1WA==,type:str]
        - name: ENC[AES256_GCM,data:4O2RQh3wn6f/lyPxciZWuWyQPQbrZSLAVhqL3B/Z,iv:cC4rhd42vvklB3LzNrsITfouyszgUhC+0fSKQeczRjc=,tag:sMU2m6JdVm+rA6c0YZ2QIg==,type:str]
          value: ENC[AES256_GCM,data:jAVMG4NEhzBFS/9fqpadsdvqpaT6nH5cD/HdIdjm32ULnO2n,iv:j4UUqKq1habmLtxi0q+kpB/Um9DWhdTT1Awro3wwZYw=,tag:5uiB5nQz79C72dB/8mS1Uw==,type:str]
        - name: ENC[AES256_GCM,data:1oAXjyoi2cmoFtDIhvr6qP4liMytcmz3RHpnDnq1Gt/PzQ==,iv:y+dXCxGSbHiTo+zBMvAPYB8WJFW4EIdgUvd2ZTkiWnI=,tag:vTFOjhaQkjxgGzuM/52lKA==,type:str]
          value: ENC[AES256_GCM,data:DhWQWIzlwKM6t2LrE2Ya/x3YBoOmDxcpnd5oK3a5uhA=,iv:YkX72jRr67WeuR7VQI219rqryolDtT0V1CkK57hL9hs=,tag:JWzKxCojPij9e303C29KsQ==,type:str]
        - name: ENC[AES256_GCM,data:MP3kkBEBZrwQx5Ov41vyzKrRyS2K02TyjCiqkee2Il9IPK8=,iv:h88tCgii0RfM3UprnOm1hoo18yJi4w9Sk0M3ujdsUUY=,tag:gistNpXZBlB3qNUs0CkzPA==,type:str]
          value: ENC[AES256_GCM,data:Q8bdgs8ER8ATDnj16w33tUqNP7sdY4OVam4=,iv:h/ka/qSm3VYr6XwNowVQ1Xw+JHEuPJL7XVI13g809rE=,tag:3Ve0uLPcaLZq/6lzyEQn/Q==,type:str]
        - name: ENC[AES256_GCM,data:f4r/Zq1yA8KaEbc6886AJ6tPqZRU0U9gOXhC,iv:paqfY05od3uKrhTcfX0Jw5sCIMiM5qVZ3IdSlcFOk78=,tag:5eUxDsEd9I8Qi9VjJshWkw==,type:str]
          value: ENC[AES256_GCM,data:DLVk0v5XA/lWTB4hBJ62IB5tiUdp9qVQ3vxj,iv:AEn7NwBkeQvoTPg5+EjrcVIHiw0QN18PujIb9U6BEQM=,tag:P5tdtTOg5b+UUdA3gNR5+Q==,type:str]
    config:
        watchPlugins: ENC[AES256_GCM,data:zU6kig==,iv:RCYPxNiINVS0hpVDdREyUltNhFgZLHce26Hb/AGZoTA=,tag:bsqqzflYhUmi6QNGsvRi3A==,type:bool]
    pluginsManager:
        enabled: ENC[AES256_GCM,data:6ke8hw==,iv:vr+DGmXOypy79hG9yURuaJvsO06p8ZyoQ+NdasY6l4o=,tag:oh3qLZtdXNx8Cht18S77tQ==,type:bool]
        configContent: ENC[AES256_GCM,data:JthFWxBOM+2ZGX0QE4tPCQ5MTNXcj9NYwhrIFHPj9XJE8U6J5NbmQWzQAD5/YW8fDd8F2VIea3Jjhf/3TBXsdF8oDK2ctLzY+UUzkZV+zvwQgKo/O8x/E6sF6go0LhiPAaLPsfYvF6lmhlFGv0LlPBdYT8UJHjjr/Z0t6d8F4hPQWUyhQla2GB9DZX6hLTY=,iv:ZmjT+hbZDcxJWgz2firgOj/xUOlRRAA9YD0YnhhWblc=,tag:qYtHE3sPOLYQfu15qf/TZA==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdndTZXlUdlBnTWZTb0N4
            ZHJLbHFEbHlOS2xicUZoc2VXd0hIWXMxRDFvCjlFQndiVjhTbVY2Z1FKODdjNkZJ
            NDdydzNhdnJWa2M5b3JBZnRpWjd1ZlEKLS0tIDZESm5RMXFqdTI3ZFZHL2MrUE45
            QktsdTE5dVcvd3NpNllFVVBZOXVQcm8Kud0wwNGbQC30Bs1FDCBnsUCg3/016a/C
            tuj1mMFY7Bij4a+SOClk3j8ZZal+uKzWdz3bkHDQoiUz6sd+nWBX4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T18:39:52Z"
    mac: ENC[AES256_GCM,data:ur/qWAMxIaWkba2J132YCyR4SxjJ0/chc166ZRcXORylfm7vvrt7r+njUWMVs/75QG155WxTUyENgRw2kXlJFipLfzYPCHH99QxK8dstBsXf8e93Ah+weDZIUkqDxRc6mHfrHMY+j2dbp1138fUQJCXpzVIhp1fps5FV7j2lnPg=,iv:eLWyPMs/lSCqztCIcCYWJgVOnQ7k3C4R8gVp19i1zuQ=,tag:Pg3WSh/Fb5g/YbyQJBucFw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
