headlamp:
    serviceAccount:
        create: ENC[AES256_GCM,data:A34dEw==,iv:LkHNIuDVxGCw8lVCYuLF9xQnGAfaAuepGavjhrkINB4=,tag:difH80EDdLZQD3w84RCdwQ==,type:bool]
        name: ENC[AES256_GCM,data:S3JCpiL/uIDcS46XDZg=,iv:UdkKfvlAzZYmihP0D0McIoqxiHJ8DdbG5w9oY0+5zN4=,tag:ZMKvjrSLbwsbjqR33uwfTw==,type:str]
    clusterRoleBinding:
        create: ENC[AES256_GCM,data:iVhWUg==,iv:ATgoZeTtapJ5eTmB1qyvHJozu8cQleFi5ffgneB/+6k=,tag:TIqoQXMTnurKSMCH+58AIg==,type:bool]
        clusterRoleName: ENC[AES256_GCM,data:ADGQEjwX4Q2QBg0GyQ==,iv:ixu+Es/kS9Xvg1yx0YpW2B6qh9SrlmpnHxR+w7PvupE=,tag:0lRiFliM4uuMI5aReDg3FA==,type:str]
    ingress:
        enabled: ENC[AES256_GCM,data:OiHE/w==,iv:R2a84SZakT7P3AHF6ICt9/leDUCBXwmgW2wS6Gti5Vw=,tag:6SzNi1dR5sKBQhRFRVZA0Q==,type:bool]
        annotations:
            cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:JRqEFTX09r9Fxw15zKX8Uw==,iv:v+uATzSmM5/qk/rjytYrZywa3+TFdD/Ym+mtB7tfpR8=,tag:io0PvJzJ1TnQmHp0S6sMXA==,type:str]
            gethomepage.dev/name: ENC[AES256_GCM,data:K8z979NIKjg=,iv:24nOgdDLQM67sky67VxuQs2fQOBawHueC9fXSUJc/SE=,tag:0ZtM3iKk6BeShyaeVPXjeg==,type:str]
            gethomepage.dev/enabled: ENC[AES256_GCM,data:oMjZEA==,iv:f2vS5zukoZZfEpeLTqbT0CNod4wppUSRFgu7WHFTv0U=,tag:mOXxqLEtlmUlErI/XZQxBA==,type:str]
            gethomepage.dev/description: ENC[AES256_GCM,data:TajYBDp/VPfUk9n0l2w=,iv:blO6TaeV8T4Zntmn/p87ifg+POv2aivU7gvEU9dwkzA=,tag:KyRIDqkTRiLqDi42vqOwPA==,type:str]
            gethomepage.dev/group: ENC[AES256_GCM,data:z3x+6v/u,iv:KWoSNc+lG5w2eOSvQYruLHmSc3sy8bfaZbe9g5hVLoU=,tag:i6LP5KCnEoOMsd3DSdfhXg==,type:str]
            gethomepage.dev/icon: ENC[AES256_GCM,data:D7oyH1UMPXAP0+nrecO0,iv:5emjEOeyqLYJIwBZ6h0/RMTp7xpo50ro55Qd2FtB9uU=,tag:Mtz2CsNaeTjOjwH6wbT/HQ==,type:str]
            gethomepage.dev/pod-selector: ""
            #ENC[AES256_GCM,data:fodoL7Z7yAUKk59LZzS+wZJES9U/OUH11qEuFXZDTi6JIrLInBJD+xCVMeRsYtiMhMKmQ2Y=,iv:hVmEk0PocyLafJ0LoaVkvU04P8gh1Lx2/E43e65W8jE=,tag:yiJqeI0V4Uj73cwquxXxZg==,type:comment]
            #ENC[AES256_GCM,data:KzhZ8ZPhwK2ZMs0KTFznYEJjCpQ/C5AeveorF23bol8Jm40zQ01KehrL5yeXig==,iv:obn3ZbZdo6BtPVqpdG+/kMRVmU2JlJb24d4ke+KCn88=,tag:D9cNw5iYWABJKeqjUjMPNQ==,type:comment]
        hosts:
            - host: ENC[AES256_GCM,data:E3IcNE/4WTwM7QoB+GmpqcCY4ls=,iv:6u95fONtVTQFNi6e63kpINbh/x4Ss4l+TIn9hZNGzGA=,tag:+9nnrt/ocGFlpnYDE3bdMg==,type:str]
              paths:
                - path: ENC[AES256_GCM,data:oA==,iv:ndik+0it0Wh7X5adnv6aLByg4G8sExOS6j4TmECBnbs=,tag:HUiKZSchbrwPsZXCvceepA==,type:str]
                  type: ENC[AES256_GCM,data:DusMny02,iv:4pfmLBKibRqC4y6FOO0mcMzxcGCAMaCpHN89i8Aibuo=,tag:2i9hyX9C1RjaPo9R5vizew==,type:str]
        tls:
            - secretName: ENC[AES256_GCM,data:ZRFrEFM022RNLUPweSv2aWc=,iv:LWguzTs4PrWVC0R13id9gIIKsjA+MNXL8RQClIpI1lc=,tag:iJFVaDoKn9PBnBeZJl+BIg==,type:str]
              hosts:
                - ENC[AES256_GCM,data:Dg78/9B654fjQkF1fF+48oYBsA4=,iv:x4onjN+6r1+s0WneBRhFavqh4sr7+sZx3W8EDWMplpI=,tag:txKq2pFIGC9adlgtIa+y1g==,type:str]
    env:
        - name: ENC[AES256_GCM,data:zs8deD5cDDNTc777w8OFo9qBBzngiQyIa3VWhjnP,iv:+/zel7sNRhSf99LBvj3MzbSFyE0vpMdGXZzQ/AJ0uZ4=,tag:EK1tOHwBSN6fr0pRisUl2g==,type:str]
          value: ENC[AES256_GCM,data:nHc+ENcr8IiIHmFfJgkWiY1/44MbS9OrmXNjmgmUfk9ANsYA,iv:NDDQhRcKYud7PSVqy/tvh1eXKdCuhUSSjYWAK4FuK3Q=,tag:OJJB2CSWE+I3Rs7WEm9c8Q==,type:str]
        - name: ENC[AES256_GCM,data:tLeKxnPO6ASk3/SVLTldxlY2D28NJjmx+hUJmeMupk4l2Q==,iv:1ARU0RkE4JnqZ9gFtT8U69tCJGnkyuIwLREYitYsxPU=,tag:+juay9mxJWlwaZ4WImFfcw==,type:str]
          value: ENC[AES256_GCM,data:cUJmr/haielg5+x0Q1EpPRl9z/Mt/E0XnFJLz2S7UTQ=,iv:TNgsNY3YUvZIk0ueVz/s6xXDRN0wwlk/FGC0meQ01bw=,tag:vlm+RFjEbkMj7v65d8T/4w==,type:str]
        - name: ENC[AES256_GCM,data:QQVO5MIJsL8Cf9/TQ9SfRuEAJhv/CNtsICdLwdc1Ql+KVQc=,iv:P+smyPe8vmBLhF2Bfh3Rmp8hGMav56fT72qtCXRuC3A=,tag:VhrwB5y7zYv+3PzZyZV4Yw==,type:str]
          value: ENC[AES256_GCM,data:Xjq+cOgtB6wQ8/zLBN+Oq6JNtj9PIHYLNeI=,iv:PzfYPQC+/dnEJ+SePFyel8Ig6hqzJ5y4SR/XBe3QGmo=,tag:knrjzhCRlUpWlcxGovf/Og==,type:str]
        - ENC[AES256_GCM,data:ZUVLdyJY/Dk0gosEGTfNlLhv+I2NlECzXCaWPm5dANpxCuvyF3mDrIUcWEwmxQ==,iv:qEAwPtKbmMLQbp3I4IADG2+wqI7wpygQAqQwWLB8Hd4=,tag:P1g4Er6cd7fa4OLENciY9g==,type:comment]
        - ENC[AES256_GCM,data:bcncYaFE+W+Xbx1/bqt+Ag==,iv:GF5MRicImRfGYeeOUoyKyq075+fqOwR2pHa8Oc74yn8=,tag:CE9Ijm4yIMARQdTwKr6UMg==,type:comment]
        - name: ENC[AES256_GCM,data:YEd0I6RtLq7u9LNxzpsmbFxeMU/b3jVcgrn0,iv:q//n2L1Xg/9yoRLatqzXMbkW4tyqzFaEyx6eSXGNyZQ=,tag:5B3WRF45qTEWO4UsOgyNzQ==,type:str]
          value: ENC[AES256_GCM,data:rYzRsdlHmkDuhh7+DE4W7Mf0sLqKBvwBsA==,iv:ci5THGZSfKiNpRYzRk/uoCGtaZWO/olKUFG4MdLPVso=,tag:/p3QBWLSmftNOa2H8oz/Mw==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUVJSanZucGlUYWo3UldF
            M2NFKy9oWXlaOHFqQklpZGtlMkZ2OVA1emc4CjRyZ09YT2FRQ1FLLzl0ZVBNSFZr
            M1Zib0Z0aVNPRHhPWCtGUy9Db2hRSWcKLS0tIHFseFpETlFhQWlpWDg0VkQrQnpQ
            elBRc2dweC8xdlJzaXdhalpPbGhXWTAK6LojEv8wlSHlCn6gQIfLiY0VEQU/aRwC
            hQSSyMsTNocbCs3u96FGUgyTLsdggexlRn/55Bxm0e1bFApmyn7GaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T23:09:27Z"
    mac: ENC[AES256_GCM,data:v8v7oAz28S7YSvLUM4eYsPIsLVaC9qMOpdjx6FRoPYlrDAedSMhfO43NtINvwZ6SBZ5J7VD80zzrrq5y/8TBMg5T8GuIZG+Vl2AGa3dlHNmqmYZR0oxa7SyeWTab0GtWeWfmaBktq0Uj+czig7H7161O+/dF1TIgAGo9sKEDz6M=,iv:3c3uRuY/s7H6INUfo7RfDMz4nToZQ+XBfLodhMCUz6Q=,tag:lMuamb3dKTkLxL2IfvqboA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
