---
apiVersion: v1
kind: Service
metadata:
  name: traefik-api
  namespace: kube-system
spec:
  ports:
    - name: traefik
      port: 8080
      protocol: TCP
      targetPort: traefik
  selector:
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/name: traefik
  type: ClusterIP
