---
app-template:
  defaultPodOptions:
    enableServiceLinks: true
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: plex.tv/host
                  operator: In
                  values:
                    - "true"

  controllers:
    filebrowser:
      replicas: 1
      strategy: Recreate
      containers:
        filebrowser:
          image:
            repository: ghcr.io/gtsteffaniak/filebrowser
            tag: 1.3.3-beta-slim
    sonarr:
      replicas: 1
      strategy: Recreate
      containers:
        sonarr:
          image:
            repository: lscr.io/linuxserver/sonarr
            tag: 4.0.17
          env:
            TZ: "America/Los_Angeles"
            PUID: "1000"
            PGID: "1000"
    radarr:
      replicas: 1
      strategy: Recreate
      containers:
        radarr:
          image:
            repository: lscr.io/linuxserver/radarr
            tag: 6.1.1
          env:
            TZ: "America/Los_Angeles"
            PUID: "1000"
            PGID: "1000"
    lidarr:
      replicas: 1
      strategy: Recreate
      containers:
        lidarr:
          image:
            repository: lscr.io/linuxserver/lidarr
            tag: 2.14.5
          env:
            TZ: "America/Los_Angeles"
            PUID: "1000"
            PGID: "1000"
    prowlarr:
      replicas: 1
      strategy: Recreate
      containers:
        prowlarr:
          image:
            repository: lscr.io/linuxserver/prowlarr
            tag: 2.3.5
          env:
            TZ: "America/Los_Angeles"
            PUID: "1000"
            PGID: "1000"
    sabnzbd:
      replicas: 1
      strategy: Recreate
      containers:
        sabnzbd:
          image:
            repository: lscr.io/linuxserver/sabnzbd
            tag: 4.5.5
          env:
            PUID: "1000"
            PGID: "1000"
            TZ: "America/Los_Angeles"

  service:
    filebrowser:
      controller: filebrowser
      ports:
        http:
          port: 80
    sonarr:
      controller: sonarr
      nameOverride: sonarr
      ports:
        http:
          port: 8989
    radarr:
      controller: radarr
      ports:
        http:
          port: 7878
    lidarr:
      controller: lidarr
      ports:
        http:
          port: 8686
    prowlarr:
      controller: prowlarr
      ports:
        http:
          port: 9696
    sabnzbd:
      controller: sabnzbd
      ports:
        http:
          port: 8080

  persistence:
    fb-config:
      enabled: true
      type: configMap
      name: servarr
      advancedMounts:
        filebrowser:
          filebrowser:
            - path: /home/filebrowser/data/config.yaml
              subPath: config.yaml
              readOnly: false
    config:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 4Gi
      retain: false
      advancedMounts:
        sonarr:
          sonarr:
            - path: /config
              subPath: sonarr
        radarr:
          radarr:
            - path: /config
              subPath: radarr
        lidarr:
          lidarr:
            - path: /config
              subPath: lidarr
        prowlarr:
          prowlarr:
            - path: /config
              subPath: prowlarr
        sabnzbd:
          sabnzbd:
            - path: /config
              subPath: sabnzbd

    media-downloads:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 300Gi
      labels:
        velero.io/exclude-from-backup: "true"
      globalMounts:
        - path: /downloads
          subPath: complete
        - path: /incomplete-downloads
          subPath: incomplete

    media-nfs:
      enabled: true
      type: nfs
      server: 192.168.1.200
      path: /volume1/media/
