litellm-helm:
    proxy_config:
        model_list:
            - model_name: ENC[AES256_GCM,data:FvlwmIZhUaq+2A==,iv:WllQialKxEvtF7P9JhiKeWYM95eRBa5DXycyKysf0/8=,tag:wGNsB/crFx6l/QfYniFwFg==,type:str]
              litellm_params:
                model: ENC[AES256_GCM,data:GXyC/QRHbGAc4E5dQbpeiaU=,iv:EnZux5wjh3F2fIsl4qdcFYuRfGhF+q8QKFsJk0HAOA8=,tag:xnbpXNpcaE5owuU0sblsqw==,type:str]
                litellm_credential_name: ENC[AES256_GCM,data:EnUbWiiVERQkBDAb,iv:5+yypyYfeUdBWSKbNfwe372KfgTV34+ZjqavSLxI9Mg=,tag:PBPuUThD5YbEXKrRsRl3QQ==,type:str]
            - model_name: ENC[AES256_GCM,data:O0Gs6NTJAejV9Q==,iv:lXhYpMs39fega5UEVj7gGGXE9rdgQYbqbE0Ku6Qqnho=,tag:xJ9a19NniHpDhxxUmpEUUw==,type:str]
              litellm_params:
                model: ENC[AES256_GCM,data:fU6pS3XlozjozFDbtmUktK0=,iv:eAph9PRRZDsMmMXQos2yvb8DEPqJHRs061WRzKzhAdk=,tag:tJZn+bVzGA4/YxI4+um1ag==,type:str]
                litellm_credential_name: ENC[AES256_GCM,data:guc88PFQuK3PUqnB,iv:YiGpsYh6weMu/5nXC3lcXOvUq4FSmNlNVvIMnylY0Os=,tag:KAk8hiDUPRC5UAJM4o/LuA==,type:str]
        credential_list:
            - credential_name: ENC[AES256_GCM,data:1QYr9FKDjg4T1ElG,iv:viZMN4Bfezcxg6vlafCG9GEJ9pLo2uhwynvl8UBFtb8=,tag:Tlq0KQDj2C1Ype8aCKIeoA==,type:str]
              credential_values:
                api_base: ENC[AES256_GCM,data:su+FUDQgXp/mGZdy6v3GbikjTgRYPvmSOHU=,iv:1CPKgNoEkZva0riKni4OOZCimULpCYCeqnK5zl89PsI=,tag:lUjrzf8pWsFPId8NTPRFzQ==,type:str]
              credential_info:
                description: ENC[AES256_GCM,data:AGdy6Ub6iRh4ZhA7MO+3uP+T,iv:JIaryQZ0QdjHbg4QILTgNQzfUv89e57G1veBmi6Gb6M=,tag:xqZmVKa4XgyKMxgEpzstXQ==,type:str]
                custom_llm_provider: ENC[AES256_GCM,data:XiBIxhhi,iv:tQfIxmVNYvd3sr+imYOmyHo/iiM1GpB4mosnJlGTxyk=,tag:HefH6PHqJnKn5Xq0A859vg==,type:str]
        litellm_settings:
            drop_params: ENC[AES256_GCM,data:HO0big==,iv:jqSt6WXt3DGcR5FffKW725gdIG6sRnkvvqYY5YYskvo=,tag:VusU8EOuiMZAcFn+BoRuSw==,type:bool]
            #ENC[AES256_GCM,data:qJdYUIiOvBTEKS4tAIhdXL9jhA0AS9SX4Qsmg1oNIQ==,iv:wUZZ6wNKK1Aha4GT++dCn7NN1LksA4bti7LAJKqBk8o=,tag:oBIoO1A185w18YpDEw1jDQ==,type:comment]
    masterkeySecretName: ENC[AES256_GCM,data:9m3Ukj2boNoip5LfL053F2s=,iv:d+st0zzxxQMDhMlDg2L5gxhuavY7QPe5vAEu1hEn0go=,tag:CJbznLUSaWmwaBDS6GKeHA==,type:str]
    masterkeySecretKey: ENC[AES256_GCM,data:t45SpPA4yLoR,iv:QcqFFWbGp70H4l85qpqdOfDp27e7BS55WAWpph0LqNE=,tag:15DTOAzTtH3PbOx1QHhZAA==,type:str]
    db:
        useExisting: ENC[AES256_GCM,data:k5kPBA==,iv:95V1bSzcPDIyPKj3FRWrDC+hCI0CmKp3trjCqSkZBZ0=,tag:6Q5FeCyf/BCjCbN4n/2l0w==,type:bool]
        deployStandalone: ENC[AES256_GCM,data:gtt7Ajs=,iv:XXzauyQI48yd1vc01/7MG+571eSR2+yuRkZTjXL0fuo=,tag:zpd1V1AePekiJczXH0tiIQ==,type:bool]
        database: ENC[AES256_GCM,data:4+EhBMCttw==,iv:2UJ5hnFTkbfJcmlL4h6DoxXQNMnhLctxYQYZbg6C7HU=,tag:VRy13CEjDciFYXr4iGWraQ==,type:str]
        url: ENC[AES256_GCM,data:DFzAmbEIpZBbDcka4zcndbYhZ3bLMQ29otgbQb5TyAFem1yTpGPM9xzWEen1ineO1QTj3v5GSFsosG77A08Q46zjvDPooydUzmSJIFFHJhXDdbF/y1FOEQ==,iv:l0DOj2NDnT+U82qgzZYzFhdz85myE/HeoxeOuJiyDQ8=,tag:pDcjgYOJHDJkIuTu5Qw9ew==,type:str]
        secret:
            name: ENC[AES256_GCM,data:IvBs0jhRPBuJDOlNDdkq0PlAWME=,iv:0zI5pPRyCQ+7TDwN/wnVAjGkfeXvfXrd9AjWcgdgF6c=,tag:72+1RCK0xB0hJuhfkqf7Ug==,type:str]
            usernameKey: ENC[AES256_GCM,data:bJltUJlzhY4=,iv:jS6mMOsbYVz1J/hGJZJMA03ZGG9O6oa/pvY3oM2480Y=,tag:9H+cszJjkD05jXsAup+P2Q==,type:str]
            passwordKey: ENC[AES256_GCM,data:08DM2KQ0GVE=,iv:Z1fphvi7U2j3VzG8/BO4kyC38yiBxLCMyzBtKDRNV34=,tag:7kKcatoQlvc+LmmnVGPEgg==,type:str]
            #ENC[AES256_GCM,data:dvk4aXERPzzlV6zs0hHlhur3NdnasGthuV+EiCavNrwyd7jE3VG0W7mpSkXnjmhZ4Hzs3o+fw+EYtXgXNTj98iKha+hKQQ2quIk=,iv:NOvaFWBTTCD1/Uy5C0TnZu6kK4Fk0co16jruJ/CSJQ4=,tag:OLtnqmzKUTnRVUzQMFOMZw==,type:comment]
            endpointKey: ENC[AES256_GCM,data:XSu5lw==,iv:e5ACwQQcDnMaBRsKAQeF6bLWHZPqvp4aOZSuwe7Dlm4=,tag:qXYv/TNTiyA5NSnolGOUuw==,type:str]
    ingress:
        enabled: ENC[AES256_GCM,data:f8MUEA==,iv:CfsbrBAKWuhiG1OcALg3LFx10aPTBG/gN9Y6eY5D14o=,tag:3W80w6JlCxv9WPDn+1TGdQ==,type:bool]
        className: ENC[AES256_GCM,data:XrRklSNRdg==,iv:X2lC5RtZlr5vySlYfnbg4hbo+Y1h8PMLbmXkaEwJ1UI=,tag:DL2xa9MlJy3nb2a7NDaSxw==,type:str]
        annotations:
            cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:wq8ThsHyBaAHDggx90LHkQ==,iv:5MUkSnHV6RB4FTPOUCd+ovJZ9BGVttQxDswuvJj3edI=,tag:OqPxxoHbpsPXyR+JAD+Lvw==,type:str]
            gethomepage.dev/name: ENC[AES256_GCM,data:HmFiAweX1A==,iv:tQP4sPLDKb+2vJFsfJQiZ+lmdIax58XjRW7FyxJP9Ko=,tag:xn0O2xkSk1kM/HOuvCqKgg==,type:str]
            gethomepage.dev/description: ENC[AES256_GCM,data:ODF1fHJHdw==,iv:+sNdLNTCD6S80aPXSShxgiUWq/V/ZlcfS5Msee9jQow=,tag:Z/v4mYo1ya2zUy5t+ClIgg==,type:str]
            gethomepage.dev/enabled: ENC[AES256_GCM,data:WiwNxw==,iv:URQDGq1C9GofxMMU5zyQ3laizgVi7xhrcGpqgdBNkHM=,tag:4z29A7F78npWlhCNBZxh5A==,type:str]
            gethomepage.dev/group: ENC[AES256_GCM,data:0f4=,iv:QBEoIGLe91BpiMPwOnBaUT6TvqzXgBwhtvVXvykRfQI=,tag:SmXAe0/bkt+IgA9n0cyMqw==,type:str]
            gethomepage.dev/icon: ENC[AES256_GCM,data:qbVBTHgsS3KelOAIQhg=,iv:Skmf1Obfw2u8sESetbDIwiSWZCtSMqYmTFZyxX5EFO4=,tag:lw68/ThbWqixd/9nT993Ow==,type:str]
            gethomepage.dev/href: ENC[AES256_GCM,data:046OnHnLWmpaik+F1nXzyjzXZHpMKULDioSm6tM8Pg==,iv:6bRC+qkx/U2QuvxFAarvYHw1EznbD72pUFZV4eVxbrM=,tag:AvPVknL1+1MMfJW2L5Icwg==,type:str]
        hosts:
            - host: ENC[AES256_GCM,data:bDFqM5/Hd8KMv1uTg+H2yAnXzw==,iv:NgkAyDScu17eCN1rU91hPLtsvxZWajzFB4kYaS39gh0=,tag:L9o0ZVNkvrYRW/LrSfppew==,type:str]
              paths:
                - path: ENC[AES256_GCM,data:xQ==,iv:Q7ekRB3VOia62XS42dLmg72dz5khkpF9SwCMXwUzRno=,tag:sUBSVErCWJbaNlL6jxd2EQ==,type:str]
                  pathType: ENC[AES256_GCM,data:9tA2tUQZewwvUjuv6N3KG64a+592HQ==,iv:Z3wQlwnLBQa+9FHHRaBURCHL/rQblfxixb770ki6AG0=,tag:Dy+4qXGXHls5T6g7yMA6Ww==,type:str]
        tls:
            - secretName: ENC[AES256_GCM,data:lyPRdNZxtkn6vzY+/Pd04A==,iv:LCxki1nWulb2nqAq85NSb7QEZlqNHIsyajgN339zMGU=,tag:vmhZ19AjJHEOMwuBTKEUxg==,type:str]
              hosts:
                - ENC[AES256_GCM,data:r3QdiswmRA0OZhJyNRjWy3iC3g==,iv:VtTZTmDdi0zbwdoBALAkGiYbhAb57mTCCc+0TAtrxtM=,tag:Q5Jkfl+2SsWfx7ZjO02KVg==,type:str]
    migrationJob:
        enabled: ENC[AES256_GCM,data:1NsTnL4=,iv:8wl5PmwVW91ag0n4lMyZHqPHC6e/qL+nw0l4788C/fk=,tag:0xNPx6JQNe0t2kUj9Eks2Q==,type:bool]
        hooks:
            argocd:
                #ENC[AES256_GCM,data:CvpttHhReJnCVzBsV8y4tTrFH4P+JzFFisAK99dkZg==,iv:F5XH7i108tatPyLx0CxJEeaGo9oz77dkhiCpFzEVDjs=,tag:pSjP033SY/XzORkBWVk00Q==,type:comment]
                enabled: ENC[AES256_GCM,data:R2I+spM=,iv:IoyvUEnuJXZ5wZlW94vqs4pI/5Yt4HYMW/J4xlLE90U=,tag:XDhu3jizwIk3uG1Y/9fjxA==,type:bool]
    environmentSecrets:
        - ENC[AES256_GCM,data:tiwMU6IuWJjlRh8=,iv:CbysCc/E4RPv/Wlq+NgTwpNVLpJJQCA5TNlY+kfsvFM=,tag:6dsf0eM7jPHpMMhEFSwQ4g==,type:str]
    extraResources:
        - apiVersion: ENC[AES256_GCM,data:Luk=,iv:MVS8k/v5z/JAE7EAviDLhA25FJKRxIPXVEdyLIPxFMQ=,tag:N85TkTBPvm4Ct7L9rq67RA==,type:str]
          kind: ENC[AES256_GCM,data:rQ5ANvcm,iv:TxS6NjCFB442SRPwMuK1+ALRgK770QbG543wiz7/v98=,tag:wRJxbbyVTTCuD69m8bsLcQ==,type:str]
          metadata:
            name: ENC[AES256_GCM,data:jru9bdJiLNKL1DU7jgAY4s0=,iv:eMEGSSZZd5m9+/5OZ1g8OkMsJQ1w/i5C+/sWPVVRy1s=,tag:nfICrXjraWTpnr7lDHg2lA==,type:str]
          type: ENC[AES256_GCM,data:V7p8tUyE,iv:DsyoAS32J+MoTMl0rno6Bouv2BfSR3rAeGCa8jedIsI=,tag:NQr1kyiQwssf7ImDh8qBDw==,type:str]
          stringData:
            masterkey: ENC[AES256_GCM,data:9IDFSNL8UvPr+F2VkPEZxdUzHRGOu/Llxs1Dg+ia5vyZgEimDpfz59giahLrDVoZ1AQi,iv:tSRtri33081TywMKNvVtstYdYZ46kd/P02SR6a3hyGk=,tag:lMefIjyoPcnR8OuKOYeSSw==,type:str]
        - apiVersion: ENC[AES256_GCM,data:Xkk=,iv:dYbivgDuJfMhfzeZQ4uaXO3JhcJ6XNY0kc7mwT5c9zk=,tag:v42GjP4jDn9dUUukIgtCyQ==,type:str]
          kind: ENC[AES256_GCM,data:Dw0q7rW4,iv:Ex6OPOxuj0mICuKuvYMShPLBZD9EqQ8uphuVZZy+Ad8=,tag:z2LHfBk+VVVeWCK/X18EFg==,type:str]
          metadata:
            name: ENC[AES256_GCM,data:O+PtkxM3NsCsIkw=,iv:XaxtNS+z80UW0H1JKb7xS4jf7E6CdPvTZrpZq21L9w0=,tag:g2n+rccNDNxuDiVMR2PFbA==,type:str]
          type: ENC[AES256_GCM,data:wUX1rGd6,iv:0IrGKMbpiNUXscbJpO6Fd4QS2jmNScNpzIly9BYHSAs=,tag:96B4x+tidSyn2SSPt/EVEA==,type:str]
          stringData:
            PROXY_BASE_URL: ENC[AES256_GCM,data:1+S0VpVjKOWHiTwp60q3NDCIBq6RCWBtzGTv,iv:AT/CmAdaMjzQ90JDidAfZluHHVnGIEMKZQTH9/RREuc=,tag:PIiqkBvjujLNV2kbIiW0MA==,type:str]
            PROXY_LOGOUT_URL: ENC[AES256_GCM,data:ByUPVf7Oi6NTr1/mLhG36TWdZ7bxLhTIe3tt,iv:E9Txncls2w6iqCaL+wIwEYDP+GDuFXjpelrjOVzLcr8=,tag:H5h+4gbrxtvspT/IJiYqXQ==,type:str]
            LITELLM_SALT_KEY: ENC[AES256_GCM,data:Cbo1aGPFSxTkxmhsRfvDSIz0CagSpNLeN7OM2w+oM4W67kBPVpNC9WerDOkLI2MWjYel,iv:QtAKwKPBy3lTgRhc/YGIvdb07+SbdwflYlNmM9N1R8Y=,tag:UM/YTrKsWZ/9R25/0hyMAg==,type:str]
            STORE_MODEL_IN_DB: ENC[AES256_GCM,data:u8WC+w==,iv:h5MNrYPm3IU7XWzGN1KFv5lCVbYCJuo1Eu+4rPDQb8M=,tag:cHjfapzFZP1wCML0sPlDCA==,type:str]
            GENERIC_CLIENT_ID: ENC[AES256_GCM,data:MMANl0+7XsZHeEs007DxMLARqNClPa/wWFq31Lcgm/J0rMcz,iv:Z30u61p/LAdlVm9rR5ufykyQJgAQPHUdTDVIl6zCmdk=,tag:uuuPz47RBFtaUjwNBrLIdQ==,type:str]
            GENERIC_CLIENT_SECRET: ENC[AES256_GCM,data:1UDxKGKbpbWKysm+VTjx/QsuKLpyq6vFJvHXrBMmI60=,iv:ut2Rdo51OWtkPDNjgO1G9XQ+rj/6B5P/S8jE/Ffb2Zk=,tag:CC9b8+LgVT+rMnFU2pEBdA==,type:str]
            GENERIC_AUTHORIZATION_ENDPOINT: ENC[AES256_GCM,data:kbU1EWnTKTiP9kyAB+80cRYRLzD/qSgmkyFXV+2Suqws6SJt,iv:cylUdP1WR4lF4e2BR00wpKQhkvX10EzO/WAlfrW8RG0=,tag:Je7DAshcv59P9Vs313aBKg==,type:str]
            GENERIC_TOKEN_ENDPOINT: ENC[AES256_GCM,data:GB8d7z/+n+X2A9TpXpazQc55NMfAog54jeQoFYOQH/Gkz7wBKaPl8HA=,iv:0xOQU6nrBbH9MW3Gyle80k5Cr7gcZvXee7RV0hfz+mA=,tag:0sbjxREFhhio9ol4sUow/w==,type:str]
            GENERIC_USERINFO_ENDPOINT: ENC[AES256_GCM,data:5DLU2puv+cR278ICAWeeyK9VuRF3flpFLJFPHhrf3sMW6mUMZRPZijgK3D8=,iv:E3fC/z4jGfK2oO3Fh3wlLIHUM/G0U4xy6fPpYpSsAvg=,tag:GJu8Bk2YfFtI1p2U9lbEaw==,type:str]
            GENERIC_USER_FIRST_NAME_ATTRIBUTE: ENC[AES256_GCM,data:syPfwno6denRMw==,iv:AFjB51ZdK+dmfV30V+IBpuyWzwxdW0y65PfLX/1+5RI=,tag:pltW0R4Wu67g8cwmG4kjzA==,type:str]
            GENERIC_USER_LAST_NAME_ATTRIBUTE: ENC[AES256_GCM,data:pgbqnpiHcYhkBcs=,iv:WLywX5FFhc72zf1/QTGJ6pceB5sI6wHEwA2DuhMNeLc=,tag:0i0C8G3ubRxv9pZybssHSQ==,type:str]
            #ENC[AES256_GCM,data:miUNv8SGif31KjEZ/E/Uhb9FNcR8IQv+,iv:eJTnvRmE/rPKeJrQ35vFVihxtYr1MNVj79TYMDM/35A=,tag:vAGgiClRjE94bB9v8Ddl8A==,type:comment]
            #ENC[AES256_GCM,data:m3xOkV9Whd1QrHFsZQeLAMPa1O+unRgx,iv:Kyu0oxSBeLIxOnxwPC43GA334xjiV4usm3Ih0RTfpeU=,tag:EE/KLlHstXG40abr2T67BQ==,type:comment]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTVJpeTJLUWdpZ2FLVXdU
            RVNFVHQyR1RaZWJYTzVVU1ExTnYxY2EzbUJNCi9GWXpWSzMwRjVNMC9yaWYwWGQr
            Nk9jVEF1T0NNcDAwT09pTDZzTmJWc3MKLS0tIFVjSU5laDRmV3dmNjk5bXN4L242
            cU1samxVajV4RWZmajBia01sVkZoOEUK0z1cOxSZ58Awdo50kX53DxfOiaUDMQJq
            Pi9TY/4Toq0xkYuA5MoTmw1MBLclHrZEGtitGbqnZ1+hihfZjEhzfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-16T23:49:51Z"
    mac: ENC[AES256_GCM,data:rF2NG1JxsfSz/FaaXD015ZVcg/Rw7LgjRjxFDGK5Z3QeZIDpRb/go7C1MXvJxYcxhPA4YOCc40g4ub6w02NsCf5SdPgLKBHQz7yPw7k8/YUXXiN1YrzKxY4iQHEjPqUfd60ybwiYHFqHwjiFXHmRuKlM3s7Ju/FmdlxqkD/tTRY=,iv:ezrO1ndmKojy+tSQpfqqKYn2xy8o7GZ64FQNXHjOCb0=,tag:+C49QXcF6W8btdTXW7U3NA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
