app-template:
    ingress:
        cleanuparr:
            enabled: ENC[AES256_GCM,data:XLNpdg==,iv:NBy9yVMmVWxJhpnGBPbchekXzEF/qHV4aX8THtd2C1U=,tag:BaN1iKuMiiEUglTM4l3ZrA==,type:bool]
            annotations:
                cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:4fW8Qe95eZyPvwt8wIIHTw==,iv:DEkVf02lwFMfwDrYqIL+agq5hncEdNco1xqAfE9Zh5U=,tag:fPnn9lHy54N/CP+ZMfWxyQ==,type:str]
                gethomepage.dev/enabled: ENC[AES256_GCM,data:N5wOpA==,iv:4NIQkXvis0aqQdA7SsH2fi2Q5f61K21k2ECUA6/6pTI=,tag:1BhNkhFvFmoBgwRAjYjKMw==,type:str]
                gethomepage.dev/name: ENC[AES256_GCM,data:KvIMsj0oco9pbA==,iv:cft4OmkWmUWRi/TOWKyoaQe9z3ptArrJ0YlFL4VD64Y=,tag:3DY2QxgsNzZZI6GOUQX97w==,type:str]
                gethomepage.dev/description: ENC[AES256_GCM,data:RgqZe0qi5OYabIfIIyiog/YgNTbBsFqhnbbUMA==,iv:yIOKyTvKoSPcPmRteTKMzCiB3gr7Sz45VNiu54NUaY8=,tag:OMfVAIKtXsX++BVTDhOg+A==,type:str]
                gethomepage.dev/group: ENC[AES256_GCM,data:r8oTRZf/Dx40c0RIHFA=,iv:jyMN2Eg28L5Db8p5QnR5jGFDf6mQxl8sjMRTdyDRpVI=,tag:AFACisUmqsJ4lrUcJBSpTw==,type:str]
                gethomepage.dev/icon: ENC[AES256_GCM,data:ZQCtJCJcnu7BK2HfrHwPjfs=,iv:OyB7YaDrDCc4Vg8OfpwD6sSi0TE5dQEoWA3D7ByQvJ8=,tag:Witgd31GiylbSXgweTpxsw==,type:str]
            hosts:
                - host: ENC[AES256_GCM,data:0glzwWAYRgj9x7LWZt3aCKygWIO2zA==,iv:ML9hLDXu1/aGs/QZvgVck/nzIo4eb2lHvRTvEz3ydDc=,tag:1Ryxu1++B9ti/180YBAyGA==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:KA==,iv:scjRL3VAHauaOfsAWoNMprsdVOj5+RcYFtoBdzevnLU=,tag:vg6g/3Pw/FeKiZOvovcLKw==,type:str]
                      pathType: ENC[AES256_GCM,data:vGucM/2b,iv:LqE15gmeLMaQpKHKnBG+i0vkA0RF9AqKErjn8UFh1uY=,tag:SGL8Z+64Gosm8+S8b8f0YA==,type:str]
                      service:
                        identifier: ENC[AES256_GCM,data:483Ks6rI4zECQg==,iv:UNmVB8K9NfhsbfIuh+a6QtVg0gRoAgnw8NDCG5vdtvQ=,tag:MS7y/pcNhH7hswtLYB+KKw==,type:str]
                        port: ENC[AES256_GCM,data:RoZ6vg==,iv:YJtM7+nbUyOttS7AWbxeQVMiWyGeGdQmmC1+IrFFuKY=,tag:YuOTh6lT8bhBMOgS6pUghg==,type:str]
            tls:
                - secretName: ENC[AES256_GCM,data:sZiAy/WvcIxuLz4eOtvUj8OEfg==,iv:oh1eneBtwfqB6ajV8Rsg0Vv+zWZv0quLlifzALdX5lQ=,tag:urOO536EglNuFWBf0LkZ9w==,type:str]
                  hosts:
                    - ENC[AES256_GCM,data:dySkYYQ2y0b8XCbSDqSl8RKEuuYIVQ==,iv:kuVD8c10bgceVb+WpWl2gcQbRf+6zWZAGekS/UCzNLk=,tag:VvswxvbMRsYtrX0aOu/kMQ==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtc201VWNOUm1XSEtLenIv
            aHUvWHNuaGUrUVhoZEUrY2NHUGtHbHlnSXdzCnZnajEvYjlBRXpvRStrb0pEbnNy
            SG1aalFYQWRlaGgxc21YS2tNRHQ5QmcKLS0tIGdicks3RlV5MVdQdkRxODQwZDRR
            OUUrb3lCa3RicDg3eDdKTnVxWEFEeHMKMKdY46Yi2FRNagPMMCGyyP5C0deswC8y
            TU2zHYIqccegEHyjwp3wOjapTook0tf2idXx3KEBtFxlZ/uMt88VKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T19:02:30Z"
    mac: ENC[AES256_GCM,data:AZMSxQ/GPCVWO5X27g4+CFtyf/YESZ9/kZHwhgsQxoa9TMWURT8wg6fRWuPYkAJC0E4NPlbYLBi5uJYOS65GeugXfmuuzNfn/95XE0MxldkcEQ4HOpbjpC6uX2STQV4qy+QF16/9nauR+rJax4G/UVeWfqijfainL16L496j9xs=,iv:/s+cnJcM1Wg1MH9JdstejNiQTPdpj0ltZXJrBekXmtQ=,tag:6Q3EPPRtwbsC9j1NsyO+ug==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
