app-template:
    ingress:
        cleanuparr:
            enabled: ENC[AES256_GCM,data:skloNw==,iv:vRJZBeBiPVmeA5v6PP7MNY6TyOgULxH1PyoqrQfTkHY=,tag:lkl//0vXO5tp7u5pL6616w==,type:bool]
            annotations:
                cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:uDAFmyFPcXBlIjFuYOSpMw==,iv:X0BNy837ZFNTuUjYzdAItccJIc8U+CtZKPUJXoharWY=,tag:7HSs+TFAqxZC1G3H9qi3RA==,type:str]
                gethomepage.dev/enabled: ENC[AES256_GCM,data:SpgbDg==,iv:SLO77RsPPCxNbb+oI/HGb9+iiq6XCaraiei3JFZKyDo=,tag:mwXfMC/2nDTnTNW0Pu+hDw==,type:str]
                gethomepage.dev/name: ENC[AES256_GCM,data:nnfdqkACAYZ3nQ==,iv:AOmyw82XcqWLbLRTBhaC5aZ84QWO5TMzHvyMQnX6VnE=,tag:hr/No0ZAVZd0CMT8Vr/lWA==,type:str]
                gethomepage.dev/description: ENC[AES256_GCM,data:c9ojxkfM5apRyWdYPyvCLQ9IbFvD1+bUB/a9Fg==,iv:M1MEbpb9v4ntVrKtl8a1l/RqVRMWucNwQYvSGfdyrlg=,tag:f0uW7w9rYiSMxeDRG2L8Tg==,type:str]
                gethomepage.dev/group: ENC[AES256_GCM,data:56P5Y3z2De0/KNU=,iv:aARpu1bubsh+ptMYz2PzAU/OKTcV5P9YJXC14TmCPSE=,tag:QN9Yt28xIzZ9YzoOlbPD+g==,type:str]
                gethomepage.dev/icon: ENC[AES256_GCM,data:x1LR8sg3Qwqkpik0gc8+81E=,iv:gr9nLOs/YQFyxywJ192MpTW+tALjc9sBfqmscmtXHvQ=,tag:vZVLEczW+fGgFOwObIwy6w==,type:str]
            hosts:
                - host: ENC[AES256_GCM,data:+MpxIjwWC+eEtKasH42wYsE+ZxGoxg==,iv:NUhirOD9y9Apl2xrbL0kl33X0/ycp7JvL3fqQpM+pEw=,tag:ts+zvfbLi6Ddrmn21MDmkA==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:bA==,iv:10E8rwrULSkRxfQZ3LnMlaIHTHUKV1DL2m6WQecN55E=,tag:6TAAl7tA47RQeSZ1PkNpBQ==,type:str]
                      pathType: ENC[AES256_GCM,data:Bm1/M6iz,iv:Ayel/M/TKMRwCRzmov2nrXcjLsjGYJPZB6VZakn5Iaw=,tag:mgiiq2IwZufWplw3i5Ct7g==,type:str]
                      service:
                        identifier: ENC[AES256_GCM,data:2Lwv8OSYsWYzqg==,iv:/wGkadCWyk/8OwKvBdCDJe2YFv13d4OmHDPRpnoO4Ow=,tag:wFBDuUUTw7XS91mr/HjxCg==,type:str]
                        port: ENC[AES256_GCM,data:WrOlKA==,iv:GS9u8Sor3jAnBhk/zP+9a/mpIJDLom/5ZPk1mlr12ig=,tag:oy90I9wLD0VVlxh59BMqpQ==,type:str]
            tls:
                - secretName: ENC[AES256_GCM,data:0aZ+TPRf7t9AU+mQvUAxyOaA+A==,iv:NcY1COh8pHasXI1p6isGAjGeLfUQ9lPuyF98Jve2VuM=,tag:jgi95qTvrgp8yuqosMwPHA==,type:str]
                  hosts:
                    - ENC[AES256_GCM,data:xwM2f5lqDpRySsnzwMoDOcw+ncl7pQ==,iv:D/65p8MAKskVPbx4aD2bcWWbDOBE0WwLhGMXELbMl70=,tag:eUlvdyb9zT6UIA4r11I9qg==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bzA5aVdTczBjOSs2VVJz
            anljMWF3ZjNISXJ2MzdDaTNjNWtBVkhoK2tvClQrMytnbk9seUFSOVNEaGJUVVM4
            eFdsdEozTUl5NUV3SncwN3phVHk3Wk0KLS0tIE1wRVlRNGNURkJMcHExRkIzSGZB
            RjRneUdQcGJqbU9pOEdXbXZyZElLYkUK4xezN8zLUM4sQAHyzPgKbw359Ly/FOju
            lfyj6rtYEyN45Hz9WeSZNojUDe5buxLm+T0VG74NnpwrGyYomLV0EQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-19T15:04:13Z"
    mac: ENC[AES256_GCM,data:XVobxP9Rpka4pcjbBpxTnNTpv664CGh5k2NsTP9jSriSojO+/N+A6oPD56o2rmfjEbwR/zqqgkOJDuHPQ7h5K8aeCHtaSl/V/UURHujj0mba7Cxv5fb0gtQLowQy6i6z+zK0xsoUEUrIzc+yaTre8rKgbxVcpkWuGNg5lrQfutk=,iv:aVSYXEyQhB7hx0mq0xJjgFIgkjLoe07IIWixZpGi4xo=,tag:oNogopE9AuFPXetAWmCZug==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
