---
app-template:
  controllers:
    cleanuparr:
      strategy: Recreate
      containers:
        cleanuparr:
          image:
            repository: ghcr.io/cleanuparr/cleanuparr
            tag: 2.9.15
          env:
            TZ: America/Los_Angeles
            PORT: "11011"
            PUID: "1000"
            PGID: "1000"

  service:
    cleanuparr:
      controller: cleanuparr
      ports:
        http:
          port: 11011

  persistence:
    config:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      globalMounts:
        - path: /config
