app-template:
    controllers:
        main:
            containers:
                main:
                    command:
                        - ENC[AES256_GCM,data:7FNhxWLUsw==,iv:ZvAd28/so4vBm1PtXUB7d2yqRfav4LNUu17pWB9r4co=,tag:Ol7mpdB0RKhuwLtsxEZTkw==,type:str]
                        - ENC[AES256_GCM,data:Ccz4,iv:D+UwIYBA/rljympsbFVCvWnovWsZQxU7SaO4rNvi5N8=,tag:spgc+kmSE9n/MbZgCc+68A==,type:str]
                    env:
                        HERMES_DASHBOARD: ENC[AES256_GCM,data:MUlq+Q==,iv:LgUvA9oZf17p868w9Mn6l6eo9Jlay6rqqXo6Y88k5Qw=,tag:x/vGTXfiDpu8ai5Wa+uUhA==,type:str]
                        API_SERVER_ENABLED: ENC[AES256_GCM,data:Axp9zQ==,iv:AWJkzhBk7WeM0ztx5t71JuXUK3yQzuRTQgXYpcbHxv4=,tag:aS18kw0yJVuCK0H4M1GYGA==,type:str]
                        API_SERVER_HOST: ENC[AES256_GCM,data:zdUt0Y75ig==,iv:kAjILBmjuO0+7NOv6macERMrmt1bgBNjGmFCV9ceD0Y=,tag:p9Fqk3IZcVpjUS23bve+zg==,type:str]
                        API_SERVER_KEY: ENC[AES256_GCM,data:pG/mbEMttmoEE5OEBNDslgocuXm1JjyE+sVynf47DVd0N10c7LibYyhquDZXP5XSorZk5wIn6KDqBDTeQzvdIg==,iv:RBl8mY2QZPQd/wz/2VTFIPwWWZZ5fA7cZXZnUxQJb6k=,tag:CTKOoGMGbUGLBwyfuINqWg==,type:str]
                        API_SERVER_CORS_ORIGINS: ENC[AES256_GCM,data:Hg==,iv:url5lYd3YmaPoPc8yhzPeK6lo+BCfp2fcDQ5UmpBvMw=,tag:mF3hiEh9i21m6f/4YX4f5g==,type:str]
                        HERMES_DASHBOARD_OIDC_ISSUER: ENC[AES256_GCM,data:g/CJQZpQ6eWfQA2rUUPx4LOemXQ4rAODalk=,iv:sI1NoJjePIlwzVYYhv6ZE6nIjhB8Y1uzbitQphh6+Xk=,tag:jPxl3PY1xbzTSnDqFALk3w==,type:str]
                        HERMES_DASHBOARD_OIDC_CLIENT_ID: ENC[AES256_GCM,data:+Q3mgeGMhA4gDxcCtOXJ2rzXWwPg4MSLY6aS4/K2zFheTsfX,iv:o+NcnPASagUzZOSSsPSSDiDICFE+1/qQ1w8I9zLnNoE=,tag:zf2ISTDGVc36bUNU8SWD8g==,type:str]
                    resources:
                        requests:
                            cpu: ENC[AES256_GCM,data:xQ==,iv:2nZ67Bpsqiv0vVrZlhdoilixGFsKLuD8lWbS4ax+/5k=,tag:EXgOn2Q9+5VTI8wmzA7gvw==,type:float]
                            memory: ENC[AES256_GCM,data:msAz,iv:EJpgRYR/yiaMN6LiUngtx+9wA2PhcjaJr97HLP37Nas=,tag:Wpw4IDwOhCp/krbYn94YmQ==,type:str]
                        limits:
                            memory: ENC[AES256_GCM,data:r1CY,iv:o2ZKicPBkVtnGXDgUfzf7eveeVHxLUDe3/q3IFD5nS0=,tag:EZNMFUqhqPwjV5IsdIJ/kw==,type:str]
                            cpu: ENC[AES256_GCM,data:EQ==,iv:2D4hc63COHpidS1cqf1xeb2iSzrG9qQbbqve6w9YLEk=,tag:oRapdA63WUK1vmNcFhXPTg==,type:float]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWEdFcllCSGs4SUs1K0xX
            ZUVwV1dFbk5wRUNQMzFHZGI5eTZiUSs1MGpNClBKWkRmSFJuL1VDUmpQWjZTYmRj
            V1R0OWFYRHFhbmhaNkxoY3BFc1ZLeFkKLS0tIG85VU9VUHcxa2hVL0ZlWUhUMjll
            OWpIU0x0K2xvWGVicTBPTk4vSlhiNVEKJIKwGnCwgMvcdRAB5djdRHmWS7JQ8ut3
            YAAabuVlHzft3XnWO037xCc8YieQl6Cvh9Zrj/j3oy1fNerRPmC/2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-24T20:07:31Z"
    mac: ENC[AES256_GCM,data:vrTG4c47FAg+HBdlWLhhER+4EKbjgdF6Rpn9Ybvm6lIY2eLKSFABcBg15SrjtQADTcPv/h0ZEfVLlO3ffrPtJ/75bzgRJZ8CP5znstnbMKC47C66+Pl9uQcUae2I/gZ9gTeWkJoIgvAYzxJLD0/u88qOX5kP14jstvnhaqNTpgc=,iv:8h5dAb0WBOoFQmL2a4Qb6vvwSfSszx7NsIjKsbejyhA=,tag:rOed3BrecB16QAohS0N4Vg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
