app-template:
    controllers:
        main:
            containers:
                main:
                    args:
                        - ENC[AES256_GCM,data:fDlFsEgb4Q==,iv:no6azW5TJ7xiHvB3p6FKKFFtdWZNYjJwk6YVlpqhAgQ=,tag:Bn2aPHfDUwSvomFwtGJDbw==,type:str]
                        - ENC[AES256_GCM,data:bK3q,iv:wFqhfJbQXahq5eJGqgbalcweq0NusloAPtU2kP+Ctpg=,tag:9LGuCziyZJ8vTa+xiY9Npg==,type:str]
                    env:
                        HERMES_DASHBOARD: ENC[AES256_GCM,data:hIH2WA==,iv:VYLPDabiwEK8rBP+lowkOd9EGlvZjdBK34MXL6pU/V0=,tag:V67uyDj+7/YQpaq+A8stUg==,type:str]
                        HERMES_DASHBOARD_BASIC_AUTH_USERNAME: ENC[AES256_GCM,data:dTcqJnZdaw==,iv:Eh2NGb36A+iPmCI43GDDkNhiOzpvpHPl0XWi3BYtvUQ=,tag:/9JMKZoZZey9ss//o1pv3A==,type:str]
                        HERMES_DASHBOARD_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:v/eXZ428vtRPVXWTH0P0cpxzUPI=,iv:yGIflKv4OJirg3aj66YgXO8HC6C5D/MQ+NhvlFZSvTo=,tag:vhdXHbvbfTXfaR9iPdDTFg==,type:str]
                        API_SERVER_ENABLED: ENC[AES256_GCM,data:LUpZ1g==,iv:CrMrqgtbbZLLcg4ysl0Qbgy7yXdssMk5ULGx4vk4KqA=,tag:oh2nwC6oqm8SyQh6cIIuUw==,type:str]
                        API_SERVER_HOST: ENC[AES256_GCM,data:QhGzO6AQKg==,iv:vShxl9TvoNcmcC49gS1pVCrCRhq/KEwPwZwswwRK8XY=,tag:+Ea56fBynS8X2y/rtCfSZw==,type:str]
                        API_SERVER_KEY: ENC[AES256_GCM,data:EZPfyG8q1vfqwmgnmSMJyeempg==,iv:YLSxahqEbjqy8SAAUx5XauPCSCd8fMEcZCK6YKFn0gQ=,tag:WqqzR1EYBXOFTW6WwETPbA==,type:str]
                        API_SERVER_CORS_ORIGINS: ENC[AES256_GCM,data:vg==,iv:r0G33OsHYwA0vl2RoZu5hHsALt6JypcUd/bXrrH05Is=,tag:Vre96ckkf/OB0GV19k8koQ==,type:str]
                        OPENAI_BASE_URL: ENC[AES256_GCM,data:cNl3g4qZowiVtTSuhZqldinwVfPtSerWqmlu9/A39YvU9HVpQGzf/dqmT4KMOSdM,iv:0pU9119np6wJCiy/WL41/xhHQdi5sqx5Eul3fyRD7WQ=,tag:yQHX3F99NLZmcoWbsAleFQ==,type:str]
                        #ENC[AES256_GCM,data:xm5HbZnjFaZLGy283uq4lV18OwXR,iv:J/ipwy5FeX6u5xukWzAhWnoWimF4sONiiofXQ+t7V7Y=,tag:CFiijPK5SDdQBzpXA9/r5w==,type:comment]
                        OPENAI_API_KEY: ENC[AES256_GCM,data:PhiloQQL5fYLDMvgV0h3QGaENAULkqJkQg==,iv:Yn12YJDQBFM6k6aym/KvvppqNOi1KZTlMNXi5ZpWfGI=,tag:8ZRN1f7zIolT24KpRhkKNQ==,type:str]
                        #ENC[AES256_GCM,data:ygh/NzKh9was71m0z3eBWEQaIynqkArfYNX6i119O+PLr+MIKhs6cjO6AD849K1OfW4fh0yw2rReyA==,iv:fDL5+//7Vl9ILL+Uch7bPJDu5VTSG4sWsXOXRWbidSM=,tag:ubsSctu5iaDeLxR8Zr0+TA==,type:comment]
                        #ENC[AES256_GCM,data:bBVne9tUzx939PA1KC/haxlreVcnEvKiJJhDWsSIIkMhoReJItjTRd5E6SuOudUO2MZYT4QgQxPHipE=,iv:ftExGbHscp/qn5aRUuUAytENzOADzBJvwD9toFl/f2s=,tag:n+WZxTGYfWLphminEdsqBw==,type:comment]
                        #ENC[AES256_GCM,data:ckY5UXtk5M1+QVAvDHlrA3RoWE0c+SIwMc+avMIAt7fi0XBDFrswhrppvpDoy/9M1zpbpD0R0kSTkaK/zkURXWdR9YucQUEo,iv:uhTNbp36CC04f8qOFg8pUereI8M23Fz5FqNR6BsTpaY=,tag:ejtQoft7xie9cCqDJvF/EA==,type:comment]
                    resources:
                        requests:
                            cpu: ENC[AES256_GCM,data:PA==,iv:7kCe/A8LTsF2as1vHq9/idle0U/8rUB+8d4ldx1ckdY=,tag:a5BNjzE6PANrSVe6T0gi8w==,type:float]
                            memory: ENC[AES256_GCM,data:7Xzy,iv:4JyandvJcYdAki4YRU1Y4Ax4PBMah6PzIl7bxYuNq24=,tag:bdhUBMkMS6Rvi5KAR/TkNA==,type:str]
                        limits:
                            memory: ENC[AES256_GCM,data:paxx,iv:/Fgm6VHcDv+LVrwM5p1of/TMcg6Hb3mt5lAANv+ga/0=,tag:5Hu7QjnvXfE90N97KBYHzQ==,type:str]
                            cpu: ENC[AES256_GCM,data:Fw==,iv:Tz0BooF8kcyZNPyT3J83kGl7c20mg0d3JyHbQYEvVHs=,tag:g/wFT5gHd0Kups1G4UpoyQ==,type:float]
    configMaps:
        config:
            enabled: ENC[AES256_GCM,data:hZGD6g==,iv:GX+klOWHYdJ/fPfWPIUdAX89eRWUhquiwgjdQGFyBks=,tag:ZRbPjJnRfKkBb1re67LMWw==,type:bool]
            data:
                config.yaml: ENC[AES256_GCM,data:uManGAHuqLclp4E0l8Kt94Wb7fhzD6wvNjOfzF7MGbTmogFD5lNOWm0eWq8tIXo3ttNd90VCJHI2CDqXbDmYJvnhUpda/ozYLDr8lJD9U0zQ/jqSRuhIjqY5q+fB+yX1J4ek1ZRWGp231bYr1ujR5Pgp4HrHMDSa5U50dL0pjxJSz9Fe4Ms3TZnrkMg/7IY=,iv:XZAzb+tSJ45hRexyffZvlIQX09Xa65MNk3dIhqRiYTY=,tag:qakde4SP3rXykfbomE3XDA==,type:str]
    #ENC[AES256_GCM,data:leMFNaMloaOU,iv:x0If3EBSha9i/EYllkeIZXVm1vSY9ETPsCZ5XfYfNY0=,tag:kiMKuGvD6tIl49ApnaNZPw==,type:comment]
    #ENC[AES256_GCM,data:XS2TWnAtcvpOGNrKldqh+UgGzA==,iv:CVFMV8NMgEQJWm90jwoHr0/Ay7mqMVCqZcnHWJ0Ojno=,tag:pdEuGERw97XxKp0pKDoGNQ==,type:comment]
    #ENC[AES256_GCM,data:4zoPCkkXR67mOQbQWxKBQG5u,iv:yGYC0KKBYAsqsPwLw3VoOQuwvKiUh3S9NdeqCDq50XE=,tag:h5oJoSSGSYoSoR67GoE1tA==,type:comment]
    #ENC[AES256_GCM,data:oGHEUFr2V7f82FTl8e+sqbBtqrw9Zhpeml4liuFBZTy8,iv:Q1zU+xhUoqkVTy4iM8iXLpr24U7ALR1mrYd/xDQxgNk=,tag:d9IoCNFBXo57wJUy+9VPng==,type:comment]
    #ENC[AES256_GCM,data:G11TGNM0c0g6jvaKi81N7w==,iv:E9C51/lIVD0cAHtO/OKIa33CH41Uo7PZMztAS8tjIBU=,tag:wEyEZjHRI4Hb7q2b/mbJBw==,type:comment]
    #ENC[AES256_GCM,data:xC5Drk8Rca6MtDVQmTM=,iv:/VBqwCo6tR0NUXYBbaOfpZup9nfJR3LPKrqVzwPqmcc=,tag:kzWYDP9B7m1ETkluvussIQ==,type:comment]
    #ENC[AES256_GCM,data:oYEYfi1IpL1enLBkrkMfBNDlU+MBgF8bDKHl9aE4B6E5B+P/KK8GHzS8u7ezuPQ/2V5D,iv:O4RJ4b3+yvW3Tk/Y+qgh4GVlgxfx8l1QWhW0KTL4B8o=,tag:hFc1KoVKegl8LVXcw23aGg==,type:comment]
    persistence:
        config:
            enabled: ENC[AES256_GCM,data:mcwJEw==,iv:vVh8kCE3bESjM83FSFb9VHyT/gEzH+iaG15BRnvZUdg=,tag:tNoCWL8YNA7TyZFxYgbG7Q==,type:bool]
            type: ENC[AES256_GCM,data:9WHLcT5a63LK,iv:fuwDTsTQ9WVe7P582WL4UBNbcPpoFIKgTjD+kFLThPM=,tag:2T5D5sx4nIbUIWN7cnLBgw==,type:str]
            name: ENC[AES256_GCM,data:ltEvOGnh,iv:Pt+3hRtqwINJ/hNyiCaW/1OEfF/M2naBmuuSV1mt08I=,tag:pYHOICBfNkvVa2f2Janu9A==,type:str]
            globalMounts:
                - path: ENC[AES256_GCM,data:gkkySZh9DKGL+QxIuiy4pgMNfh3P,iv:AQoxnH845aP8x9ivui9g2Ax164HdlZu6wZDqlERaFUI=,tag:1p4aIn5u9qRq6BxyPgv4mA==,type:str]
                  subPath: ENC[AES256_GCM,data:KxRKI/oRyPHoCkY=,iv:cQqjMjhCK99lBdiqA8/TZUMro+fSGrqlF8iZbyvhKYQ=,tag:w5nMxek7LtzM1czLG3B+Hw==,type:str]
        #ENC[AES256_GCM,data:TBfBeZ6f4lxmz9/n7x7byk8=,iv:TwG2Tn/S2ZaHomG3TXTslmwM0RQyt6PrmUTb+i5a3xY=,tag:Xz2xAjeWbYZ5NoXuW6khcg==,type:comment]
        #ENC[AES256_GCM,data:ZUkX/heRpZ3CN2yE1e7R8w==,iv:aybQ75uGy3rl4WVynf5Boq4G7ArQpkJLpCHUcUzS/Fg=,tag:mtjrT/xPPUO0mifHS742bQ==,type:comment]
        #ENC[AES256_GCM,data:fsBnpMUfXogJwM60syUj,iv:EQFKEN6BIsueBdXk+YqN23EhyB8LtWFHiK0r7TklZmQ=,tag:XyigXVx0XZUu5K/XnLSYug==,type:comment]
        #ENC[AES256_GCM,data:0h6DofkwjyHdpqd8SxdcUsOwBjzBcBti,iv:kIghLLYpbsPE2K0HwmASCDtZSDxCWuOf4Af21f52//M=,tag:1fat6RP2agT44eETwV8GdQ==,type:comment]
        #ENC[AES256_GCM,data:f3AORbf7WbpCqDOAU6eXvQ==,iv:qflbgGELIX6osrULG3JSnWAM7BE2rOIxJRobzpJ0R5Q=,tag:5DUtm3JBUPTegkkQLbqgiQ==,type:comment]
        #ENC[AES256_GCM,data:k+IIGZpPBizlejYL5H7cz7qqbWd98uED4jz4D74=,iv:oyMmfjiwlXlBwqW/ij53fOC9193DeyFxooaE1k743ms=,tag:D6ahyoe3pOmjGRt53tUJcg==,type:comment]
        #ENC[AES256_GCM,data:nSGywOcuLUBMGEcwqOPNvV1rA3M=,iv:bfTyUknnqXvnC9lP4J1CRp4dfQGPeSUjEd8Hg5M4c70=,tag:eTQTpiLx1DD4sXwsty4uBw==,type:comment]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0cHE5d3FPclg1VjNSQ1VF
            czdxODhIYncvbzBBQUNpQzFFay91UGdXcXpnCnV5ZHpZWlJJd2JNcE9pRU9FdkFq
            S0FTQ3ZYR25IOUt2SndaSTBCb1ByTzgKLS0tIG1IdXlmRXVWajkra0l3MzdLcTBz
            RXZJbm9UMWo3SnludDArM09peThySDAK7nKvVswdxuoCY0G6b8ZC8bE9mf9rq55g
            392X5q6TAtR/mja6mN8VOAjoQnYSNHw34fwLfykcI5oFiVjRbhxTew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-17T00:29:51Z"
    mac: ENC[AES256_GCM,data:lvYfr/+ZhqCp0S4XaApWofiaAxRx3NMuKsMbNn5NXk0UgDcWvJn2O6AdJ9V1BTZLfZX5Yc4sjRqNG61/IK6F8VEEzP/xNWA4FlRp7HT1w5o1LFcZ2CXW2SUL/nmpXsmnYU2bUmxkjs2rV+KZoR4N8nHPL/K+WYH3K+kSAadpLHQ=,iv:mARoL1fnK3VPZOp8E/MuWkAhjuqoMhhNjYMKNeCDfcQ=,tag:VciV/jMtab1dVByxaCoZyQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
