app-template:
    controllers:
        main:
            containers:
                main:
                    args:
                        - ENC[AES256_GCM,data:JcclysNXDA==,iv:mCVmKdCCKNYJ5O5MdOJQlNqwoE1sGxwLmTvjnUvmWrg=,tag:US9M3HdvkF1HV0RmxB+Xyw==,type:str]
                        - ENC[AES256_GCM,data:l+SA,iv:Clzaizrt9wzaBsEI1FeI12FLNo5+mp5ZERWegsTk0C0=,tag:KmlI5v/ahtxruZkuWVLnYA==,type:str]
                    env:
                        HERMES_DASHBOARD: ENC[AES256_GCM,data:RKdXtw==,iv:/nLPut50/W9H5XTIuVonMjNJQj3hajMphaPIUXczp4A=,tag:ZfEfkEZvV9DgjKsHzKxcOQ==,type:str]
                        API_SERVER_ENABLED: ENC[AES256_GCM,data:iP7z/w==,iv:+YVGadYYCjUUepY9euCHErqrrssZVloNQmTGticd9zk=,tag:3YP9QzFGXxmc1zc+R4Erfg==,type:str]
                        API_SERVER_HOST: ENC[AES256_GCM,data:Kz2mpHKYIw==,iv:X1vfOdJ1tiRM6hsQEwoOllUFJubBD4F9LXii7ktnlT8=,tag:qndNBjMyGu+Vkodkb/7NkA==,type:str]
                        API_SERVER_KEY: ENC[AES256_GCM,data:8WkBOsGrQa2E9AYEU8Vgt7mpyjxe91h67glq3TrmmsMCxrD/bKawTa/HpZ1P0cQ+k7l4VpRf8vo/Q3PHHHM4EA==,iv:9spDm6TEpJ7s8Gv/zhCl0aA5qJI2z6DDXL+5a36GAIc=,tag:QZXG0D9hFHVrhKfbxPtZ1w==,type:str]
                        API_SERVER_CORS_ORIGINS: ENC[AES256_GCM,data:0g==,iv:KYBhlPD6wgE+X+hyAgon+oUUzTChvastqnPWFmTwxmQ=,tag:IhDXmDNK2y+fq5MbroOlmg==,type:str]
                        ANTHROPIC_API_KEY: ENC[AES256_GCM,data:6B4CjwE6aHKTXNv2WOnWCV3hnbggLSsS4m/dPAtswUSu8UbW1NlHGMKrUgdXXPewIAPmeAtWBydA1ioRAHPt9GUYiKfWcAZjFLeX4vnFF4DO0JsGyTxDsjOW6OX/RgSU2whivvSwZt1PGRrR,iv:ddsCTYlFjQCu4pzhyCZJQz80PxMoN1IIipJy28pfHZw=,tag:bYaFXvwJN8vkHyD7KF2OVw==,type:str]
                        #ENC[AES256_GCM,data:oojiHHUAFg1rsZqQsRShg2KUly0XlHh24P1J+Rwc9zGFFsUepxNFm7gMklX1meFBAd/OCyK8vepGzA==,iv:ZX8J04wXcdJeGJyHBjdDKgKLKUgDBz7dPHdz5N57yi0=,tag:QJj+iehbDY0r0ByaQvt/hA==,type:comment]
                        #ENC[AES256_GCM,data:n+aP0QyItaU6+ynwjp1gB1ZndL1IzWPOuo/eLF7zE+Q+cpb/NjFhAxTZJatYv3Patmch35N1uuhOzIU=,iv:FYP70E+gSZdM/CgEkcb+ts5dRWRYt42WwU0wOggxsbo=,tag:1I6cYJGsSAzqZQInI8Bzhw==,type:comment]
                        #ENC[AES256_GCM,data:a6rRyNg5nRYC2h5195u2vynmKXNTtPv/FEHKs/WOU1zOkVUIbFEe64wj/vFpM0skgwrIcuTR+fLccHUX6M9EK7wMJRqjHnMj,iv:h1OhYu7VI+9Y0Ulwy6/ERqjHZ015LNXJGnShk9Mz4t8=,tag:SiV1nx0S1wCc+fIjkf2sCw==,type:comment]
                    resources:
                        requests:
                            cpu: ENC[AES256_GCM,data:WQ==,iv:/YAWlSxwhOcektwEdLdBpTKQ1mBZgjnE2OSspzZD75Y=,tag:TI/oLlOpp1uxx03h6jVOhA==,type:float]
                            memory: ENC[AES256_GCM,data:SGhn,iv:HMrutgrC3ELFp68mzFsbIxmBn1gqm/l7Xt6pZ59L4Ds=,tag:Rtzkb8xvfa5t7iy7qQXuzg==,type:str]
                        limits:
                            memory: ENC[AES256_GCM,data:7IOl,iv:oItRBYEjY5ePQOlKDB2zsfzPJV6oYow34oai5uEDDNw=,tag:yLmndyVsV0IeeZnHUUDMcg==,type:str]
                            cpu: ENC[AES256_GCM,data:sA==,iv:s9ftJwa5Pmn+heLa9dmMqROUeYNJlbkV0SNP1UQK/So=,tag:FzS0N5kSa/VWi/6xdjZvqQ==,type:float]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZDl3aVRPT0w1MThLcmhZ
            L2x3Rk1kRWJ3eTBtYzdsSVlFdG9XMzdIRnlRCmRsa0w4d2NnSUc0aFJPVllDenlW
            WDRJNkg2c3hQalZQR2c3SmVNaHRRMm8KLS0tIDFCY2ZHY2srMFRWdXovQXZ4WUlF
            b0Q2RnBwamVUblcwa0o0S051bjd3OXMKgnhnzhsFSt7oFW2Zzv+5nN5Btq1AcM3/
            5FYHeeBshBoahkDzNSLM4c2OHUYfRmgo3m5c22XTWcGPPziPMwg3hg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-24T20:39:29Z"
    mac: ENC[AES256_GCM,data:E77iivsOTkq2U0PWkX/+1msVlMmYH8/hwPl8XDHq6L1rrT3r/LFbN39UWBw0OMkPPGyL5tmgEbVZWMHs3NJVv++1yNJ4eOt8vwrmL6KXnryheEGfx/PEY1QjMH6HUnRR1W3i3+BMzS4dKvUWUOhQU5c4gfgtF29Xb8KjPr8vDaU=,iv:n/qW5zg4DT7+ZteutpOmd1GfVY4es4KDV7AgT8Ks9iw=,tag:oSdFYahI7vmH3JoCad3C4g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
