velero:
    credentials:
        useSecret: ENC[AES256_GCM,data:J9/zgw==,iv:1srWlPbxA8/XS3dRL7Xtbo7QDF93SI0iyJZLaAZj6rQ=,tag:Mj4P7b5aw4xw3qQZ+RnJyg==,type:bool]
        existingSecret: ""
        secretContents:
            cloud: ENC[AES256_GCM,data:MSTeqEi1+lbUpNFV/t2peMqqgc7rsUk7f9zAzSzNrxFk70NJb7yMZiohXj7Cjxain5wUwDny5ZQmoeM/Cj2zj6aKq49nNc63ci0Dw64/c3N6m6waLwnvxmyVa57W7w6rSlZOMxoB+Rxzy/L/kTM8tQV9Olie3Gq5GIfxUP2Xu2SJp8ixahMItjfUhHswfQ==,iv:e3W6gvpuE/StJPR07b+REy9VBq1kV8XTsF0Ueq6taRI=,tag:hoPKNRh+RGjE1g7sjKEVTg==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVDQ4NFRDWXQwYXNmYmE4
            S24xVy9IaGNRRUF0SHVKU2l6eVk2MHpIZHhZCnVkMWV5dDNQaGhKbnlaRXFRQ2NO
            Rk9sNzhGUTNXM0RyemRJUjVLZ3JRYVEKLS0tIE5GS0pNdWpTNHZrWDNjUmkrMjFB
            dHUyTmtmaTVXUlRPUENWM2xYc05TRmMK9kJz6iUAy8TP33y2EPP3cVIUHFpqFJqr
            g2hfXpYSZfHhq8f34pqNGtRp0kVozQFo/UEmxUo00xozIQ/VsHTJ/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T21:50:54Z"
    mac: ENC[AES256_GCM,data:NwL0+2/SDXs9grZPjSr5rePtkFv0m+1IkTrpXxIwsyr3uY/I+tMqk3JdmaYWGUAF+0QWHwAvGkSXfmy63mBJhK9Dfte2xMDaoBi3YKciWa1IQ3DFUzj5Tlrs2z6+xAafAzHrIGDh25GyjX5rA9GZn+sn7OUPkfKZM4kH9iFIUfk=,iv:lTmlLco+p65hZ1zi6f2QuLAAHr0T5m7r6Y910/mYS3A=,tag:CwX2n6OLXKdrmYgHoHVRaw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
