velero:
    credentials:
        useSecret: ENC[AES256_GCM,data:8kkrOg==,iv:TbvETAIxr2Wkw9R0RkEHHY3WOv1liGaF7YHGfed0OzU=,tag:dOAq8i560ymUjnXNQ73h+A==,type:bool]
        existingSecret: ""
        secretContents:
            cloud: ENC[AES256_GCM,data:GZ7/s/kQS49GZ5NA31WSI4HTU9QNoAsWf0YIiglG3sJMeWiqVstHFMrN4i3+mg0/DkQVfJFYWXm4QXNJ4ayD273XZTMH5C6Sb8kE7WFqjsTkpOmxWZzJi8PMUjjc31aDcaYacwcjHPCH2sXX50tS1kG/UOJtSFUKTjmIeUlpxihX3Ax3rZg85Fc3eBmz2w==,iv:d3ksPpOfRtmCR5D52RHqgtSQkyyb5KYfvkvMjysJUDk=,tag:KfrEzbKLSoesA4b3FlG1Tw==,type:str]
            r2: ENC[AES256_GCM,data:XaHH03MkFR5vTT8E5jM7gS+b5E9DzEqwskH7g21G0C3GawjRgBCapQs8oU6epSj7M/LuxLxr5GSzQUU7LLS+Fbvt5JeQClNTM1a1BKtN4IZWj//mZJIHH6YDFRp0kb7adeCviQ9qylNQ6fa3DjBPt9IEz7W+mplYa5q74r4E0n/plPYqMr/VBhKsSPscpSPM6bMSOA==,iv:/3CeWdOGBHml8R5rLlmNYwML8F2MG3z2vWXCSD7Jaak=,tag:2TDO5y7trSlaAabJFztpnA==,type:str]
    configuration:
        backupStorageLocation:
            - name: ENC[AES256_GCM,data:mgvsfSDoLQ==,iv:aozbuGhH4qT5jY5KFMyyGFdVjzd/gcd3j64dV+jLnwM=,tag:dfWOXtntupfVLfC4TCyt/w==,type:str]
              provider: ENC[AES256_GCM,data:cGT+,iv:GMEoZ5VohXAZdtGnbUpxbZw4A1HAwgsnRrU6b4O0bRM=,tag:K4i7l4cU/VL3fOsC9Pmy+g==,type:str]
              bucket: ENC[AES256_GCM,data:KMIHF74a,iv:C9UUyp8hoQAFoQ25nuTxz7mtz7DduT8oZdasBtFCFwM=,tag:iAee8bSXv7iuoM6CSbL4gQ==,type:str]
              config:
                region: ENC[AES256_GCM,data:b06Ghnsk,iv:F4IewseOin6eFs89P67f5NR3Saad2JJxV1AnJwBkfh8=,tag:cj/5NNsJUJK4sHSpkx7LDw==,type:str]
                s3ForcePathStyle: ENC[AES256_GCM,data:upObOQ==,iv:aLXFgqMhmY+HGnV6+BJZ+s2EOYZx0XpgvB9qEezcn80=,tag:CAbyPF655UHipAu9XKezVQ==,type:bool]
                s3Url: ENC[AES256_GCM,data:qJ3AXstHGmAFUIRqYnMvYm4TEWD6Y78C1waBlyLhRYu/dcw5WELkoomabA==,iv:iZs/Q8X7nzFSu0MxMB5Q/wHLrBk605yhXMEIR1xBMPE=,tag:Kn6Tgmko0Bniqj2mVOiMaA==,type:str]
                publicUrl: ENC[AES256_GCM,data:VxPZeOVKBvL9XsYTcPWie+06e45kkw==,iv:HcbQjdNSWti5Lm5wBfYobpgyZ/Jzzs2xLEDTMbTszpI=,tag:G2L/CNi3jRIS5KWLM9fuXw==,type:str]
            - name: ENC[AES256_GCM,data:jFU=,iv:sfX7cIjukGSfaVo0dgIo6GTn3ROnGzyRqEzsBEbJgmk=,tag:M0aUEZI5onhgbJ1ZJzbtqg==,type:str]
              provider: ENC[AES256_GCM,data:1aon,iv:H0oeO0jKk87ITczi4cVM3Pb6k2Qo3havmgL/H4jxBDI=,tag:HFctLWXIdo7mfPnuc5zIuQ==,type:str]
              bucket: ENC[AES256_GCM,data:C9N3OWt2T3ZQqko6CMQP,iv:G06XxxcxStonewhr9YcGM68/RCeHV5XcRsNuEchOJVY=,tag:TDuJZcRRNByq4oTeaGxF9A==,type:str]
              config:
                region: ENC[AES256_GCM,data:DDIq8A==,iv:CNQ/Kc2wU1XJKvH5RRaEGRHnJ52y0ToLll828bLNN2k=,tag:erUWNJ6ypKtWsops/letWA==,type:str]
                s3ForcePathStyle: ENC[AES256_GCM,data:m+RR6Q==,iv:V6D3P3kwBC3XezSpAZeNL33KuTNzhMn8OP3HDrhqFbM=,tag:jCMqJVQ1WGzAruQ6/qawqw==,type:bool]
                s3Url: ENC[AES256_GCM,data:IOt5yyCblswWwwkYP32GiK3U2gyqBXYOSCiCNsESKEqtVQP1LKNktB/TAyWZ6HhzODKx0gAQHVDiBLorBHkgflY=,iv:rGiwOt1BFB8DoXv1lgUF7vLJHtgelYZo58k+nZYqKpc=,tag:Mq9Ng2m1fMuzVpyUTWOGnA==,type:str]
              credential:
                name: ENC[AES256_GCM,data:Nzk7TKA8,iv:cHAj9mLhkJKZ+CggD13HafVNrHuBHZvJAXrqAosML34=,tag:AtQhQACa5exFFWX1nKplcw==,type:str]
                key: ENC[AES256_GCM,data:3vw=,iv:koe3HnAXsVP41gcryktNxp9iRqYOOELf4UGeMijDL6I=,tag:t0eih3vwM4xxjtATrzwOSQ==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArT3ZVT09sTG9HUU5KQVdW
            K0pDWHFacHdZUkVjNjRacGVtdjRQbkZLcUNjCmZjS1QzZW5VN0xHKzU1TXBmWXp2
            cHFQdmJyWHpVRmV5TjNpYXZudndUS3cKLS0tIFM5eS9RN2ZYa3lDUGpva0FDZlpY
            TStUK21KTEM2T1Y1MTFhUnRoWHpqQ0kKkQV3YG6xyqbl8tyCeKSFT6GKUEBR5KXW
            NL2b3tTrwQ/BFQB2MyZj5JatVybs2lji7dv1MbYwCj+xJtNDdIbCPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T22:19:04Z"
    mac: ENC[AES256_GCM,data:s0IG3rv2ME4FtcjKqa2TMho4iZDcHeiKP1f37nP2Cy/NwlzNZ6axztrtcslWDm/XFarKxhsdyVFUOKlCCJQ1rJ8tJVCT6vkIF8KvUaT/yW3Z4C1Wov3qTAxnHGAZxCMjI8i6HD/PIDe3eACqaMH+hE2SQqvekxi6fXNhkQ5YpOA=,iv:fdMrsfQLhUxJeBmONKBU3eDKHuwz8XUJl8NUtE58VZA=,tag:Wcrbmh2PlxvwOZYjJ8eIAg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
