velero:
    credentials:
        useSecret: ENC[AES256_GCM,data:s8kzMw==,iv:mKHw4RMYIlk2/8ajuoay89sHYfnv6FO6t3UGBsa4YZo=,tag:aIVz9KdkaNlbCNda3ae87w==,type:bool]
        existingSecret: ""
        secretContents:
            cloud: ENC[AES256_GCM,data:UvYR7PWn2uCB4Fo+l3SbFGskUV71u29euFbzl3UIE8TX2tnTS7LRpTmWyEWJCbwtRMJb25qVd+qnDmsfwJdXH2s2Qcm3XeekYN293FZmw/ROoZ5GSfyImb9G9GWs+S5JM3vZMLZEVs48SLD6/Z5rvhxPoiJmt/9rDGAA+IzVQC1X4aVumt8AzRo6dywzmw==,iv:QhM4xmV5EJgcQ1t3dTtwBRZu1OqecX3iFw6cYLiiyrg=,tag:nef96eJ5K43rCBGoDUUi3A==,type:str]
            r2: ENC[AES256_GCM,data:arJKbfu+ENNX+KJLPubTnxWgtGMdxMLbK01BL7IhD49xNskFqlgUAPTPL1IKnjDXKSjYIZKhk+zitybdJhymH+TOM3lrgkSqxuVOFjZcRxBdLI4aoGoMA7mmikomGChZae5gBs0AGrQ3Tb0JPS0NhJqlhgLMLZjG6DeqGV91PD0WMGPkzM0z33Xur31ET3CB6xv9nA==,iv:FRv5lvPkjWy0/EfA5rTFMWvqO3iz4EtY8vItRQDkjmc=,tag:+/YhLlRy/fArsZPRkxTuUA==,type:str]
    configuration:
        backupStorageLocation:
            - name: ENC[AES256_GCM,data:g7ckssUEdA==,iv:y7lIJjjBqSbHW5JnmUylSJAB2+2nEE5AJOy+txUqx38=,tag:m7OoMzerHF2V47x24tT5wg==,type:str]
              provider: ENC[AES256_GCM,data:fV3k,iv:AQLlc8cN023Dbn1+Pq7enKRt7lz1IVhtLQYFmGzUpEY=,tag:GfeNxIni55yDLb2AH8bNug==,type:str]
              bucket: ENC[AES256_GCM,data:YWmsz1Me,iv:knat5Hv8X7uxkWlznuW2h8Z+JxZFf7lPCEd1vKIKCOA=,tag:rR8vK9uim1h9ZmReDho2zQ==,type:str]
              config:
                region: ENC[AES256_GCM,data:Kz4Wg4zj,iv:gh7DH2R4TEACNOcoTqARrLHi6HApyPwJwywhePs61VQ=,tag:F+mvSKAZgy9wg+IYtptflA==,type:str]
                s3ForcePathStyle: ENC[AES256_GCM,data:5fpaMA==,iv:Qc0InpPTEKu5CE8yBBoV5kYPMSf51KbwkrXAVG4+AEQ=,tag:gEpi/QKN8/4kOU4/t3kN3w==,type:bool]
                s3Url: ENC[AES256_GCM,data:2EUB3RYANm1z0fc/39mgXhU1k/61LVJBB/p7L6rOl2nlAxrPvu14S3FgFw==,iv:i86U4I03MD428sg2bjbD6U/ZMdb1q8TyJTwy1nHcokg=,tag:eFe8NJ1ksdR3u//tFy9BmQ==,type:str]
                publicUrl: ENC[AES256_GCM,data:a3p1thORjCOafnM9YO8FzjHVf7z1LQ==,iv:a59fcjKMsrmRCFA95Xwd0L594SNXOdaSbQ3bkEXRNkU=,tag:5GOzMCyC8ebBJO6t2CUwMQ==,type:str]
            - name: ENC[AES256_GCM,data:3zY=,iv:xPCNN9W8Rpfm3848kdXgwSwtyrp1mYhl7ZAB+ejJV8s=,tag:2L1sqDzzN8R/mfAol2S1hg==,type:str]
              provider: ENC[AES256_GCM,data:73uj,iv:32jFuAou9lHLR0O5JZwJq2pv9tKkcP9NNN+UjPKWZj0=,tag:6ApQFzAqjhSe3k3KylBfOA==,type:str]
              bucket: ENC[AES256_GCM,data:NVbgQGeyV9133idCym4T,iv:IxBRUF+rXoyv7Bqpc6y8MMIDLWJIuJtzwAZNIt8yQmk=,tag:9PSBA4Cu0agft4tFFN7aSg==,type:str]
              config:
                region: ENC[AES256_GCM,data:xURudw==,iv:9yom5GLy+fMMAAm4DlJZXlqfkFIRXkpaCq9Ahfktb3g=,tag:enee13+dGy2eS/xIVt7phg==,type:str]
                s3ForcePathStyle: ENC[AES256_GCM,data:R/13pw==,iv:guG+wmX2yJqsL6opFNwYmIub6RNngh7DA8ULvo63CBE=,tag:a6A4YxjkYOvOJgr8HzcEAw==,type:bool]
                s3Url: ENC[AES256_GCM,data:LVotoA4nFQDu15m0N01KJJOihxdIZFd13sGMB9nuDZd5EmsqEpmy+4gt5pYE36PiUX6B5zDp1ocURq23YFW6JvE=,iv:VQwOs0qSIEPxhKBZKIZR5wp5Yg5yVNyXAu3m4NGuhDE=,tag:7tTFV2xttL3S5K3W/zfT+w==,type:str]
              credential:
                name: ENC[AES256_GCM,data:hdbBq2GI8ssIW8RngSR398s=,iv:SswNwY4GY5vBhfUqDEhxN+ozvFe/1e540j8Y0v4JYpY=,tag:H+rmqEekzgyjFBKzU5oo9A==,type:str]
                key: ENC[AES256_GCM,data:15g=,iv:UXkr2KdYgeL+900DL9ZueYA67/MD1ezXZv2aNJ4EmmA=,tag:u135y+gUzHkFlNQUQp2Haw==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGeWpBRlpOaHVtdTJMRUs5
            WDAwRU5aZjZKVFdBSGlTdytmNkVDQlBpZlhZCjNDK1NZd1I3ZHVSSVlhNUg0RGNN
            SmttSmd0QnhRTWgxZGU3RGUvR2Y3TUEKLS0tIFNUcFdwR2crQWx5Yi9LbnAzV3Ri
            aWNPbDZSb0hYd1V0ZExBdEN3WTZrWHMKs4AZEplJ3v4L4uKH6vV7mvdTjLKsP98A
            qD4O6nkHV5+0krSW1kUOkxWhcoeATba7GYFMEQ53WuXbxHmaPvZDLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T22:07:34Z"
    mac: ENC[AES256_GCM,data:9M9ZsUw9RhZ9m/KuJCgAG6YAFnE+my9Fap6Q0FBEBNv1Bh0wEG5nfxvmGZoJlf7LDcHlMH5c49Q2iKJL4z9R2Fcn+cKzFzQItTRuwEVHn8VV6tPy47iV3Elq2wXtVKnQhu15kUiXtqTuOi1IasJo6kf4soHG79Zoa73gpQ6o3rI=,iv:KO0UMt6lYw6pBTxdAl20+Q36NJIUCnHc2WQGVdq7sb0=,tag:rMpfw6gE466mHVxJFqjODw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
