---
velero:
  credentials:
    useSecret: true
    existingSecret: ""
    secretContents:
      cloud: |
        [default]
        aws_access_key_id=GK54e00b1b39ed858a6a620611
        aws_secret_access_key=0b2c695c81bbf46b5f2f41d01d5b19d72767c2ab871a379cc3e1b8a45eb1cbe9
      r2: |
        [default]
        aws_access_key_id=0912132426f3cbf965a1f9baa218950a
        aws_secret_access_key=732a02bb57b3244bc882ebd9cd4553a374b7d68ccef27329bee4fdf384c4e2a4

  configuration:
    backupStorageLocation:
      - name: default
        provider: aws
        bucket: velero
        config:
          region: garage
          s3ForcePathStyle: true
          s3Url: http://garage.garage.svc.cluster.local:3900
          publicUrl: https://s3.mdeleon.dev
      - name: r2
        provider: aws
        bucket: homelab-backups
        config:
          region: auto
          s3ForcePathStyle: true
          s3Url: https://683d43af18913fe58dc1c66b52e4a027.r2.cloudflarestorage.com
        credential:
          name: velero
          key: r2
