---
apiVersion: v2
name: karakeep
version: 0.0.1
annotations:
  homelab/description: "Bookmark-everything app"
  homelab/url: "https://github.com/karakeep-app/karakeep"
dependencies:
  - name: app-template
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 5.0.0
