app-template:
    ingress:
        karakeep:
            enabled: ENC[AES256_GCM,data:1Z/kCQ==,iv:imGEao8lmpWpK5U3vMICJBt17cULdpOOSxiloVCJXuA=,tag:QQMTLnpxThbN8wjRKx6sTQ==,type:bool]
            annotations:
                cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:L6tLRpinMQcO0cVFD6FOiw==,iv:nCyzRotBDiePXGLq9kycmTGyzwyKawCmlvTP+Cl0qkE=,tag:5lEfcyYYE9ZIs4uez4+axg==,type:str]
                gethomepage.dev/name: ENC[AES256_GCM,data:A3sfxVP4Sh4=,iv:VWN9mWR3AjhliGvhlATjGGbn4eZtyWudgTpy1M/h3v4=,tag:J5XssS36/i0AKE+ePFITfA==,type:str]
                gethomepage.dev/description: ENC[AES256_GCM,data:KleyQQCU0qkFEJe9qjZo7ZR70A==,iv:vN5zeEx4KE71/4YemNgvA6/8UcVUcs6+If6A1L17D/Y=,tag:5HLeMM0QsPOf+0KacpEVBA==,type:str]
                gethomepage.dev/enabled: ENC[AES256_GCM,data:d7mYPg==,iv:/Rr01kHNh9f/TYlE7dr2jsbDMWOm8ftpEOiRQ+GD81c=,tag:wweX3zbNKLVo2UsZHNRlhA==,type:str]
                gethomepage.dev/group: ENC[AES256_GCM,data:1RFDVejXBFas,iv:1wMh1kEeA2O0B630tpUBYIOxy2lR04mCUmo3AKjVS+o=,tag:XOXIo7CQODJnPgDCPyCVlw==,type:str]
                gethomepage.dev/icon: ENC[AES256_GCM,data:wDE3JE3NkyDf21hSD5Ul/ocJpCfj,iv:wF6/E/xOvoKAXbK092xlkWUuINSBmOEi4vBgReehgN0=,tag:6ALAN2eUjGK3j3iuclM8Eg==,type:str]
                gethomepage.dev/weight: ENC[AES256_GCM,data:Qw==,iv:jbvGiOAVuaKygZzgJem5Hk7OjddujIVXyFm8l+hNam0=,tag:/9EMVsOll3sOHMWOC34+Tg==,type:str]
            hosts:
                - host: ENC[AES256_GCM,data:JqxkO923i/IYA3jaEdpdULhcaTY=,iv:iXPpc/V5eZ9jCi7XI//Mrmb30paFdXUknR/X7P2t2Ak=,tag:qlmUkGJLmAbVKu129BUVqA==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:Jw==,iv:IalrQUbYCmtaY0uSO0FhTrMMfK5A4sIZrZvGRnpkKT4=,tag:Hm/sjgo3/VoCLqKCd39NFw==,type:str]
                      pathType: ENC[AES256_GCM,data:HEw2iqJe,iv:M4g0MH8/2PT+/QQ3WqqoqIW0AR5Scc/0+HQrTbq5qhY=,tag:r3eqqlNxVDogr2+6jgapZw==,type:str]
                      service:
                        identifier: ENC[AES256_GCM,data:i/503BIvfW8=,iv:nOjp94Sb0iWIAo5m2H2dS+E4vUUAGHGcIKDYdWccaN4=,tag:jm3c0UbddC5P8oy7e8CSfg==,type:str]
                        port: ENC[AES256_GCM,data:uGCrKQ==,iv:Kz45NzUNDNIHdogLmMWzf6iurxImZ0DL9nkDJ1yJR24=,tag:D6VSP/kG5m2gvd/Tv1VJPA==,type:str]
            tls:
                - secretName: ENC[AES256_GCM,data:NVXIPez6jKW8hSGkW/6+kw8=,iv:QP19vz/w5nl8eqoBhsU/+S/CZLjSMldPUxL+PIufL70=,tag:s9D+yH5R2dLiKLErAr6Ulw==,type:str]
                  hosts:
                    - ENC[AES256_GCM,data:7IPRvfg3SFu17MmmmLPVVOO3z0U=,iv:JfrJQDdRMOI9kGuNOeDrTBjVRXAYDPClHSaRaPnZfYA=,tag:xAVD0FZMxvSCD9nWu9jGLQ==,type:str]
    controllers:
        meilisearch:
            containers:
                meilisearch:
                    env:
                        MEILI_MASTER_KEY: ENC[AES256_GCM,data:VQvUP41eBhlTxOvKbFt5wmdIukclj6nTRnJsFL6qLEEtYk+FzZdBY6Xlpw==,iv:j6F7RyZj3Cwa1st6cIHIRaNizAazcQiU9JWE4zCj/DQ=,tag:aCkGjvCEuXYCAV/4FO2Ihg==,type:str]
                        MEILI_NO_ANALYTICS: ENC[AES256_GCM,data:xf9JIA==,iv:eqF6bDo2+heQUph864ilQokXWYGPinmQFHG0EriAs80=,tag:v/ImjJ/5DeLf87q+hlSbOA==,type:str]
        karakeep:
            containers:
                karakeep:
                    env:
                        KARAKEEP_VERSION: ENC[AES256_GCM,data:dKxrNaZb7w==,iv:1RTk45A4qku6bIqvapp5YfKVNu0wI+0wu8TE2jD+SbI=,tag:QkaOgPZhsyhzJA/KkuRkdQ==,type:str]
                        #ENC[AES256_GCM,data:pMfRTrNfMt3nuzT9uUoneBERTvBhUk9M7XKCxI1mFAVZHSvVxYa4d6zL57DLALJWO+qPfqbPVmMZ2CXAr5V8z8KMAuTz+svgxW30j6vUeaBhhiRO+LGOEEGKlkyqq7ehMmnXSXIkTJ0EOnhGdkfBJUDoNsu//9W2guXE2t0MqY4gO4JES6Rnrg5ViwyKzWYfCXKOJsMBjckIhgMyaslS+bMLaz9dksR8RF5UiGZjdZyHa7OMityN,iv:HPXeTXtoxg8J1UoAL9Ssrh7oMlvnKM7v6CI/3eCP38k=,tag:mmExrNVbaUdS+yt4poNtkQ==,type:comment]
                        OPENAI_BASE_URL: ENC[AES256_GCM,data:rBFeQrMcd7BVioQXznSJxl+c/nYouciWNFCkfeHNq/eaNfJRrlJYoBGBWMHJ2Ff6,iv:WQ83pRd+ZushhU7ZETTh1tfKSVPAwG8VxE6yVVHRK48=,tag:sNzgBds1U3dEDEh/RAYUQw==,type:str]
                        OPENAI_API_KEY: ENC[AES256_GCM,data:6kjCECMKSDJGsInEwcndYF8dudjw/T6i1fsdlUzkIRyW+t9rXWWC,iv:xcA+/rKAmMnxSPB9SvL0MIq4yC2ZS/hueNeYF7LHMW8=,tag:1sdAjEhgXfMleq8FfdYG8w==,type:str]
                        INFERENCE_TEXT_MODEL: ENC[AES256_GCM,data:kqzZsVsd0iMaatsL2OwBfw==,iv:GzDRlsRiI9XoN4a/gtREZUoOovBTY1WIlUn5H3Uhsog=,tag:gqCMVmCwqEhVBQW3VIYbTA==,type:str]
                        INFERENCE_IMAGE_MODEL: ENC[AES256_GCM,data:L9tUlf5ftRxcJZYy9Li49Q==,iv:3nH3Q8f0xJcyids0LxBTCnF4cNtnO2rlbRnxo1arrD8=,tag:dh52nl3Y1hI+eRZvYFGJSw==,type:str]
                        MEILI_ADDR: ENC[AES256_GCM,data:m1Jkqck8qPrHlfFfz2V/vRB6+dq6eu1WYTLsoS8tJg0=,iv:156pBHbex1t7hfT3jYE3zDiqSJzgQ4dJT4K22OTtdQM=,tag:FNHOYaVENpDhKYqf9FZIPw==,type:str]
                        MEILI_MASTER_KEY: ENC[AES256_GCM,data:DYaSg4bo7pHBco4QSYVv0h5BpiBCMuJE74ot/i5urU4RJgzi08A9DLuv8w==,iv:0utjHHwv0vtY3j2/zNA57Cb2SL2Br39vwYSdxlORZZc=,tag:0AZK8nVMw2CbaWMD34iG5A==,type:str]
                        NEXTAUTH_SECRET: ENC[AES256_GCM,data:ugC56SheBlS9hzK+/zRKmIk2qMMk2wneCwpo8dXjegDSlkPugnDJSu4Se23Lxfoi,iv:PvJkDDdpY+latslKE6aVivKBOSKsRzGDPNpbraI7ibM=,tag:egw3JvOSAkTnyYXYsfkfLQ==,type:str]
                        NEXTAUTH_URL: ENC[AES256_GCM,data:pOMOQ0WRKz3B/R5lyF9nc2jRIMWBt5gdN3dxyA==,iv:rcmhWVS32awhjIsy8pnknyQARSs+pF8EUb7zeOAKQ88=,tag:ifKekPXkCj/gNHPDMnsUwA==,type:str]
                        DATA_DIR: ENC[AES256_GCM,data:+6JNXx8=,iv:pIbaVgyIs+ZNa5B1F0kNGaEJX051+PPrm2P0+Bl4DH0=,tag:VviD1wU2vuEM3SM8vVVpLg==,type:str]
                        BROWSER_WEB_URL: ENC[AES256_GCM,data:Jbj3Xwu/Ri/CP6wOTPE0ZSSOfC7l44fFQhnu,iv:SNioslqAigI656Tclf5CvGXLHR13Tpd1HWq++BuRgqY=,tag:m7UL6kaDuSJBzoFaTNXaeA==,type:str]
                        DISABLE_PASSWORD_AUTH: ENC[AES256_GCM,data:hmm7BHQ=,iv:ZcnDBEkPXMrOEjW3wOtelTWrt3fmBxIwJXdLFkpOeVw=,tag:A4cjfx/uVsAmVMDcDtH6gQ==,type:bool]
                        DISABLE_SIGNUPS: ENC[AES256_GCM,data:WieqKw==,iv:gjVa6DDDRS+Gc0Hcp1vCXh1LxAjvRUbWA8qE3RLJocg=,tag:EsC0YB5nfTzuuSBhNlz5NA==,type:bool]
                        OAUTH_WELLKNOWN_URL: ENC[AES256_GCM,data:OyPlK3bH/8p9x+zYJZyunzfOmbEpuaCmhJ6eG528H12cwmx7z2z6qeItRRdpdSrlVrbKJompZp7eL6s=,iv:+lfQYTIJxgGH9gFNVXtjeQVXKaR9B7/fUrck0ZSAoGQ=,tag:+k4SbB07YpaLHx/F9kBdVA==,type:str]
                        OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:baiy+DClzBqpNYhONch3mQwVpi/CNYUpba2CoSHLC78=,iv:H64pmHs4zZKn7NtKqFCb0FZe0MYun25Oby3jTPkF+b4=,tag:cZMteDbIQNHdUPAymF82OA==,type:str]
                        OAUTH_CLIENT_ID: ENC[AES256_GCM,data:u3WESkLW8x26C4MPBiCXqqXEyWc8mdt4HIbBE9cS1qdSANo4,iv:6EcHQkmPDEoQw7MPE/GOyumTVb2YguklgS56/YvdRA8=,tag:rIpHneC3QhKEhDFt7V3c5w==,type:str]
                        OAUTH_PROVIDER_NAME: ENC[AES256_GCM,data:Nwv1l7hR9itp,iv:al0wi6I5F/OZ+DjvhngSpc6Mk2VYkVviu2wbjcoM0e0=,tag:N2/BZjwIQV8kq6lnCFQqag==,type:str]
                        #ENC[AES256_GCM,data:Z1tl7ukz8ZpNzz1V/hFZOXqrGz581zU3nmVLWv6rVqSRtxBnesLUcoIQBmr0VqH5/Kw4hS8KvOk5zNntS164MXixxBxGhzb2fCJ1skuwzX5vx8o=,iv:bYJ5ppiZMHEmtMnvp5BUNZvtAmNAQrAjc6/P3H0S1WU=,tag:YIS6il9kDftSrDi8vte0vg==,type:comment]
                        #ENC[AES256_GCM,data:KyxxFPiO2PgRzDiNrccdQAB55mu1otJwA5t81XHfkPEc1YMBsVkSXSUUvNSBPT7FWDm6Obx4A6SU+oCsCBDe4fwsXmgdOh7t6f9xANr20YyNTsyFG90=,iv:prnjDP8OsOYxN98s0kXvfKG5IT6Pe17w4x2+zcxboks=,tag:ZgHeUlorfE3k+zKP2Z3lmw==,type:comment]
                        #ENC[AES256_GCM,data:dDdp25dqMYJsYIzxoR73Sx2xMKcfjI7tXEng8RoXTLnFXF+907vlbkEp5YYUYuzB/FU=,iv:6dDsyUJXkPDMtNhx4AYo0l0oAJq9gmOdY4qekIuOh28=,tag:aKxXw46t1Ksc606r3NFSkg==,type:comment]
                        #ENC[AES256_GCM,data:2qey7wo9uZjXpXpmmmQSKvmNSQHfJ/kVg7Vx,iv:zTv8Rky4lxzfxfjq+iZeQl4FzMcFXWTTDI9xrTDJX40=,tag:+85ULxfJefstwFKTBtdkkg==,type:comment]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwRVJzR2RBTXpkeXhkZ3V6
            VU42dXM2RnZUcWIrbDhtZG5KVUpNbER4YlhJClNPcWRiOFgzNnM1aEdjRk5xN0h6
            MS8vdVYzc3ZWTHIyM1gvMW4rd0FnNjQKLS0tIGFhbmJDK0JXbzIzaFdzbWwvU1RT
            ZytXMDZKY1hyNEpyKzV6cW5JaFo1M2sK2foVM/pDbx6s8gjaIziMqYgoNliCyO66
            lOXqHzxQf2DBwMhBWR+ZjOcelJkn0Bna0fa+UzvUrx1jBXxEHNMRDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T19:14:12Z"
    mac: ENC[AES256_GCM,data:rKW60zozQExslDpPUt7y94NpmQ8cPXvpuSxbW6bfcxSmYtrnjoSq3udoro1D4B2sTVYFkFgXG30EY8oX8ymLS2XGDqqXjf0hh4aewZ987ecD/MO+RRIagaxzmD2mwwX/PVPTkkvL9NdTpjWjVoZd5pBZS2QAfmrkCpofbbm4EBE=,iv:/+D3ZBeihwDsho4yqELO2eCrWw0TjEfYU+WSu+/zb1Y=,tag:9GfDIeAg2fRZu6cxxGBosg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
