app-template:
    ingress:
        karakeep:
            enabled: ENC[AES256_GCM,data:xwTyvg==,iv:MUGuZxe45mvdSpwPxvJWJYPGYSpEDCPlqp7yqfHTb38=,tag:ZXqBhAR+a9bxDRcdwF2Zyg==,type:bool]
            annotations:
                cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:kmblXeX+4Wzw416P9uAcZw==,iv:D4xQvbd025rHBHWMOyflJc9r1ACG/fKcNIte80S7v8Q=,tag:B0AlZj4ir2j4Lv3YS10+dA==,type:str]
                gethomepage.dev/name: ENC[AES256_GCM,data:vJHp8s3z53g=,iv:H+QL3HDKOWz2TeQoOiPBGCw3suolQyGxg8Iz8Wweegg=,tag:VtG+qdwACAnBw9jnppI4Rw==,type:str]
                gethomepage.dev/description: ENC[AES256_GCM,data:yMeN+6g6hNE1N8iU3yROxQ63ag==,iv:18QXX/Pr94nD02p/JNY0QpcfhpiDoyxSyTaAFUOBtTU=,tag:PqQzt0+vnVcoSFtf1dcUNw==,type:str]
                gethomepage.dev/enabled: ENC[AES256_GCM,data:yABGBQ==,iv:71L6V62fSHlSHCPxM4oc0BTlzlRTILNI1zcEXPvcJo8=,tag:O7/uHRUNROu88wgGjllFvA==,type:str]
                gethomepage.dev/group: ENC[AES256_GCM,data:ZLZ8vTBm8x7U,iv:b2N2VdDoiBnE6jewYDaLLynpK4AHTcZmc421AnrRXoM=,tag:oH2FGiPCRNeOu7e2j2mQUQ==,type:str]
                gethomepage.dev/icon: ENC[AES256_GCM,data:XVVNvyOLD9eBNSekKC0NUV7QiFbD,iv:E/ClOFk9LVEey+nu59CtmoSDZRpEIQsJu0Aq75PkrLk=,tag:+koxhCIvXGbOz+oOrrf2gA==,type:str]
                gethomepage.dev/weight: ENC[AES256_GCM,data:sw==,iv:RBvz99O8Fqj3pkxpgb65ihq+LnCL+pWcMVTaoKVhpR4=,tag:11MdyOiEhtcBAJDX/DmjwQ==,type:str]
            hosts:
                - host: ENC[AES256_GCM,data:ndaJxU4ddDBNnIBglk2LsuGs3Gs=,iv:uEz18qm3sjV3wgsvUC2Xmr7Tw5TdBe05nfh9mENFW/4=,tag:LLEUug4YdAFsxfNPlrKKCQ==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:+Q==,iv:B0JrxN2p1U+Sa9MSg9sBQpt4vVSfMRck47lG0C73KO4=,tag:XQkQEugmxS/abDR06sTR6g==,type:str]
                      pathType: ENC[AES256_GCM,data:qUIfG02f,iv:HqKCTGg3cdSomrlpRvtWgUBpms5uHT1TJwIMJDc7S0w=,tag:Qw1lbzJSkRVzMIXerCeUqg==,type:str]
                      service:
                        identifier: ENC[AES256_GCM,data:PN9VnmCjfe8=,iv:HmbIJiTPvH4NLC58YP5jIaSvnbcZjH/HGMYXoxTNQts=,tag:7aPtDdRWyv8lrw0x/zWeiw==,type:str]
                        port: ENC[AES256_GCM,data:PRkslg==,iv:PF1ldHjNjWfgsfc5TqlanOJ3fFyw+FcTH4MzOrdqpu0=,tag:EM97rWR02MF5MaY6NMrvqQ==,type:str]
            tls:
                - secretName: ENC[AES256_GCM,data:OtB0yPW1nx81C2zZidCfwZo=,iv:3+EZ0TPtY8jpmJ9dNKqxO4DmeR6Yrv/KlCiU0s6C2FU=,tag:Z6cZEUaQvVdYTySEXfDFqg==,type:str]
                  hosts:
                    - ENC[AES256_GCM,data:29CaYvmoT5gOq/b3S7azRP6vE1k=,iv:WCbw3WKtFnfuSrJpQXRS1qqPqxAMyKIZw4md7j7m6fg=,tag:qD1eg15WfgvOpzFJm0m/NQ==,type:str]
    controllers:
        meilisearch:
            containers:
                meilisearch:
                    env:
                        MEILI_MASTER_KEY: ENC[AES256_GCM,data:rEVp7uwXy3h6ESi0X2nKjoXV9hKN1W/VpSLuElCIaKEE5IAqoJN4YnV48Q==,iv:WsLnLB6BkPLCZnT+X78yMdH+NlVIPyIpM0LKJcgH7rA=,tag:WkkKEJMCLz5Mx08Y6vYKmg==,type:str]
                        MEILI_NO_ANALYTICS: ENC[AES256_GCM,data:VdYrWg==,iv:oFoajLsw69nAWD/qvV9IN31WBIcbDuTkrBjF7gNQ5e8=,tag:1zkaxd6OrQ3r1Xx8lZTLBg==,type:str]
        karakeep:
            containers:
                karakeep:
                    env:
                        KARAKEEP_VERSION: ENC[AES256_GCM,data:dB2WTFodgw==,iv:GuFuu7eqHchbPqWEJZ05rkhlQOOYCi0/MdlVBP4Q4bY=,tag:kNjU8eKs0MCEMFRAhCQ/Cw==,type:str]
                        #ENC[AES256_GCM,data:VbFIhJd7m2Bgj7kphGUTgOjMPVelnNgxsY7wutqVx57BLjHu8otoAvaacCDpeoGYJSQOW5j64iu2FvlfIVhnQJtdRiccE1Ti9igdA9BUS3zTX4g9XpWKtcMX3L4dX4/+NclVosIdHTVZV1oJ4HfHDv6s54ddeogm3fDo8emm610EDTApx+jpFWUY4rmeU8NqrSiYHFDYxLkm+aS+2l98DQsvc5bezLvzNmTM7CDUBtGHxaZzEozA,iv:Kb1Rql0OzPFQSILsEAk5Qndl1Su9AWCPmCA4xmwgdeg=,tag:4BBQWfx1fi81AAk38Wtglg==,type:comment]
                        OPENAI_BASE_URL: ENC[AES256_GCM,data:FqgA/RMOcCdXBgDgD9kb6nylJmVPwEd2/SbRT7stIg689imlKw3Q/VLxkEwQ1c/Y,iv:Vpjx1Bc5ienzvycqMYW+fQX4r6UEn9CqU8wIYRdB5vE=,tag:JnHPx7p9TyHyBig1ONQ2Zw==,type:str]
                        OPENAI_API_KEY: ENC[AES256_GCM,data:qLH+j/21+8f2NMpcxIy/6p+7jpB+DkHgc1wIywoxgF3saypEJBmA,iv:hYacEa/LkegknUJ0ANJvaSTyjI2bGbAFBAjJy8/tf24=,tag:hG3CMUoiOvexTgUg+SWQ2g==,type:str]
                        INFERENCE_TEXT_MODEL: ENC[AES256_GCM,data:4uj4tqwjEcVbkpPD3u2Pqw==,iv:T2tm46F3GowzZAjQAA25/k+49k+YoDOavcg5Gk3784Y=,tag:noydpDvAu7cEqgsVHGnpoQ==,type:str]
                        INFERENCE_IMAGE_MODEL: ENC[AES256_GCM,data:hGnOFMXK+2pf8J7PX1E2qA==,iv:5VP7CreiY9C1oAhLruFOVsXvm/u8FzE3IbIktfMtq44=,tag:Mku7dgp/6KWPPk2p6gjYFw==,type:str]
                        MEILI_ADDR: ENC[AES256_GCM,data:OToY2QxsEXjqVRNV+2r0S1cuqWLDeF7C786mSbDEKPk=,iv:cHbJgPl7/QeSw0I7vmD+P0gVHFBcTrzjQTdeCjIX8OQ=,tag:0VExP1OiSaUO+NMiG9EbBg==,type:str]
                        MEILI_MASTER_KEY: ENC[AES256_GCM,data:TBo3xJRdsrePD/jq9becEI4jsEpOml6AqMM9NPT0KsX2t6Bq7PHSdWPwjg==,iv:J8BPyOaXuXPX1NUJ+c65O+jRhmdjPy/+8PezX849FkY=,tag:Zsst7Kn6BUs0DVB7dBQ9fg==,type:str]
                        NEXTAUTH_SECRET: ENC[AES256_GCM,data:zyBZelfb/kAJ82F9xKESxxuR5Ig1GFkJDcjkpUz1ffszOshKWfzPeQC78kEiLcVS,iv:SP0/EzQ2x+x6BZWam5ufISssr7NTV+rSQIIuLZsi/Z4=,tag:j+DVE8ingZ7rGPQxflTZqg==,type:str]
                        NEXTAUTH_URL: ENC[AES256_GCM,data:+77t7FCR051mIaMobab9FQnQUQ+MnCqFMy33BA==,iv:G+VdaFnxGZ+Hm3J4ZyY1VVb9v6Kp58fgmNeDr5zYJdU=,tag:BrpnXdq70BKQmbaIkG5Ljg==,type:str]
                        DATA_DIR: ENC[AES256_GCM,data:9HnBwr8=,iv:nOMlD6+BUU56SzGofoyxdYQD1i8AHCu2FldW/F9uMXk=,tag:r6x/F/YUy+FMZXZiGO075Q==,type:str]
                        BROWSER_WEB_URL: ENC[AES256_GCM,data:FHly4zw6zqqK0U+tM8W2K8d3oCBpFuQw4UXP,iv:60GKMO86RTW6YFY1UvVIX9b16NKmV3DmnEhk4d9ubD4=,tag:WUoZ+I8nfvl+NrwgMocvpA==,type:str]
                        DISABLE_PASSWORD_AUTH: ENC[AES256_GCM,data:DbdrFnI=,iv:1qFtGPG2Z2T8VetSVQTKbjj5AajxsWHlXlMNIUEklzo=,tag:RlZx5Q6sAYpkHn5cWA/3cQ==,type:bool]
                        DISABLE_SIGNUPS: ENC[AES256_GCM,data:HpEw3f0=,iv:EVlMcLBrqugsbwqzG+B+xWQT952SR6x7fNLUN6LJzmw=,tag:tFmJX0MCl016Zs+Uvb9A+g==,type:bool]
                        OAUTH_WELLKNOWN_URL: ENC[AES256_GCM,data:ModVa4813xXQ92YTfvBX4sQe6Bxwa8bJG6Y+XcS/3meYVrTmZtTfHVj6kwZzQ2iu3y5fvqvTKk5bDoU=,iv:Xo5paXhRcjKyT3kWovtnkA5jQsC2kDDiGkU2mS29m4Q=,tag:n5QTlT4Ge0NFJRm0G0hqxQ==,type:str]
                        OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:9+3ONayhO6hd0UoBp47FgETlNbuBB3zNe2Qp4x48h80=,iv:tBzeA28FsRuCXhiEhvGN0U7MHyvYdGOwJ6SNPIp6XbU=,tag:HHgxy5R+Ry7O3w/aKpaxYw==,type:str]
                        OAUTH_CLIENT_ID: ENC[AES256_GCM,data:xjifaaFahqDguWkgO1z12tu8ozftDZ53qrKl5Q3ovBOzr6CC,iv:Ty4cf2W3SvEiP4/RC0DFPu3gCxn1oMXccWqILP+s1FU=,tag:P2QjgM5oAIlYREGIeLM7Mw==,type:str]
                        OAUTH_PROVIDER_NAME: ENC[AES256_GCM,data:28XFjqC48gHE,iv:jv1YGjkU5sMtAhm3uivahu/EAkGn+fTglUvY/fmI7bs=,tag:5luDGzHSTAWFNpgzSycFQw==,type:str]
                        #ENC[AES256_GCM,data:2mE0C4GlW9FZhRICj1mf1DL1KH9xPtJE9vCzcEtuGrKpQRbNTN+xoCUSHsIbpaDKmngEP++Ec3wwcbUyrSIFbmw/xpfLm0+Pgi72ss2kV9q/Y4I=,iv:Ago9pY5bSe6NQDqkBXrzhsKussFgL4r0ptMrY/8Lf8w=,tag:eBuhEuit+i909el/Ji4GmQ==,type:comment]
                        #ENC[AES256_GCM,data:HAtjDHtVjXX9zP+ObptjhT6mTsAoPoWJYy894T1CyH7DE16MXxdyQvLNMOSSi9s6Y8G8k58yaTvJRXRHHkoETr6QiRQVKgxAarO02Tuw7BaDr7zaDm4=,iv:Z8EfReIdtPVM3B61KnZbhb1pYqK4945SqKcTM3yPFJU=,tag:EGnTsO3o5hqYwiRQG8FfGw==,type:comment]
                        #ENC[AES256_GCM,data:tqisVL/gKwQqayHE203NQBdYLKze8cdXC/RYgjQZsDVVymHOAt+GHBoWOqr3uCvvFwM=,iv:0sIrjGYwOwOpMUayk+AaNmKrX+drbhQt1YMcEnonfLM=,tag:zKqzv2Hq1+NHx9cGdEqHoA==,type:comment]
                        #ENC[AES256_GCM,data:tRsh2pYjXuQzrNKj31F6YxBBODe8MHY74hR0,iv:QwAKcA7FljSHf92VBODh5Bo8QtWnDTvuETsywRr7zwU=,tag:kmM/GS7kM+WN8+dhFGMrZw==,type:comment]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJcWFGU0tqRE5EV2V3VkIx
            VFdvSmFBZFA2b3AxZ1FHaFgrSm5ZWmUzMUdJCktXWmEzSVMyMVdlTmF0ZURrdExk
            dzRZcU83Y2JrTGg4RXZjZEg0ZmsyMjQKLS0tIEx0bE5HYVROc0UvNVJJRW11U2Ex
            MDl6Mi9qVXhzaDRjYzB0YzhRTDNhMEkKeFMyE8hvisIRPtUoh9RsEz6cJ9h3ap45
            y12jJpjaSqARS7uCJKxq/xpq1CwyzNJ9W96o6YrFCXG4z92S1bBbbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T19:30:29Z"
    mac: ENC[AES256_GCM,data:BPUm2BB1DiBHzpqBBYu8SDonz8R5ci5LjbE4vxf647JmCeKC8QHUdXLVr1MF+xlwgYDGgVJgDN7365PMv9/7GCAdHuRRjjoBBt4DWusjaOieShtqUEiq4yXh88NtWk/cCPkuq8cPMeZ3i0CdETjSCKUi3aMMQfcs4+67GCZ1RWg=,iv:/nkBC5KpIChokkfBrOyLLvlegMZsav8BgZIZKd0iBws=,tag:Kh/xz8rxD4E1TyIM2+MEVQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
