---
apiVersion: v2
name: tautulli
version: 1.0
annotations:
  homelab/description: "Plex monitoring and tracking"
  homelab/url: "https://github.com/Tautulli/Tautulli"
dependencies:
  - name: app-template
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 5.0.1
