app-template:
    controllers:
        stirling-image:
            containers:
                app:
                    env:
                        DEFAULT_USERNAME: ENC[AES256_GCM,data:KE956Pc=,iv:B3iLPan9l9Np9Ziql2qX4/QHCK1zzfLHfaS55Ljh33o=,tag:JTWpsrn9bgDoSz9J8AxrWw==,type:str]
                        DEFAULT_PASSWORD: ENC[AES256_GCM,data:1Bfuj/0badPr9AjY8oamZytkxzC1xlb0LPPU6jWVoVtP8dKrBLm4l25LjPk=,iv:NN/Ukt1rOdfg+VLo7OS8pGe4qDZrrZQr7dif9n2lDL8=,tag:oxm/QB8s0jnssiDTo5hIdQ==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Ry8zcVBQK05Vbi82b0kw
            ODFyUGlRVWJJVFNWakNZcUxISWZEa3dtQkhBCkZtb3RsQ29ZZEZqc2xabmJmYzNC
            aFNmdENvYkprWjRzTHdKejJRcWIzdEEKLS0tIC9qMWZZOWpnNGk1c0V1SlFrZW9K
            UFhucHplRXRIUFdvc25OQTR2dk4xdGMK8GppXowdtb1msLhGJwtBWPXvMsu2gOA3
            C6j8VS2B8KWS3bt8CWn6n/JTACLCQXygvgpLrBz3OkVulsc7owTcxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T01:53:47Z"
    mac: ENC[AES256_GCM,data:x2/NNlhY+NQIYChRcurfhPIAYu9307k1Bzt2LtjCVsE4uuCoDmu+0JP8u6aApGMeoo+lFy1CeJMg54FcAGlybtVSys0n8Fv1uZlZftKVhBMG5gOxrkd6vHSZQJZeNcSx8+da6WMu+/u6Ee4e74urneG0Vf654ATfEMkeB0A8Y3I=,iv:/kW8Lyucs9AnkuYVhavUM0wR+DAxkI46BmDfthx2WLQ=,tag:dMsH8xW4Q23cYXz3VFfmrg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
