app-template:
    controllers:
        stirling-image:
            containers:
                app:
                    env:
                        AUTH_ENABLED: ENC[AES256_GCM,data:i+2EEos=,iv:XUxUH8OBix/XgpLUjuS5EoA5+sPexLcr5StMv1NNu2U=,tag:6lMPQ6U5dQjGeD+bb47v4g==,type:str]
                        DEFAULT_USERNAME: ENC[AES256_GCM,data:UP8COak=,iv:6jxDjJ7SfDnvdpwyFK8WOfG7W69ZLwIElWszQHaVraA=,tag:/BIV6efb4BBXm460R2QFMQ==,type:str]
                        DEFAULT_PASSWORD: ENC[AES256_GCM,data:M4viYf/n+MiIxzo8RUebQ15Jk/vuRUt9mZ1T0yKy0YXPMGCaMGjLhPJz9A8=,iv:t3zS0RpTtOk6hx034vpSPnUBwqXWC2hDrghmzWYSw28=,tag:aT2012ReOzEQ8LAdocTnkA==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacHFMbjVlbi9HaGpIMmR0
            NHRKcFQweGFNUXRxRjlNY0lYUzBGV0c0V0hBCmU3VlZMZzBBSUZJeldhdW51eXRk
            WkNpODNvejJKZmhZOEh1TkZON2NpOWsKLS0tIGhtWkI2UkVJOGxDY1pOR25KVW5y
            VjRLOG9zSVAzT0tlNktLQVl3amhmSzQKvh7jMM1Wcf0SVAXdHYOJo3muJsX3oldI
            ETnW+/Js4IElAGZ74G+MzNtcZpnixJBWL9mA1yleACsbpqXOvVNpGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T18:07:29Z"
    mac: ENC[AES256_GCM,data:EPvHF/NXakHixkUPd0SdG/5GCItM2Earcg8ghyePw6YWJPyhuKaqra1fhYa1myaCqZdLeMpez1j+yUDEZCRvwXS6GzqJkIMqjiKb5uAa7k4oSRhgZfRY5uGs1hJhJkQ3ZMWwdJSAJVmliwCYnz7QxQrOMigAeVHuf5epVc68dJ8=,iv:9T+N2Rx3haCXNscuWCyvDAoq6Q9OHgXeR8MQHZB9AdQ=,tag:5ZKghZk3X4MKqIlXTqZ8SQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
