---
app-template:
  controllers:
    stirling-image:
      strategy: Recreate
      containers:
        app:
          image:
            repository: stirlingimage/stirling-image
            tag: 1.7.2
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              memory: 1024Mi

  service:
    app:
      controller: stirling-image
      ports:
        http:
          port: 1349

  ingress:
    app:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: Stirling-Image
        gethomepage.dev/description: Powerful Image Processing Suite
        gethomepage.dev/group: Documents
        gethomepage.dev/icon: https://raw.githubusercontent.com/stirling-image/stirling-image/refs/heads/main/apps/web/public/logo-192.png
      hosts:
        - host: &host stirling-image.mdeleon.dev
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: app
                port: http
      tls:
        - secretName: stirling-image-tls-cert
          hosts:
            - *host

  persistence:
    data:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 2Gi
      globalMounts:
        - path: /data
