app-template:
    controllers:
        garage:
            containers:
                garage:
                    env:
                        GARAGE_RPC_SECRET: ENC[AES256_GCM,data:nSnogt57SJJ65i+MKasHFFPWCVGLDzHq5tlHONz1bk/vZ78u,iv:Kwk/yUhheEOGEyjPGMTUpTJ/71XkHNhiNfL6CPMcpJ8=,tag:gv8xzDtcvk022i4dG+cqcQ==,type:str]
        webui:
            containers:
                webui:
                    env:
                        #ENC[AES256_GCM,data:kbIpIwsOsRcx4CJXB7YWRUv8B4drmn92rsyQtmnha8bPA60YbeQU0GtvjTIc1e1pcd+VCvZI/ONaeG0q8lETo7vIMUfUfXvwM5U8jOrP7tvB6u8j2V5Z6te+ABVdjfV7q4rNLMHVaC9KCjCyd0tHBSUOaw/9zM950A==,iv:BkC9eaQuJdFFvzWhst8sAvfhbdCnwZ6ENvwPYXEakro=,tag:rSJi0dQiCisbhTAMmvtKlg==,type:comment]
                        GARAGE_ADMIN_TOKEN: ENC[AES256_GCM,data:UILgC+D1wBS7EYj0uC6sIUmq71sSBHIcpL2Qz/9DtQvp9l6z,iv:4oa2I26MhK4k7cZxSMBs/SvhDQZfZ/08jnfG2XVhqWU=,tag:XkJUYNWwd3ZDsc00z9inbg==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRYzgva2RBM3I1b3FHbXg0
            cGZhMzMyYzRaV2RuZzFYSjBQR0ZjNnpTaEZFCjZyQnBJblNpNVR1MGhCNjROU3Vy
            cmRzenVJWTlvSDdPN054bVltaE1aNGcKLS0tIEphbnFUekR1WFFENG16bUNWL09P
            TytObXpERk52SWc0RURpb0lLc015dm8Kd0EC8//itOrn9QTvBtHeDGW13Gs9Qdg2
            3VwhotfKG2mtLjiONk2AIWmdOucc0vqHHLL0Vo8f0pncdzemjfhKnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T02:05:02Z"
    mac: ENC[AES256_GCM,data:M2mVW7/Vpa/+eT8m2MjgaHEzzZv3LGMlJJtYXwKo8TVJ+61ExE990Zqm8gSb+OdWILuzm4s/cbbLdr14mDltrFYcl+5VmDfce0iMpYg9wAyXnWqSVer6dV77lHorGdjR4YLr6qZ0dkCrbZh3OkP/F1zjR5QX6c17ZgoueYKvNjU=,iv:8xV95yk5yTL1L3hSPUAFsfG8ZC43n+qTRg8pIDVa2TM=,tag:VUUAkLXVyUEWbE5PV/ZcAQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
