app-template:
    controllers:
        garage:
            containers:
                garage:
                    env:
                        GARAGE_RPC_SECRET: ENC[AES256_GCM,data:6QCYdnlPCydw3YZ39J7ZxTDeEFPNEkXmsn+s82RFP4DkwpHNw7TafI/93vdrDdU/kL8w50ltj+B6PA7I4HJ/gw==,iv:5j5pfbyZuPu16DMWDQtkJXZrjCc0ItLcLuj9evLXBuw=,tag:aMxmiJdIZVwnsdLcMetnjQ==,type:str]
                        GARAGE_ADMIN_TOKEN: ENC[AES256_GCM,data:Otfc1clZP4x/KtPTSBsfBxROZ9qaVrm8MxEXldGSBW3R91soirR8yvF3XqOG0Rbme+hc2rtrKsgztP6OEk19xw==,iv:z6sB4wptyzjZ66KIyimN5odC2rjNC2iC25Qz7oUX6H0=,tag:5PmB3bvJSxoY3VyRf7sOgA==,type:str]
        webui:
            containers:
                webui:
                    env:
                        API_ADMIN_KEY: ENC[AES256_GCM,data:GUTsgm+Odif9F8fZ0j/NHTtRL9Uah/l1glbAVQET07trjtdRCxMLW8AvvQS4zMZCfU8/pw41typI7liHEwmAuA==,iv:zFIpPutqahxGFcl3FuXewAwLB8AziVaBcwkkXpu57x8=,tag:a32VQwwGTmQ+UcOiX8PV0w==,type:str]
                        GARAGE_ADMIN_TOKEN: ENC[AES256_GCM,data:v9mkm5Akf11xzG5vJrkf1+aqWxBHbCvsxMRrtfOyUhOQfqFNT/WSvR5jRDy7BdvtJ9mKweH+mreeNbIEWJLj8g==,iv:ljVMCjloJ5/9i3kKtfZXWYIOcI46GHEiKqFC6cxN5yY=,tag:bRqMy5oIKwmPDnVujD7X1A==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEaERnQnhQZ1dOdmVzRnhY
            b2FhMk1VUTVvSm9RY2syL1c0OWlnMFQ1TlVJCm9zZlBhSDVFeWkzSUx3cVZHUUk2
            Z3Z0WnRNdWQzVW55NmloMW1TdkI2Rm8KLS0tIGpYbzlvTUFWanJmc0FRVGhpTUx0
            QzNSVFB4T3NxT0xtSEFrdlgyRXNheW8KDc7r0C4Y12dhjr9Pf7hiCyhTO8zxJqpz
            oY4hGhsUHW2D0ga5T8eCtTU0Wh7MrNOXx9uBuJT06Jhek1KCIS2cbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T02:32:39Z"
    mac: ENC[AES256_GCM,data:/mzLoJAZHox31XkKjG5k9Vl9sMrpqvqGId4Fv9wlueZ7B4yRGNIp9tRajjT74jF2HS8ogmMLOuzlukgpU7P2FCD5UEfzgZSDzMrlsw0jYzO2KIPjTPO66v8dhcVvNUmzsSzjqmzOruS05C7xJsibEEzHcEuMyNaO0TWXyKk3/uA=,iv:oevhfFE3aSSGg2izGw8j0XS/AQD7oT6hV321kf/q5As=,tag:F/WfVXObDOy+yVfAm2zU8A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
