app-template:
    controllers:
        garage:
            containers:
                garage:
                    env:
                        GARAGE_RPC_SECRET: ENC[AES256_GCM,data:hicbWW22e5y7yoYTFWD74zqzNPOiNl0Pt1f9Qb44BLSIUFsL/xN1cCZZkvra4gHG6vrwHf7mg4tjHeFGwPw4Lg==,iv:t5IfZGQ1RVPzxwa2/nG93OPvyc127JttbMGbEBOUlw0=,tag:OuW8GO9oEbhonnzkwDwIlQ==,type:str]
        webui:
            containers:
                webui:
                    env:
                        #ENC[AES256_GCM,data:4Fk5JrLS/SKv0Ee4Lw+B8I1vyYp7HMgRSKDKRR8dj9MIe+5k7lyfyw0FHPi5+jCe/NCdA/xFBdJ/dWf7rJDPvCzn1yL/mhtR2bd+rX0zWh4xPyYlPnhnILSUHG8V9FnclsXFKVSYEnjG0rvzbhHgilqpkU/09WMVdw==,iv:nfM/+Z9UOwrz0Umy5doX6pcnrAlfgZgG42hSNSdWQyI=,tag:FtMP00i5CT9XXzyctJpPZQ==,type:comment]
                        GARAGE_ADMIN_TOKEN: ENC[AES256_GCM,data:V0NnD2G3U1g2EnGyHcAyxphRC9dGEVFcmSo+G1XItoCcARSgEef/Ea2I5+/2D16hx7B+8g5ugGnmV+eoPVWoIQ==,iv:ZvRd5HHS1lzr1BRwo/0eHn0QKAR1dyxq067X0CGliYI=,tag:2CzRtQsrMzir5btXHcYJVQ==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZFRmOW5BRFV1YTlXZzYv
            MGRnTmhrRkVYVEJQeDR2aWhndEFYR3ZWY2g0CjFDbUk3amdZd2tmQ25MNk5HaURz
            a2lCZGpGNEtJZlYvdkFtYXhYRnpTR2cKLS0tIER5TjkxY1lKK0J1bWNRcWlyUnNU
            bHJIYjVTcEdJbzdXa2c2NWo2bnZFL0kKIay16E9m4HJ/Pvu3ZwmiL/fdQvdd/vFM
            LLfbnDMo+JPa2fAh9zUUrbCKP+mVCLFLLbxP0O/g9oYps14sI/SBiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T02:52:10Z"
    mac: ENC[AES256_GCM,data:pf6Xj07q60GUeInx7NaB76Qj88qZRNoTsgUgF/7zHN+r0Lz4Pc5S+WGIaFs7B5cGV88R2iGjZ+0ey6+9USsBiPOTtvx7dPcTysNzMXfT2u8jOaSzZt7zVAamzfjauLOqTq4F4qyt+mTqAxINbiEhQ7blS15Q3l6YEEHNxo7mURE=,iv:HYn2rR3Dt4Mi2iqzXNfemrFtqMAu6IW4EOSAgaxpqV8=,tag:iqfAhb0nuZwXU36VdX0oIA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
