zot:
    ingress:
        enabled: ENC[AES256_GCM,data:M6/Y6g==,iv:POV/J4RWsZqUwOqJ8E2rjmliGl+POmcUUkwmANB3z5w=,tag:EmL7ZBFwln09PmOZnFW/nw==,type:bool]
        className: ENC[AES256_GCM,data:q8MfxWcLEQ==,iv:w/xubf0At3wwcsMXSCZ/7uZ/90Zpe/OCc6JJu4g1ehg=,tag:0rsf43x2X40zXOLPjtM6QQ==,type:str]
        annotations:
            cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:PzTqKbf6xPPQYk6lZTwshQ==,iv:EmXFKEvJJ3EefoTKAzDUgnDfpmLh9kEZ9Saxhz3PkCQ=,tag:xI+HcjpAC9zwF8s9ayZUDw==,type:str]
            gethomepage.dev/enabled: ENC[AES256_GCM,data:RbFSfQ==,iv:mBwvlNTfgnyd1x6kHdQ/x+1OKTzFn6zBl2W1mIRO3Ok=,tag:hrrUEpsNA1nzqrRLyRWIlQ==,type:str]
            gethomepage.dev/name: ENC[AES256_GCM,data:YI+m,iv:9OEBlVj9DHapKYCP/AxiVmp+UgDGCg7PUehzM4T1UBo=,tag:XVauKaMh98SXYLnThgn+8A==,type:str]
            gethomepage.dev/description: ENC[AES256_GCM,data:oAdtGIsdXMnHZSNM+m/lPRrB,iv:ZbNiFE2tUFj89HogOUN61apCiqADu5W4Ad16G7blLzw=,tag:65Ii1DQFKG3Pbt8WLwdfYw==,type:str]
            gethomepage.dev/group: ENC[AES256_GCM,data:degwmBKaVr12zMh1uz3iZGA=,iv:U4DdRcqucHCpgJcRyDbWRMSo+lGcZjSngF1TbYoqLWQ=,tag:ikiJjphgkXas5mjVpZZ79Q==,type:str]
            gethomepage.dev/icon: ENC[AES256_GCM,data:mmsmlGewQynFIjs2KSaVppUx0w==,iv:JqMNAAuAoBpSWQBvMURqLl7r8/89hP20YwyoC7cHQe8=,tag:nwWDcunTtUfA9zBlBWC/dQ==,type:str]
            gethomepage.dev/pod-selector: ""
            gethomepage.dev/weight: ENC[AES256_GCM,data:Zw==,iv:0JQTlA2bfXsVQai8V2W7OWhNyHJBOu7ggk4iwuxTrQQ=,tag:akz3DbOIKt1T8JECYa0tPg==,type:str]
        hosts:
            - host: ENC[AES256_GCM,data:mcvjk/NegJAMSdgkfzVB,iv:0Gne/y21ZKoK+qO/xcHVxX5Wac9KsVmTvaM+hQGc05c=,tag:oNOofBmA3b2pi6HqkxEYug==,type:str]
              paths:
                - path: ENC[AES256_GCM,data:yA==,iv:86ZmYfKiZDyGXIhuTKhmP003bey8Ozl/QalZCEftvK8=,tag:r4re6zHL1Z4kmNWzmUe7Ag==,type:str]
        tls:
            - secretName: ENC[AES256_GCM,data:ei232SqMomZbqfQk,iv:CzEQnPSYPMmmoI3tKgZB5/jI0c6rMPzSO9wDPSE+f7s=,tag:ce8vexZfPapaO7lAg4OWYg==,type:str]
              hosts:
                - ENC[AES256_GCM,data:99dIbZKJrBxSYVvzLhbq,iv:r/rdw0TeBhx+BqnkMrxio4oR7BBCMbNb6MyL6DdT57Q=,tag:7Cjtg41gt5p/vS4DdFMPPA==,type:str]
    mountConfig: ENC[AES256_GCM,data:YvfNFsw=,iv:e/Al3CYo1XcxfQu8UkcafcDKzbuYe0F4O9VmdlYnKVM=,tag:w+S/pOcwOkDvH6ciwfWWYA==,type:bool]
    configFiles:
        config.json: ENC[AES256_GCM,data:bxeUjs9ftGgGCBoTjPl9jrqHQLDSj97FMxgnMwAQQBOJqHC5ByPOYbbVWqymb/bXZ/Bd8xM8Wj6g7jFabA267sVCQnwIhJ5hYKLaKdpCChpsTSLPDu8y1oSmh/5rCgQNNxXNjyIg0z4w5d7UzbSb7ShdVXL3g/Quf2zl8PKeKTdPzDTZxq94ebkulLE=,iv:aZr2PtaFWI37D7w4M5IlHZ1Df0kj0crW5baSqQCMhwQ=,tag:/+sdgbJ1x/jB3Wh4DmQbKw==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUmFKY1lMbnUvc09oUXFC
            K3ZPMGY2Z1VQc0FNWTlsUjJFaGVYS2l2QmlzCnliK0k4Zk9VRFpQdWhqSDNzbWFh
            MkUvK2JrcFZqeTliWFZveVBZbjBWTU0KLS0tIG90T0JweXZqL28zRjBYQ0dIWVdW
            NG0vdVhiTHlsbUJaTzlkUlFEWCtCTG8KaxSkVV1KHok/S1EDla7FWjZBcb7oqW0K
            VS5ee7vFwURIG4GRDBmW0aqcbbcRIpRXcqV+uHfcl4OEzcbiyvgRWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T19:41:11Z"
    mac: ENC[AES256_GCM,data:PREPLNd3RxEX0uMJVylagTGQFpaOF5JIDNYrELVhV35ClCB+BVjgQnMUk9Syh9rCB9LVcskyN0gC53yPUuQ9yfWJzMNo1us1ipHu2Ue3bJQdvJmtfyo0PJwkRA8tDrUex7xbFgUlhWYhEwq6/nuGEAUuj8pKdhcUDTto5lP7ENA=,iv:1zmPB1hDCjgD4pODfGI+jHW0Gwu5TbdU2X5p1IMKXFg=,tag:9IQIzVA/T9gT5t+fob6SMw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
