zot:
    ingress:
        enabled: ENC[AES256_GCM,data:U28xAg==,iv:rbYzlPoyhqMUkJqZeyG2q1SqXPaLxwiEehhv6S2KPYE=,tag:B4RE/NpkvzzE+4ixU0bw0A==,type:bool]
        ingressClassName: ENC[AES256_GCM,data:fxRRQooe4g==,iv:q5uBdCYPgcY4pO2dvu/AMR7akQ1NQY1Rd3m3y/ILXa0=,tag:XWHQXw2WaDwR/apENnVyLQ==,type:str]
        annotations:
            cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:t6hLMLKWfvViDN34a+/vow==,iv:EprCkk5FTnKocKEc/mmlerl8yrluSCYVxkbQ+qVtZqw=,tag:irxOXpNMSsoChZAThcy30w==,type:str]
            gethomepage.dev/enabled: ENC[AES256_GCM,data:DdLPVQ==,iv:6aeuzHbi/9zVtHe9Bf8wiB7jbdncdNkRBHEoQqS9jOA=,tag:PGmns+uwwRBzo/aVdFVIJQ==,type:str]
            gethomepage.dev/name: ENC[AES256_GCM,data:P7as,iv:NWyafpIefRyyZYcj9vDm4WB4YE6KWZHc4OUZq6v4IZ0=,tag:CwpWnUA2R/LEjZC/6aqm2A==,type:str]
            gethomepage.dev/description: ENC[AES256_GCM,data:o9FP5Xu/XBx8ayJMyPR9xoyX,iv:sLYB3tY0l1gDrQFuv0mv5nFv43figEkOtmiFmiOn93A=,tag:58yjmPxXloTW3sX9Jj40NA==,type:str]
            gethomepage.dev/group: ENC[AES256_GCM,data:YMDYQa7BsoYSHGKg0cx51Aw=,iv:zSZ7y+8D0fwNn/uNH+hBX9QZica8LijMzgqBq2IBPsQ=,tag:rej3t+6GcKmFk1CKmGE8KQ==,type:str]
            gethomepage.dev/icon: ENC[AES256_GCM,data:kMcolCV/CYs83WrujKlyBlRe5w==,iv:9lH17ArC5A+f9NRfLGlImLh5NHdwsG1IjYsQ2iebnM0=,tag:Itm8PSOLwTvlGzT3LSmF8A==,type:str]
            gethomepage.dev/pod-selector: ""
            gethomepage.dev/weight: ENC[AES256_GCM,data:ow==,iv:M6izzAaAdGabzRluhVgk7c4WJfeVIB2Mll8eqKR4ilk=,tag:0vbOyl2a7gAprenpdjQaNQ==,type:str]
        hosts:
            - host: ENC[AES256_GCM,data:o0MKUPo7x5z5kekOS5o8,iv:mZis3aKIxbIlUF8WNWSyAK5NrMqfOI6CKIj5a7R5SLc=,tag:uTVuJQ23+edfytSfjaNbEw==,type:str]
              paths:
                - path: ENC[AES256_GCM,data:6A==,iv:hlFsiw96epzeltWoRTd44gLJoSIYVC/5lrCTBDfsiI4=,tag:aOi5y9uBUj5Du1EHl5yiDQ==,type:str]
        tls:
            - secretName: ENC[AES256_GCM,data:kGYI5qcZMNj7+8+W,iv:6yuQysuE4m7522FIWqRKWLfb2OfzyeneJLfyuLjpgug=,tag:d0AfOvAQWlbC+01ejuSZQg==,type:str]
              hosts:
                - ENC[AES256_GCM,data:xEIFA9UcdCMYK23oiMgv,iv:NOwnM3dHrxc5joXq+zDLd6UEPqyKG0M2e9I4PaZFcpo=,tag:GRRX5bD6X4vbHdS61Z2B7g==,type:str]
    mountConfig: ENC[AES256_GCM,data:WdTk2B0=,iv:JsDfOFwPGs40onLrlqT7QxK5yO+LhjG+suZgWDt0vWc=,tag:sUHTpnHKBTPrmIBeMtFr3A==,type:bool]
    configFiles:
        config.json: ENC[AES256_GCM,data:lKvFa3/Az8DkPDg+fnQm+Sk8gXRypMDiWHdLPXOizQWxSH7zNuPHOQnILQGJ1zjtetmsfs7hlglJPtbCu5uk9AI6udqoB95hKgGW5bnsRv1x5NQXAqyL+ShxupGpc1Q41FvRezuJbY2u6tLNGLlqiP+CbQxfRUvjZT9Mg85Dw4aDI1jeQlbmUl4JT6g=,iv:H/ljxFkRmMDY9Qp6EsvtUB/Rlv0C03DcVJSsp5lRKvE=,tag:Sf5T6fNcsSTWbWnj7xItaQ==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNVG54TGZRcUlDcEFVV1hX
            ZFEwVTBRdWQvaGJnSkM3WFQyb1l2dlp1ZGk0ClJKL2VqQ0NQaTJyZjlLTTlBbDFS
            Uzc5R1dKeXFvNXUyUXlZNG4ySXhLYkUKLS0tIDA3cFVjb1k4d3Z3YVh0NWVrT1Zu
            WEk5dDhXdkpoSDh4VzliL3dmZjZpdGsKsIGj1fGSeyAUCzLwiOWTqyCbFK5CiBIr
            W/AQm4WmP43dOwh8WQ7/BS9FBV61JGimigvubyJyJnAEobRn4aVVLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T19:39:27Z"
    mac: ENC[AES256_GCM,data:HWdh3GTUZJZbH2cdRPjloV3LwT9ZDlAKR3cttUddVsZY+szFl3fYfbwNZFHL35pr/LHRvneIi3HTyBSFiOEd0h7H4WaxDXfyuPTNYCWa4yiBBjd7/+e3CnkuG86iKdm9peellVO2M0PnA2i38aaPdwVfC3RmvZDuxKbBIk+qpb4=,iv:QmMLhV75h2rw3ZPkwxZ/rVB8yTnsFf/Fo38Q5RYmDFc=,tag:zjhOSQBnsx63zXBq4QPTzQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
