zot:
    ingress:
        enabled: ENC[AES256_GCM,data:AFqsNQ==,iv:xdbjySD04gt/vYuirCMjntGdhFIodOyPLCtRyijHClM=,tag:Gwqy+wVwmP+8ToDdLg5jRg==,type:bool]
        ingressClassName: ENC[AES256_GCM,data:1IFgPd7sWA==,iv:k07T9z++3Vwh3w84VyJm8eYoQyrmXGjBMJ/ja6QrrqQ=,tag:e0A9H1qBsV4wIautIcviKQ==,type:str]
        annotations:
            cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:PB8/z4mfv4TQG09+neyn0w==,iv:0Q8kE2A0bYolwoxVjwMhM3RF/v0mQA3MgXv1RglfNe0=,tag:R1TNGqF72fiBXJicDO6CYA==,type:str]
            gethomepage.dev/enabled: ENC[AES256_GCM,data:TuApDA==,iv:GG9n79CnStAbDbj6O0nlJu+p4xmN6ZDZZdVuXH7xzWc=,tag:DVpz0XlblH2lWV+kNZ4Oow==,type:str]
            gethomepage.dev/name: ENC[AES256_GCM,data:/7RC,iv:Litu91dCRsqQtBuF2Y+TCC4zgQi+/Ds7icwrqB8S5Sg=,tag:MoiXojBdIyOpRhfTsjp6EQ==,type:str]
            gethomepage.dev/description: ENC[AES256_GCM,data:VwZzUXsfZNqLfEsIUUgog83b,iv:RIF8m9+EQpYZuzonhYz6QnVtckmRzMrY/XKbDMzQVKU=,tag:eYCX/7fIITPKBcKEEIoTWg==,type:str]
            gethomepage.dev/group: ENC[AES256_GCM,data:xizTvQRtUMUTiiV6YNDLt4M=,iv:aq/jATdQSgxqI1r/ZaCgPWjIFyGNp7YoRy0stpKAkyM=,tag:fPI5E3NZ8rO65oo+FIGiRQ==,type:str]
            gethomepage.dev/icon: ENC[AES256_GCM,data:j9wfgmmzMCurvfCYyN18ByNotxcHT1nFg+oKolsyUTTJBVbPoVd8X04UMLyN9BsRiexSwcg=,iv:jY8N6sW3/phii2KYZ5nbrme9I8jfOvVTBMmGHx1aL2Q=,tag:M2jPl5UQ5t61/qLlHUFcpw==,type:str]
            gethomepage.dev/pod-selector: ""
            gethomepage.dev/weight: ENC[AES256_GCM,data:Jg==,iv:HHxhNjHbvunCg58I+zj6nWmGGLPtCRnXYTHPt9XmIWM=,tag:XtvBdFAjOZuTZ/IePFIvfQ==,type:str]
        hosts:
            - host: ENC[AES256_GCM,data:I5tA1hOCtRbgbTM+EdXg,iv:Yk51vzd6EEBIK6opXCW+FQkEQd+75R5By6IEvqDzvaw=,tag:cHn5D8WQfb5GmpCYG2rS2A==,type:str]
              paths:
                - path: ENC[AES256_GCM,data:dQ==,iv:41+8pZSBOfDZXExxDqoI2GyH3iREf8Azzjv/MMt/4VQ=,tag:5Rfz3xBvwZuEYLzarjykPg==,type:str]
        tls:
            - secretName: ENC[AES256_GCM,data:4HlmKrWXQOZH7hg+,iv:yrrpBtbbXXYIRPlgbFu3YQ5K7ab9mmAT48EEoOsRxRE=,tag:mH0OdIwSB5uqpyDqgfR+rQ==,type:str]
              hosts:
                - ENC[AES256_GCM,data:Kiy9Mm9gWO18Xv7y/Hju,iv:TLGQKB5zkglmatsaBeg3JrxXVKjX4PXPkas2eTsIeHc=,tag:T9Ni5Qmpfr4TTsY+Iv0ixw==,type:str]
    mountConfig: ENC[AES256_GCM,data:+xiUA3c=,iv:ehSZDlb0wtsq/yZGghEBIPDRI6eel2637JzOkElZWGY=,tag:b4lKUXDZDWChmaxKXoEcTA==,type:bool]
    configFiles:
        config.json: ENC[AES256_GCM,data:6p7qNBQf4njTN/jE4z9/Zl6VBO3LsQxiH+U4EOFdDg3HTAQzkvQ6svRHl5SeGOfzdvSfYXAhVPXLvFqKKZdv+r6bfAh+U5VZcxHCjLwe7owaqSAGik9Sjw30OkwUcgbI3wIe9rgY4g/9u9MOtuW7bekj2cVtEfuwlvsGLA7oOVmBdFA1QOO1Jr/fk1U=,iv:FElsfYX/XU2femlYycNvAlpL+EUgXV5LnVqG/W9UTz8=,tag:cs+jopI44wFpJG37s4iCMQ==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSjdaZ2hMV3Z6QTEzWDhV
            VVIwWkhHOEtHUFRtTzdnaEhMTXBEYzBCS1g0CmNNdkdYcXd4NDNER2pZeHltSmZH
            bktOODNOOUkvMXN4WVRNTmJuUDMyM3cKLS0tIEIxRlpyWEZFVWdEek5hNVI3SkIz
            QUZ3UGlWOHFiaGVqcllxVGJkOGwvRzAKTtEMTKVh2Qgl6ilvlc6iUO0gRAdKYSO3
            yvl8x0npjjTJGI3xs6N028SpO7BiRJopxg0I4ogCtYoLjba+jFZqow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T04:51:57Z"
    mac: ENC[AES256_GCM,data:XpGdnj05mbr5g5NiG5kSmOVw3zRiRYhuCdZ94z7ptuUZyqwXGJXC+9HUkL7UyM4FdQ65E8qv5OE/6qlQG9/c6cBrXBRbNiXZBVzWUd1UP2NAUaC4jqGdRy+2rpkSoDgOSMJw+QFnAlc0fHb/iulGqo4Fq4RvId1Nd147vl6zQKo=,iv:T793X93Z4/ikqv6aceni9+4WnYUnZMTOklFdopwr8bw=,tag:fjStC6VG/a++11l1b3oUHg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
