app-template:
    ingress:
        mealie:
            annotations:
                gethomepage.dev/widget.type: ENC[AES256_GCM,data:PaTeehSQ,iv:yenfAYr/wm3aKB9AAoXc/CVSZ6QTuO1GNjsFwYb7Jjc=,tag:c+vhMMn/nt0DVG7JPzdSFA==,type:str]
                gethomepage.dev/widget.url: ENC[AES256_GCM,data:p8zrdXQlks6LmjytTWLUnY4X22OYC11Fqck=,iv:dtSi645KRV+PLFUGU5cGMpafG+VWRN1rsTtkZpwzjLE=,tag:5c/B2BjwSAzGXxHOGCmcNg==,type:str]
                gethomepage.dev/widget.key: ENC[AES256_GCM,data:24XHZlTHjvcm4XmU0J1P0GVPUyhJFyvFT6ao9QOnzVrEXrfjodRqFnKe5VcpuMcumaHHadal9DKV9jDPUOGQDUZQBMMzoCGlqx16+p7myz3gwUaETzaVE8NtG8vzafYrbPNN8KpyTkqj2H6BFAVJphprg8Rzuf8fNfbr0/kIGnnKoiUA7tdUhH/FlR8LqUz3+Y5j5x+lW+2H63Ovjw0ucl8YJWWYwZrgb0U06NHnGbU/FuTkQCGt6GyZ0zqj5ilhRwkdznsLOzuc/7EQ7IYadA8X6r511d1ZMzqCIWLy+sm/go/UsLasjAw8CGAqByF5Ezhd4K06o3I=,iv:Mrjak79PiBoQ0nFFuc4zAzqMRrTYaiJonS6ZZ62uZxA=,tag:IEq+rbBEZCeyCiY0tzI2Eg==,type:str]
                gethomepage.dev/widget.version: ENC[AES256_GCM,data:Uw==,iv:2+Qn7Kn/9i/v2L5ZJ9d4ejIrBFpVY+8T75Aq7jpJCq4=,tag:Agr/vQ5hAXgIAGtrCDQCOA==,type:str]
    controllers:
        main:
            containers:
                main:
                    env:
                        DB_ENGINE: ENC[AES256_GCM,data:+m0fMZLtvWc=,iv:UJP33GiZP372a1mTMMx3TGPUQtxEvXHda760h5+o5+w=,tag:VBMpOHR5Em1xFxn2ccSUZw==,type:str]
                        POSTGRES_USER: ENC[AES256_GCM,data:TTN+dngq,iv:prY+bQqu9267qG9erWRBE1G9BbewuU0JjuPWF0/5S6s=,tag:sYTkeAvGrEEHdqviSS+CQg==,type:str]
                        POSTGRES_PASSWORD: ENC[AES256_GCM,data:DeSPRZ5uj8fH3lqez+jRiKXxXg0L8fpkG2FEz1imQ9M=,iv:hqfbTFR/yofG4OVXGb8WRowlEnVbe3D3JSFcB/rR+wE=,tag:La6pYZ2R0ltnAWYeK9WoYw==,type:str]
                        POSTGRES_SERVER: ENC[AES256_GCM,data:67BH3ctggMkWS2c4Xg3d,iv:lMHP2poLdNqp1Jr63E99/Mt1v+cxt8HC5LkArTB8JqQ=,tag:ZCydjngJiZl4Ug9f0vWwTQ==,type:str]
                        POSTGRES_DB: ENC[AES256_GCM,data:gJH9N89X,iv:E47x8V4QhDJz8uGCdSaCScktMX+slIuryqhUzid0CJ0=,tag:b7ZcHcwTC2gXznvO7Zeimg==,type:str]
                        OIDC_AUTH_ENABLED: ENC[AES256_GCM,data:byr5pA==,iv:Btc/SXSMKcA0l35yjmnSomF3fx1nf5eTF+pShkGsiQE=,tag:RnZZhdhlQfbgc5xVG94Qhw==,type:str]
                        OIDC_SIGNUP_ENABLED: ENC[AES256_GCM,data:lHXDvcI=,iv:zS4uTFpWa4nfVmirWq4COMnsRiuIRG2xnViiQAGeNHE=,tag:hm4omJUCt3j7ADOu4oVC4w==,type:str]
                        #ENC[AES256_GCM,data:av0IqQWlw9urjEDY5cjSL5feavHK0ICDpRUbUYZ7wkeHGfxE4e/8QFsJJvw2gTmLmEs09eIREze1iL4t/ToADcjREf+q9juD5HZWUIP9PLiPyHz7hppw7A==,iv:yb8pAoRNo6O7YYBmlvch8kzPG1Z4x7nnG5VvHoI42eA=,tag:O0qwGrNRAJtYgBDjop22oQ==,type:comment]
                        #ENC[AES256_GCM,data:2mZAwQzT89nmXeXQvQCdYaOZoNe/oJu7NymYtg7hKobJiuBvhtmPOPC1+HyegHNuhvOz,iv:BR63VC4M6tIC82NE466FCkj2SWQrHOcBUqCGU5ktECg=,tag:wWl/3m/xVRDx/4AmY2T+Hg==,type:comment]
                        #ENC[AES256_GCM,data:WzVOqTKizTd84BpaEM8gSAzJAN79gMaDxKp3J4OhvJwiuR6GBykpZtSJ4eDmrntex7FC3RqRK0OTqXmyNQ8vKGd7KxWKV623KCnsnWiHlJmASEEVB2L2,iv:RYEAc5IXefDP595bb9wVA2tHI056KO7phy0KGI5BcXY=,tag:UosNDUa1zNjepXLFLE4m3g==,type:comment]
                        OIDC_CONFIGURATION_URL: ENC[AES256_GCM,data:fS/Iqdnfv+O4rk5ZmLGFDbJ/NqhRaKDYGKYFyLIPWBQ8K0DDjtUtGgtEEOo7B50jyIP+TrD16WrMU2g=,iv:kPrJ6jpRKb1/TQIDfaknjqOf0t5hrBAcKQPgE1mRDV4=,tag:BRTQpA/D7+ANfC4PK1VoEg==,type:str]
                        OIDC_CLIENT_ID: ENC[AES256_GCM,data:WrjqJ84oEPP3wQHVh5/VcjG6tQjmlOQ9DgYg30Gxhpsz7yE3,iv:GxDvUc5+juSs5xis0swHEZ6tGhe5oY06AlcW/1pVLQE=,tag:2H/byOTcKHwzMNMg3JIQjA==,type:str]
                        OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:CI96S4FuQk+2P7mPJ78c6VV3L8zerUxrUQXPGyBYWOM=,iv:WnTbl6fWRlF7XyGZ7NcLJ1d/Gb7w2l/XURG5UMhnjLk=,tag:cc5W33/KvkQa3w8u82532Q==,type:str]
                        OIDC_PROVIDER_NAME: ENC[AES256_GCM,data:8XxJ5Q4/AAWZ,iv:zKKfzfnEh3R7xFHjGSBHBY5Pe9+DRP/D8PrsiHhddnU=,tag:9kc3TlhkyBLUJMBUIWnGSA==,type:str]
                        OIDC_AUTO_REDIRECT: ENC[AES256_GCM,data:SKH3Aw==,iv:udUzNuVbtD6Y6rmPu3DypmfTnFSLDgDbZ5KBaVwyCcI=,tag:TWeIALwDeWSPstjjG4DL1g==,type:str]
                        OIDC_REMEMBER_ME: ENC[AES256_GCM,data:oIjN27E=,iv:bTGaSy9A1BP5iff/uvdY+esSK1Xea9q69c+fxW0x2xg=,tag:ke6C37CdYJu0TVY3EkGngA==,type:str]
                        OPENAI_BASE_URL: ENC[AES256_GCM,data:mUisWBiQDbFAjLtAyRUWVPSGyibeJjuIC24S37MCpUAZPhbdQQKGtoFNX05f7NuI,iv:MEp3mKL4m5WcrbgKwk7WUeMCUk/I1aUYgJwZ96Kj3Ig=,tag:2DIiYkWu8kdYUwWOXbEwPQ==,type:str]
                        OPENAI_API_KEY: ENC[AES256_GCM,data:AgXZj8cK59sC8YTvwZc2A0pD0yK0f0WpADsPtuKaAWLxdlT374Hy,iv:+5M6cvhpE3LOCZwwWfK4RRXBunRSS/F0ptKuEFyMH5M=,tag:DfCVIN8GBjbQQbb3uBNZ9A==,type:str]
                        OPENAI_MODEL: ENC[AES256_GCM,data:hSGzjPY0OBuHlq7rQtvvAg==,iv:9RbdmPpePTHCgUwB0KH07xGRPVB+RIySpAyZpgRoMYc=,tag:Vj2OhZq8mDJ3p7HzUww7hQ==,type:str]
                        #ENC[AES256_GCM,data:gfX5dXSjRkk8oubqxvEDHRmxtfBFU+L4T5+7hLkewf/Ki9vtGsI0CxjTQiMTWm3Aw9qgxEwUeNZl8GunWmMGhFH/axDcF9/3k1BlYnZrJXYDY4vcpPCTURNaCZKy32rMBfVdF56OuoEnPK61FC/GgxopgTvvaALfyWu1afE0FWoazBDnQ6/7rzby+bcdzIUgfmynAKPtM8YZSDmzJpOnSHDGR41VlqZ0skpEkgbJQYHGwyrxuV+3,iv:tY2D1IOUJXHFAulDuDGAdGFwagQ0wDXLe4vFD88BvAw=,tag:QeMnQhoZi8AMrPGr1B9G/g==,type:comment]
                        #ENC[AES256_GCM,data:aI5mcqo9qxlwfqU1LQrMYRP5IyUPBnDvgDr29PeqUfC+jSPUt10=,iv:w1KZHvDVvOLW5rAdBNS2YqYHjrqFyRpkc9NOobeLdmA=,tag:1Z689skU+/xxn21rHrxqnw==,type:comment]
        postgres:
            containers:
                main:
                    env:
                        POSTGRES_USER: ENC[AES256_GCM,data:LTOBqtpQ,iv:SGNgLwK5f/u/t1j5uRVhg3RzsmMxQdeJr2/ZYhEBirM=,tag:SyaOFiRccG5xbZgPURmcLA==,type:str]
                        POSTGRES_PASSWORD: ENC[AES256_GCM,data:4oSvtKk7ob3yc05gurjRtGx5BZ6TWeXvL0jfIusw0Jg=,iv:NBrQieXJA4rgpXJqD6EGbEgXJwVUzqybuLXqWXMlovA=,tag:CgQiNnP/VmoAJrH8ysVihQ==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4VEVKUG1EV2dpT3d2bUZR
            MU1TSmdaSUI2a3RwWGg4NnlubmQ1elE3WFc0CjVLUEx1QXQ2WWJRUDM1YlZpYXZK
            TmdjRlpuSEZyN280RndMbUc1ZVExL1EKLS0tIC9KTXhTQUdaai9SRWROMG5KSE1o
            SEdpaXlpZ0Y2TVgyelNyNkptRGRYRmcKr+Oov59wK3r3Au1Vrv/C+7PD9+vbQ0DE
            3RggxH0qfRDe2ja3b0192Z/HKgvlBSwmn3hAwfW9yVhJelJoeLd/+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T07:05:31Z"
    mac: ENC[AES256_GCM,data:FXP677v9Xfb4fXG3LfXyeplQxmoE5nAcju9P5c/6PoiZh1qK4WsUUt/UqwkhFLdkq6hbO99KeWUUKILh3+4JvklGXG5Pp3EjS0rCxyTZooizyyLipsYh/NQBd+KGBRrD4FlFK5/JPpbQkpEIOK1nUqwVMNhywRpqExQD3EDYHQE=,iv:REcWu/YLQtCpR3MW0wmMIz3EUKXA+ekjHQzqaFz9eSU=,tag:vKW1X4FFP7hqiXVVdRRE5w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
