---
apiVersion: v2
name: jdownloader
version: 1.0
annotations:
  homelab/description: "jDownloader 2 is a free, open-source download manager."
  homelab/url: "https://github.com/jlesage/docker-jdownloader-2"
dependencies:
  - name: app-template
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 5.0.1
