app-template:
    ingress:
        jdownloader:
            enabled: ENC[AES256_GCM,data:avQV+w==,iv:/sc+ovnbdIZXOlRF3TGUxmngHd/6oF28F8c1eweKOro=,tag:9s9VzmFjdjubslBk9btoNw==,type:bool]
            annotations:
                cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:3ZDYYADsfcWUvo5748H93A==,iv:pgPo4OSt9Y+F8v5eaH7agqbeVe69JG0WDHFvCk5M9JY=,tag:ggNxYnC+nMtsEVL8drYr3A==,type:str]
                gethomepage.dev/enabled: ENC[AES256_GCM,data:wg0y9w==,iv:ywTAaJacAdEZj1ibjdJWJMhreeCGHBwEJ7C0eUhYBB4=,tag:HJBK8hCZsaH1nVuRD5EHTA==,type:str]
                gethomepage.dev/name: ENC[AES256_GCM,data:gxktvtxqMARz8tbGyg==,iv:3Zj7lVD+nnDMywLB3Eszpyh8YxmYs0KpeuRldypjLbA=,tag:GkO2UxCDhWW0kvuyVW7uWg==,type:str]
                gethomepage.dev/description: ENC[AES256_GCM,data:5Wb+ojyGTD31VA7iF/RaEQ==,iv:qXKM4GwsULXh02E1jlIqRYjwHElfrfLrVflmCt8t9aA=,tag:+qV343jR3Zh5b+qFhjLBoQ==,type:str]
                gethomepage.dev/group: ENC[AES256_GCM,data:AKyx7TLrPxl6whMsaKU=,iv:S4Bm+Pdn1uFGcm2dTyclJ61Egzc0XunOrrJyZFEiwwo=,tag:T3tttvmvCmj6G8cz6+3CUg==,type:str]
                gethomepage.dev/icon: ENC[AES256_GCM,data:0C0IY9FAagjRkM4VvGBwtDeN,iv:0w8gFJUqV+1/PczMimGEEBe7XgG0HYuojSNXpedOc7s=,tag:lfddrGQPRvF7f5C+uhmwSQ==,type:str]
            hosts:
                - host: ENC[AES256_GCM,data:BklKrMbAp/OJzVC5rhrooekor943GJI=,iv:h4xfwG379Z8+qPnnM0AJq3FFaNdbQxs4vkV6Ot+8fgo=,tag:bnKe2+Q/RFwzTCrwZKR/9g==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:tg==,iv:yY6va/i3WAVZrEpzywuo2GE4ecXYW+mgqHLXT0oYKDs=,tag:DMorJVIW3IVfHKnfXF1oTw==,type:str]
                      pathType: ENC[AES256_GCM,data:pRe7Q3lJ,iv:5Q7egVZw6v/Jzp3j1lppTVx2G37pNzDMTgOU2zR8o2M=,tag:o28nK7zUQGicwPU9EqFc5A==,type:str]
                      service:
                        identifier: ENC[AES256_GCM,data:KgQL2xpRkZjPph8=,iv:lZJVxpYX8GgMUp+YXklVU0ntjBuCdKVBYCf4SpBqivI=,tag:bP60g7WKT0itEeL7BsjSmw==,type:str]
                        port: ENC[AES256_GCM,data:e9DfIw==,iv:yG178pSvEDGz24RA+IJFRpOSH7p2yfhDH71/VIS6txM=,tag:05v/DdWdQEt8T+HKZ7pi8w==,type:str]
            tls:
                - secretName: ENC[AES256_GCM,data:i4wdO314UoMPP0LXiEoOtbZ2MRY=,iv:E+yyeehlWN8zOWR0kvtAGdOrA+jiSXAxsa0woreZUic=,tag:fbSDoV1/HklmnA45RfvgJg==,type:str]
                  hosts:
                    - ENC[AES256_GCM,data:k7x/NuTGLhLXEwGxUUN0+XrEkd5AtKE=,iv:1p/Hm/lDpDCHpHeSJ2z71lCaiQfk6vsp+PAS3ENizJk=,tag:T0p6XyYmNLLlXM2EQn+1Sg==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZXlaU0ZXVEgvK1lySUlH
            bGxBV0Q1S3E0Y0NHRk1MZlhuamVFRk1NeVZNCmdjaVZpODd1K0tuNzUzT1lxb0hN
            dFJ3eCtuWUl4alZDaEFxRnRST1lWRlEKLS0tIDdHWUxJaHFjbHdQLy9RVExwcUxM
            V0oza1dvdFNoRWZ5ZmhUVE95UFI5ZUEK+Vfv+SMnCMED1GXWMnMOL0baFSiksOGc
            TlXXAvr62A/26ZiLpEqC/+gSVz0imdTc7XuVbzc6igw2ifCHoGXWBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T18:47:45Z"
    mac: ENC[AES256_GCM,data:Rih5bFHRx8DtFFaaixbc6bAUvje9aDPZZSq9C7MlYhqIHF1G3juj90dEijbKZDx3h4rUnPs+/VKfkXe33butI8j9YhaaM0Kd+iiIXtVm4Qa47MfYAs8+hQ49n6pSXDmAxKzGDxosuilH7hTwD+nm5hPVHRxKno0WqBcuzn/tKKY=,iv:BrpWjTJJcIw7qyE5Rl96sv2XYXhVDG1lKYpPHIeYcek=,tag:HP6UKSnTt64PzJbFldNcaA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
