app-template:
    ingress:
        docuseal:
            enabled: ENC[AES256_GCM,data:OcQ4QA==,iv:ntDy1tmTjKrYJJRM+7G7i5sCNUkuMGyYCOcK7NNn/tw=,tag:0FE9FSQvVn87ksqvChwYOw==,type:bool]
            annotations:
                cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:5/IGg6cGryaogiy3WSuLKQ==,iv:g8J+PQDzpAIEBdhTo8qBzQEiKPow3w0qlvZL+cJ62UM=,tag:ie3jLQt+at1J4OYnxdriVw==,type:str]
                gethomepage.dev/name: ENC[AES256_GCM,data:am+DLT0EidBgr3lMx84o5AHpug==,iv:sySlr1OpigaYRTHvui1mamTnUuTLha7z7bnfTLQn+eI=,tag:XcNI5525+AIAbq3qo7TxJA==,type:str]
                gethomepage.dev/description: ENC[AES256_GCM,data:zX4RYtJ06+T9ljUTGoT0NefZDe70nJIuKGON,iv:FHwsNXQzJlLBVOIxSh5fBY4BmdihIk/OmGMO4n1lz18=,tag:mSc6vtzDEYoCUgAI+iI67g==,type:str]
                gethomepage.dev/enabled: ENC[AES256_GCM,data:rK7gEA==,iv:Di5iEddJr2FHqv06/s8GUkRuWi37hINbMGuMtANCOwk=,tag:YKftWhv5PST5z+j+23ET6w==,type:str]
                gethomepage.dev/group: ENC[AES256_GCM,data:AvjQAdEp5+Xx,iv:Lcczg5UurMb6rhxUoroWYLOdUateqQULVu1RW2QDHq8=,tag:0oEY2L47AwC2KXv9twBWsg==,type:str]
                gethomepage.dev/icon: ENC[AES256_GCM,data:XVAG780MDuGLmbE7Gyvl,iv:Lk7MfV4rLuR8usLZfV3Avx99buq8bQHAHz8JLoQbE48=,tag:spcQ5IXdmrId29RGW8hJlA==,type:str]
                gethomepage.dev/pod-selector: ""
                traefik.ingress.kubernetes.io/router.middlewares: ENC[AES256_GCM,data:XxEjWoe74IuSiIPBwKlfpD017UnmFJwXvgZxwgA=,iv:yWVF98ss9SzBw76H9gFixHHXuHaFqR80QnQq3QikagM=,tag:K2/f98JSA0CT+DH4DSHQWw==,type:str]
                gethomepage.dev/weight: ENC[AES256_GCM,data:cA==,iv:RMIGdZHeKIS6/U/hXAVVO+dQDkX/dLxsMPmkjKxByx4=,tag:r3BkP97zzbAWD8xSauNT7g==,type:str]
            hosts:
                - host: ENC[AES256_GCM,data:OD5n88hSXnwKjeiO2pWuQr7A,iv:JPO7Ygeg4aWLz721rBH8bz/jJqzZ3Q1gNPKhtHYLHN0=,tag:TGUaq7TTEzCC6x+69TmphQ==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:VA==,iv:tOvPwU0FVUnXZHGaAAPSx0Q6BE5KYZUmpCSuzTaMFls=,tag:k2I91K4bWAdARPMbTbnD5g==,type:str]
                      pathType: ENC[AES256_GCM,data:VzUd1sHd,iv:XKhCx5P6FXi3R2HWVy2iSQMPuv02SkhyAE/gFUaot1g=,tag:rH+W2y30KVoETJMSoMnVcQ==,type:str]
                      service:
                        identifier: ENC[AES256_GCM,data:3qMadilDVBQ=,iv:3+XV/DAgvg/ok2zkX76sW9DSGOsuvLmhjWqUShTBTsU=,tag:1NcoYfZF62Vv/TIVdo/WvQ==,type:str]
                        port: ENC[AES256_GCM,data:r/YqKQ==,iv:mHoeI+9U4VB1VCrB5yByv3/i5OgXBUSswAuqgJu7uAw=,tag:j0Z0nn3BHn3EXXk3xl2xqQ==,type:str]
            tls:
                - secretName: ENC[AES256_GCM,data:QKG5Qi/ZUpVUUKpSzviqEuiRw6g=,iv:DPsvqZW40vH1hAECw1NTyrc/VoV+kh3fd4aoEVUgIRE=,tag:BQ0nxGzQuzOfbwFmd0Fusw==,type:str]
                  hosts:
                    - ENC[AES256_GCM,data:0HgGplqr308IH2Bk6R7td/dm,iv:z+vpsHgAlnBcvyo8JYQ+S85yOcqtYtvid7E7z+JAUf0=,tag:xE7hzwm5gJSw1rvcpdoB4Q==,type:str]
    controllers:
        docuseal:
            containers:
                docuseal:
                    env:
                        DATABASE_URL: ENC[AES256_GCM,data:TpyvXG40dGNhACPVhKgXJDWfCjg6OEa7eMgzteHNeS+Z+xPGJ76r8bkr1GwhgIJZCRAhX2OETYAG44UFgqCC3k7hZVhkf3Gwl/lgHWmwlTnrtW4v+MEzE1o=,iv:IE9CEWpM98LnwCmMvaUNKvnQdBlW7eRMJ2xrHDnKkHQ=,tag:54FfmYNzeW00CvM6qiT6IQ==,type:str]
        postgres:
            containers:
                postgres:
                    env:
                        POSTGRES_PASSWORD: ENC[AES256_GCM,data:6cJ8yQ3pEo5MrBA0CKAq0+V27BZItZbLn5yBbP1ZWr0=,iv:jpqzi5y8Rt3fEmrfbfpM7PmuDzpZzZfpz63Bkex8ODE=,tag:prIDkpR/cQMZut7Feq6W6w==,type:str]
                        POSTGRES_USER: ENC[AES256_GCM,data:11gWmLBN310=,iv:r9NNVLrAJ5pBsg9w2CbOknCzKCPjVdaSrq+vB1yLcJY=,tag:qC+OiyQJSrQZB9hpRaNtzQ==,type:str]
                        POSTGRES_DB: ENC[AES256_GCM,data:77EQFzKfXvs=,iv:5AM3zO/iwMp2YF0fqupd9IDflrzTzSAm7Lnb15YHyRw=,tag:EchZjC/g4CVkI7PY9o1Pzw==,type:str]
                        PGDATA: ENC[AES256_GCM,data:QivG50ldwXrph1xekN2AQ6Ic672o2sITnniB39ioqvg=,iv:pyXJrvvsEnV8N6aTA7hj/6B5iVuynZZMi6d5ic+E8/I=,tag:02ICecOWhoKC1DsiYk6WUA==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSnRtRy9jVFpvaFpDZEti
            WC9HOWNmaFM2anh0eWNBNUFmTm5WRGppSzE4CkUwOHd0WWRvRW1uQlZGZzhaeDZk
            WEh6d2kzUWVOaktqaWR2MERXSFlpRTgKLS0tIDFUSWNCNjlWb0tLNXpuVkpzTWUx
            NTZDRXFNSkF3QzU2WW1YMEF4SE5DUjQKav6EPq5e/yWkKNxpfjNN5cnVi4BC9IQv
            dPML5a/P1rbXR7OVzb4Z9on+NJ4KAZs8NEyHJclEKE965L3pItO5WA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T23:05:09Z"
    mac: ENC[AES256_GCM,data:jsUGMCCQN/L9dmf75bowQwbsCHKgOLShJ5o6GqbYkb6nmqBnS0L1dai4TkgyjBZ//QAavmvop1QTPAOwuvL0eXXkdRNI0H78qt0rEXv84vgBrgDTGU9c6qX8eCHj2PBzJFg/JcuRQ34k79sL1B2jPk5nncpUzbjuQPMHxjZh9P4=,iv:rxPV0Pj9kvWYRweewPO/1780b4EvJZpG6SKz6npGz9A=,tag:uGafRkwCsxxJIo+24F48uA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
