app-template:
    ingress:
        docuseal:
            enabled: ENC[AES256_GCM,data:vWkMyw==,iv:Y9GAVB1mN2478VRKkXharbgC2Ycdd4b0jeI6TMm/Uew=,tag:QFXXq7MqfmS+TEavwaKnbA==,type:bool]
            annotations:
                cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:Z0TBaCnRLxxvRfaF+U2Abg==,iv:C9yc6TcVmFFVSLNIvSNuxVOcehseFyM/SC9Jor+Kl80=,tag:hHJaESLhtV73+zraDRypXw==,type:str]
                gethomepage.dev/name: ENC[AES256_GCM,data:sdW4CuyPzgktEhtdwgAMG1uMfA==,iv:V3FSu4cqW8adBpHKBZ6LwmuMUPxq7lvc2An7RCVPDFI=,tag:8HVmKUOB9PwWElr6Kt4Dqg==,type:str]
                gethomepage.dev/description: ENC[AES256_GCM,data:R8Qh4JwJCVRZDYlU4dC2OIAYgq54+YWEegx+,iv:tWLiqP6s0JbUpUgndnrYZvT3q8SyPf7Cko4JyouVwMs=,tag:fYeN6X8jOglDMsFz2Kr4YA==,type:str]
                gethomepage.dev/enabled: ENC[AES256_GCM,data:fqmfSQ==,iv:2UzYTYimVx9oH9dlAe4cutMbfg+paBHUdhtgSy+Q0oI=,tag:FRPz1Ogo8a3NEIZYZo8E5w==,type:str]
                gethomepage.dev/group: ENC[AES256_GCM,data:2TyebwesSOzg,iv:XzIXLy8XW0ozuG3z41gwQcn8PqViPK0VwzGsMaRwqKM=,tag:36CWOyMWmLGS0BHBU/VHHQ==,type:str]
                gethomepage.dev/icon: ENC[AES256_GCM,data:0ck8527jbVmOQwYdw6az,iv:oVvKt/dhaZkfeNoKW2nH000OklJ4UR5WniK1JGNAMAg=,tag:KFU0GUqOkK/iCJ5LZvK7wQ==,type:str]
                gethomepage.dev/pod-selector: ""
                gethomepage.dev/weight: ENC[AES256_GCM,data:sA==,iv:UpF0P7o0VMjdAgYWXICu611zMDkOlR8LfDrVVlaOKzw=,tag:21IsKdSK5yuPp4S5ePH5mA==,type:str]
            hosts:
                - host: ENC[AES256_GCM,data:AZ5wk8Oolimy24b2Ga8UHsIf,iv:asjSJFVleXt7T7oLPTurvB7cYu6eXUyu83A3b0XFGcA=,tag:g6xvMcx/jKevwvIorLvGNw==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:eg==,iv:I6ffHzCHY3uFubHPKm6O+CgdJw9imSMwVAPr/NPj82o=,tag:eaU61dr8QiuKkKGYxJ5tGg==,type:str]
                      pathType: ENC[AES256_GCM,data:msUS54HU,iv:MjJMcj5GxOcxOysaK9aBT5h/eHDwtUwmem6jp8XJIpg=,tag:i4k9A+B1yoNiWa9hqrPJEQ==,type:str]
                      service:
                        identifier: ENC[AES256_GCM,data:CkH4UJe5IDs=,iv:WymAgj5XXe5E9v9FS4mEa6cr6C1pZQBw/xRH4I/7knI=,tag:1altuTPDc5GG/Tn27rEuFQ==,type:str]
                        port: ENC[AES256_GCM,data:G87vhw==,iv:wK3RMAaWf/BhtYDXc2GjEGfQqAr5FINcMTL+8X5q/LY=,tag:I2zdyc+fXW2EQ5cwj8w2Yw==,type:str]
            tls:
                - secretName: ENC[AES256_GCM,data:3Zo+XhoJJ4mE6i/zm7vLo4gguM4=,iv:Vaic+p6HyWHXoysPl1gf1acLr/zHUz1oNzVi7PUw88c=,tag:7Aq8kODuvKPyHhb8C4mgLQ==,type:str]
                  hosts:
                    - ENC[AES256_GCM,data:hAtmXmMStsShWGfe21oCaNyu,iv:GQsCVTU0tF8tjl9NpqDdw4dXfN+8kyXuRN7bjgw+JAs=,tag:ZIwHV1mMcmo5yrW/yVM37Q==,type:str]
    controllers:
        docuseal:
            containers:
                docuseal:
                    env:
                        DATABASE_URL: ENC[AES256_GCM,data:7TlpOG4HuK3ZaWRKw2RNwB7gAJrZGELA60/PWG/3k4eT0+kzTRuEokI0m0Hp5Wijou2ULh0VkPdjLyUb6PqAZLJG7nxm/WGLaLg2w1YExG2mS9d0Gu0YCGI=,iv:XaIxPl7kMP0yT7FXqcdGiIYMX+7fU++IVA3eUPvG60k=,tag:HYfrLKLDyMGrbL/1A5SDMg==,type:str]
        postgres:
            containers:
                postgres:
                    env:
                        POSTGRES_PASSWORD: ENC[AES256_GCM,data:ilyJajIqxNiP510iXPLOvUiTnPYd0JGUqpGJ1m33JHw=,iv:edQRJsWQUyq8+TdlYlvE0xIMFosMnnENWRfUoFqRuGk=,tag:Vmng1/wNHd77TIUI5gXRlA==,type:str]
                        POSTGRES_USER: ENC[AES256_GCM,data:G3rA6KdlYXs=,iv:W5KCO2bUKm+jR6vKvkFu7Hj5u7uAQZoSj8IENgaa0vI=,tag:i2FbMmuqD3jSyRJmlKC+gg==,type:str]
                        POSTGRES_DB: ENC[AES256_GCM,data:Ip5hZxVB2xk=,iv:9UCH1IzUabLceMUlrmmveN3rTO1XwG3tv+aUzmteLS8=,tag:Nl51zcnDBDx5JRdwrPQjlQ==,type:str]
                        PGDATA: ENC[AES256_GCM,data:iXSoPubWx13pi7W8XhOSwaAHu5CJkfKsLy7Sn+KK1X4=,iv:728ZYNChwD5VAwDAH3p/fvVn81WjxoAGtL+FzVWVzig=,tag:h1X8zmo5OXN9Kcj4v5CsTQ==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTGxZWGVtZGt0SmlJRTZn
            RkFBeFhVM29VNVJ4YVF1WVhicXZjb2I5ZXg4CkEyTE9SeUhnY01aNEV0WWVhazJY
            T1VpWUxaZ0FRcEdkQ3lKTGhLOGh6TlUKLS0tIHNTSzhObUdkR21vNlFsUVFGcmhT
            eDEvdnM0NURxaUxuQzBLNktsVnZPc2cKs+ZIX11Z+VzxL+zsE4QLuOFDtGUW6b20
            /HCUfWkOsldLKklB8xosXpsmcCT2Ud4v1ZrHfb5rBuwhtJyWBKgv4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-29T21:34:58Z"
    mac: ENC[AES256_GCM,data:VriRdlv2UeC0VQVmF5y0aQxvR8098cwDtkGPwOwp2h6ABvMpcbGrOvFAVsgvG7k6WpnxhBCAJLdft1SrxuTk+2fllSUXdwqJDsVdU+ET7mX2WHxc9pyhZLgbjvQS7VB9oCdr//Uuimd7MpgclRjLOohUVUKzAx1vCWMIsRgFiXs=,iv:wSbqvEIA2VWtIgsOsOklvfS6Ahw/qAgra+f3khke9QI=,tag:Qj7b7tNiLsVBYwdRB//RQQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
