app-template:
    ingress:
        docuseal:
            enabled: ENC[AES256_GCM,data:shJ1rg==,iv:u8kUXgVR3GRm2LJm1i0pHpMaDWaB78zGbjlsBNW0T+o=,tag:wXOST+azaAGQOqQU5mGVMg==,type:bool]
            annotations:
                cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:nYMIwis1YleP+GLz8O50kA==,iv:+EcAAo5uOVupSN8osKehebd+bCaQ7P2yfBgCR8sRnYM=,tag:NZ52c1eNawjugiL4zia7iA==,type:str]
                gethomepage.dev/name: ENC[AES256_GCM,data:Wxu1UI0w4Xw60uDpu1rb3SWicA==,iv:X7eExf+dXaiDdBlhD4/CDf/N2HVhHil3Rpm0iCfgq5w=,tag:v7fAAyZHJfqUboVHSDM/PA==,type:str]
                gethomepage.dev/description: ENC[AES256_GCM,data:TOZiMznqCZNfBI+fC9AtB1ZeweUZGfq2GmTO,iv:lQYJ+I7QE8w5grd595iEi6+NwcMvioUYZO6Kfs7dEOw=,tag:I/deRN8a9TA4GdnXVWi1gw==,type:str]
                gethomepage.dev/enabled: ENC[AES256_GCM,data:iQIxYw==,iv:7PR81yLszuEFJoSD9fmM3t9iFb3z3HeegKkfxTcGfCE=,tag:hnwacQ3vqjyeLmrsJ8GRMg==,type:str]
                gethomepage.dev/group: ENC[AES256_GCM,data:o/FSEkP6+DIT,iv:Q5qB2xK4LnedgKOCNID7/0nx134rY1PBSfJkRmNPFg0=,tag:6l9vICJW+feto0+pEtERJQ==,type:str]
                gethomepage.dev/icon: ENC[AES256_GCM,data:829fDez0VZWaw43Suxft,iv:Qk7LJtZcTEFDqFpPpobUO5CWfs3LcCHHAODwiJDTxMM=,tag:R4t/BUKQcjvr9Ilr+682Dw==,type:str]
                gethomepage.dev/pod-selector: ""
                gethomepage.dev/weight: ENC[AES256_GCM,data:zg==,iv:ZWvQtjC0/xgyWpx6OlmZ0gkADoShcu755nZLhHomkrM=,tag:YU+gNq/q7k19CV1TiJlE7g==,type:str]
            hosts:
                - host: ENC[AES256_GCM,data:j+h7llqPmZ6A2SlHPDw/tzbp,iv:w4+/RTO2DKLxaUdAFA5LdXt5JEitNeGTVRg9tyswy/w=,tag:GnVAzh72MwPniZXonYe4rw==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:8Q==,iv:JAiuSmfzx3ibrUMd9EUOuQCA1JbGCXK4yNYsjrgkhaE=,tag:r/+DZWlMhg8K3RT5OOjS5g==,type:str]
                      pathType: ENC[AES256_GCM,data:OkXz0wtf,iv:+t7LxId4DjB/qtctwfNyTeA/fPSRclD/sqcxaKxwEuk=,tag:i+ucs+EUNWQq2zGQLqiijQ==,type:str]
                      service:
                        identifier: ENC[AES256_GCM,data:DQ1TaqaHLJY=,iv:rBIF9FvJpWxvS8zd3ntdD2NEV33uzxBPZW6iLNHXUKQ=,tag:VV50KXdacH1CW7ppSbM66Q==,type:str]
                        port: ENC[AES256_GCM,data:6+cwjg==,iv:MMtKIWbt0aq5qBSQehA8LTlc6a4s6cjb5Jx+vOnn8sM=,tag:/HkugA5vzPww9kG26csjSA==,type:str]
            tls:
                - secretName: ENC[AES256_GCM,data:jFQcugmWgLZyvAO/Y+MulSlNcTc=,iv:haRZzoLa0gEENJRyKoVi0GAPnLMwuiUZcB71zLMQ06s=,tag:qZJfH7RxGN8wDBS6lr3Qsg==,type:str]
                  hosts:
                    - ENC[AES256_GCM,data:6U8UIvADbxwUzpv4lFw74Lsg,iv:hlV7CbEqLa2DIuPDRnY9IH1g2OLrArvNicoySKJqzLo=,tag:MK3snztAZI7s9BxZozpoew==,type:str]
    controllers:
        docuseal:
            containers:
                docuseal:
                    env:
                        DATABASE_URL: ENC[AES256_GCM,data:d2c3jdRda22DUQVGCS2mLUAV/KxrzbpvNOaG2rwEGLX3PP1LiSj78YxmE2aeS/0e29K6GSlvM3qPUCZgdeePIemnYE4KAPvT/YfYBnI6eojJofUM2Z83zeM=,iv:r3NGdP4L169l8g37vvJXzM/PVM1HVX778ytBPz078ZI=,tag:mY6XwcfBU64MOtsNXPBj2g==,type:str]
        postgres:
            containers:
                postgres:
                    env:
                        POSTGRES_PASSWORD: ENC[AES256_GCM,data:wgX9TeLMf/EcVcCGnjPDoTUGeeOK4+HGqwpJRbs8rFI=,iv:rtZJzDgQsBFiHWtLQrhl6e4lszZ4mdTjKMwnDlTqtUs=,tag:QwQgpxlCvtf0QN5tjnXYnA==,type:str]
                        POSTGRES_USER: ENC[AES256_GCM,data:JmdLKG3QI3I=,iv:LeKnnvyfRgTliUOdWOgCfMsvRqpRu3iIWAoIHTXwRZw=,tag:EaTHWOxOEFxcvAy4Cy4EkA==,type:str]
                        POSTGRES_DB: ENC[AES256_GCM,data:Jl0w0DF2FUY=,iv:zVGgsLlKRZu7zXNTnasEJoMVov3DFq+I/65eaSKi+gY=,tag:eazXYpzQvIO/V1CdDP5jbw==,type:str]
                        PGDATA: ENC[AES256_GCM,data:/+gId84y94J23K7WRf4gQevGdkJOxK7RSGWg0bqRLHM=,iv:Md4Xp8l6Kw5G+wjw1efPlPh9mdlAnzZpBdoEYa436No=,tag:rWVzfmHt7w6MjNTmq5sH8A==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvNW5SSXlnTldBSG9PcEtZ
            ZmJqOWhuMlBSM3Y2THZCQ3ZoODdTYUhmTVdvCkw4N1RZalZHL1BqcEhZL29QZHVk
            c0JveTU2ZXpKNzhhS2Y5UEkzY0c5TTgKLS0tIHZHZE9HTEVQYnFoS3lLM0JTbjha
            QU4zSlI3WENUM2djZGFXc0NnQXR0dmcKaQHVUesfetJ3xmgwFGSypv+j87hwGBOn
            oTdpGlkBlDG7B9Rm0HDWa2J/u92PWjU+l0zNB24kdYaFNnye9pdkhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T23:09:27Z"
    mac: ENC[AES256_GCM,data:LNQNDd+JYTJHDnuWeeCiGqiHsHBrizgphm85+NYLdqwCBhzkogfMIyQq7+Bsj+wDAQmZvdZwBIOFYcRnn+T0+rJv8H+bEUB58a5B4YUqjwxpS1+yFawxA/7q1lSeXB3Ike2H54rpRt3xbV8FXx/LzA5mqYlM/uqFVIND+KM7I8U=,iv:WGNcKJFvoTigVZ8aTDvD04qUviIWS10VHpQjG03w4ZY=,tag:oZHFqDgnGz1pq/59xWJGTQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
