plex-media-server:
    ingress:
        annotations:
            gethomepage.dev/widget.type: ENC[AES256_GCM,data:HFXmzA==,iv:LPdg4gAyX1Hs9xwnz9pLXk1Mqxa3LaetwclMRNUtd+I=,tag:8oQjZ7flCEzM23TvGGUAEQ==,type:str]
            gethomepage.dev/widget.url: ENC[AES256_GCM,data:DfmM9qdtu/zQpo3HFFX4mKUW8D9VO6Pgmg==,iv:QUr+g/FS+1ZJgHFcG3n8MJLUbBMTfm7mVJuMxrJE/Gs=,tag:OjrHsVZkCV0sojAG87ERGw==,type:str]
            gethomepage.dev/widget.key: ENC[AES256_GCM,data:LHtCMHBickI8Kd/VytcIgTje480=,iv:/HJ6D2uHzfjpPPDmkfd7wH1VOEiupYkgLVapI4+nfdg=,tag:vk92aUCptlyV7z2YuWTLZA==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWEEvbE5HQ255d003MU9C
            aTRSVVBIL29XRkhRc3VlTml1NUNDL3gzUFRzCkpPMWQ2ZzlENG16K0RXdkNudHAx
            MnlhSmhLVEVEWURqNnpvZmFIVGdSMmMKLS0tIHVpL1pUUzFKeEphUEVzaGVHZXJ5
            SEEwM1pEZ01pTFNWRHNwT24xL0lzOTAKfXt9pHICfkmslrGeBYA//NAW7mLraiki
            jzu0n6G0fQL+9M0c8QvYtRLNhQr4w0RG9KxGN5kODrU6HcVoCsb5/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T00:58:48Z"
    mac: ENC[AES256_GCM,data:P0Fd1nj6UWYDXbxMeik5EMmkBkJW4uIq+VaedpYx20NJXiuzi2myNhewZ6+EQe4IVjIS9OrWyjye3r4SyQrZdy9P+/Z7x9X/EVu3mpV1tvEjGqVPEyyvw2O5X6xQbJW2skZOkY1K4/cSpk/yBCjU8XMuUymww87UJt6yurh2ZUs=,iv:hM/x8XEk1QI5H0v5d0prfStMFHWtOzjVZ3kRqYkJYOU=,tag:ysuhUX3KIw+DVlYMIwxFRg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
