app-template:
    controllers:
        traefik-manager:
            containers:
                traefik-manager:
                    env:
                        ADMIN_PASSWORD: ENC[AES256_GCM,data:WpDTL458Kzo8A3hJWkXijkK8HnW7Tqdq4CCVeQKet49SnKeGgW4ctpLYuzQ=,iv:gmqedX2cf8iiH4NORINsiQGhQu+7wAHDn6MI+36j5Ig=,tag:DRj5Y2jUnQaWRxAQYsBXBA==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ZXE5UU5mZHRiOWlpMHJB
            RHBUMVk2Z1VkbFhkem1nOVZOTVJzbWE5TEE4CmtxemY1NVVDNlUzQXdrcExGMXRy
            RmdBV0w5b0F6VllTcG81bzdOWlZCVEkKLS0tIFZEeTJtMFI5MVAvTmw3WnVDNzgr
            WnVDZ3dMdXRvRFkreisyamtLWW00K0UKJsAKjK4qo47HSt2rL/3f58u8Sv8kR56Z
            A/0Y0YUac21ouQNcOcmAm4iDRWCMta1i4VStsNuAWPG+DNUv3lZ6ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T20:42:34Z"
    mac: ENC[AES256_GCM,data:kolMknlrHXekVY6dZuQ/RZKtzXOyM6E4GwnX44ua2o9K6TRVHDecb0QcbFqGO75BGM0wGE77nC7THMPJb6s7Sn40frsQ64n3t40cEhWAeScx2OVUzjnirxhHZ5LHH6V3rYrcP7itfm6o71xnNRbkexXLCl5bv4cTh4YZSDV614I=,iv:37ZW6irZqcMuf3M5kj92PGI8gphngSxahPFcDFz7UuQ=,tag:zYj36+DeoDLQtIlQ/p96Rg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
