open-webui:
    ollamaUrls:
        - ENC[AES256_GCM,data:+i6cM0AqEQzp6xs6eV2nziOpBP0=,iv:xS0Z+OxHojJKIQMCkcnUtJD8HwdWCn2aT2q7qxdihvU=,tag:ZC/FYcyorKOknS4zl5CqtQ==,type:comment]
    ingress:
        enabled: ENC[AES256_GCM,data:rTRRBA==,iv:zXKTGqGOGaRg6JL7VLansOO3K+yM+/3ZBiZnv1Dnn8E=,tag:gnl7IkCtGnAvqfmzA/HctA==,type:bool]
        annotations:
            cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:PcB4nysdn08vYS1Jmq5MAw==,iv:KGdje0cJH52kCoggpmyVtZ3toJMUIyK2wnPiDP9mD/0=,tag:Xd48wvpg4xnKx3yAslhfdw==,type:str]
            gethomepage.dev/name: ENC[AES256_GCM,data:mjV3oNVNGCOQLg==,iv:hsA6yVAdtvi+QZu1TGmSLLk6burIU1MbJdBp1Pl29wM=,tag:jgQv9BM7xE6DrKKb3Sz5yA==,type:str]
            gethomepage.dev/description: ENC[AES256_GCM,data:KpwBQTpzpKT/nSc=,iv:4qFcCn2yN9FKY+dkzRahA4ScwRk3Rlb9q5+w8rGjI0U=,tag:i9Zt/mDXqhZ8esBwegsQCA==,type:str]
            gethomepage.dev/enabled: ENC[AES256_GCM,data:h4vBOg==,iv:TkH5WBg+u3tKr8FMMNbGUCU+4stGNbciwAetyZGXp4A=,tag:YLJaOQMB2PwHYQaw2GsOtQ==,type:str]
            gethomepage.dev/group: ENC[AES256_GCM,data:hX8=,iv:DFoZ2nFKoL2KAeM3cfhVUXT24fmeYt2rWvg9XIXgy2E=,tag:1Q6uAGoqqkOVP1mME/gMTw==,type:str]
            gethomepage.dev/icon: ENC[AES256_GCM,data:pHHVRFEmYymPFR6H8EwJTjo=,iv:Rt7psHg9t4H2STzc/KoUAjYpcLMTOn3TsE130l+LcHQ=,tag:4DbYb41jd7uIFENrh8h32w==,type:str]
        host: ENC[AES256_GCM,data:6YBmCqN2AwC0d3w95zSISCTq7+QJOw==,iv:bXpoBq8YeR9ipz9z0vsOusrXzh9SDWtsGU9TNIj+PbQ=,tag:+sEhE2/bK6qCEWjVgvRHgQ==,type:str]
        tls: ENC[AES256_GCM,data:LHAV4Q==,iv:lz6AJU1C5uVSHTUGE957rUgOrJXW6H6x4Oq0TJYOj/8=,tag:Jf+JLdvm6bHuU0e5ahjbeQ==,type:bool]
    enableOpenaiApi: ENC[AES256_GCM,data:0zTfKA==,iv:vCtL3JbI6VgsU8kNcAyJKQGjA+emWpn1Xb0+D+K+v90=,tag:7oKEIJk5yJbL8pymFrQL3Q==,type:bool]
    oidc:
        enabled: ENC[AES256_GCM,data:poQPOw==,iv:D3ooBpMO9B4b2NIp37rGx4fa1Vd6Hh4fRC6u4ontiA8=,tag:UfM+ySYmn8aFiN8HU7v8Yg==,type:bool]
        clientId: ENC[AES256_GCM,data:13WXATVt8GatwksP9bHfqbA9MjUlHO6rhvXVjywn+Sybslt9,iv:ghBMJ5sKjRzNb02xatmMrUmr/8GHpk7hBglyHXGHzAU=,tag:uZOGNXnysKewUTCeBPqfAA==,type:str]
        clientSecret: ENC[AES256_GCM,data:+H86k1OC1kdeZwFdDsM43qR8Tj7tOovN4wvDc/l3xOU=,iv:ymsjAJ6fKXHllf3t6ndRk+s206KbIs5Yg1JPe+PGABg=,tag:m6UyKU8zhS1N8r0slTounw==,type:str]
        providerUrl: ENC[AES256_GCM,data:yerqAcQf5ceJ4Es7FmsRjvHWsHz5bFu245a2kfhBHTY0mV5EtWEadeHIHHU5XGvRraz/f4I70Fk5FWQ=,iv:0sGsUMel296Vpip15fJqfVo4TmIWLk5kQv6u0YnqjLs=,tag:TMhKjUbK1A99Lk2d+F7A2g==,type:str]
        providerName: ENC[AES256_GCM,data:078pvgs7z42L,iv:eEgou37MRcBL1ROt3wUZnr6qiu4nxDGlTLxitq5q/wY=,tag:hsBrQgPzMycrMrI1xbcnnw==,type:str]
        scopes: ENC[AES256_GCM,data:nkojqSTwT0z57inrPQe5YKD0xAg=,iv:wdroK60J9uPZ1Tgg/ebHXuMA1cARTWcD4oCXRC1siQo=,tag:MnUDPTE0+MDPdF7+Cq2bVQ==,type:str]
    extraEnvVars:
        - name: ENC[AES256_GCM,data:FshUCyUBvCEwZrJvzN4khDCctA==,iv:ZIJ4JS9/L8idGLSSAXsc3i2XzdysGDB3d7IVtm63e6E=,tag:7NqkIBQjiDHee1SmWOvVdg==,type:str]
          value: ENC[AES256_GCM,data:6i3LeA==,iv:atnaOwzpP36VHZitIl/3fQcuSw/IVodtlbroMXf0HVg=,tag:1OUX8X/+sHQCUvGTO0gc2Q==,type:str]
        - name: ENC[AES256_GCM,data:0AXxlGKN0a+W,iv:kRSjmRmpRUAWCHDuAH6L0lQYP2sZETxAhX+rrlQ+lQw=,tag:nFv65D1XqENYAx0a1bX8yA==,type:str]
          value: ENC[AES256_GCM,data:rpepF9qj+dxiJjp7jBMUfYa7CeH/X2ABn8MVP3i4,iv:NVx+W5wUDkr+BKsdepRjb/9WFaU/hV2WOlv2DOiBCq8=,tag:c0yCKW9KfCD4b92WL+/ueA==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyYldHVU51dDcxQnE0WWZV
            VUQzQ2kzU05pS2l4d3QvZzRXRkhXYlJWY21VCjF4Qlp2c0huU0pSaGIzZ25CQUdl
            Q0pKWGNOdGxPZHdteUJCL2RML3VLZ2MKLS0tIEhxVW5WbnQycThlTDdJUHhyVVkz
            dFhDZ3EzK2NRNVhoM04rT0ttNEVFcmsKOA4JwFEtM62EEJ0K1LfFpJPljnrbgms0
            aXYxhJf3gn3oV4UUXgX8Ek44CTIgo0yFC+LKVKc0Ps/ghzw8h1sKxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-24T01:19:43Z"
    mac: ENC[AES256_GCM,data:eTgcOw49MD1vBmowWxSzF81iR7VYGQlwFjaah0MQEE1Q4B7NZVuG6MB6+GPn9dzgwfozNMvl79XDqovNH6bUkNODGwQfgcvQfFOS6b1w2qLaapGeX8tpKkabesy6t+wcaedGRJvH0/DippTxx3TuL3SHaE0xZ31oYMwuYer5zxM=,iv:pVBS4rW2VaYxwBCed7k9VKXMrOFVfkKpsxnZTFrocrs=,tag:+RmJFGJe8yv80kwlb4Gk4A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
