open-webui:
    ollamaUrls:
        - ENC[AES256_GCM,data:9KAMl+GqXFbBP99iyAokHD86950=,iv:KoJ0Llm4YmEjcrPqAg/iwNMb0bT/dih8s02bWdvTz30=,tag:FQAo6qG+NaJF40IDJB6myg==,type:comment]
    ingress:
        enabled: ENC[AES256_GCM,data:wOcGfw==,iv:GWrplBVdytXPjRmt/FwVWl6vaIce8fC3vG6vRILofDM=,tag:HPCyPUSE5WPG1dU33lDVyA==,type:bool]
        annotations:
            cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:meo6lpZTgdU2I8Sl3QkHqw==,iv:9oKpI62V5ecT5pE8bCTRTS4cESdS7tRAkqe5osiFY4w=,tag:El3HbaRVc6kj7i6owIJ8/g==,type:str]
            gethomepage.dev/name: ENC[AES256_GCM,data:dehRWheaksRC7Q==,iv:Cl6B3A+Bgzlkb/u2+XE6XgLhzOSBArxyBBd+8QhPwpc=,tag:Z0qH01pQzCySjtdlggytzA==,type:str]
            gethomepage.dev/description: ENC[AES256_GCM,data:nOdh8jCmxht66Nc=,iv:YAAtdoAHveRValDzzhm3nebEUe4jQtyVZbeHrbKVOZg=,tag:P7DESmU3evjNXT8riVUSsA==,type:str]
            gethomepage.dev/enabled: ENC[AES256_GCM,data:HXK9Rg==,iv:k2rZR6tqd2CB6a5Lr5mizIGg1gUAwvW+8apHs+PAgzw=,tag:YVEl+WnlD6eRPuf3rCnczA==,type:str]
            gethomepage.dev/group: ENC[AES256_GCM,data:zD0=,iv:V3du0yDcLX9JJDnm5TlOLzAaRBbogt5EzY8/4WARpNw=,tag:5BioYbTodrY2Tj8e/k+Drw==,type:str]
            gethomepage.dev/icon: ENC[AES256_GCM,data:hjpPhESvsTzcVp58uSjOy7g=,iv:HK86/M0FW6chI4dbxDDTHqwmnt9QTpBtXmo91uu48O0=,tag:HpAbNtSMhj7KtWOjOrNBYg==,type:str]
        host: ENC[AES256_GCM,data:PSsUx4cEMhfZ5Y/pInmzm1vu+1ViNg==,iv:Oc1Pla56qT6R0BgOZC+GzT7/lpjSl5pc6Ckd5Pgc8MI=,tag:tIS44f6PHXS0Xbw/o4S2dg==,type:str]
        tls: ENC[AES256_GCM,data:0H75cg==,iv:M2/hCoKWG+9cHUGLifTPkNhP9B2vCjOmpfQFrmz4dQU=,tag:dfxZeqFgu0R9i+EFsTV3FQ==,type:bool]
    enableOpenaiApi: ENC[AES256_GCM,data:NNYrnA==,iv:hfQBicDgn8Hcdqiw7WlaDqtr/wdo7UatS58IYuBUc80=,tag:iC/Lmiq7LSc0TfTZutkxGg==,type:bool]
    sso:
        enabled: ENC[AES256_GCM,data:WPkWvQ==,iv:UrPYMxMuFLK0Ku+BGUv1EF4puQpyXU98o5yTbEIPL+w=,tag:z6e9LZi0Ja4+RTrOeXcrgw==,type:bool]
        enableSignup: ENC[AES256_GCM,data:oOw6L24=,iv:Pt5HaVMyfmNlYuUgQhCAj0MI5Wg65FRLUHZwo2d7Etg=,tag:Gyc2lMBB6YrGlp1v+LPBGg==,type:bool]
        mergeAccountsByEmail: ENC[AES256_GCM,data:SP6xFw==,iv:jVlP+7jITF0nAlwu2w+vDIAUyO62iHQiHQYHyfywyAY=,tag:pxb0jEMR1gx1OIsOx9y+Mw==,type:bool]
        oidc:
            enabled: ENC[AES256_GCM,data:kzIUgw==,iv:Xd/lnGYdmrCJt2SNViFrpaiEWUeP0xBnZkRyXTMym8M=,tag:ugBW8zaZzFqkycdDY3NIsw==,type:bool]
            clientId: ENC[AES256_GCM,data:7jmFta+La6BHE3zrPCUPnBZnAdDEOe7Ph5uityxxzRUdHe2O,iv:YHPkxOatQ3TUKRIsSUgPMe8piY9dHLemsZFtd32NeC8=,tag:qypP6GAXgnEbem+pQ8VXHw==,type:str]
            clientSecret: ENC[AES256_GCM,data:EQLDfrXdpTQi+IpVbaFKGk+bLgUmETGZu3HqC4gen5s=,iv:fG1AtV38es+YSRrQRqCrZf52cfRC3mQD6BKh9WsDvI4=,tag:nrEdlGMmLv8YVwheevzV7Q==,type:str]
            providerUrl: ENC[AES256_GCM,data:PD/2VBEAyyBXIfqoOp0QPgYT48SOSP2cZWFhxJviaYKSLvwzozOHypvMnSD2+M/8nclyIlGgQigkM6A=,iv:nVva7jy5N1wlykBf6gnaYqnsxUA6DhuhZH/eZzo4JL4=,tag:nGnMi9qFrEm6oPlI+qpXDw==,type:str]
            providerName: ENC[AES256_GCM,data:XYMf6aAuZx5b,iv:BnqZX7dqK94F63n07QN9B9sLPQpQajIlygUbotD4PvE=,tag:TURD4FzuaBXLLOeQ6SZaiA==,type:str]
            scopes: ENC[AES256_GCM,data:xPwe5nwFSHw1ADIE68wGCzz7/To=,iv:bjJ5QspQd/9EgOU8jRPlzdUdVG2RQjXTSE3FVz8Clac=,tag:mWKM/K+Wk9/5XAyA/GP3XQ==,type:str]
    extraEnvVars:
        - name: ENC[AES256_GCM,data:fFsmfbupqySa,iv:97djOTWOqn34q4JBWEfC8fDLtQLowY/hRrQQVDfJbss=,tag:eiM6P3j4lnv4EH8D4kTCqg==,type:str]
          value: ENC[AES256_GCM,data:yp2tbe/i1sfb2k0QlIBGHSPAcgCqj6QfluabR7LI,iv:CYuiWADnsCqJXWo2PFOlKNjo2Tnhp4m3TJLveBcMPYM=,tag:X/DJ4pMh/iLBNbuM/TRyXg==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaeUx2Z01uZVNkY0Vmb1A4
            bVVtdmZGTTRwK0ZzOGlqMzJSdzd4MjBab0UwCnJYU3RpVHJ4THFFeHMveXNadUsx
            Y1YrdGdlREUzWFdncFVxSEordVVWc00KLS0tIHlxK0lCUWNyelduSDJieHVlSmRa
            emVCSGhJSkp3SVZ4dmZPUzdaa3lQMkUKXO0D79LgEvmVBTrKB/GzLE+PQQDCsLQT
            swl9qGIKiuexM5AoZrwtKGP6xzJKg/o1oiSUq3vM/Y+zlvSGAM3PvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-24T01:30:28Z"
    mac: ENC[AES256_GCM,data:jczhvHePT4C3u0c3pNNPrZqkAPPZJ5jySoW5iWFp48GjwHbZHa97cvNXPByagFrvoldr1Nrq763IjXdUeQOkDu963hDmdpmkeOMFBRim/O8nxVU+3iGjRZ0F0JeayDioUiY0sWKCfYkVdIvNwptGlwdj7FID07Lol2EBN+WRLpg=,iv:qqLA5HM9oGDnk0q1isfJCQTdvzLTkW7mzulBkC6Y8SQ=,tag:8qfMGbNlzEG6a28+28ObsA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
