open-webui:
    ollamaUrls:
        - ENC[AES256_GCM,data:AimAn46FsV/rWxGutnppGqaL2PVDkZcNZNw=,iv:Tm2ALECx+ufdoguf3QJL9ssUcNPe/u1Idy7OJvUOyAc=,tag:WqHAQ+DMsfUT2HSc5B+Rew==,type:str]
    ingress:
        enabled: ENC[AES256_GCM,data:dCkA6w==,iv:E591Hdz8O+cY4QeYQrkcfie65K9nWfvxLs9Af6l0H+Y=,tag:+WZVl9KFfD6CicdWKsprZQ==,type:bool]
        annotations:
            cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:jVSOvJEoRrkBr0gh7esyCQ==,iv:5fCOCVRu4k/EI7qZkAIB1K/tYJ3Uk/I2kcMPScR2+74=,tag:3uFhd330ZRNMk5aVCKaI3w==,type:str]
            gethomepage.dev/name: ENC[AES256_GCM,data:njyWpiE6l5enaQ==,iv:yminKhX+YyoMv6AEVds/NLa+OmO46wiqK2HWS3pDGnE=,tag:5OBb4h7zz4QDQu+wtbVFuQ==,type:str]
            gethomepage.dev/description: ENC[AES256_GCM,data:UmzupGnTbtnGc54=,iv:pRn1IAJ7vdoUah+VfmSbBdWSTvZGHv+vowtOWd4KXIs=,tag:o/BSQaAeZTCBrmAOQiNTmg==,type:str]
            gethomepage.dev/enabled: ENC[AES256_GCM,data:wdZ8GQ==,iv:o/K4U/ByH2TZfPC4mFYBqvDEE7ap14GhmEjJFoDdMjQ=,tag:kIxkbZAwLmRnHvq0b3e6MQ==,type:str]
            gethomepage.dev/group: ENC[AES256_GCM,data:qAw=,iv:2LA6mN9xuBAoXc9TW+AS4r9xlgzDqydpvsBdFPwJshQ=,tag:ty6g+7io4opg3WerB7U3aA==,type:str]
            gethomepage.dev/icon: ENC[AES256_GCM,data:D8HHeqwleu0dkc8Jhv0j9bs=,iv:qM8Xyqzmc8fUkS6GVbxQLv9K/WlM2qUcrD3Reak4o5I=,tag:jMR8TeEKmiZidrRoVr3z9Q==,type:str]
        host: ENC[AES256_GCM,data:FiUaCi3yYM+0FHhfmkj80nl6RpdZ9w==,iv:mlGfiTmMh1AKAHdLUKTInBsApN/C0I4NRHQQ5Hlglog=,tag:Lun8KMz1aElF5w8F0+rlnw==,type:str]
        tls: ENC[AES256_GCM,data:/8DQqw==,iv:y4XopoDLxvVZjd0wSH6B2MbUQFWkTytxEJ3HiB1n0qg=,tag:0zNtGYk4nyoOwqi5T2Ii2Q==,type:bool]
    enableOpenaiApi: ENC[AES256_GCM,data:bLr9EQ==,iv:QIukxYpZAQGcJuNItJtbM00Xlk/9GRYGqT14l7t/Kgo=,tag:6rUWqBOizsm70j41Q+4+/A==,type:bool]
    sso:
        enabled: ENC[AES256_GCM,data:FmsqSA==,iv:QiVataVJ3G3M6f926PD3j8LQRXSEkG+Le6D70zEIiO4=,tag:VuidwQQUijm4CNiwxgaCcA==,type:bool]
        enableSignup: ENC[AES256_GCM,data:3BA170Q=,iv:A3k6OcsD0Fnmqy3sW2JxKsaAG9bfAhrDMyWXd1aLXqU=,tag:LhfD+tdiKKq4TfVdmDMMVQ==,type:bool]
        mergeAccountsByEmail: ENC[AES256_GCM,data:JPGThQ==,iv:8jC1+FD3g0B/ez1zkFQyqcb4ZGuUbXmzDxT+YDhau98=,tag:4AXtQ3bBQbP1pkdXYtk0GQ==,type:bool]
        oidc:
            enabled: ENC[AES256_GCM,data:TlBgxg==,iv:u9CJieph72Mqm0bz0kLdiOLi+4nQ/2/GQ5sNke8klOE=,tag:MPCaUI/rAiNrbt2766kJug==,type:bool]
            clientId: ENC[AES256_GCM,data:XNDpaZus/KHuf5/FHWhPgXuUjlfOmcwvvguS4w6ebR0mTd+Y,iv:zbOvlwmigA3mfoRsJVL/Ri1RhtkMRRSjVfNYJc+Z3cI=,tag:DUKV1R/DfEr3kmohbWjpaA==,type:str]
            clientSecret: ENC[AES256_GCM,data:wBR5WVKTsfSd9JVltw8WO3VpU3/bAiyB+c+u0iTVbN8=,iv:Ren3xilX2HZ9IqZaQ7aEmso87FhCH2Sp1cpG84p59ZA=,tag:1Q1bn7MfpoFfNTgImaCVjA==,type:str]
            providerUrl: ENC[AES256_GCM,data:SxS9Gmo6tcnYxqbsKm6cltnSLliAYJXRODQOpDoFzQylf68RRiD4o2suDdLXvYYvqnNwxOtK5axaxVw=,iv:5qDAVlGDlCL9cftM3FzKyFWVhUWl8nfZmh90JVsoHYw=,tag:lrrqN3INQ5M80lB4NPfl8g==,type:str]
            providerName: ENC[AES256_GCM,data:SF6XaVd5AIy4,iv:VlC4EJqSGWco624N+3yIOKUA/BwEYVq1XMqnO2R5xxM=,tag:X2i4U37zdkNKVZ9YD9syFg==,type:str]
            scopes: ENC[AES256_GCM,data:DcEf4aRjvttuSpn8HcFjNpFAn0Y=,iv:YSjr5uViyZNsshDkOukbkmbHpOWxG5bMPD5ZwWd2CdQ=,tag:fAnYfiNCSDgHzyqfaDPkWQ==,type:str]
    extraEnvVars:
        - name: ENC[AES256_GCM,data:tR8PS1uAYU9p,iv:WHrqq/AxAe61tex9bau1ZrEZzJF3Umg2MKSGTObM0z0=,tag:P2AZ+pGKn6OiT0lL5QV6HA==,type:str]
          value: ENC[AES256_GCM,data:Ul5IPnnkqSxyiQIRre8ldwar0Ds1FTQPoo8sSEq+,iv:WEQ/o/fyKQu+QUjdQd7sa51i+gZL9AfKjvCheQQTXvg=,tag:uzeZOKWweqxhoTvkr9yJSQ==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBYURsS1J1dU01WXZnS0pp
            aWUrMmpDOFUvZEwzRnNiQzZ2bG1OZUtHTlg0CiswOE9sN2dySTZQUWV6bFpqU0E1
            RGhCakNIbFZPL3pIWWdacXBkN0dJZWcKLS0tIDRQNloxVDZ6U3N4eWFBQ2lwMWk5
            UmJGb1BlQzdZeXl5SHYxR3N4Z3ZEQzgKvvVFbXrPCoVc9ekHbDFGArufrw3NBlN0
            6Q3YOMIYd1F+d4JHKE80hwaIxtFJitznjuQNNeF7Y6p7LDxosksYLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-24T03:06:53Z"
    mac: ENC[AES256_GCM,data:vDEacs0O9/TH792Da3bV8yFg8LUgtTWcmOi0REdv7T2HzLEaGx1me93Qg2phh6JVdGge+5zg9ujKWd6MBCLCweiBA+oVabJ5FwApWStKRZiRcb8lfixJXDM105BocQ7+QWfjWoIlllCw/SQLS5miuDWqH2u8cZ+f6vAmvNG5prs=,iv:9YJYTOBTgWXrh+PO4i0fgBSF2X7o224swploGQDMGiE=,tag:YkEFaLSdm8K4TAEr9SID/A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
