---
apiVersion: v2
name: myspeed
version: 0.0.1
annotations:
  homelab/description: "Speedtest tracking dashboard"
  homelab/url: "https://myspeed.dev/"
dependencies:
  - name: app-template
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 5.0.1
