app-template:
    ingress:
        myspeed:
            enabled: ENC[AES256_GCM,data:lLq62Q==,iv:eibkNKo/UO3X5wz4iDy9SN1bpvmFM1J48oU+TKL/L80=,tag:pzsx6K3g9zQZ9aMplWolvg==,type:bool]
            annotations:
                cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:NESDNTHjbN2tcVaFF8Z1hg==,iv:zza0lkh1P4AOeD8rBQMbEDN/vaqWSuYbLRSbY9711fY=,tag:sJLIqKe5cCaRWu4F7RGyGw==,type:str]
                gethomepage.dev/name: ENC[AES256_GCM,data:+4KXt4/PGA==,iv:29WqEnTf1rXvDDxGTrFugELxzzE6osM7LZtktCjv8XQ=,tag:M4Cf3KfRZ7z+uEfRr/XoAQ==,type:str]
                gethomepage.dev/description: ENC[AES256_GCM,data:eesymzRNb5Aubw==,iv:2OZsvUco6208iMptN+w9k2YDvnmsv0jUnHPgQizi7cE=,tag:1HBjfMyhZ+1433eE0dXmcg==,type:str]
                gethomepage.dev/enabled: ENC[AES256_GCM,data:U8MAeg==,iv:AMMIKOYSJmFoZfNp86RKQIhNwBZLDhazJilier/2YIU=,tag:DE5IObFa7N6FfLDjAyD8Tg==,type:str]
                gethomepage.dev/group: ENC[AES256_GCM,data:/dw3TxxEqCXm25jyPQ==,iv:QBCIFn6654JsGmaTCKAEta5W1UQp9cc5XsI7MC11yqI=,tag:wiW7Z5wX1blOfmNiYP7Seg==,type:str]
                gethomepage.dev/icon: ENC[AES256_GCM,data:wlsRcpj1uGZOB/KXya0=,iv:a1zpJN+/hF9hRUDfwIPKagNQPzHCFEBDe9X805fguP0=,tag:3ujQ5aZFrn6D9NpC1m1Qaw==,type:str]
                traefik.ingress.kubernetes.io/router.middlewares: ENC[AES256_GCM,data:kNbj+cze4yjUYLgdYj7FgkiE+f2HCvuwlO++lLs=,iv:Cpopgvs9uW+N51bE0/D2STKplMCAKzYNmReyOqmfXic=,tag:UzF+B04yuXmMbdt6fbr6AQ==,type:str]
                gethomepage.dev/weight: ENC[AES256_GCM,data:WBQ=,iv:dW8QW8JXsQJqdrTMPgOlo/xAwFM4AwICPcdKzWI2jdA=,tag:p8DsPOY1Di+grD1OhzLxQw==,type:str]
                gethomepage.dev/widget.type: ENC[AES256_GCM,data:FCh1o+ArXw==,iv:GlIA5uRME2pyphx4ChyhtwXCgp+7xGjJWtoATz8voHg=,tag:vcaAKN+BEU9tMH/iX0wR2w==,type:str]
                gethomepage.dev/widget.url: ENC[AES256_GCM,data:mPPaA5HELyhOXtNebxatRDbr9IKayYMLF5UYKhww0A==,iv:jXyiuO5BgBCwAwUkmdm9hJFngCmKQmIUpVZs7U9k3OM=,tag:yMaB4IJrudRUO64xfV4YFw==,type:str]
            hosts:
                - host: ENC[AES256_GCM,data:0BCtmif/9ko4h2OlnWLIqltj2w==,iv:Jn7IU8YHkyZPYcDqkkQl9U04VavJXmN5Ol6Bd7hLsv0=,tag:Zt4Jo3Bh+kIRY/xUs2I23w==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:4w==,iv:GMYUGTy1hDl3+/tI9FYLeAnUpPXgkHXciOrGeW5Gpa8=,tag:R9gNOJM5Ipr64MaWvqXrcA==,type:str]
                      pathType: ENC[AES256_GCM,data:lWWlbLLq,iv:wbGqG9gesN3+sV+EGo97iqSzby21f57Aq5aK0fBUFHU=,tag:VPnJx/z9K/mvQL85MPw+4Q==,type:str]
                      service:
                        identifier: ENC[AES256_GCM,data:WdGQ0zOq1Q==,iv:No7eGvhF0Zmm8UeM72XFGcuhC+ddJmsLEdP2QjCvxIo=,tag:1f2naKcIWO5ZsyKZ0a4Jlg==,type:str]
                        port: ENC[AES256_GCM,data:N9g67A==,iv:Eh7arZg2xKopEFVaKo3gyEfvGAbmBNitvCJsi6AhMbE=,tag:f81SyjW01uv+58Ylr3yV2w==,type:str]
            tls:
                - secretName: ENC[AES256_GCM,data:HJmMDE6llJTVjEASDmyx/w==,iv:XQ4/uVlkLgOjgOH7ImlK1uID+46BMUSVuj86HqHHo+w=,tag:lyNj7aFDw3VVPd7y9TchSw==,type:str]
                  hosts:
                    - ENC[AES256_GCM,data:zWxXg5KM58590WbjYcQsFjOUHw==,iv:/vOSEPgY99i9XWgNVXJAMyhn+ee9OzfGDwNmlOSVXrs=,tag:CW+Ab17bbZl3RkMsdf6PBg==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQWMxV1NmcjVkNExGai85
            cDlBc0trc0dWdGg4eVl2OGt6SU9GTjAwdUdJCk91cXpnaFJUN3huSkU0VUpvZThR
            UnZRc0pHR3JIZWpJSElieEpIa0ZlWjQKLS0tIGdxd29hdk83N0RENGF4czc3eERy
            QWRSS2s2S2NYMDVQc1BCYmhlNWZNSHcK4dEVMl845zA6suyQilZhJJARJPHdqfOK
            oVN4MvO/bx7M7b494z8NiIw9bksHJvBG7wknCNaLTant9dUBDlI1mQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T23:05:09Z"
    mac: ENC[AES256_GCM,data:eTUHANMNzVzg9q3Ibj+dhoAY6GadoLfi2QmXMR3Sbp4i6dnaGmWh857raUR42IJkcj1h/fxRJeAsDhL6kjqGNU+st+ognladoAtoC4/z4voWzLBfs7Wf/Ls5Hqh0ha5XJFlYtOYrLP6yJoIsq+S5uKlhyk5ca3jF67UnPl2XyX8=,iv:p2ctpdVgXXhArUQBUdnKhRQAFtM0eWX3UKC42hV2IwQ=,tag:CjVpuUu8Rz1xuIUQvjP6aA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
