app-template:
    ingress:
        myspeed:
            enabled: ENC[AES256_GCM,data:8Fnq9g==,iv:0VDKX+4TD7jm25KXNV+Fkdxsl+iOLx9NB8aWIHQBZk0=,tag:0u09SS+wd3vsAMgwRmCCsA==,type:bool]
            annotations:
                cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:viDnOYhTz+ZseURCtgkjaw==,iv:VFAL7kpP+f+87PoVBZzu36Y//yVzVAkLeWxHVBOParQ=,tag:N43zfoubeBwWuAd99TuaKA==,type:str]
                gethomepage.dev/name: ENC[AES256_GCM,data:cauQmoK9eQ==,iv:pVQPRf3W6Ovgc9B9Q+ywSA9zYTZCbc0OW5X0CjzMWcQ=,tag:J3+WDaRGruTAgk2UHHv4/w==,type:str]
                gethomepage.dev/description: ENC[AES256_GCM,data:nQb6Vi1NMIsgNg==,iv:/sKwQ86P5bV0agxDtmw0yuG1gbJzhfyyHIQRud5f7d0=,tag:60BxPGUsJ38Bc2QJ+8Lj0Q==,type:str]
                gethomepage.dev/enabled: ENC[AES256_GCM,data:H9etRg==,iv:TNBSGzHcJmD3nJvn/qO2hGzCrofzRm3zYfJ/YY5x8pc=,tag:SLJ7VCl6KhNG722XcGaIiA==,type:str]
                gethomepage.dev/group: ENC[AES256_GCM,data:bgxrZ0fTN2p9NZqCnw==,iv:755MJ5CHzT9V5M6U7fq/q2Ta39l6eHeUoB3PMctjboE=,tag:5O75JS5TiQyUuVMXO+bF7w==,type:str]
                gethomepage.dev/icon: ENC[AES256_GCM,data:jcyaqhgBsQb21virYcc=,iv:yH0wq9lgGVoJGiEIKbxqZLERXl+x9euLZ0CvyfI2mQQ=,tag:B+tV1Gjx26w9VRREQ2u3gw==,type:str]
                gethomepage.dev/weight: ENC[AES256_GCM,data:aTY=,iv:5tKWOcNz0QfUGecOe+a7Zz+m7pGZ9uq/+3iIIhwbO3M=,tag:W3I8YuMXQ+tAh3WcoPfB0w==,type:str]
                gethomepage.dev/widget.type: ENC[AES256_GCM,data:vPVGRViKtw==,iv:m0VulXUYyDzcXRt8huRltEoO3m1hCbmWUqHzsgcXGfg=,tag:kuNVrV1iDzYl+8DdSatYRA==,type:str]
                gethomepage.dev/widget.url: ENC[AES256_GCM,data:t0Tr2S9Z5MaJYKej8q8/qR0XdkTBcqmxXJDtZntFqA==,iv:JuP1YmIozYPXYl4JYz3RvkXmU29TaNnX7xMXGWGImvM=,tag:OARDzplVVgw3iXzovxj+Tw==,type:str]
            hosts:
                - host: ENC[AES256_GCM,data:cpyMPYn5ITtVGtQqSDpthsa7WQ==,iv:W3u+6vxZ3eronsACVyjBFIo9wHQCMgXs46/aNVRDUc8=,tag:hgnW/8bCRo+zltEJW/FJEA==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:5Q==,iv:PNcAGMAfS6NG9X2uNdPRBkFlZhvR3S29cwlD576jyww=,tag:DIYhuxsauhzZ/GCbaLzyAA==,type:str]
                      pathType: ENC[AES256_GCM,data:dlU7v6mJ,iv:ETOZRGmONm3r3GOK6FSXjYDYIYX400FTbtysKee+ZB8=,tag:N85oWULJ30gYAFmNnFphiw==,type:str]
                      service:
                        identifier: ENC[AES256_GCM,data:UDnC4WXhEA==,iv:Av6On6zmxgc+PxZKLbW0DzN3qZ74p2aAVB2mkGG1ei0=,tag:na60RjZQnucaASBJZE0sUw==,type:str]
                        port: ENC[AES256_GCM,data:Xknjig==,iv:b9QiLgRlCBq1WdTLnmF/BXuLew2hdvIZA7jloZfyCPg=,tag:hRxRYJDBdclVPDBaYPvbNg==,type:str]
            tls:
                - secretName: ENC[AES256_GCM,data:FmZ5WWluO0JdXb3PJzPUog==,iv:bNuGKUAVqx7Prp+Aa8xOGBIg7S8Csp3w8hCzH2viXoI=,tag:jhqRFRVHvCVQqkIX3DeBWA==,type:str]
                  hosts:
                    - ENC[AES256_GCM,data:+Ion+snISC7uFcUz3ZMEPeRKDA==,iv:EbSEmrkQYxHxBrL2/qXosTKe5kpxEBWOg/3eh3Ny/fc=,tag:jq5sMyTdNb0D43ljuFjqjQ==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6M0t4a3h1L2FqanlFVkNs
            eHQwZCt3MjY3Tk9lZ2drbWtkYlQzYnB4NmlBCm1KeS9xWDhwaEZ2dkpwK3FZdkZD
            OVoxekF4ZWQyUkg5K0VSeWFFUndBTlkKLS0tIDFZUVJhRnA0bXBRYnRhWlBUSTl1
            dVBFb0N2ZUFtYmYrUHNIOWVUYlJ3RGsKMnqav7APEqNPzvmZ4edl22Krq9fOyyoK
            lkX+YKx7wcFBfY8EBlOJji+TNYEVjqks5FPZTePqltPYgXXaOJhPcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T23:09:27Z"
    mac: ENC[AES256_GCM,data:5Zc0IE1AZo8udcaDFCHvIIyBfK9aX/wrr9F170d/q9HU2zl2vyjlxBlTK5QfkahkDhlJv+qBH80/fXz2+3zbDFoJrupihsx7nyAmQHDXTiAavP26IbygCtz0Owd8RyMOAmza/Iy6FAQ/tuDucrbBgD0euEJ2tbt+SuhEOFdjAp4=,iv:EIw4LnBhDQsKn8PwTtkMBdw/FcTfe8kKMCCJ+ysxYmw=,tag:rXiOzuel+bco/ZUXVae9uw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
