---
app-template:
  controllers:
    main:
      strategy: RollingUpdate
      rollingUpdate:
        unavailable: 1
        surge: 1
      containers:
        main:
          nameOverride: hermes
          image:
            repository: nousresearch/hermes-agent
            tag: "v2026.9.7"

  service:
    main:
      controller: main
      ports:
        http:
          port: 8642
        dashboard:
          port: 9119
        mcp:
          port: 8080

  persistence:
    data:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 20Gi
      globalMounts:
        - path: /opt/data
