app-template:
    ingress:
        docuseal:
            enabled: ENC[AES256_GCM,data:j5670w==,iv:vQ471UHqPgXoQvmgLZQk/NJxYy67c7RiyLwAsSBV9Kw=,tag:TGMlADXnUgwfongrg7cs5Q==,type:bool]
            annotations:
                cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:qQHhwo5eCBm4G2BzDJE3GQ==,iv:MYXw05dj7EPa/zbNfRyyY/phVaLj2bsAFxvcZ+7Q7DM=,tag:Mf55CuD6llrW5yj3lU7WjA==,type:str]
                gethomepage.dev/name: ENC[AES256_GCM,data:rsErydMnzcw=,iv:P9kGVmK9acGltjg8Q2dwd0NpF9xVmlbgR9zlYow1+JU=,tag:sGtqFn6xbtrEMRPJLnE22w==,type:str]
                gethomepage.dev/description: ENC[AES256_GCM,data:H2O9PWcIHGWtNl87dxOBWGijLD3doS/qOXPV,iv:QAC28EdBnfU6emHMLk58DK+Hxym3qieKjEah7efn+wc=,tag:z7Xf06uQDIjhPcJlXKWaIw==,type:str]
                gethomepage.dev/enabled: ENC[AES256_GCM,data:eJAOVA==,iv:dePUgfNB35gx2W8zWEF9AP7DSeos8rXraJytAjriVxY=,tag:5QoZrMZAGjbElUwDxbnZbA==,type:str]
                gethomepage.dev/group: ENC[AES256_GCM,data:7JNPwrB6zgyB,iv:1aFtNH33I9QGhf4UO9D/ip8SXZLhpQWIb7P017M8DJI=,tag:9qvDaT1F7Fqc0LodUCcu+Q==,type:str]
                gethomepage.dev/icon: ENC[AES256_GCM,data:JZI4cgmbNBzIFZPIeLQd,iv:7YhRL8NTIIbbimSSoJDZDWbOk0vNf8XZj0cwnVcH6Oo=,tag:80WGGx77IChf6AuCt4IlFw==,type:str]
                gethomepage.dev/pod-selector: ""
                traefik.ingress.kubernetes.io/router.middlewares: ENC[AES256_GCM,data:8r/JP2naXhWP4Edx0Q7lI7EDqVJvwuif7TmXWoU=,iv:fEyxH0BSnVXDRqvDxPfCr6+/6+zP1DXZ/Y9wbInafE4=,tag:UrKMKT/rG1HmRmGKkOagrA==,type:str]
                gethomepage.dev/weight: ENC[AES256_GCM,data:zw==,iv:UodTtSfHrM5sngbjTiDSXBRjc7Q2dTTahIRbjJfFgdg=,tag:Kfn9UrEJMueOUO3SMHrW/Q==,type:str]
            hosts:
                - host: ENC[AES256_GCM,data:z+nLihamLRhcXj36EgEY4Zy1gIE=,iv:2eeZ7kWasG/ezXq/ztTBuxd0iSnTCsw5D6Q7IEkPvic=,tag:ItJFt+hCp+GGarfJFEI3kg==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:4A==,iv:R8ja5grljG5v701p6I/6PEXh+sRZe+/1nnRYM/0iwnY=,tag:QK2p1BOumqgmLHdWhwteVQ==,type:str]
                      pathType: ENC[AES256_GCM,data:zdzvODWD,iv:j7zr4KBaPDoCMi+yWJZLo/EeD95HmpbWNhwkayMkMUo=,tag:diS9geZBSaSUSgwuz4nbbg==,type:str]
                      service:
                        identifier: ENC[AES256_GCM,data:/iPQSuzlAxw=,iv:8kdcxh+7gg9/ElahUZcRDzA5ook3bTTwGFeRZHv1XgI=,tag:lICuOF6I3R7O3OpeIQAtQA==,type:str]
                        port: ENC[AES256_GCM,data:V6/DKg==,iv:Fv06nJJSqIhzM6KaJNZkciYYEP/gT5edDcQqWS3Enq4=,tag:rtkXVfO6ivP1oiZFp7dGvA==,type:str]
            tls:
                - secretName: ENC[AES256_GCM,data:vMK7eLIcI/x1TzUTHCRqT4A=,iv:NBgQN/H3MpkrNIA+I+eMmEcGJpFCo+WeskcDNUpsWcI=,tag:ZZ/vV1RYmQf5rloTL7HpTg==,type:str]
                  hosts:
                    - ENC[AES256_GCM,data:xIjCq9Ce2MeB9sg0np8UJcYo5gM=,iv:/M4UmO4rdgXdKyO0w+yNuycPFjPTIf4epO9pFDkp+fs=,tag:kcqDKoUkr4zmc6bGBTccuw==,type:str]
    controllers:
        docuseal:
            containers:
                docuseal:
                    env:
                        DATABASE_URL: ENC[AES256_GCM,data:CaVulufLAekLKCoTnZfH1seHx8tecii/5whkR5W0PX88wvqmLBzl4ELm4GSNjYxo5L6QqfaMWJNZDTlAr8rMCCIicdMPCTgagzFLSmI2oRU2Hhz9HmM=,iv:/wT4yvpvUwGPcO2O+zabbrYuhjgXu1q5jgRM6KkrmjE=,tag:XT/+Pxw9i1zLQs65anrNmQ==,type:str]
        postgres:
            containers:
                postgres:
                    env:
                        POSTGRES_PASSWORD: ENC[AES256_GCM,data:PodN5Yktp9/FH9f/jMyYOmNUM2cPoN+zE5SB8GVbhhI=,iv:zd49a0HUd+XpanvxNf/zMks4yCIyIAm7c6U0tbtOCtw=,tag:oJBIiugSVeONws0r9R2HqQ==,type:str]
                        POSTGRES_USER: ENC[AES256_GCM,data:W7rDpZQCEK0=,iv:dgKnmKJnDTuF1cSotkvlEuJ1bjcBRDWuRDcvRm2RHR8=,tag:cRNRFPfOtBy89TNh/OykGA==,type:str]
                        POSTGRES_DB: ENC[AES256_GCM,data:j7oXGfHTzKo=,iv:GY3wqfB13y4Q09+z/ncAl8tiOm1FOyBbroIr4+8N6Lk=,tag:CShc+Y5gguheQVAPd3KL3g==,type:str]
                        PGDATA: ENC[AES256_GCM,data:YOIeg76Fl5VbLUYE1vylJIFi1mMTG2xnp3IKeMJk59Y=,iv:20whPPcaS49wzmYkOWt6MqistNZlp/0q5FrD/oArX+o=,tag:uN/5wPVLGmoEtd6QNxngLg==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZ2FlOFphVXF2bWJJayt1
            QWlyK0VxcEpBVWdZcGE0UmNlTXJlL3RBUnlZCnJuWnhockxYSnluVVo0dStsVVJR
            cGMwMUVYVDRuclF2Uk1ER0pqOGZpUUEKLS0tIDZTaWZmZjFmY1ZnUFpISkJob3lh
            b0VCM1plVW8xYnBRRWdoRGtDa2ozMGcK0VA/3giIEaErgvNfB/haHm5ZeeXN3iuu
            bZ/xrVQHbMcNn9otNc1voRVzr5M+tXaB0Xlc0BJ/GhMJHSE/wKMwUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T23:05:09Z"
    mac: ENC[AES256_GCM,data:25C3izp6u+Oskeu+H06rSEAJ4h8dcwc4V9+BsptGVc+nJI8TFxI8EOrFIHWy4U6+rCtn6Uo2GA5/Jk7jbeRmHoeVgAiMpuDCaKEN7ZpsOAQfS/4X9CFzibPb2isTs1kHV+Xs+q8QBAb0VRbRSqGxGyu7X38H8LHmz9QBqUmgbl4=,iv:9gZX6q/Hxws05dEMDJM3MaDomep215JtGNLT57C0YOg=,tag:WtNKSUB3C5gxcz4IW43usA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
