app-template:
    ingress:
        docuseal:
            enabled: ENC[AES256_GCM,data:Rssbbg==,iv:fjW0YTKsFPvMoPyhfZXmp3l3tagHH+aT1dUsyQQ1OqY=,tag:MSaFsvC3z/jaD+mqQCZ/7Q==,type:bool]
            annotations:
                cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:eXHG/F3Smk69t3vyQ2qAig==,iv:Jg6sf5TGFgJ+sQMiukddQjOTqMakpz4HoNUu3UkThZA=,tag:LnM8+OphbllKD/YNI+Qvpw==,type:str]
                gethomepage.dev/name: ENC[AES256_GCM,data:vyVn3Kt5o1U=,iv:/oTr3BTYjkYSLVnYpXSsDHUzyc9+IMrMymnhHD6wVUs=,tag:stzyyxOvg70A/wWwX+di8A==,type:str]
                gethomepage.dev/description: ENC[AES256_GCM,data:VC0Zj3qEr4rJ/oGQD7vKY95S5rvKl5b75NGD,iv:7wJn/Qe5s9i3RAYkGFd0TsS4EAwYQM/b3f5BLfNT4P8=,tag:fJ0x+lkIP838rgMGfP6x1g==,type:str]
                gethomepage.dev/enabled: ENC[AES256_GCM,data:ubnvsA==,iv:XqQTnS9LyT+C0jz5RmtzRAoet1PK/bwtZmBRLUy6ED8=,tag:qNJCSVHitoAWXqWDMeVlGQ==,type:str]
                gethomepage.dev/group: ENC[AES256_GCM,data:vAHcSgoKjXZP,iv:qPxhJWMXbAshKic2h1AVvLrDHst51TjQbI/9Y/thIhw=,tag:B9bRX2mcFN9FRYmCcxY0bQ==,type:str]
                gethomepage.dev/icon: ENC[AES256_GCM,data:1i9s820TIZIqnNqGTjWZ,iv:iPfLf38WyJRUgcDt516eKqimpoRXqsMTWfm+ts5+NUA=,tag:L+FE52i62HCRCSPA7eXthg==,type:str]
                gethomepage.dev/pod-selector: ""
                gethomepage.dev/weight: ENC[AES256_GCM,data:Jw==,iv:cAHBcWsaePryrnIFPibFIbrcol2few36q1mq/FD+43Y=,tag:rJO9FoCF6sa6Te4j76V9TA==,type:str]
            hosts:
                - host: ENC[AES256_GCM,data:9u2vwegOwGzpvMMZtvrLh932sD8=,iv:nyAT0Idlrka1WgB8C+q2cpEmt6dFb3aPzbOKgp2pLZM=,tag:gdVCfQfaoFA72NhcZUNXjA==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:6w==,iv:Apfyk3GckfqZK2SM4zxBhYKqMypYokgtSFPQMgTpqf8=,tag:JNIMc4m/JeKTvEOzMvDymQ==,type:str]
                      pathType: ENC[AES256_GCM,data:ld+CdsnI,iv:jvHbj88og4ztY1cPrUDVm0MYERLgrLzw1j1lS1R4CaA=,tag:KGIaGcILTzgPOin/05gYPQ==,type:str]
                      service:
                        identifier: ENC[AES256_GCM,data:B4aHfnld0I8=,iv:qTaCvzk2NIcbXZ+F+Bo55BpoYUxUHE+oXea4M+tTiys=,tag:WsKGSqcDH0tQ7vETgToJCg==,type:str]
                        port: ENC[AES256_GCM,data:igtWcA==,iv:w01WenWNgvNH6VROdQrJA51qp0zP1auAhFY6XzgDpag=,tag:TCFb0vodfOwencu+eh4Dfg==,type:str]
            tls:
                - secretName: ENC[AES256_GCM,data:9slJKMwd9SotsTGrouitUEE=,iv:YH2cZRvdyfALCoGRCsKMpko+J2eRdf4y1fI8mY4fbzs=,tag:5Gz1IRUYXQjmT0tCoVeDsA==,type:str]
                  hosts:
                    - ENC[AES256_GCM,data:UBwJBemAg90t9vJYGAYuSbo8rbI=,iv:pxzAKvSYVi9BjB/+D4oH3uovfLZRMoo5Lmetsf4RuSI=,tag:I70rw9ikMpRRqbyqlP+XkA==,type:str]
    controllers:
        docuseal:
            containers:
                docuseal:
                    env:
                        DATABASE_URL: ENC[AES256_GCM,data:iyb/MvWz8eGAvYwEaQkNPH6JPSSermBwA4N/L3PEMdjtFgrHz5UW6ZfM0GVl26I2vVDDoEcqaGZHmF9QPsXlR2+kP/qY1xR0K1mekjKQuEfljQVxf20=,iv:tok57ooCyqQLxhh+OwRkCvuooHHjuLjDribMFfgSZ40=,tag:5m1JTX59ld9dcYJvsX8B7A==,type:str]
        postgres:
            containers:
                postgres:
                    env:
                        POSTGRES_PASSWORD: ENC[AES256_GCM,data:N0x+XdEanqtu3+ouKaMZO5So39qlqEnlcjfe5YNFHso=,iv:ghqGpuUK3B2Ig9EbtyOAr6GnGVUTAqckH9n7Co9y03s=,tag:iH/cF5AoXudaK3mwHhMQjw==,type:str]
                        POSTGRES_USER: ENC[AES256_GCM,data:vav8FSjFwSU=,iv:jMUgpuZfxsEjTW6ZbjHYX4RoLPnzAqj6IUhH1XL3eJE=,tag:Ec3MLW/HMrfhySlM/F7huQ==,type:str]
                        POSTGRES_DB: ENC[AES256_GCM,data:rh8cKhdNUHI=,iv:La/KwAdMG9QuYUq2QOH3R/q0bNhT8zeddp6jOL8cc1I=,tag:AfFiOhQgjHBStIi/LHpqHw==,type:str]
                        PGDATA: ENC[AES256_GCM,data:XgRpphP/nQn/6aXOOANK7SeiqcBNAm3GlsqGxghz+HY=,iv:Ec2S7k5JIsJao5xMbXgWzqlW9zyrE792e2/atpkIkEg=,tag:t/O25hK+ZghS7YX94bCghA==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySkFKTWJ3cWNVZVJ6N3pk
            b0FFV0V0cU9qanBtKzJIQjVHcmxRNllDMFZrCnhUaDgraVhha0cxL0N1TzZNOHFI
            elZVaGg0anhVdHVqVm1OcjZQWVd0aW8KLS0tIFRENGVSUXZXOUUvWlFlaGxSNjZ5
            TGdqc3gyY1dWcHUreTFldmtuOXU4SGcK8oXhxui2Oc+9evCsfqrH7T6qbCeXsL3t
            FQp/ZXPDK9pQiV6LeW6legnPxy+WRbJq2XCtaEsXYWUFBDjnzSaqbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-29T21:34:54Z"
    mac: ENC[AES256_GCM,data:bThFOvc8o8mk11S/MbC97fg7Yv+H8g2lfQyKhZzY4piGZaJieL3KH2Vzj49FDhNUgZn6WL0WaA+O6QJK1t3wpLzLuE6W94u9mNyZrUFljWsj3UCzgrsjZQnhpKxLCwokyb+CRPSl43mAJMnAsmkYCoVe/k1nXHNPAhiTgCWfXHQ=,iv:a8/M0v2W0GZKByG/FQO4Rt736ZNkUD18Zh08j6f5oKs=,tag:4ELyduPdV7qDV8FqwPmLUw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
