app-template:
    ingress:
        docuseal:
            enabled: ENC[AES256_GCM,data:dsRkuw==,iv:vShYPel6fHnU/Yjz1mOHk2AS1gFAi50Vihssy61Jylw=,tag:KReNIEt0e1SB2xnlohniZw==,type:bool]
            annotations:
                cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:B8GdNaPjol7xLgjyWpaN5w==,iv:MjJFVW6NvghozyqgJaabQZ2fWw8OWBejeIRgK1KYJqc=,tag:nveUQ5D8rlmlr9K/d4hwtQ==,type:str]
                gethomepage.dev/name: ENC[AES256_GCM,data:VDaZWMF9olM=,iv:50AjmFCcCgnHIpit9u6S488wwiqPv9UPKDnvefNDbsI=,tag:0tLN5kBap3BgdQuaHnQa4A==,type:str]
                gethomepage.dev/description: ENC[AES256_GCM,data:nD5B8C5k2kZQDsd2BVwiI/wsZUMkkAkNer4G,iv:cOsoKYZKtHjhvtGIVP+0mPB18rXWQ+slM7pfztUYmF4=,tag:6hzo1b9tVyFPEmK7iK8g6g==,type:str]
                gethomepage.dev/enabled: ENC[AES256_GCM,data:DW1ywQ==,iv:dxulzbZxu2JwCUphe+O6dedR38nA2zS8sl6wzfN8CLM=,tag:W5oSKAc0tlD04RDUDnXDqw==,type:str]
                gethomepage.dev/group: ENC[AES256_GCM,data:+01+ukODAZWz,iv:5EDr1Yoo9/+JQK8XbY3JNjztvJlAjwYseTT77bLIXy0=,tag:1X99rmg02SxKuw1/AdvHXg==,type:str]
                gethomepage.dev/icon: ENC[AES256_GCM,data:gounVPz93KysZ1bgtGSe,iv:9mQprXDI0PVeiMjDbFI7m+H4gDuRCj+CqYg4jIeKnWY=,tag:+/VOpxJS6I1Xmdqehil7dg==,type:str]
                gethomepage.dev/pod-selector: ""
                gethomepage.dev/weight: ENC[AES256_GCM,data:XA==,iv:dK+yehXyNbqQ0kWwuX2KqHeaDreFNXLza2z9daA/Mu4=,tag:b1oaZuoQFd6boLoko+qoDg==,type:str]
            hosts:
                - host: ENC[AES256_GCM,data:Nacdf2lkvt8wz2XLN7/1jceXtY0=,iv:Un88/j3sxVZITO3LaUyP2tx2W0KPo2vNgyeYKqaNyGw=,tag:e+6MU2o0wujq7zFQwV0mzw==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:rw==,iv:1QyndHnHMXcyXt7pdVSLhG87qoDCQdPWWxqh9OANWtQ=,tag:AIUPJX4dCaG0kB6gjoCdQw==,type:str]
                      pathType: ENC[AES256_GCM,data:OmGQQG2z,iv:sUOJQrz30tLhBa2vD4iUHe2fsi+npWpUvVnSTSPyA98=,tag:VMQllU1T8qe9QeXwvNJC4w==,type:str]
                      service:
                        identifier: ENC[AES256_GCM,data:0uvQiVAcBHk=,iv:bSQJsSJH+q9NRMj1xa4DXlBbR+7DPrtpv8cHAbsDsQ4=,tag:OT/6rjfD/qg3AajaKLhRnA==,type:str]
                        port: ENC[AES256_GCM,data:MXfAjg==,iv:3mePKlskm6lil63RCwdP5JTYuSaIXUVDGGJeZtfdQyA=,tag:KLkLt9FV0shNjenFlDbb5Q==,type:str]
            tls:
                - secretName: ENC[AES256_GCM,data:Xw8tJ+uqDqnjFvD9K+qrzfY=,iv:vHKQPW1K4lNpnHxE97PuP3pFN3cxsnXfgUBitC71U5g=,tag:4Xc7zAhH9Kcz2X4jvdDSMw==,type:str]
                  hosts:
                    - ENC[AES256_GCM,data:QHXUXdfS9Qv1ehE6+knJk/um1bM=,iv:hyoJz7UWlLYXgMZ6w9ZnVYAadpZdNfQtQ9WiDflFgUA=,tag:ic9XN4hS2KQZpi9kzwAx1g==,type:str]
    controllers:
        docuseal:
            containers:
                docuseal:
                    env:
                        DATABASE_URL: ENC[AES256_GCM,data:j1dJ3j+AIvkO9Zk8MljgAJKcV5+RE2m2u3XuDnyUf/206XrxB7NQnYwWBFmsjKeFQRwNC/NGXmEnFKjP4kERV9s+6HTL+R7iLmP4PDwhvrCNntDWyV0=,iv:cp5PoxB1tF+x+gRrDDqomc+XnqLOZRAgYr0PmCMjw+Q=,tag:2BFBs+uyGqKuk9KicfMPfg==,type:str]
        postgres:
            containers:
                postgres:
                    env:
                        POSTGRES_PASSWORD: ENC[AES256_GCM,data:P3fBaoehjsuGSRdByT4PSl6ft1K/NuVpCUDPLN9wtYU=,iv:wd8dBDHMdMmbmzSz/6Zl8wDSrIby+cTuoUwq/14+l/k=,tag:uwF/l3kq0jRW9YSMjkSHew==,type:str]
                        POSTGRES_USER: ENC[AES256_GCM,data:BMB7YvxK4+4=,iv:P0PrgEM8bHJk+U9NpjwaQO/iLFlBPyHsqRQbKyKJ1s0=,tag:AK8GKNX6+vzB0Lm1ZmBE1w==,type:str]
                        POSTGRES_DB: ENC[AES256_GCM,data:bd7DLtAJjh0=,iv:7/J20XWZUsyF1ZWgaSOnktW+gGaWFsPD5jYDuj24K2A=,tag:ghLprI8xJ/dKqlu7i85shQ==,type:str]
                        PGDATA: ENC[AES256_GCM,data:K9tr211ZoB5Wzaxshf+yLJUx1lHUrGpOO2rCTrZM/5M=,iv:Nya3ziTcrWZbmUAhPRoSOlku0TDyblwREAFrzTxDY/E=,tag:qzKPBQy3NL6fv/uyy3U4iA==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjdmVBQ0xZdEtSamQvVXE0
            NXp0Zm1mRHlPZC9BUW9MdG5zSkcxY0VKWUR3CjFXaTRQZyttZ2EzRVF4V3BDbXhl
            RUE0czhOVWZ5QlRxeVg4NlNReGRwL3cKLS0tIFJhQ3FCSm51dEFPcGFiY0EvRFd4
            enk4cXFZSjNsNldSakxFZURpS21xTzQK21jv0Y8MGUKVkfQf9DyesG0rgx43Dbgg
            Y7Bwp7secxASfieq4KpMKRJuwFSJG2yzm6gVG92el94iTwhrXEwuJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T23:09:27Z"
    mac: ENC[AES256_GCM,data:LI+0qjxXndlMheFjrsVjkUsglF2WR2jlyqlfs11b35xXrYlVUbeiEiX8ZpTZRwNaYrwnEpEPy7y9Ri7dx780T/75q1XSikgLHnSvIku70+a3qWnFmdCYnDxe4a5PzfuxbpdiZPynNU8ie2n2kVLXcjiam76hCgzo+hfOhAfGz24=,iv:3o24qc18+ziWMRAOrqfxRmWk5ZqzJWoNUZXJOCnZF90=,tag:dedJO8HaH8kaLw8Y/1e3ww==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
